import { FACTORY_MEMORY_ADMISSION_KIND, FACTORY_MEMORY_ADMISSION_VERSION, FACTORY_MEMORY_RECORD_STATUSES } from './memory-admission.defaults.ts'
import { isValidFactoryMemoryNamespace } from './memory-admission.plan.ts'
import type { FactoryMemoryAdmissionResult, FactoryMemoryAdmissionValidationResult, FactoryMemoryRecordDraft } from './memory-admission.types.ts'

export function validateFactoryMemoryRecordDraft(record: FactoryMemoryRecordDraft): FactoryMemoryAdmissionValidationResult {
  const errors: string[] = []; const warnings = [...(record?.warnings ?? [])]
  if (!record?.memoryRecordId?.trim() || !record?.memoryRecordKind) errors.push('Memory record ID and kind are required.'); if (!isValidFactoryMemoryNamespace(record?.namespace ?? '') || !isValidFactoryMemoryNamespace(record?.projectNamespace ?? '')) errors.push('Memory namespaces must be non-empty, relative logical paths without traversal.'); if (record?.scope !== 'project' || record.namespace === 'factory') errors.push('Project memory must remain project-scoped.'); if (!FACTORY_MEMORY_RECORD_STATUSES.includes(record?.status)) errors.push('Memory record status is invalid.'); if (!record?.source || !record?.lineage?.contractProjectId) errors.push('Source and lineage are required.'); if (record?.containsSecrets !== false || record?.containsRawEvidence !== false) errors.push('Secrets and raw evidence are forbidden.'); if (record?.globalPromotionAllowed !== false || record?.promotionPolicy?.globalPromotionAllowed !== false) errors.push('Global promotion must remain disabled.'); if (record?.codexTaskAllowed !== false || record?.projectCreationAllowed !== false || record?.repositoryCreationAllowed !== false || record?.deployAllowed !== false) errors.push('Codex task and creation/deploy capabilities must remain disabled.'); if (!record?.recommendedNextStep?.trim()) errors.push('recommendedNextStep is required.')
  return { ok: errors.length === 0, errors, warnings }
}
export function validateFactoryMemoryAdmissionResult(result: FactoryMemoryAdmissionResult): FactoryMemoryAdmissionValidationResult {
  const errors: string[] = []; const warnings = result?.warnings?.map((warning) => warning.message) ?? []
  if (result?.admissionKind !== FACTORY_MEMORY_ADMISSION_KIND || result?.admissionVersion !== FACTORY_MEMORY_ADMISSION_VERSION) errors.push('Admission kind or version is invalid.'); if (!Array.isArray(result?.decisions) || !Array.isArray(result?.recordDrafts)) errors.push('decisions and recordDrafts are required.'); if (result?.canWriteMemory !== false || result?.canCreateCodexTask !== false || result?.canExecuteCodex !== false || result?.canCreateProject !== false || result?.canCreateRepository !== false || result?.canDeploy !== false) errors.push('Runtime, Codex and creation/deploy capabilities must remain disabled.'); for (const record of result?.recordDrafts ?? []) { errors.push(...validateFactoryMemoryRecordDraft(record).errors) } const rejected = new Set(result?.rejectedEntries ?? []); if (result?.decisions?.some((decision) => rejected.has(decision.registryEntryId) && decision.memoryRecordId)) errors.push('Rejected critical entries cannot produce admitted records.'); if (!result?.recommendedNextStep?.trim()) errors.push('recommendedNextStep is required.')
  return { ok: errors.length === 0, errors, warnings }
}
