import { FACTORY_MEMORY_ADMISSION_KIND, FACTORY_MEMORY_ADMISSION_VERSION, createFactoryMemoryAdmissionPolicy } from './memory-admission.defaults.ts'
import type { FactoryMemoryAdmissionEntryDecision, FactoryMemoryAdmissionFinding, FactoryMemoryAdmissionInput, FactoryMemoryAdmissionResult, FactoryMemoryRecordDraft } from './memory-admission.types.ts'

const token = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'unnamed-project'
const reportRef = (input: FactoryMemoryAdmissionInput) => input.integrityReport.registryIndexRef ?? `${input.integrityReport.integrityKind}:${input.integrityReport.generatedAt}`
export function isValidFactoryMemoryNamespace(namespace: string): boolean { return Boolean(namespace) && !namespace.startsWith('/') && !namespace.includes('..') && namespace.split('/').every(Boolean) }

export function createFactoryMemoryAdmissionPlan(input: FactoryMemoryAdmissionInput): FactoryMemoryAdmissionResult {
  if (!input?.integrityReport || !input.createdAt?.trim() || !input.createdBy?.trim()) throw new Error('integrityReport, createdAt and createdBy are required.')
  createFactoryMemoryAdmissionPolicy(input.policy); const report = structuredClone(input.integrityReport); const admissionId = `memory-admission:${token(input.createdBy)}:${token(input.createdAt)}`; const sourceRef = reportRef(input)
  const decisions: FactoryMemoryAdmissionEntryDecision[] = []; const recordDrafts: FactoryMemoryRecordDraft[] = []; const rejectedEntries: string[] = []; const blockedEntries: string[] = []; const findings: FactoryMemoryAdmissionFinding[] = []; const warnings: FactoryMemoryAdmissionResult['warnings'] = []; const blockers: FactoryMemoryAdmissionResult['blockers'] = []
  const identities = new Map<string, Set<string>>(); for (const entry of report.entries) { const fingerprints = identities.get(entry.contractProjectId) ?? new Set<string>(); fingerprints.add(entry.expectedFingerprint); identities.set(entry.contractProjectId, fingerprints) }
  for (const entry of report.entries) {
    const critical = entry.findings.some((finding) => finding.severity === 'critical'); const reasons: string[] = []
    if (critical) { reasons.push('Critical integrity finding prevents memory admission.'); rejectedEntries.push(entry.registryEntryId); findings.push({ findingId: `memory-finding:${entry.registryEntryId}:critical`, entryId: entry.registryEntryId, kind: 'critical_integrity', severity: 'critical', message: reasons[0] }); decisions.push({ registryEntryId: entry.registryEntryId, contractProjectId: entry.contractProjectId, decision: 'reject_entry', reasons }); continue }
    if (!entry.canUseForMemory || entry.status !== 'clean' || !entry.flagsSafe || !entry.pathContained || !entry.expectedFingerprint || !entry.expectedIdempotencyKey) { reasons.push('Entry does not satisfy clean memory-use requirements.'); blockedEntries.push(entry.registryEntryId); blockers.push({ blockerId: `memory-blocker:${entry.registryEntryId}`, entryId: entry.registryEntryId, message: reasons[0] }); decisions.push({ registryEntryId: entry.registryEntryId, contractProjectId: entry.contractProjectId, decision: 'block_entry', reasons }); continue }
    if ((identities.get(entry.contractProjectId)?.size ?? 0) > 1) { reasons.push('Same project identity has multiple fingerprints and requires contradiction review.'); blockedEntries.push(entry.registryEntryId); findings.push({ findingId: `memory-finding:${entry.registryEntryId}:contradiction`, entryId: entry.registryEntryId, kind: 'possible_contradiction', severity: 'error', message: reasons[0] }); blockers.push({ blockerId: `memory-blocker:${entry.registryEntryId}:contradiction`, entryId: entry.registryEntryId, message: reasons[0] }); decisions.push({ registryEntryId: entry.registryEntryId, contractProjectId: entry.contractProjectId, decision: 'possible_contradiction', reasons }); continue }
    const duplicate = report.entries.some((other) => other.registryEntryId !== entry.registryEntryId && other.contractProjectId === entry.contractProjectId && other.expectedFingerprint === entry.expectedFingerprint); if (duplicate) { warnings.push({ warningId: `memory-warning:${entry.registryEntryId}:duplicate`, entryId: entry.registryEntryId, message: 'Duplicate project fingerprint detected; record draft is retained for governed deduplication.' }); findings.push({ findingId: `memory-finding:${entry.registryEntryId}:duplicate`, entryId: entry.registryEntryId, kind: 'duplicate_safe', severity: 'warning', message: 'Duplicate project fingerprint is safe but requires deduplication review.' }) }
    const projectNamespace = `factory/projects/${token(entry.projectSlug || entry.contractProjectId)}`; const namespace = `${projectNamespace}/contracts`; const memoryRecordId = `memory-record:${token(entry.contractProjectId)}:${entry.expectedFingerprint}`
    const record: FactoryMemoryRecordDraft = { memoryRecordId, memoryRecordKind: 'factory_project_contract', memoryRecordVersion: FACTORY_MEMORY_ADMISSION_VERSION, namespace, projectNamespace, scope: 'project', status: 'draft', source: { integrityReportRef: sourceRef, registryEntryId: entry.registryEntryId, contractFingerprint: entry.expectedFingerprint, idempotencyKey: entry.expectedIdempotencyKey }, title: `Factory project contract: ${entry.projectSlug || entry.contractProjectId}`, summary: 'Canonical project-scoped contract identity admitted from a clean registry integrity entry.', canonicalFacts: { contractProjectId: entry.contractProjectId, projectSlug: entry.projectSlug, contractFingerprint: entry.expectedFingerprint, idempotencyKey: entry.expectedIdempotencyKey, integrityStatus: entry.status, notExecutable: true, codexAllowed: false, projectCreated: false, repositoryCreated: false, deployed: false }, references: [{ targetPath: entry.targetPath, metadataPath: entry.metadataPath }], lineage: { contractProjectId: entry.contractProjectId }, tags: ['factory-project-contract', 'integrity-verified', 'project-scoped'], retentionPolicy: 'retain_until_governed_removal', promotionPolicy: { globalRequiresHumanReview: true, globalPromotionAllowed: false }, stalePolicy: { markStaleBeforeReplacement: true }, replacementPolicy: { automaticReplacementAllowed: false, contradictionRequiresResolution: true }, containsSecrets: false, containsRawEvidence: false, globalPromotionAllowed: false, codexTaskAllowed: false, projectCreationAllowed: false, repositoryCreationAllowed: false, deployAllowed: false, warnings: duplicate ? ['Duplicate-safe candidate requires deduplication review.'] : [], blockers: [], recommendedNextStep: 'Submit the record draft to a future governed memory runtime or human review.' }
    recordDrafts.push(record); decisions.push({ registryEntryId: entry.registryEntryId, contractProjectId: entry.contractProjectId, decision: duplicate ? 'duplicate_safe' : 'admit_record_draft', reasons: [duplicate ? 'Clean duplicate-safe entry produced a governed draft.' : 'Clean integrity entry is eligible for a project-scoped draft.'], memoryRecordId })
  }
  const recommendedNextStep = blockers.length || rejectedEntries.length ? 'Resolve integrity or contradiction blockers through human review before memory runtime admission.' : 'Submit project-scoped record drafts to a future governed memory runtime; do not execute Codex.'
  const summary = { admissionId, admittedCount: recordDrafts.length, rejectedCount: rejectedEntries.length, blockedCount: blockedEntries.length, namespaces: [...new Set(recordDrafts.map((record) => record.namespace))], globalPromotionAllowedCount: 0 as const, codexTaskAllowedCount: 0 as const, canWriteMemory: false as const, recommendedNextStep }
  return { admissionId, admissionKind: FACTORY_MEMORY_ADMISSION_KIND, admissionVersion: FACTORY_MEMORY_ADMISSION_VERSION, createdAt: input.createdAt, createdBy: input.createdBy, sourceIntegrityReportRef: sourceRef, decisions, recordDrafts, rejectedEntries, blockedEntries, findings, warnings, blockers, summary, canWriteMemory: false, canPromoteGlobalMemory: false, canCreateCodexTask: false, canExecuteCodex: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep }
}
