import type { FactoryContractRegistryIntegrityFinding, FactoryContractRegistryIntegrityReport } from '../contract-registry-integrity/index.ts'

export type FactoryMemoryAdmissionVersion = '1.0'
export type FactoryMemoryAdmissionKind = 'factory-memory-admission'
export type FactoryMemoryNamespace = string
export type FactoryMemoryRecordKind = 'factory_project_contract'
export type FactoryMemoryRecordScope = 'project' | 'factory_global'
export type FactoryMemoryRecordStatus = 'draft' | 'blocked' | 'rejected' | 'replacement_candidate'
export type FactoryMemoryAdmissionDecision = 'admit_record_draft' | 'reject_entry' | 'block_entry' | 'duplicate_safe' | 'possible_contradiction'
export interface FactoryMemoryAdmissionPolicy { requireIntegrityReport: true; requireCleanIntegrityEntry: true; requireCanUseForMemory: true; rejectCriticalFindings: true; rejectUnsafeFlags: true; rejectMissingFingerprint: true; rejectMissingIdempotencyKey: true; requireProjectNamespace: true; requireLineage: true; requireNoSecrets: true; requireNoRawEvidence: true; allowProjectScopedMemory: true; requireHumanReviewForGlobalPromotion: true; globalPromotionAllowedByDefault: false; allowContradictionWithoutResolution: false; markStaleBeforeReplacement: true; codexTaskAllowedByAdmission: false; memoryWriteAllowedByAdmission: false; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true }
export interface FactoryMemoryAdmissionInput { integrityReport: FactoryContractRegistryIntegrityReport; createdAt: string; createdBy: string; policy?: Partial<FactoryMemoryAdmissionPolicy>; humanReviewRefs?: string[] }
export interface FactoryMemoryAdmissionFinding { findingId: string; entryId?: string; kind: 'critical_integrity' | 'memory_not_allowed' | 'duplicate_safe' | 'possible_contradiction' | 'global_promotion_requires_review' | 'invalid_namespace'; severity: 'info' | 'warning' | 'error' | 'critical'; message: string }
export interface FactoryMemoryAdmissionBlocker { blockerId: string; entryId?: string; message: string }
export interface FactoryMemoryAdmissionWarning { warningId: string; entryId?: string; message: string }
export interface FactoryMemoryRecordDraft { memoryRecordId: string; memoryRecordKind: FactoryMemoryRecordKind; memoryRecordVersion: FactoryMemoryAdmissionVersion; namespace: FactoryMemoryNamespace; projectNamespace: FactoryMemoryNamespace; scope: FactoryMemoryRecordScope; status: FactoryMemoryRecordStatus; source: { integrityReportRef: string; registryEntryId: string; contractFingerprint: string; idempotencyKey: string }; title: string; summary: string; canonicalFacts: Record<string, string | boolean | undefined>; references: { targetPath: string; metadataPath: string }[]; lineage: { contractProjectId: string; opportunityId?: string; approvalId?: string; candidateId?: string }; tags: string[]; retentionPolicy: 'retain_until_governed_removal'; promotionPolicy: { globalRequiresHumanReview: true; globalPromotionAllowed: false }; stalePolicy: { markStaleBeforeReplacement: true }; replacementPolicy: { automaticReplacementAllowed: false; contradictionRequiresResolution: true }; containsSecrets: false; containsRawEvidence: false; globalPromotionAllowed: false; codexTaskAllowed: false; projectCreationAllowed: false; repositoryCreationAllowed: false; deployAllowed: false; warnings: string[]; blockers: string[]; recommendedNextStep: string }
export interface FactoryMemoryAdmissionEntryDecision { registryEntryId: string; contractProjectId: string; decision: FactoryMemoryAdmissionDecision; reasons: string[]; memoryRecordId?: string }
export interface FactoryMemoryAdmissionSummary { admissionId: string; admittedCount: number; rejectedCount: number; blockedCount: number; namespaces: string[]; globalPromotionAllowedCount: 0; codexTaskAllowedCount: 0; canWriteMemory: false; recommendedNextStep: string }
export interface FactoryMemoryAdmissionResult { admissionId: string; admissionKind: FactoryMemoryAdmissionKind; admissionVersion: FactoryMemoryAdmissionVersion; createdAt: string; createdBy: string; sourceIntegrityReportRef: string; decisions: FactoryMemoryAdmissionEntryDecision[]; recordDrafts: FactoryMemoryRecordDraft[]; rejectedEntries: string[]; blockedEntries: string[]; findings: FactoryMemoryAdmissionFinding[]; warnings: FactoryMemoryAdmissionWarning[]; blockers: FactoryMemoryAdmissionBlocker[]; summary: FactoryMemoryAdmissionSummary; canWriteMemory: false; canPromoteGlobalMemory: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryAdmissionValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export type FactoryMemoryAdmissionIntegrityFinding = FactoryContractRegistryIntegrityFinding
