import { createFactoryProjectContractV1, validateFactoryProjectContractV1 } from '../project-contract/index.ts'
import { createFactoryProjectContractCompatibilityPolicy, FACTORY_PROJECT_CONTRACT_COMPATIBILITY_KIND, FACTORY_PROJECT_CONTRACT_COMPATIBILITY_VERSION } from './project-contract-compatibility.defaults.ts'
import type { FactoryProjectContractCompatibilityBlocker, FactoryProjectContractCompatibilityCheck, FactoryProjectContractCompatibilityInput, FactoryProjectContractCompatibilityResult, FactoryProjectContractCompatibilityWarning } from './project-contract-compatibility.types.ts'

const forbiddenEnvKeys = ['value', 'actualValue', 'token', 'apiKeyValue', 'secretValue']
const check = (checkId: string, category: FactoryProjectContractCompatibilityCheck['category'], passed: boolean, message: string): FactoryProjectContractCompatibilityCheck => ({ checkId, category, passed, message })

export function evaluateFactoryProjectContractCompatibility(input: FactoryProjectContractCompatibilityInput): FactoryProjectContractCompatibilityResult {
  const value = structuredClone(input); const candidate = value.candidate; createFactoryProjectContractCompatibilityPolicy(value.policy)
  const approvalRef = value.humanApprovalRef ?? candidate.lineage.humanReviewRef; const checks: FactoryProjectContractCompatibilityCheck[] = []
  const envWithoutValues = candidate.environmentVariables.every((variable) => forbiddenEnvKeys.every((key) => !Object.prototype.hasOwnProperty.call(variable, key)))
  checks.push(check('candidate-ready', 'readiness', candidate.readiness.status === 'ready_for_contract_draft', 'Candidate must be ready for contract draft.'))
  checks.push(check('human-approved', 'approval', Boolean(approvalRef), 'Human approval reference is required.'))
  checks.push(check('lineage-complete', 'lineage', Boolean(candidate.source.briefDraftId && candidate.lineage.opportunityId && candidate.lineage.decisionId), 'Brief, opportunity and decision lineage must be complete.'))
  checks.push(check('own-repository', 'repository', candidate.repository.repositoryRequired === true && candidate.repository.ownRootRequired === true && Boolean(candidate.repository.owner), 'Own repository, root and owner are required.'))
  checks.push(check('runtime-independent', 'independence', candidate.independencePolicy.mustNotDependOnJefeRuntime && candidate.independencePolicy.mustNotImportJefeModules && candidate.independencePolicy.mustHaveOwnRepository && candidate.independencePolicy.mustHaveOwnRoot, 'Candidate must remain independent from JEFE runtime and modules.'))
  checks.push(check('env-names-only', 'environment', envWithoutValues, 'Environment variables must contain metadata only.'))
  checks.push(check('quality-profile', 'quality', Boolean(candidate.qualityProfile?.profile && candidate.qualityProfile.requiredChecks.length), 'Quality profile and checks are required.'))
  checks.push(check('security-profile', 'security', Boolean(candidate.securityProfile?.profile && candidate.securityProfile.secretValuesForbidden), 'Secure-default profile is required.'))
  checks.push(check('evidence-requirements', 'evidence', candidate.evidenceRequirements.length > 0, 'Evidence requirements must not be empty.'))
  checks.push(check('execution-disabled', 'execution', !candidate.executionPolicy.codexExecutionAllowed && !candidate.executionPolicy.projectCreationAllowed && !candidate.executionPolicy.repositoryCreationAllowed && !candidate.executionPolicy.deployAllowed, 'Codex, project, repository and deploy must remain disabled.'))
  const blockers: FactoryProjectContractCompatibilityBlocker[] = checks.filter((item) => !item.passed).map((item) => ({ blockerId: item.checkId, category: item.category, message: item.message }))
  const warnings: FactoryProjectContractCompatibilityWarning[] = [{ warningId: 'projection-run-id', category: 'lineage', message: 'runId is a deterministic compatibility projection placeholder, not an executed factory run.' }]
  let contractDraft; let contractValidation
  if (blockers.length === 0) {
    const slug = candidate.identity.slugSuggestion; const projectedRunId = `compatibility-projection-${candidate.candidateId}`
    contractDraft = createFactoryProjectContractV1({ createdAt: value.createdAt, project: { projectId: candidate.identity.projectIdSuggestion || candidate.candidateId, slug, name: candidate.identity.name, description: candidate.description, projectType: candidate.projectType, businessDomain: candidate.identity.businessDomain, owner: candidate.identity.owner },
      lineage: { opportunityId: candidate.lineage.opportunityId, briefId: candidate.source.briefDraftId, runId: projectedRunId, parentContractId: candidate.candidateId, generatedBy: 'JEFE', generatedAt: value.createdAt },
      paths: { plannedOutputRoot: `projects/${slug}`, projectRootPolicy: 'independent-root-created-only-after-approved-contract', forbiddenPaths: ['ai-orchestrator', 'electron', 'src/factory', '.env', '.git'], evidenceRoot: `evidence/${slug}`, runArtifactsRoot: `run-artifacts/${slug}` },
      memory: { memoryNamespace: 'factory-global-reviewed-learning', projectMemoryNamespace: `project-${slug}`, globalLearningPolicy: 'review-required-before-promotion', promotionPolicy: 'JEFE-and-human-approved-only', retentionPolicy: 'project-scoped-versioned-retention', staleDataPolicy: 'mark-review-and-retire' },
      stack: { ...candidate.stack, testFrameworks: [...candidate.stack.testFrameworks] }, environmentVariables: candidate.environmentVariables.map((item) => ({ ...item })),
      quality: { qualityProfile: candidate.qualityProfile.profile, requiredChecks: [...candidate.qualityProfile.requiredChecks], optionalChecks: ['visual_evidence', 'accessibility', 'performance'], smokeRequired: true, domainSmokeRequired: true, unitTestsPlanned: candidate.qualityProfile.unitTestsPlanned, integrationTestsPlanned: candidate.qualityProfile.integrationTestsPlanned, e2eTestsPlanned: candidate.qualityProfile.e2eTestsPlanned, visualEvidenceRequired: true, accessibilityRequired: candidate.qualityProfile.accessibilityPlanned, performanceRequired: candidate.qualityProfile.performancePlanned },
      security: { secretPolicy: 'names-only; values-external-to-contract', sandboxPolicy: 'project-root-contained', networkPolicy: 'deny-by-default-with-human-approval', filesystemPolicy: 'own-root-only-no-jefe-internals', commandExecutionPolicy: 'disabled-until-separate-codex-permit', promptInjectionPolicy: 'untrusted-input-review-required', dependencyPolicy: 'locked-reviewed-ci-validated', approvalRequiredForExternalCalls: true, approvalRequiredForDeploy: true },
      approvals: { requiredApprovals: ['contract_creation', 'before_codex', 'before_deploy'], approvalStages: [{ id: 'contract-creation', description: 'Human approves the projected contract.', required: true }, { id: 'before-codex', description: 'Human separately authorizes construction.', required: true }], humanApprovalRequired: true, autoApprovalAllowed: false, codexSelfApprovalAllowed: false },
      repository: { repositoryRequired: true, provider: candidate.repository.provider, visibility: 'planned', owner: candidate.repository.owner ?? '', repoName: candidate.repository.repoNameSuggestion, defaultBranch: 'main', protectedBranches: ['main'], commitPolicy: 'small-reviewed-evidence-backed', pushPolicy: 'human-approved-ci-gated' },
      ci: { ciRequired: true, provider: 'GitHub Actions', requiredWorkflows: ['quality'], requiredStatusChecks: ['typecheck', 'build', 'smoke'], stagingRequired: true, productionDeployAllowed: false, rollbackRequired: true },
      publication: { staging: { enabled: false, approvalRequired: true }, production: { enabled: false, approvalRequired: true }, domains: [], deploymentStrategy: 'not-selected-before-contract-approval', rollbackStrategy: 'required-before-first-deploy', releaseApproval: 'JEFE-and-human-required' },
      analytics: { analyticsPlanned: true, analyticsProvider: 'to-be-decided', monetizationPlanned: Boolean(candidate.monetization.trim()), monetizationModel: candidate.monetization, revenueEvents: [], killCriteria: [], scaleCriteria: [] },
      evidence: { requiredArtifacts: candidate.evidenceRequirements.map((item) => item.requirementId), reportsRequired: ['validation-summary', 'delivery-ledger'], screenshotsRequired: true, logsRequired: true, validationSummaryRequired: true, deliveryLedgerRequired: true, traceabilityRequired: true },
      lifecycle: { lifecycleStatus: 'draft', readiness: 'compatibility-projection-awaiting-final-contract-approval', warnings: warnings.map((item) => item.message), risks: [], blockers: [] } })
    contractValidation = validateFactoryProjectContractV1(contractDraft); checks.push(check('contract-validation', 'contract_validation', contractValidation.ok, 'Projected contract must pass FactoryProjectContract v1 validation.'))
    if (!contractValidation.ok) blockers.push(...contractValidation.errors.map((message, index) => ({ blockerId: `contract-validation-${index + 1}`, category: 'contract_validation' as const, message })))
    warnings.push(...contractValidation.warnings.map((message, index) => ({ warningId: `contract-warning-${index + 1}`, category: 'contract_validation', message })))
  }
  const compatible = blockers.length === 0 && contractValidation?.ok === true
  return { compatibilityId: `factory-project-contract-compatibility-${candidate.candidateId}-${value.createdAt.replace(/[^0-9]/g, '')}`, compatibilityKind: FACTORY_PROJECT_CONTRACT_COMPATIBILITY_KIND, compatibilityVersion: FACTORY_PROJECT_CONTRACT_COMPATIBILITY_VERSION, createdAt: value.createdAt, checkedBy: value.checkedBy, candidateId: candidate.candidateId, briefDraftId: candidate.source.briefDraftId, opportunityId: candidate.lineage.opportunityId, status: compatible ? 'compatible' : !approvalRef && blockers.every((item) => item.category === 'approval') ? 'needs_human_review' : 'blocked', canCreateFactoryProjectContract: compatible, canExecuteCodex: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, checks, blockers, warnings, contractDraft, contractValidation, recommendedNextStep: compatible ? 'Submit the in-memory contract draft for final JEFE and human approval; do not execute Codex or create resources.' : 'Resolve compatibility blockers and reevaluate the candidate.' }
}
