import type { FactoryProjectContractV1, FactoryProjectContractValidationResult } from '../project-contract/index.ts'
import type { FactoryProjectContractCandidate } from '../project-contract-candidate/index.ts'

export type FactoryProjectContractCompatibilityVersion = '1.0'
export type FactoryProjectContractCompatibilityKind = 'factory-project-contract-compatibility'
export type FactoryProjectContractCompatibilityStatus = 'compatible' | 'needs_human_review' | 'blocked'
export interface FactoryProjectContractCompatibilityPolicy { requireCandidateReadyForContractDraft: true; requireHumanApproval: true; requireOwnRepository: true; requireOwnRoot: true; requireRuntimeIndependence: true; forbidJefeRuntimeDependency: true; forbidJefeModuleImports: true; requireEnvironmentVariablesWithoutValues: true; requireQualityProfile: true; requireSecurityProfile: true; requireEvidenceRequirements: true; requireFactoryProjectContractValidation: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true }
export interface FactoryProjectContractCompatibilityInput { candidate: FactoryProjectContractCandidate; createdAt: string; checkedBy: string; humanApprovalRef?: string; policy?: Partial<FactoryProjectContractCompatibilityPolicy> }
export interface FactoryProjectContractCompatibilityCheck { checkId: string; category: 'readiness' | 'lineage' | 'independence' | 'repository' | 'environment' | 'quality' | 'security' | 'evidence' | 'approval' | 'execution' | 'contract_validation'; passed: boolean; message: string }
export interface FactoryProjectContractCompatibilityBlocker { blockerId: string; category: FactoryProjectContractCompatibilityCheck['category']; message: string }
export interface FactoryProjectContractCompatibilityWarning { warningId: string; category: string; message: string }
export type FactoryProjectContractDraftProjection = FactoryProjectContractV1
export interface FactoryProjectContractCompatibilityResult { compatibilityId: string; compatibilityKind: FactoryProjectContractCompatibilityKind; compatibilityVersion: FactoryProjectContractCompatibilityVersion; createdAt: string; checkedBy: string; candidateId: string; briefDraftId: string; opportunityId: string; status: FactoryProjectContractCompatibilityStatus; canCreateFactoryProjectContract: boolean; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; checks: FactoryProjectContractCompatibilityCheck[]; blockers: FactoryProjectContractCompatibilityBlocker[]; warnings: FactoryProjectContractCompatibilityWarning[]; contractDraft?: FactoryProjectContractDraftProjection; contractValidation?: FactoryProjectContractValidationResult; recommendedNextStep: string }
export interface FactoryProjectContractCompatibilityValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryProjectContractCompatibilitySummary { compatibilityId: string; candidateId: string; slug: string; status: FactoryProjectContractCompatibilityStatus; canCreateFactoryProjectContract: boolean; contractValidationOk: boolean; blockersCount: number; warningsCount: number; recommendedNextStep: string }
