export type FactoryContractRegistryVersion = '1.0'
export type FactoryContractRegistryKind = 'factory-contract-registry'
export type FactoryContractRegistryEntryStatus = 'valid' | 'invalid' | 'blocked'
export interface FactoryContractRegistryInput { storageRoot: string; generatedAt: string; generatedBy: string; policy?: Partial<FactoryContractRegistryPolicy> }
export interface FactoryContractRegistryPolicy { requireStorageRootInsideCodexTemp: true; requireMetadataForEntry: true; requireContractReadback: true; requireFingerprint: true; requireIdempotencyKey: true; requireNotExecutable: true; requireCodexNotAllowed: true; requireProjectNotCreated: true; requireRepositoryNotCreated: true; requireDeployNotAllowed: true; detectDuplicateFingerprints: true; detectDuplicateIdempotencyKeys: true; detectConflictingProjectIds: true; forbidPathTraversal: true; forbidAbsoluteContractPaths: true; allowIndexWrite: true; indexWriteUnderStorageRootOnly: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true }
export interface FactoryContractRegistryMetadata { metadataKind: string; metadataVersion: string; persistenceId: string; approvalId: string; candidateId: string; fingerprint: string; idempotencyKey: string; targetPath: string; writtenAt: string; writtenBy: string; sourceStatus: string; runtimePersistenceId: string; notExecutable: true; codexAllowed: false; projectCreated: false; repositoryCreated: false; deployed: false }
export interface FactoryContractRegistryEntry { registryEntryId: string; contractProjectId: string; contractKind: string; contractVersion: string; projectSlug: string; projectName: string; targetPath: string; metadataPath: string; fingerprint: string; idempotencyKey: string; persistenceId: string; approvalId: string; candidateId: string; createdAt: string; writtenAt: string; status: FactoryContractRegistryEntryStatus; validation: FactoryContractRegistryValidationResult; notExecutable: true; codexAllowed: false; projectCreated: false; repositoryCreated: false; deployed: false; warnings: string[]; blockers: string[] }
export interface FactoryContractRegistryDuplicate { field: 'fingerprint' | 'idempotencyKey'; value: string; registryEntryIds: string[] }
export interface FactoryContractRegistryConflict { field: 'contractProjectId' | 'projectSlug'; value: string; registryEntryIds: string[]; fingerprints: string[] }
export interface FactoryContractRegistryIndexSummary { totalEntries: number; validEntries: number; invalidEntries: number; blockedEntries: number; duplicateGroups: number; conflictGroups: number; readyForNextStep: number; recommendedNextStep: string }
export interface FactoryContractRegistryIndex { registryKind: FactoryContractRegistryKind; registryVersion: FactoryContractRegistryVersion; generatedAt: string; storageRoot: string; entries: FactoryContractRegistryEntry[]; duplicates: FactoryContractRegistryDuplicate[]; conflicts: FactoryContractRegistryConflict[]; warnings: string[]; blockers: string[]; summary: FactoryContractRegistryIndexSummary }
export interface FactoryContractRegistryQuery { byProjectId?: string; bySlug?: string; byFingerprint?: string; byIdempotencyKey?: string; byStatus?: FactoryContractRegistryEntryStatus; latestOnly?: boolean; readyForNextStepOnly?: boolean }
export interface FactoryContractRegistryQueryResult { query: FactoryContractRegistryQuery; matches: FactoryContractRegistryEntry[]; warnings: string[]; blockers: string[]; summary: { matchCount: number; statusCounts: Record<string, number>; recommendedNextStep: string } }
export interface FactoryContractRegistryValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryContractRegistrySummary { registryKind: FactoryContractRegistryKind; registryVersion: FactoryContractRegistryVersion; generatedAt: string; totalEntries: number; statusCounts: Record<string, number>; duplicateGroups: number; conflictGroups: number; blockersCount: number; warningsCount: number; recommendedNextStep: string }
export interface FactoryContractRegistryQuerySummary { matchCount: number; statusCounts: Record<string, number>; blockersCount: number; warningsCount: number; recommendedNextStep: string }
