import type { FactoryContractRegistryEntry, FactoryContractRegistryIndex, FactoryContractRegistryQuery, FactoryContractRegistryQueryResult, FactoryContractRegistryQuerySummary, FactoryContractRegistrySummary } from './contract-registry.types.ts'
const statusCounts = (entries: FactoryContractRegistryEntry[]) => entries.reduce<Record<string, number>>((counts, entry) => ({ ...counts, [entry.status]: (counts[entry.status] ?? 0) + 1 }), {})
export function queryFactoryContractRegistry(index: FactoryContractRegistryIndex, query: FactoryContractRegistryQuery): FactoryContractRegistryQueryResult {
  let matches = index.entries.filter((entry) => (!query.byProjectId || entry.contractProjectId === query.byProjectId) && (!query.bySlug || entry.projectSlug === query.bySlug) && (!query.byFingerprint || entry.fingerprint === query.byFingerprint) && (!query.byIdempotencyKey || entry.idempotencyKey === query.byIdempotencyKey) && (!query.byStatus || entry.status === query.byStatus) && (!query.readyForNextStepOnly || entry.status === 'valid'))
  if (query.latestOnly && matches.length > 1) matches = [...matches].sort((left, right) => right.writtenAt.localeCompare(left.writtenAt)).slice(0, 1)
  return { query: structuredClone(query), matches: structuredClone(matches), warnings: [], blockers: [], summary: { matchCount: matches.length, statusCounts: statusCounts(matches), recommendedNextStep: matches.length ? 'Submit selected registry entries to future MEMORIA or Codex Task Contract review; do not execute Codex directly.' : 'Refine the registry query or review discovery blockers.' } }
}
export function serializeFactoryContractRegistryIndex(index: FactoryContractRegistryIndex): string { return JSON.stringify(index, null, 2) }
export function parseFactoryContractRegistryIndex(json: string): FactoryContractRegistryIndex { return JSON.parse(json) as FactoryContractRegistryIndex }
export function summarizeFactoryContractRegistryIndex(index: FactoryContractRegistryIndex): FactoryContractRegistrySummary { return { registryKind: index.registryKind, registryVersion: index.registryVersion, generatedAt: index.generatedAt, totalEntries: index.entries.length, statusCounts: statusCounts(index.entries), duplicateGroups: index.duplicates.length, conflictGroups: index.conflicts.length, blockersCount: index.blockers.length, warningsCount: index.warnings.length, recommendedNextStep: index.summary.recommendedNextStep } }
export function serializeFactoryContractRegistryQueryResult(result: FactoryContractRegistryQueryResult): string { return JSON.stringify(result, null, 2) }
export function parseFactoryContractRegistryQueryResult(json: string): FactoryContractRegistryQueryResult { return JSON.parse(json) as FactoryContractRegistryQueryResult }
export function summarizeFactoryContractRegistryQueryResult(result: FactoryContractRegistryQueryResult): FactoryContractRegistryQuerySummary { return { matchCount: result.matches.length, statusCounts: statusCounts(result.matches), blockersCount: result.blockers.length, warningsCount: result.warnings.length, recommendedNextStep: result.summary.recommendedNextStep } }
