import { FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_KIND, FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_VERSION, FACTORY_CODEX_TASK_NOT_AUTHORIZED_ACTIONS } from './codex-task-contract-candidate.defaults.ts'
import type { FactoryCodexTaskContractCandidate, FactoryCodexTaskContractCandidateResult, FactoryCodexTaskContractCandidateValidationResult, FactoryCodexTaskIntent } from './codex-task-contract-candidate.types.ts'

const taskKinds = ['analysis_only', 'planning_only', 'documentation_update_candidate', 'test_generation_candidate', 'code_change_candidate', 'repair_plan_candidate', 'factory_project_materialization_candidate']
const decisions = ['blocked', 'reject_task_intent', 'request_task_contract_changes', 'human_review_required', 'approve_codex_task_contract_candidate']
const statuses = ['blocked', 'rejected', 'changes_required', 'human_review_required', 'codex_task_contract_candidate_ready']
const hasDangerousAllowed = (intent: FactoryCodexTaskIntent) => [...intent.allowedSurfaces, ...intent.constraints].some((value) => /execute_codex|run_commands|access_secrets|deploy|modify_files|call_model|final_prompt|create_repository|create_project/i.test(String(value)))
export function validateFactoryCodexTaskIntent(taskIntent: FactoryCodexTaskIntent): FactoryCodexTaskContractCandidateValidationResult { const errors: string[] = []; const warnings: string[] = []; if (!taskIntent?.taskIntentId) errors.push('taskIntentId is required.'); if (!taskKinds.includes(taskIntent?.taskKind)) errors.push('taskKind is invalid.'); if (!taskIntent?.title || !taskIntent?.objective) errors.push('title and objective are required.'); if (!taskIntent?.nonGoals?.length) errors.push('nonGoals are required.'); if (!taskIntent?.acceptanceCriteria?.length) errors.push('acceptanceCriteria are required.'); if (!taskIntent?.proposedValidationPlan) errors.push('proposedValidationPlan is required.'); if (!taskIntent?.evidenceRequirements?.length) errors.push('evidenceRequirements are required.'); if (!taskIntent?.responseRequirements?.length) errors.push('responseRequirements are required.'); if (!taskIntent?.stopConditions?.length) errors.push('stopConditions are required.'); if (taskIntent && hasDangerousAllowed(taskIntent)) errors.push('Task intent allows dangerous actions.'); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryCodexTaskContractCandidate(candidate: FactoryCodexTaskContractCandidate): FactoryCodexTaskContractCandidateValidationResult { const errors: string[] = []; const warnings: string[] = []; if (!candidate?.contractCandidateId || !candidate.sourceContextApprovalId || !candidate.sourceAssemblyId || !candidate.sourceReadRuntimeId || !candidate.sourceReadAdmissionId) errors.push('Candidate and context refs are required.'); if (candidate?.contractCandidateKind !== FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_KIND || candidate.contractCandidateVersion !== FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_VERSION) errors.push('Candidate kind/version is invalid.'); errors.push(...validateFactoryCodexTaskIntent(candidate.taskIntent).errors); if (candidate.status !== 'candidate_not_approved' || candidate.promptAssemblyStatus !== 'not_generated' || candidate.codexTaskStatus !== 'not_created' || candidate.codexExecutionStatus !== 'not_allowed' || candidate.fileMutationStatus !== 'not_allowed' || candidate.commandExecutionStatus !== 'not_allowed' || candidate.externalNetworkStatus !== 'not_allowed' || candidate.secretsAccessStatus !== 'not_allowed') errors.push('Candidate statuses must remain non-executable.'); if (candidate.canAssembleCodexPrompt || candidate.canCreateExecutableCodexTask || candidate.canExecuteCodex || candidate.canModifyFiles || candidate.canRunCommands || candidate.canAccessSecrets || candidate.canCreateProject || candidate.canCreateRepository || candidate.canDeploy) errors.push('Candidate must not enable prompt, execution, mutation, command, secret, project, repository or deploy actions.'); if (!FACTORY_CODEX_TASK_NOT_AUTHORIZED_ACTIONS.every((action) => candidate.forbiddenActions.includes(action))) errors.push('Candidate must include all not authorized actions as forbidden.'); if (!candidate.recommendedNextStep) errors.push('recommendedNextStep is required.'); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryCodexTaskContractCandidateResult(result: FactoryCodexTaskContractCandidateResult): FactoryCodexTaskContractCandidateValidationResult { const errors: string[] = []; const warnings: string[] = []; if (result?.candidateGateKind !== FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_KIND || result.candidateGateVersion !== FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_VERSION) errors.push('Result kind/version is invalid.'); if (!decisions.includes(result?.decision)) errors.push('Decision is invalid.'); if (!statuses.includes(result?.status)) errors.push('Status is invalid.'); if (result.decision === 'approve_codex_task_contract_candidate' && !result.contractCandidate) errors.push('Approved result requires contractCandidate.'); if (result.contractCandidate) errors.push(...validateFactoryCodexTaskContractCandidate(result.contractCandidate).errors); if (result.canAssembleCodexPrompt || result.canCreateExecutableCodexTask || result.canExecuteCodex || result.canModifyFiles || result.canRunCommands || result.canAccessSecrets || result.canCreateProject || result.canCreateRepository || result.canDeploy) errors.push('Result must not enable prompt, execution, mutation, command, secret, project, repository or deploy actions.'); if (result.decision !== 'approve_codex_task_contract_candidate' && !result.blockers.length && !result.reasons.length) errors.push('Blocked/rejected result requires blockers or reasons.'); if (!result.recommendedNextStep) errors.push('recommendedNextStep is required.'); return { ok: errors.length === 0, errors, warnings } }

