import { FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_KIND, FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_VERSION, FACTORY_CODEX_TASK_NOT_AUTHORIZED_ACTIONS, createFactoryCodexTaskContractCandidatePolicy } from './codex-task-contract-candidate.defaults.ts'
import type { FactoryCodexTaskContractCandidate, FactoryCodexTaskContractCandidateBlocker, FactoryCodexTaskContractCandidateDecision, FactoryCodexTaskContractCandidateInput, FactoryCodexTaskContractCandidateResult, FactoryCodexTaskContractCandidateStatus } from './codex-task-contract-candidate.types.ts'

const token = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'unknown'
const dangerous = new Set<string>(FACTORY_CODEX_TASK_NOT_AUTHORIZED_ACTIONS)
const intentDanger = (input: FactoryCodexTaskContractCandidateInput['taskIntent'] | undefined) => Boolean(input && ([...input.allowedSurfaces, ...input.constraints].some((value) => dangerous.has(String(value)) || /execute_codex|run_commands|access_secrets|deploy|modify_files|call_model|final_prompt|create_repository|create_project/i.test(String(value)))))
const unsafeEnvelope = (approval: FactoryCodexTaskContractCandidateInput['memoryContextApprovalResult'] | undefined) => !approval?.approvedContextEnvelope || approval.decision !== 'approve_context_package_for_handoff_candidate' || approval.status !== 'approved_context_candidate' || approval.approvedContextEnvelope.codexTaskStatus !== 'not_allowed' || approval.approvedContextEnvelope.codexExecutionStatus !== 'not_allowed' || approval.approvedContextEnvelope.embeddingsStatus !== 'not_allowed' || approval.approvedContextEnvelope.projectStatus !== 'not_created' || approval.approvedContextEnvelope.repositoryStatus !== 'not_created' || approval.approvedContextEnvelope.deployStatus !== 'not_allowed'

export function evaluateFactoryCodexTaskContractCandidate(input: FactoryCodexTaskContractCandidateInput): FactoryCodexTaskContractCandidateResult {
  const policy = createFactoryCodexTaskContractCandidatePolicy(input?.policy); const approval = input?.memoryContextApprovalResult; const intent = input?.taskIntent; const createdAt = input?.createdAt ?? ''; const createdBy = input?.createdBy ?? ''; const candidateGateId = `codex-task-candidate-gate:${token(approval?.approvalId ?? 'missing-approval')}:${token(createdAt)}`
  const checks = [{ checkId: 'context-approval-present', passed: Boolean(approval), message: 'Context approval result is required.' }, { checkId: 'task-intent-present', passed: Boolean(intent), message: 'Task intent is required.' }, { checkId: 'creator-present', passed: Boolean(createdAt && createdBy), message: 'createdAt and createdBy are required.' }]
  const blockers: FactoryCodexTaskContractCandidateBlocker[] = []; const warnings: FactoryCodexTaskContractCandidateResult['warnings'] = []; const reasons: string[] = []
  let decision: FactoryCodexTaskContractCandidateDecision; let status: FactoryCodexTaskContractCandidateStatus
  if (!approval) { decision = 'blocked'; status = 'blocked'; reasons.push('Context approval result is required.'); blockers.push({ blockerId: 'missing-context-approval', message: reasons[0], critical: true }) }
  else if (approval.decision !== 'approve_context_package_for_handoff_candidate' || approval.status !== 'approved_context_candidate') { decision = 'reject_task_intent'; status = 'rejected'; reasons.push('Context approval is not approved for handoff candidate use.'); blockers.push({ blockerId: 'context-not-approved', message: reasons[0] }) }
  else if (!approval.approvedContextEnvelope || unsafeEnvelope(approval)) { decision = 'blocked'; status = 'blocked'; reasons.push('Approved context envelope is missing or unsafe.'); blockers.push({ blockerId: 'unsafe-context-envelope', message: reasons[0], critical: true }) }
  else if (!intent) { decision = 'blocked'; status = 'blocked'; reasons.push('Task intent is required.'); blockers.push({ blockerId: 'missing-task-intent', message: reasons[0], critical: true }) }
  else if (!intent.objective?.trim() || !intent.nonGoals?.length || !intent.acceptanceCriteria?.length || !intent.proposedValidationPlan || !intent.evidenceRequirements?.length || !intent.responseRequirements?.length || !intent.stopConditions?.length) { decision = 'request_task_contract_changes'; status = 'changes_required'; reasons.push('Task intent must include objective, non-goals, acceptance criteria, validation plan, evidence, response requirements and stop conditions.'); blockers.push({ blockerId: 'incomplete-task-intent', message: reasons[0] }) }
  else if (intentDanger(intent)) { decision = 'blocked'; status = 'blocked'; reasons.push('Task intent attempts to allow dangerous execution, mutation, secrets, network, project, repository, deploy or model actions.'); blockers.push({ blockerId: 'dangerous-task-intent', message: reasons[0], critical: true }) }
  else if ((['high', 'critical'].includes(intent.riskLevel) || ['code_change_candidate', 'factory_project_materialization_candidate'].includes(intent.taskKind)) && !input.humanReviewRef?.trim()) { decision = 'human_review_required'; status = 'human_review_required'; reasons.push('High-risk, code-change or project-materialization candidates require explicit human review.'); blockers.push({ blockerId: 'human-review-required', message: reasons[0] }) }
  else { decision = 'approve_codex_task_contract_candidate'; status = 'codex_task_contract_candidate_ready'; reasons.push('Task intent and approved context envelope are eligible for a non-executable contract candidate.') }
  const nextStep = decision === 'approve_codex_task_contract_candidate' ? 'Submit contract candidate to a future Codex Task Contract Approval Gate; no direct Codex execution is authorized.' : decision === 'human_review_required' ? 'Obtain human review before preparing a Codex task contract candidate.' : 'Repair context approval or task intent before requesting a candidate again.'
  const result: FactoryCodexTaskContractCandidateResult = { candidateGateId, candidateGateKind: FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_KIND, candidateGateVersion: FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_VERSION, createdAt, createdBy, decision, status, checks, blockers, warnings, reasons, canAssembleCodexPrompt: false, canCreateExecutableCodexTask: false, canExecuteCodex: false, canModifyFiles: false, canRunCommands: false, canAccessSecrets: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: nextStep }
  if (decision === 'approve_codex_task_contract_candidate' && approval?.approvedContextEnvelope && intent) {
    const envelope = approval.approvedContextEnvelope; const contractCandidate: FactoryCodexTaskContractCandidate = { contractCandidateId: `codex-task-contract-candidate:${token(intent.taskIntentId)}:${token(envelope.approvalId)}`, contractCandidateKind: FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_KIND, contractCandidateVersion: FACTORY_CODEX_TASK_CONTRACT_CANDIDATE_VERSION, taskIntent: structuredClone(intent), sourceContextApprovalId: approval.approvalId, sourceAssemblyId: envelope.sourceAssemblyId, sourceReadRuntimeId: envelope.sourceReadRuntimeId, sourceReadAdmissionId: envelope.sourceReadAdmissionId, contextEnvelopeRef: envelope.envelopeId, contextPackageSummary: { contextPurpose: envelope.contextPurpose, itemCount: envelope.packageCandidate.itemCount, approxChars: envelope.packageCandidate.approxChars, codexTaskStatus: envelope.codexTaskStatus, codexExecutionStatus: envelope.codexExecutionStatus }, allowedSurfaces: structuredClone(intent.allowedSurfaces), forbiddenActions: FACTORY_CODEX_TASK_NOT_AUTHORIZED_ACTIONS, acceptanceCriteria: structuredClone(intent.acceptanceCriteria), validationPlan: { ...structuredClone(intent.proposedValidationPlan), stopOnFailure: true, commandsExecuted: false, futureRunnerRequired: true }, stopConditions: structuredClone(intent.stopConditions), evidenceRequirements: structuredClone(intent.evidenceRequirements), responseRequirements: structuredClone(intent.responseRequirements), safetyBoundaries: ['no_prompt_final_generated', 'no_codex_execution', 'no_file_mutation', 'no_command_execution', 'no_secret_access', 'no_external_network', 'no_project_creation', 'no_repository_creation', 'no_deploy', 'human_review_required_before_execution', 'approval_gate_required_before_prompt', 'execution_adapter_required_future'], handoffNotes: ['Candidate only; future approval gates are required before prompt assembly or execution.'], status: 'candidate_not_approved', promptAssemblyStatus: 'not_generated', codexTaskStatus: 'not_created', codexExecutionStatus: 'not_allowed', fileMutationStatus: 'not_allowed', commandExecutionStatus: 'not_allowed', externalNetworkStatus: 'not_allowed', secretsAccessStatus: 'not_allowed', projectStatus: 'not_created', repositoryStatus: 'not_created', deployStatus: 'not_allowed', canAssembleCodexPrompt: false, canCreateExecutableCodexTask: false, canExecuteCodex: false, canModifyFiles: false, canRunCommands: false, canAccessSecrets: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: nextStep }
    result.contractCandidate = contractCandidate
  }
  void policy; return result
}

