import type { FactoryMemoryContextApprovalResult } from '../memory-context-approval/index.ts'

export type FactoryCodexTaskContractCandidateVersion = '1.0'
export type FactoryCodexTaskContractCandidateKind = 'factory-codex-task-contract-candidate'
export type FactoryCodexTaskKind = 'analysis_only' | 'planning_only' | 'documentation_update_candidate' | 'test_generation_candidate' | 'code_change_candidate' | 'repair_plan_candidate' | 'factory_project_materialization_candidate'
export type FactoryCodexTaskRiskLevel = 'low' | 'medium' | 'high' | 'critical'
export type FactoryCodexTaskScope = 'context_handoff_candidate'
export type FactoryCodexTaskAllowedSurface = 'approved_context_envelope' | 'read_only_analysis' | 'contract_review' | 'documentation_candidate' | 'test_plan_candidate'
export type FactoryCodexTaskForbiddenAction = 'assemble_final_codex_prompt' | 'create_executable_codex_task' | 'execute_codex' | 'modify_files' | 'run_commands' | 'access_secrets' | 'external_network_calls' | 'create_project' | 'create_repository' | 'deploy' | 'publish' | 'call_model'
export interface FactoryCodexTaskAcceptanceCriterion { criterionId: string; description: string }
export interface FactoryCodexTaskValidationPlan { validationPlanId: string; proposedChecks: string[]; proposedCommands: string[]; requiredEvidence: string[]; stopOnFailure: true; commandsExecuted: false; futureRunnerRequired: true }
export interface FactoryCodexTaskStopCondition { stopConditionId: string; description: string }
export interface FactoryCodexTaskEvidenceRequirement { evidenceRequirementId: string; description: string }
export interface FactoryCodexTaskResponseRequirement { responseRequirementId: string; description: string }
export interface FactoryCodexTaskIntent { taskIntentId: string; taskKind: FactoryCodexTaskKind; title: string; objective: string; nonGoals: string[]; acceptanceCriteria: FactoryCodexTaskAcceptanceCriterion[]; constraints: string[]; allowedSurfaces: FactoryCodexTaskAllowedSurface[]; forbiddenActions: FactoryCodexTaskForbiddenAction[]; proposedValidationPlan: FactoryCodexTaskValidationPlan; evidenceRequirements: FactoryCodexTaskEvidenceRequirement[]; responseRequirements: FactoryCodexTaskResponseRequirement[]; stopConditions: FactoryCodexTaskStopCondition[]; riskLevel: FactoryCodexTaskRiskLevel; requestedBy: string; requestedAt: string }
export interface FactoryCodexTaskContractCandidatePolicy { requireContextApprovalResult: true; requireApprovedContextEnvelope: true; requireTaskIntent: true; requireObjective: true; requireNonGoals: true; requireAcceptanceCriteria: true; requireValidationPlan: true; requireStopConditions: true; requireEvidenceRequirements: true; requireResponseRequirements: true; requireHumanReviewForHighRisk: true; requireHumanReviewForCodeChange: true; requireHumanReviewForProjectMaterialization: true; forbidPromptAssemblyInThisGate: true; forbidExecutableCodexTaskCreation: true; forbidCodexExecution: true; forbidFileMutation: true; forbidCommandExecution: true; forbidExternalNetwork: true; forbidSecretsAccess: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; forbidModelCalls: true; rejectUnsafeContextEnvelope: true; rejectDangerousTaskIntent: true }
export interface FactoryCodexTaskContractCandidateInput { memoryContextApprovalResult: FactoryMemoryContextApprovalResult; taskIntent: FactoryCodexTaskIntent; createdAt: string; createdBy: string; policy?: Partial<FactoryCodexTaskContractCandidatePolicy>; humanReviewRef?: string; projectRef?: string; repositoryRef?: string; reviewNotes?: string[] }
export interface FactoryCodexTaskContractCandidate { contractCandidateId: string; contractCandidateKind: FactoryCodexTaskContractCandidateKind; contractCandidateVersion: FactoryCodexTaskContractCandidateVersion; taskIntent: FactoryCodexTaskIntent; sourceContextApprovalId: string; sourceAssemblyId: string; sourceReadRuntimeId: string; sourceReadAdmissionId: string; contextEnvelopeRef: string; contextPackageSummary: { contextPurpose: string; itemCount: number; approxChars: number; codexTaskStatus: string; codexExecutionStatus: string }; allowedSurfaces: FactoryCodexTaskAllowedSurface[]; forbiddenActions: FactoryCodexTaskForbiddenAction[]; acceptanceCriteria: FactoryCodexTaskAcceptanceCriterion[]; validationPlan: FactoryCodexTaskValidationPlan; stopConditions: FactoryCodexTaskStopCondition[]; evidenceRequirements: FactoryCodexTaskEvidenceRequirement[]; responseRequirements: FactoryCodexTaskResponseRequirement[]; safetyBoundaries: string[]; handoffNotes: string[]; status: 'candidate_not_approved'; promptAssemblyStatus: 'not_generated'; codexTaskStatus: 'not_created'; codexExecutionStatus: 'not_allowed'; fileMutationStatus: 'not_allowed'; commandExecutionStatus: 'not_allowed'; externalNetworkStatus: 'not_allowed'; secretsAccessStatus: 'not_allowed'; projectStatus: 'not_created'; repositoryStatus: 'not_created'; deployStatus: 'not_allowed'; canAssembleCodexPrompt: false; canCreateExecutableCodexTask: false; canExecuteCodex: false; canModifyFiles: false; canRunCommands: false; canAccessSecrets: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export type FactoryCodexTaskContractCandidateDecision = 'blocked' | 'reject_task_intent' | 'request_task_contract_changes' | 'human_review_required' | 'approve_codex_task_contract_candidate'
export type FactoryCodexTaskContractCandidateStatus = 'blocked' | 'rejected' | 'changes_required' | 'human_review_required' | 'codex_task_contract_candidate_ready'
export interface FactoryCodexTaskContractCandidateCheck { checkId: string; passed: boolean; message: string }
export interface FactoryCodexTaskContractCandidateBlocker { blockerId: string; message: string; critical?: boolean }
export interface FactoryCodexTaskContractCandidateWarning { warningId: string; message: string }
export interface FactoryCodexTaskContractCandidateResult { candidateGateId: string; candidateGateKind: FactoryCodexTaskContractCandidateKind; candidateGateVersion: FactoryCodexTaskContractCandidateVersion; createdAt: string; createdBy: string; decision: FactoryCodexTaskContractCandidateDecision; status: FactoryCodexTaskContractCandidateStatus; contractCandidate?: FactoryCodexTaskContractCandidate; checks: FactoryCodexTaskContractCandidateCheck[]; blockers: FactoryCodexTaskContractCandidateBlocker[]; warnings: FactoryCodexTaskContractCandidateWarning[]; reasons: string[]; canAssembleCodexPrompt: false; canCreateExecutableCodexTask: false; canExecuteCodex: false; canModifyFiles: false; canRunCommands: false; canAccessSecrets: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryCodexTaskContractCandidateValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryCodexTaskContractCandidateSummary { candidateGateId: string; contractCandidateId?: string; taskKind?: FactoryCodexTaskKind; riskLevel?: FactoryCodexTaskRiskLevel; decision: FactoryCodexTaskContractCandidateDecision; status: FactoryCodexTaskContractCandidateStatus; promptAssemblyStatus: string; codexTaskStatus: string; codexExecutionStatus: string; fileMutationStatus: string; commandExecutionStatus: string; validationCommandsCount: number; canExecuteCodex: false; recommendedNextStep: string }

