import { FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_KIND, FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_NEXT_STEP, FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_VERSION } from './hermes-build-dependency-cache-approval.defaults.ts'
import type { FactoryHermesBuildDependencyCacheApprovalInput, FactoryHermesBuildDependencyCacheApprovalResult } from './hermes-build-dependency-cache-approval.types.ts'

function lockedVersion(plan: any): string | null {
  const text = JSON.stringify(plan?.sourceInspectionSummary?.uvLockSetuptoolsSummary || [])
  const match = text.match(/setuptools-([0-9]+\.[0-9]+\.[0-9]+)/u) || text.match(/==([0-9]+\.[0-9]+\.[0-9]+)/u)
  return match?.[1] || null
}

function base(input: FactoryHermesBuildDependencyCacheApprovalInput): FactoryHermesBuildDependencyCacheApprovalResult {
  const p = input.buildDependencyCachePlanningResult || {}
  const c = p.hermesBuildDependencyCachePlanCandidate || {}
  return { approvalId: `hermes-build-dependency-cache-approval:75b300f:${input.approvedAt}`, approvalKind: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_KIND, approvalVersion: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_VERSION, approvedAt: input.approvedAt, approvedBy: input.approvedBy, toolId: 'hermes_agent', selectedCandidateId: p.selectedCandidateId || c.selectedCandidateId || '', commandName: p.commandName || c.commandName || '', pythonEntrypoint: p.pythonEntrypoint || c.pythonEntrypoint || '', missingBuildDependency: p.missingBuildDependency || c.missingBuildDependency || '', lockedPackageName: 'setuptools', lockedPackageVersion: lockedVersion(p), buildBackend: p.buildBackend || c.buildBackend || '', setupPyPresent: p.setupPyPresent === true || c.setupPyPresent === true, uvExecutableRef: p.uvExecutableRef || c.uvExecutableRef || '.codex-temp/external-tools/uv/bin/uv.exe', uvCacheRootRef: p.uvCacheRootRef || c.uvCacheRootRef || '.codex-temp/external-tools/uv/cache/', sourceRootRef: p.sourceRootRef || c.sourceRootRef || '.codex-temp/external-tools/hermes-agent/install/75b300f/source', pythonEnvRootRef: p.pythonEnvRootRef || c.pythonEnvRootRef || '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env', selectedMethodCandidate: p.selectedMethodCandidate || c.selectedMethodCandidate || '', checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_cache_plan', canProceedToBuildDependencyCacheRuntime: false, canCacheBuildDependenciesNow: false, canEnableNetworkNow: false, canRetryMaterializationNow: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetworkNow: false, canUseNetworkInFutureRuntime: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_NEXT_STEP }
}

export function evaluateFactoryHermesBuildDependencyCacheApproval(input: FactoryHermesBuildDependencyCacheApprovalInput): FactoryHermesBuildDependencyCacheApprovalResult {
  const p = input.buildDependencyCachePlanningResult
  const out = base(input)
  const candidate = p?.hermesBuildDependencyCachePlanCandidate
  if (!p) return { ...out, blockers: [{ blockerId: 'blocked_missing_cache_plan', message: 'Build dependency cache planning result is required.' }] }
  if (p.status !== 'plan_candidate_created' || p.decision !== 'hermes_build_dependency_cache_plan_candidate_created' || p.canProceedToBuildDependencyCacheApproval !== true || !candidate) return { ...out, decision: 'blocked_cache_plan_not_candidate', blockers: [{ blockerId: 'blocked_cache_plan_not_candidate', message: 'Planning result is not a valid plan candidate.' }] }
  if (out.selectedMethodCandidate !== 'uv_controlled_build_dependency_cache_prefetch') return { ...out, decision: 'blocked_unsafe_cache_method', blockers: [{ blockerId: 'blocked_unsafe_cache_method', message: 'Only uv_controlled_build_dependency_cache_prefetch can be approved.' }] }
  if (!/setuptools/iu.test(out.missingBuildDependency) || out.lockedPackageName !== 'setuptools') return { ...out, decision: 'blocked_missing_package_identity', blockers: [{ blockerId: 'blocked_missing_package_identity', message: 'Missing setuptools package identity.' }] }
  if (candidate.proposedArtifactPolicy?.requireHashCapture !== true || candidate.proposedArtifactPolicy?.requirePackageNameVersionRecord !== true || candidate.proposedArtifactPolicy?.requireDownloadUrlRecord !== true) return { ...out, decision: 'blocked_missing_hash_policy', blockers: [{ blockerId: 'blocked_missing_hash_policy', message: 'Hash/package/url capture policy is required.' }] }
  if (!input.humanApprovalRef) return { ...out, status: 'human_review_required', decision: 'blocked_missing_human_approval', blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] }
  if (!input.networkRiskAcceptanceNotes) return { ...out, decision: 'blocked_missing_network_risk_acceptance', blockers: [{ blockerId: 'blocked_missing_network_risk_acceptance', message: 'networkRiskAcceptanceNotes are required.' }] }
  if (!input.hashVerificationPolicyNotes) return { ...out, decision: 'blocked_missing_hash_policy', blockers: [{ blockerId: 'blocked_missing_hash_policy', message: 'hashVerificationPolicyNotes are required.' }] }
  const decision = 'hermes_build_dependency_cache_approved_for_runtime_candidate' as const
  const receipt = { receiptId: `${out.approvalId}:receipt`, approvalId: out.approvalId, toolId: 'hermes_agent' as const, approvedBy: input.approvedBy, approvedAt: input.approvedAt, humanApprovalRef: input.humanApprovalRef, missingBuildDependency: out.missingBuildDependency, lockedPackageName: out.lockedPackageName, lockedPackageVersion: out.lockedPackageVersion, selectedMethodCandidate: out.selectedMethodCandidate, networkRiskAcceptanceNotes: input.networkRiskAcceptanceNotes, packageIndexPolicyNotes: input.packageIndexPolicyNotes || '', hashVerificationPolicyNotes: input.hashVerificationPolicyNotes, decision, scope: 'hermes_build_dependency_cache_runtime_candidate_only' as const, approvedNextGate: 'Factory Hermes Build Dependency Cache Runtime Adapter v1' as const, limitations: ['Approval is for a future cache runtime candidate only.', 'No cache action, network enablement, uv execution, materialization retry or Hermes execution is authorized in this gate.'], notAuthorizedActions: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_NOT_AUTHORIZED_ACTIONS }
  const envelope = { envelopeId: `${out.approvalId}:envelope`, approvalId: out.approvalId, toolId: 'hermes_agent' as const, selectedCandidateId: out.selectedCandidateId, commandName: 'hermes' as const, pythonEntrypoint: 'hermes_cli.main:main' as const, missingBuildDependency: out.missingBuildDependency, lockedPackageName: 'setuptools' as const, lockedPackageVersion: out.lockedPackageVersion, versionConstraint: out.missingBuildDependency, buildBackend: 'setuptools.build_meta' as const, setupPyPresent: out.setupPyPresent, uvExecutableRef: out.uvExecutableRef, uvCacheRootRef: out.uvCacheRootRef, sourceRootRef: out.sourceRootRef, pythonEnvRootRef: out.pythonEnvRootRef, metadataRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-metadata/', tempEnvRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-temp-env/', selectedMethodCandidate: 'uv_controlled_build_dependency_cache_prefetch' as const, approvedRuntimeNetworkScope: 'cache_prefetch_only' as const, networkAllowedNow: false as const, futureRuntimeMayUseNetworkForCachePrefetch: true as const, futureRuntimeNetworkMustBeDisabledAfterCache: true as const, futureMaterializationRuntimeMustRemainOffline: true as const, allowedFutureHostsCandidate: [], approvedRuntimeCommandPolicy: { commandsAllowedNow: [], futureRuntimeAllowedCommandFamilies: ['uv_cache_prefetch_only'], forbiddenCommandFamilies: ['pip', 'python direct', 'setup.py direct', 'hermes', 'uv run', 'uv pip', 'uv venv against real pythonEnv'] }, approvedEnvPolicy: { sanitized: true, noCredentials: true, noEnvRead: true, UV_CACHE_DIR: '.codex-temp/external-tools/uv/cache/', UV_NO_PROGRESS: '1', PYTHONNOUSERSITE: '1', NO_COLOR: '1' }, approvedWriteRoots: [out.uvCacheRootRef, '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-metadata/', '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-temp-env/'], forbiddenWriteRoots: ['project repo', '.env', 'user home', 'system dirs', 'real pythonEnvRoot except read-only unless explicitly approved later'], requiredMetadata: ['package name', 'resolved version', 'constraint', 'source URL or index record', 'hashes', 'cache paths', 'no credentials'], cacheAllowedNow: false as const, futureRuntimeMayCacheBuildDependencyUnderEnvelope: true as const, materializationRetryAllowedNow: false as const, hermesExecutionAllowedNow: false as const, networkAllowedNowForThisGate: false as const, credentialsAllowedNow: false as const, modelCallsAllowedNow: false as const, canProceedToBuildDependencyCacheRuntime: true as const, recommendedNextStep: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_APPROVAL_NEXT_STEP }
  return { ...out, status: 'approved_for_runtime_candidate', decision, approvalReceipt: receipt, approvedBuildDependencyCacheRuntimeEnvelope: envelope, canProceedToBuildDependencyCacheRuntime: true, canUseNetworkInFutureRuntime: true }
}
