import { FACTORY_HERMES_RESEARCH_JEFE_REVIEW_KIND, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_NEXT_STEP, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_VERSION } from './hermes-research-jefe-review.defaults.ts'
import type { FactoryHermesResearchJefeReviewInput, FactoryHermesResearchJefeReviewResult } from './hermes-research-jefe-review.types.ts'
const ingestionRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/research-result-ingestion-result.json'
const sourceRootRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/source'
const pythonEnvRootRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env'
const missingExecutableRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/Scripts/hermes.exe'
function base(input: FactoryHermesResearchJefeReviewInput): FactoryHermesResearchJefeReviewResult { const i = input.ingestionResult || {}; const r = i.hermesResearchResultIngestionRecord || {}; return { jefeReviewId: `hermes-research-jefe-review:75b300f:${input.reviewedAt}`, jefeReviewKind: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_KIND, jefeReviewVersion: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_VERSION, reviewedAt: input.reviewedAt, reviewedBy: input.reviewedBy, toolId: 'hermes_agent', selectedCandidateId: i.selectedCandidateId || r.selectedCandidateId || '', commandName: i.commandName || r.commandName || '', pythonEntrypoint: i.pythonEntrypoint || r.pythonEntrypoint || '', ingestionRef, adapterRunRef: i.adapterRunRef || r.adapterRunRef || '', adapterDecision: i.adapterDecision || r.adapterDecision || '', classification: i.classification || r.classification || '', normalizedOutcome: r.normalizedOutcome || '', checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_ingestion_result', canProceedToEntrypointMaterializationPlanning: false, canMaterializeEntrypointNow: false, canRetryAdapterNow: false, canTreatAsResearchResult: false, canUseFindings: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_NEXT_STEP } }
export function evaluateFactoryHermesResearchJefeReview(input: FactoryHermesResearchJefeReviewInput): FactoryHermesResearchJefeReviewResult {
  const i = input.ingestionResult; const out = base(input); const record = i?.hermesResearchResultIngestionRecord
  if (!i || !record) return { ...out, blockers: [{ blockerId: 'blocked_missing_ingestion_result', message: 'Ingestion result is required.' }] }
  if (i.status !== 'ingested' || i.canProceedToResearchJefeReview !== true || i.canProceedToEntrypointMaterializationReview !== true) return { ...out, decision: 'blocked_ingestion_not_reviewable', blockers: [{ blockerId: 'blocked_ingestion_not_reviewable', message: 'Ingestion result is not reviewable.' }] }
  if (i.canTreatAsResearchResult !== false || i.canUseFindings !== false) return { ...out, decision: 'blocked_ingestion_claims_research_result', blockers: [{ blockerId: 'blocked_ingestion_claims_research_result', message: 'Ingestion cannot be treated as research result.' }] }
  if (i.canExecuteHermes !== false || i.canUseNetwork !== false || i.canUseCredentials !== false || i.canCallModels !== false) return { ...out, decision: 'blocked_boundary_violation_detected', blockers: [{ blockerId: 'blocked_boundary_violation_detected', message: 'Boundary violation detected.' }] }
  if (i.adapterDecision !== 'blocked_executable_missing' || i.classification !== 'controlled_adapter_block' || record.normalizedOutcome !== 'entrypoint_executable_missing') return { ...out, decision: 'request_adapter_repair_before_review', blockers: [{ blockerId: 'request_adapter_repair_before_review', message: 'This review flow expects blocked_executable_missing.' }] }
  if (!input.humanApprovalRef) return { ...out, status: 'human_review_required', decision: 'blocked_missing_human_approval', blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] }
  const id = out.jefeReviewId
  const receipt = { receiptId: `${id}:receipt`, jefeReviewId: id, toolId: 'hermes_agent' as const, reviewedBy: input.reviewedBy, reviewedAt: input.reviewedAt, humanApprovalRef: input.humanApprovalRef, adapterDecision: i.adapterDecision, classification: i.classification, normalizedOutcome: record.normalizedOutcome, decision: 'hermes_research_jefe_review_approved_entrypoint_materialization_planning' as const, scope: 'hermes_research_jefe_review_only' as const, approvedNextGate: 'Factory Hermes Entrypoint Materialization Planning Gate v1' as const, limitations: ['Approval is for planning only.', 'No entrypoint materialization is authorized now.', 'No adapter retry or Hermes execution is authorized.'], notAuthorizedActions: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_NOT_AUTHORIZED_ACTIONS }
  const reviewRecord = { recordId: `${id}:record`, jefeReviewId: id, toolId: 'hermes_agent' as const, selectedCandidateId: out.selectedCandidateId, commandName: out.commandName, pythonEntrypoint: out.pythonEntrypoint, ingestionRef, adapterRunRef: out.adapterRunRef, adapterDecision: out.adapterDecision, classification: out.classification, normalizedOutcome: out.normalizedOutcome, jefeAssessment: 'controlled block is valid and expected given no-install-project strategy', rootCause: 'package entrypoint wrapper missing because project package was not installed', approvedNextPlanning: 'Factory Hermes Entrypoint Materialization Planning Gate v1' as const, safetyConclusion: 'no research result, no findings, no Hermes execution, no model/network/credential use', canProceedToEntrypointMaterializationPlanning: true as const, canMaterializeEntrypointNow: false as const, canRetryAdapterNow: false as const }
  const envelope = { envelopeId: `${id}:envelope`, jefeReviewId: id, toolId: 'hermes_agent' as const, selectedCandidateId: out.selectedCandidateId, commandName: 'hermes' as const, pythonEntrypoint: 'hermes_cli.main:main' as const, missingExecutableRef, sourceRootRef, pythonEnvRootRef, currentInstallMethod: 'uv sync --locked --no-install-project --no-dev --project' as const, suspectedRepairFamily: 'entrypoint_materialization' as const, allowedNextGate: 'Factory Hermes Entrypoint Materialization Planning Gate v1' as const, materializationAllowedNow: false as const, adapterRetryAllowedNow: false as const, hermesExecutionAllowedNow: false as const, networkAllowedNow: false as const, credentialsAllowedNow: false as const, modelCallsAllowedNow: false as const, requiredPlanningQuestions: ['Should materialization use uv sync --locked --no-dev --project without --no-install-project?', 'Can the project package be installed into existing python-env without setup.py execution?', 'Does uv install project trigger build hooks?', 'How to preserve no pip/setup.py/direct python execution?', 'How to verify console script wrapper without launching Hermes beyond --help?'], requiredFutureGates: ['Factory Hermes Entrypoint Materialization Planning Gate v1', 'Factory Hermes Entrypoint Materialization Approval Gate v1', 'Factory Hermes Entrypoint Materialization Runtime Adapter v1', 'Factory Hermes Entrypoint Materialization Verification Gate v1', 'Factory Hermes Research Runtime Adapter Retry Gate v1'] }
  return { ...out, status: 'approved_for_entrypoint_materialization_planning', decision: 'hermes_research_jefe_review_approved_entrypoint_materialization_planning', researchJefeReviewReceipt: receipt, hermesResearchJefeReviewRecord: reviewRecord, approvedEntrypointMaterializationPlanningEnvelope: envelope, canProceedToEntrypointMaterializationPlanning: true }
}
