export type FactoryHermesResearchJefeReviewVersion = '1.0'
export type FactoryHermesResearchJefeReviewKind = 'factory-hermes-research-jefe-review'
export type FactoryHermesResearchJefeReviewStatus = 'approved_for_entrypoint_materialization_planning' | 'blocked' | 'human_review_required'
export type FactoryHermesResearchJefeReviewDecision = 'hermes_research_jefe_review_approved_entrypoint_materialization_planning' | 'blocked_missing_ingestion_result' | 'blocked_ingestion_not_reviewable' | 'blocked_ingestion_claims_research_result' | 'blocked_boundary_violation_detected' | 'blocked_missing_human_approval' | 'request_adapter_repair_before_review'
export interface FactoryHermesResearchJefeReviewInput { reviewedAt: string; reviewedBy: string; humanApprovalRef?: string; ingestionResult?: any; adapterResult?: any; approvalResult?: any; boundaryResult?: any; policy?: Partial<FactoryHermesResearchJefeReviewPolicy>; reviewNotes?: string }
export interface FactoryHermesResearchJefeReviewPolicy { requireIngestionResult: boolean; requireIngestionStatusIngested: boolean; requireControlledAdapterBlockForMaterializationPlanning: boolean; requireHumanApprovalRef: boolean; requireNoResearchResult: boolean; requireNoFindingsUse: boolean; requireNoBoundaryViolation: boolean; requireAdapterDecisionBlockedExecutableMissing: boolean; requirePythonInstallVerified: boolean; requireBoundaryApprovalTrace: boolean; requireEntrypointMaterializationPlanningNext: boolean; forbidEntrypointMaterializationInThisGate: boolean; forbidAdapterRetryInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidHermesScriptsInThisGate: boolean; forbidUvExecutionInThisGate: boolean; forbidPipExecutionInThisGate: boolean; forbidPythonExecutionInThisGate: boolean; forbidSetupPyExecutionInThisGate: boolean; forbidNetworkInThisGate: boolean; forbidCredentialsInThisGate: boolean; forbidModelCallsInThisGate: boolean; forbidProjectMutationInThisGate: boolean; forbidDeployInThisGate: boolean }
export interface FactoryHermesResearchJefeReviewReceipt { receiptId: string; jefeReviewId: string; toolId: 'hermes_agent'; reviewedBy: string; reviewedAt: string; humanApprovalRef: string; adapterDecision: string; classification: string; normalizedOutcome: string; decision: FactoryHermesResearchJefeReviewDecision; scope: 'hermes_research_jefe_review_only'; approvedNextGate: 'Factory Hermes Entrypoint Materialization Planning Gate v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesResearchJefeReviewRecord { recordId: string; jefeReviewId: string; toolId: 'hermes_agent'; selectedCandidateId: string; commandName: string; pythonEntrypoint: string; ingestionRef: string; adapterRunRef: string; adapterDecision: string; classification: string; normalizedOutcome: string; jefeAssessment: string; rootCause: string; approvedNextPlanning: 'Factory Hermes Entrypoint Materialization Planning Gate v1'; safetyConclusion: string; canProceedToEntrypointMaterializationPlanning: true; canMaterializeEntrypointNow: false; canRetryAdapterNow: false }
export interface FactoryHermesEntrypointMaterializationPlanningEnvelope { envelopeId: string; jefeReviewId: string; toolId: 'hermes_agent'; selectedCandidateId: string; commandName: 'hermes'; pythonEntrypoint: 'hermes_cli.main:main'; missingExecutableRef: string; sourceRootRef: string; pythonEnvRootRef: string; currentInstallMethod: 'uv sync --locked --no-install-project --no-dev --project'; suspectedRepairFamily: 'entrypoint_materialization'; allowedNextGate: 'Factory Hermes Entrypoint Materialization Planning Gate v1'; materializationAllowedNow: false; adapterRetryAllowedNow: false; hermesExecutionAllowedNow: false; networkAllowedNow: false; credentialsAllowedNow: false; modelCallsAllowedNow: false; requiredPlanningQuestions: string[]; requiredFutureGates: string[] }
export interface FactoryHermesResearchJefeReviewCheck { checkId: string; ok: boolean; message: string }
export interface FactoryHermesResearchJefeReviewBlocker { blockerId: string; message: string }
export interface FactoryHermesResearchJefeReviewWarning { warningId: string; message: string }
export interface FactoryHermesResearchJefeReviewResult { jefeReviewId: string; jefeReviewKind: FactoryHermesResearchJefeReviewKind; jefeReviewVersion: FactoryHermesResearchJefeReviewVersion; reviewedAt: string; reviewedBy: string; toolId: 'hermes_agent'; selectedCandidateId: string; commandName: string; pythonEntrypoint: string; ingestionRef: string; adapterRunRef: string; adapterDecision: string; classification: string; normalizedOutcome: string; researchJefeReviewReceipt?: FactoryHermesResearchJefeReviewReceipt; hermesResearchJefeReviewRecord?: FactoryHermesResearchJefeReviewRecord; approvedEntrypointMaterializationPlanningEnvelope?: FactoryHermesEntrypointMaterializationPlanningEnvelope; checks: FactoryHermesResearchJefeReviewCheck[]; blockers: FactoryHermesResearchJefeReviewBlocker[]; warnings: FactoryHermesResearchJefeReviewWarning[]; status: FactoryHermesResearchJefeReviewStatus; decision: FactoryHermesResearchJefeReviewDecision; canProceedToEntrypointMaterializationPlanning: boolean; canMaterializeEntrypointNow: false; canRetryAdapterNow: false; canTreatAsResearchResult: false; canUseFindings: false; canExecuteHermes: false; canRunHermesScripts: false; canUseNetwork: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesResearchJefeReviewValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesResearchJefeReviewSummary { jefeReviewId: string; selectedCandidateId: string; commandName: string; adapterDecision: string; classification: string; normalizedOutcome: string; decision: FactoryHermesResearchJefeReviewDecision; canProceedToEntrypointMaterializationPlanning: boolean; canMaterializeEntrypointNow: false; canRetryAdapterNow: false; nextStep: string }
