import { FACTORY_PROJECT_CONTRACT_PERSISTENCE_KIND, FACTORY_PROJECT_CONTRACT_PERSISTENCE_STATUSES, FACTORY_PROJECT_CONTRACT_PERSISTENCE_VERSION } from './project-contract-persistence.defaults.ts'
import type { FactoryProjectContractPersistenceInput, FactoryProjectContractPersistenceResult, FactoryProjectContractPersistenceValidationResult } from './project-contract-persistence.types.ts'

const forbiddenEnvKeys = ['value', 'actualValue', 'token', 'apiKeyValue', 'secretValue']; const secretPattern = /(api[_-]?key|secret|password|token)\s*[:=]\s*[^\s]{8,}/iu
const unsafePath = (value: string) => /^(?:[a-z]:[\\/]|[\\/]{1,2})/iu.test(value) || value.split(/[\\/]+/u).includes('..')
const hasEnvValues = (value: unknown): boolean => Array.isArray(value) ? value.some(hasEnvValues) : Boolean(value && typeof value === 'object' && (forbiddenEnvKeys.some((key) => Object.prototype.hasOwnProperty.call(value, key)) || Object.values(value).some(hasEnvValues)))
export function validateFactoryProjectContractPersistenceInput(input: FactoryProjectContractPersistenceInput): FactoryProjectContractPersistenceValidationResult {
  const errors: string[] = []; const warnings: string[] = []; const approval = input?.approvalResult; const envelope = approval?.approvedContractEnvelope
  if (!approval) errors.push('approvalResult is required.'); if (!input?.createdAt?.trim()) errors.push('createdAt is required.'); if (!input?.plannedBy?.trim()) errors.push('plannedBy is required.'); if (approval && !approval.approvalId.trim()) errors.push('approvalId is required.'); if (!envelope) errors.push('approvedContractEnvelope is required.'); if (envelope && !envelope.contractDraft) errors.push('contractDraft is required.'); if (envelope && envelope.validation.ok !== true) errors.push('Contract validation must pass.'); if (secretPattern.test(JSON.stringify(input))) errors.push('Input appears to contain a secret value.')
  return { ok: errors.length === 0, errors, warnings }
}
export function validateFactoryProjectContractPersistenceResult(result: FactoryProjectContractPersistenceResult): FactoryProjectContractPersistenceValidationResult {
  const errors: string[] = []; const warnings = result.warnings.map((item) => item.message); const ready = result.status === 'ready_for_runtime_persistence'
  if (result.persistenceKind !== FACTORY_PROJECT_CONTRACT_PERSISTENCE_KIND) errors.push('persistenceKind is invalid.'); if (result.persistenceVersion !== FACTORY_PROJECT_CONTRACT_PERSISTENCE_VERSION) errors.push('persistenceVersion is invalid.'); if (!result.approvalId.trim()) errors.push('approvalId is required.'); if (!FACTORY_PROJECT_CONTRACT_PERSISTENCE_STATUSES.includes(result.status)) errors.push('status is invalid.')
  if (result.canExecuteCodex !== false || result.canCreateProject !== false || result.canCreateRepository !== false || result.canDeploy !== false || result.filesystemWritePerformed !== false) errors.push('Execution, creation, deploy and filesystem writes must remain disabled.')
  if (ready && (!result.canonicalPayload || !result.fingerprint || !result.idempotencyKey || !result.target || !result.atomicWritePlan || !result.rollbackPlan)) errors.push('Ready result requires canonical payload, fingerprint, idempotency, target, atomic write and rollback plans.'); if (!ready && result.blockers.length === 0) errors.push('Blocked result requires blockers.')
  if (result.atomicWritePlan && (result.atomicWritePlan.notExecuted !== true || result.atomicWritePlan.filesystemWritePerformed !== false)) errors.push('Atomic write plan must remain unexecuted.'); if (result.rollbackPlan && (result.rollbackPlan.notExecuted !== true || result.rollbackPlan.rollbackExecuted !== false)) errors.push('Rollback plan must remain unexecuted.')
  for (const path of [result.target?.targetPath, result.target?.metadataPath, result.atomicWritePlan?.tempPath, result.atomicWritePlan?.backupPath, result.atomicWritePlan?.lockPath].filter((item): item is string => Boolean(item))) if (unsafePath(path)) errors.push(`Unsafe persistence path: ${path}`)
  if (result.canonicalPayload && hasEnvValues(result.canonicalPayload.contract.environmentVariables)) errors.push('Canonical payload contains forbidden environment values.'); if (!result.recommendedNextStep.trim()) errors.push('recommendedNextStep is required.'); if (secretPattern.test(JSON.stringify(result))) errors.push('Result appears to contain a secret value.')
  return { ok: errors.length === 0, errors, warnings }
}
