import type { FactoryProjectContractV1 } from '../project-contract/index.ts'
import type { FactoryProjectContractApprovalResult } from '../project-contract-approval/index.ts'

export type FactoryProjectContractPersistenceVersion = '1.0'
export type FactoryProjectContractPersistenceKind = 'factory-project-contract-persistence'
export type FactoryProjectContractPersistenceStatus = 'ready_for_runtime_persistence' | 'blocked'
export interface FactoryProjectContractPersistencePolicy { requireApprovedContractEnvelope: true; requireApprovalReceipt: true; requireContractValidationOk: true; requirePersistenceStatusNotPersisted: true; requireRuntimeNotExecutable: true; requireCodexNotAllowed: true; requireRepositoryNotCreated: true; requireDeployNotAllowed: true; requireCanonicalPayload: true; requireFingerprint: true; requireIdempotencyKey: true; requireAtomicWritePlan: true; requireRollbackPlan: true; requireRelativePersistenceTarget: true; forbidAbsolutePaths: true; forbidPathTraversal: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; forbidFilesystemWriteInThisGate: true }
export interface FactoryProjectContractPersistenceInput { approvalResult: FactoryProjectContractApprovalResult; createdAt: string; plannedBy: string; policy?: Partial<FactoryProjectContractPersistencePolicy>; storageNamespace?: string; persistenceRootSuggestion?: string }
export interface FactoryProjectContractPersistenceCheck { checkId: string; category: 'approval' | 'envelope' | 'validation' | 'target' | 'canonicalization' | 'execution'; passed: boolean; message: string }
export interface FactoryProjectContractPersistenceBlocker { blockerId: string; category: FactoryProjectContractPersistenceCheck['category']; message: string }
export interface FactoryProjectContractPersistenceWarning { warningId: string; message: string }
export interface FactoryProjectContractCanonicalPayload { contractKind: 'factory-project-contract'; contractVersion: '1.0'; projectId: string; contract: FactoryProjectContractV1; canonicalJson: string }
export interface FactoryProjectContractFingerprint { algorithm: 'fnv1a-32'; value: string; cryptographic: false; purpose: 'idempotency_and_basic_change_detection' }
export interface FactoryProjectContractIdempotencyKey { value: string; inputs: { contractKind: string; contractVersion: string; projectId: string; approvalId: string; fingerprint: string; targetPath: string } }
export interface FactoryProjectContractPersistenceTarget { storageNamespace: string; targetPath: string; metadataPath: string; relative: true }
export interface FactoryProjectContractAtomicWritePlan { planId: string; targetPath: string; tempPath: string; backupPath: string; lockPath: string; steps: Array<'ensure_parent_directory' | 'write_temp_file' | 'validate_temp_payload' | 'atomic_rename_temp_to_target' | 'write_metadata' | 'verify_readback'>; notExecuted: true; filesystemWritePerformed: false; futureRuntimeAdapterRequired: true; humanApprovalRequiredBeforeExecution: true }
export interface FactoryProjectContractRollbackPlan { rollbackId: string; triggerConditions: string[]; steps: Array<'remove_temp_file' | 'preserve_failed_payload_for_review' | 'restore_previous_contract_if_backup_exists' | 'mark_persistence_failed' | 'require_human_review'>; notExecuted: true; rollbackExecuted: false }
export interface FactoryProjectContractPersistenceResult { persistenceId: string; persistenceKind: FactoryProjectContractPersistenceKind; persistenceVersion: FactoryProjectContractPersistenceVersion; createdAt: string; plannedBy: string; approvalId: string; compatibilityId: string; candidateId: string; contractProjectId: string; status: FactoryProjectContractPersistenceStatus; canPersistContract: boolean; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; filesystemWritePerformed: false; canonicalPayload?: FactoryProjectContractCanonicalPayload; fingerprint?: FactoryProjectContractFingerprint; idempotencyKey?: FactoryProjectContractIdempotencyKey; target?: FactoryProjectContractPersistenceTarget; atomicWritePlan?: FactoryProjectContractAtomicWritePlan; rollbackPlan?: FactoryProjectContractRollbackPlan; checks: FactoryProjectContractPersistenceCheck[]; blockers: FactoryProjectContractPersistenceBlocker[]; warnings: FactoryProjectContractPersistenceWarning[]; recommendedNextStep: string }
export interface FactoryProjectContractPersistenceValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryProjectContractPersistenceSummary { persistenceId: string; approvalId: string; projectId: string; status: FactoryProjectContractPersistenceStatus; fingerprint?: string; idempotencyKey?: string; targetPath?: string; canPersistContract: boolean; notExecuted: boolean; blockersCount: number; warningsCount: number; recommendedNextStep: string }
