function blocker(reason) { return { reason }; }
function validation(blockers) { return { ok: blockers.length === 0, blockers: blockers.map(blocker) }; }
function validateApprovedPromptArtifactRef(input) { const text = `${input?.ref || ''} ${input?.path || ''} ${input?.hash || ''} ${input?.safeSummary || ''}`.toLowerCase(); return validation([!input?.ref && 'prompt_artifact_ref_required', !input?.path && 'prompt_artifact_path_required', !input?.hash && 'prompt_artifact_hash_required', !input?.safeSummary && 'prompt_artifact_safe_summary_required', ['secret', 'token', 'password', 'apikey', 'api_key', 'credential', 'openai_api_key='].some((x) => text.includes(x)) && 'prompt_artifact_contains_secret_indicator'].filter(Boolean)); }
function validateResearchOutputContract(input) { return validation([!input?.schema && 'output_schema_required', input?.boundedOutput !== true && 'bounded_output_required', (!input?.maxBytes || input.maxBytes <= 0) && 'positive_output_bound_required'].filter(Boolean)); }
function validateProviderModelHostRefs(input) { return validation([input?.providerRef !== 'openai' && 'provider_ref_must_be_openai', input?.modelRef !== 'gpt-4o-mini' && 'model_ref_must_be_gpt_4o_mini', input?.hostRef !== 'api.openai.com' && 'host_ref_must_be_api_openai_com'].filter(Boolean)); }
function validateCredentialRefOnly(input) { return validation([input?.credentialRef !== 'OPENAI_API_KEY' && 'credential_ref_must_be_OPENAI_API_KEY', input?.credentialValue && 'credential_value_forbidden'].filter(Boolean)); }
function validateNoToolPolicy(input) { return validation(['toolsAllowed', 'toolRegistryAllowed', 'mcpAllowed', 'functionDeclarationsAllowed', 'toolChoiceAllowed'].filter((key) => input?.[key] !== false).map((key) => `${key}_must_be_false`)); }
function validateRuntimeTimeoutPolicy(input) { return validation([(!input?.maxRuntimeMs || input.maxRuntimeMs <= 0) && 'positive_timeout_required', input?.maxRuntimeMs > 120000 && 'timeout_exceeds_reasonable_limit'].filter(Boolean)); }
function validateOutputBoundsPolicy(input) { return validation([(!input?.maxBytes || input.maxBytes <= 0) && 'positive_output_bound_required', input?.findingsBlockedByDefault !== true && 'findings_must_be_blocked_by_default'].filter(Boolean)); }
function validateRedactionPolicy(input) { return validation([input?.enabled !== true && 'redaction_enabled_required', input?.secretPatternsBlocked !== true && 'secret_pattern_blocking_required'].filter(Boolean)); }
function summarizeControlledResearchRuntimeContract(input) { return { keys: Object.keys(input || {}).sort(), safeSummary: 'controlled research runtime contracts validated without execution' }; }
function buildRuntimeAuditManifest(input) { return { auditKind: 'controlled_research_runtime_contract_audit', redacted: true, runtimeExecuted: false, credentialsRead: false, networkUsed: false, modelCalled: false, findingsPromoted: false, summary: summarizeControlledResearchRuntimeContract(input) }; }
module.exports = { validateApprovedPromptArtifactRef, validateResearchOutputContract, validateProviderModelHostRefs, validateCredentialRefOnly, validateNoToolPolicy, validateRuntimeTimeoutPolicy, validateOutputBoundsPolicy, validateRedactionPolicy, buildRuntimeAuditManifest, buildRuntimeContractBlocker: blocker, summarizeControlledResearchRuntimeContract, serializeControlledResearchRuntimeContract: (x) => JSON.stringify(x, null, 2), parseControlledResearchRuntimeContract: JSON.parse };
