import { DEFAULT_FACTORY_HERMES_OUTPUT_CONTRACT_POLICY_PLANNING_POLICY, FACTORY_HERMES_OUTPUT_CONTRACT_POLICY_PLANNING_KIND, FACTORY_HERMES_OUTPUT_CONTRACT_POLICY_PLANNING_NEXT_STEP, FACTORY_HERMES_OUTPUT_CONTRACT_POLICY_PLANNING_VERSION, OUTPUT_CONTRACT_NOT_AUTHORIZED_ACTIONS, OUTPUT_CONTRACT_REQUIRED_NEXT_POLICIES } from './hermes-output-contract-policy-planning.defaults.ts'
import type { FactoryHermesOutputContractPolicyPlanningInput, FactoryHermesOutputContractPolicyPlanningResult, FactoryHermesOutputContractRule, FactoryHermesOutputSurfaceCandidate } from './hermes-output-contract-policy-planning.types.ts'

function surfaces(): FactoryHermesOutputSurfaceCandidate[] {
  return [
    { surfaceId: 'stdout_final_response_plain_text', status: 'candidate_requires_ingestion_contract', reason: 'oneshot appears to return/print final_response as text.', canUseNow: false, findingsUsableNow: false },
    { surfaceId: 'stderr_logs_or_errors', status: 'operational_logs_only', reason: 'stderr is operational/error output only.', canUseNow: false, findingsUsableNow: false },
    { surfaceId: 'usage_file_json', status: 'auxiliary_usage_metadata_only', reason: 'usage-file may include usage/cost/tokens/model/api_calls, not findings schema.', canUseNow: false, findingsUsableNow: false },
    { surfaceId: 'structured_json_findings', status: 'not_available', reason: 'No explicit structured findings schema is proven.', canUseNow: false, findingsUsableNow: false },
    { surfaceId: 'raw_stdout_as_findings', status: 'forbidden', reason: 'Raw stdout cannot become findings without ingestion and JEFE Review.', canUseNow: false, findingsUsableNow: false },
    { surfaceId: 'help_output_as_findings', status: 'forbidden', reason: 'Help output is operational-only.', canUseNow: false, findingsUsableNow: false },
    { surfaceId: 'logs_as_findings', status: 'forbidden', reason: 'Logs/debug/errors are not research findings.', canUseNow: false, findingsUsableNow: false },
    { surfaceId: 'tool_output_as_findings', status: 'forbidden_until_toolsets_and_ingestion_review', reason: 'Toolsets disabled and tool output needs separate ingestion.', canUseNow: false, findingsUsableNow: false },
  ]
}

function rules(): FactoryHermesOutputContractRule[] {
  return [
    { ruleId: 'no_findings_now', ruleName: 'No findings now', requirements: ['canUseFindings false.', 'No raw output can be used directly.'] },
    { ruleId: 'output_surfaces', ruleName: 'Output surfaces', requirements: ['stdout candidate for final textual response.', 'stderr operational/error only.', 'usage-file metadata only.', 'logs operational only.'] },
    { ruleId: 'future_capture', ruleName: 'Required future output contract', requirements: ['Capture stdoutPreview, stderrPreview, truncation flags, exitCode, timedOut, killed, signal, usageFileRef, outputSanitized, outputSizeBytes and outputSha256 if saved.'] },
    { ruleId: 'size_limits', ruleName: 'Size limits', requirements: ['stdout preview <= 12000 bytes.', 'stderr preview <= 12000 bytes.', 'No unlimited logs.'] },
    { ruleId: 'sanitization', ruleName: 'Sanitization', requirements: ['Redact secrets/tokens/API keys.', 'No env dumps.', 'No credential values.', 'No source dumps or binary content.'] },
    { ruleId: 'findings_boundary', ruleName: 'Findings boundary', requirements: ['Raw output is candidate evidence only after runtime.', 'Findings unusable until Result Ingestion + JEFE Review.'] },
    { ruleId: 'schema_expectation', ruleName: 'Schema expectation', requirements: ['If no JSON schema exists, ingestion treats output as unstructured text.', 'No automatic promotion to findings.'] },
    { ruleId: 'usage_file', ruleName: 'Usage file', requirements: ['Usage file is metadata only.', 'Path under codex temp in future runtime.', 'Not findings.'] },
    { ruleId: 'failure_output', ruleName: 'Failure output', requirements: ['Errors/timeouts are operational results.', 'Failed runtime output cannot be research findings.'] },
    { ruleId: 'runtime_reporting', ruleName: 'Runtime reporting', requirements: ['Report outputContractStatus.', 'findingUseAllowed false until JEFE Review.'] },
  ]
}

function base(input: FactoryHermesOutputContractPolicyPlanningInput): FactoryHermesOutputContractPolicyPlanningResult {
  return { planningId: `hermes-output-contract-policy-planning:75b300f:${input.plannedAt}`, planningKind: FACTORY_HERMES_OUTPUT_CONTRACT_POLICY_PLANNING_KIND, planningVersion: FACTORY_HERMES_OUTPUT_CONTRACT_POLICY_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', commandShapeUnderConsideration: 'oneshot_real_with_provider_model', futureCommandShape: 'hermes.exe --oneshot "<PROMPT>" --provider <PROVIDER> --model <MODEL> --toolsets <TOOLSETS>', outputSurfaceCandidates: [], checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_toolsets_policy_planning', canProceedToResultIngestionContractPlanning: false, canProceedToResearchExecutionApproval: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canUseFindings: false, recommendedNextStep: FACTORY_HERMES_OUTPUT_CONTRACT_POLICY_PLANNING_NEXT_STEP }
}

export function evaluateFactoryHermesOutputContractPolicyPlanning(input: FactoryHermesOutputContractPolicyPlanningInput): FactoryHermesOutputContractPolicyPlanningResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_OUTPUT_CONTRACT_POLICY_PLANNING_POLICY, ...(input.policy || {}) }
  const out = base(input)
  const toolsets = input.toolsetsPolicyPlanningResult
  const network = input.networkPolicyPlanningResult
  const inspection = input.outputSourceInspection
  if (!toolsets) return { ...out, blockers: [{ blockerId: 'blocked_missing_toolsets_policy_planning', message: 'Toolsets policy planning result is required.' }] }
  const toolPlan = toolsets.hermesToolsetsPolicyPlanCandidate
  if (toolsets.status !== 'toolsets_policy_plan_created' || toolsets.decision !== 'hermes_toolsets_policy_plan_created' || toolsets.canProceedToOutputContractPolicyPlanning !== true || toolsets.canProceedToResearchExecutionApproval !== false || toolsets.canRunResearchNow !== false || toolsets.canExecuteHermesNow !== false || toolsets.canPassPromptNow !== false || toolsets.canUseNetworkNow !== false || toolsets.canUseCredentialsNow !== false || toolsets.canReadEnvSecretsNow !== false || toolsets.canCallModelsNow !== false || toolsets.canEnableToolsetsNow !== false || toolsets.canUseFindings !== false || toolPlan?.toolsetsAllowedNow !== false || toolPlan?.toolsetsApprovedNow?.length !== 0) return { ...out, decision: 'blocked_toolsets_policy_not_ready_for_output_contract_policy', blockers: [{ blockerId: 'blocked_toolsets_policy_not_ready_for_output_contract_policy', message: 'Toolsets policy planning is not ready.' }] }
  if (policy.requireNetworkPolicyPlanning && (!network || network.status !== 'network_policy_plan_created' || network.canUseNetworkNow !== false)) return { ...out, decision: 'blocked_network_policy_not_ready_for_output_contract_policy', blockers: [{ blockerId: 'blocked_network_policy_not_ready_for_output_contract_policy', message: 'Network policy planning is not ready.' }] }
  if (policy.requireOutputSourceInspection && !inspection) return { ...out, decision: 'blocked_missing_output_source_inspection', blockers: [{ blockerId: 'blocked_missing_output_source_inspection', message: 'Output source inspection is required.' }] }
  if (inspection?.hermesExecuted === true || inspection?.promptSent === true || inspection?.outputUsedAsFindings === true || inspection?.networkUsed === true || inspection?.envValuesRead === true || inspection?.dotEnvRead === true) return { ...out, decision: 'blocked_output_or_execution_used_during_planning', blockers: [{ blockerId: 'blocked_output_or_execution_used_during_planning', message: 'Output inspection must be text-only and must not execute or use output.' }] }
  const outputSurfaceCandidates = surfaces()
  const selectedOutputContractPolicy = { stdout: 'stdout_final_response_plain_text_as_raw_candidate_evidence' as const, stderr: 'stderr_operational_only' as const, usageFile: 'usage_file_operational_metadata_only' as const }
  const plan = { planCandidateId: `${out.planningId}:output-contract-policy-plan-candidate`, toolId: 'hermes_agent' as const, commandShapeUnderConsideration: 'oneshot_real_with_provider_model' as const, futureCommandShape: { executable: 'hermes.exe' as const, argsTemplate: ['--oneshot', '<PROMPT>', '--provider', '<PROVIDER>', '--model', '<MODEL>', '--toolsets', '<TOOLSETS>'] as ['--oneshot', '<PROMPT>', '--provider', '<PROVIDER>', '--model', '<MODEL>', '--toolsets', '<TOOLSETS>'], shell: false as const }, outputSurfaceCandidates, selectedOutputContractPolicy, outputContractRules: rules(), outputAllowedNow: false as const, findingsAllowedNow: false as const, rawOutputPromotableNow: false as const, stdoutPolicy: { capturePreview: true as const, previewLimitBytes: 12000 as const, sanitize: true as const, usableAsFindingsBeforeIngestion: false as const }, stderrPolicy: { capturePreview: true as const, previewLimitBytes: 12000 as const, sanitize: true as const, operationalOnly: true as const }, usageFilePolicy: { allowedInFutureRuntime: true as const, pathMustBeUnderCodexTemp: true as const, metadataOnly: true as const, usableAsFindings: false as const }, sanitizationPolicy: { redactSecrets: true as const, redactTokens: true as const, noEnvDump: true as const, noCredentialValues: true as const }, resultPromotionPolicy: { requiresResultIngestion: true as const, requiresJefeReview: true as const, findingsUsableOnlyAfterJefeReview: true as const }, requiredNextPolicies: OUTPUT_CONTRACT_REQUIRED_NEXT_POLICIES, canProceedToResultIngestionContractPlanning: true as const, canProceedToResearchExecutionApproval: false as const, canUseFindings: false as const }
  const receipt = { receiptId: `${out.planningId}:receipt`, planningId: out.planningId, toolId: 'hermes_agent' as const, plannedBy: input.plannedBy, plannedAt: input.plannedAt, decision: 'hermes_output_contract_policy_plan_created' as const, scope: 'hermes_output_contract_policy_planning_only' as const, approvedNextGate: 'Factory Hermes Result Ingestion Contract Planning Gate v1' as const, limitations: ['Output is not findings.', 'stdout/stderr/usage-file remain planning surfaces only.', 'Result Ingestion and JEFE Review are required before findings use.'], notAuthorizedActions: OUTPUT_CONTRACT_NOT_AUTHORIZED_ACTIONS }
  return { ...out, status: 'output_contract_policy_plan_created', decision: 'hermes_output_contract_policy_plan_created', outputSurfaceCandidates, selectedOutputContractPolicy, outputContractPolicyPlanningReceipt: receipt, hermesOutputContractPolicyPlanCandidate: plan, canProceedToResultIngestionContractPlanning: true }
}
