export type FactoryHermesWrapperNoToolModeVerificationPlanningVersion = '1.0'
export type FactoryHermesWrapperNoToolModeVerificationPlanningKind = 'factory-hermes-wrapper-no-tool-mode-verification-planning'
export type FactoryHermesWrapperNoToolModeVerificationPlanningStatus = 'wrapper_no_tool_mode_verification_plan_created' | 'wrapper_no_tool_mode_verification_plan_blocked'
export type FactoryHermesWrapperNoToolModeVerificationPlanningDecision = 'hermes_wrapper_no_tool_mode_verification_plan_created_for_approval' | 'hermes_wrapper_no_tool_mode_verification_plan_blocked_invalid_implementation'
export interface FactoryHermesWrapperNoToolModeVerificationPlanningInput { plannedAt: string; plannedBy: string; implementationResult?: any; implementationApprovalResult?: any; implementationPlanningResult?: any; wrapperApprovalResult?: any; wrapperPlanningResult?: any; adapterApprovalResult?: any; codeInspection?: any }
export interface FactoryHermesWrapperNoToolModeVerificationPlanningValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export const FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_PLANNING_KIND: FactoryHermesWrapperNoToolModeVerificationPlanningKind = 'factory-hermes-wrapper-no-tool-mode-verification-planning'
export const FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_PLANNING_VERSION: FactoryHermesWrapperNoToolModeVerificationPlanningVersion = '1.0'
export const VERIFICATION_PLANNING_NOT_AUTHORIZED_ACTIONS = ['execute_verification_now','execute_wrapper_now','create_temp_config_now','modify_hermes_source_now','approve_research_runtime_adapter_now','execute_hermes_now','execute_oneshot_now','pass_prompt_now','run_research_now','call_models_now','use_network_now','access_credentials_now','read_env_secrets_now','enable_toolsets_now','mutate_runtime_filesystem_now','create_runtime_run_root_now','ingest_real_output_now','promote_findings_now','execute_uv_now','execute_python_now','execute_pip_now','execute_setup_py_now','deploy_now']
const FORBIDDEN_PATTERNS = ['child_process','spawn(','exec(','execFile(','fork(','fetch(','http.','https.','net.','dns.','process.env','.env','OPENAI_API_KEY','hermes.exe as executable string','--oneshot as executable string']
const TARGET_FILES = ['src/factory/hermes-wrapper-no-tool-mode-runtime/index.ts','electron/factory/hermes-wrapper-no-tool-mode-runtime/index.cjs','src/factory/hermes-wrapper-no-tool-mode-implementation/index.ts','electron/factory/hermes-wrapper-no-tool-mode-implementation/hermes-wrapper-no-tool-mode-implementation.path.cjs','electron/factory/hermes-wrapper-no-tool-mode-implementation/hermes-wrapper-no-tool-mode-implementation.execute.cjs','electron/factory/hermes-wrapper-no-tool-mode-implementation/index.cjs']
function validImplementation(r: any) { return r?.status === 'wrapper_no_tool_mode_implementation_completed' && r?.decision === 'hermes_wrapper_no_tool_mode_implementation_completed_for_verification_planning' && r?.implementationStatus === 'implemented_code_only_not_executable' && r?.selectedWrapperStrategy === 'wrapper_temp_config_no_toolsets' && r?.wrapperRuntimeImplemented === true && r?.wrapperRuntimeModuleManifest && r?.wrapperRuntimeSafetyManifest && r?.wrapperNoToolModeConfigSerializerManifest && r?.wrapperNoToolModeCommandEnvelopeManifest && r?.wrapperNoToolModeVerificationPlanningEnvelope && r?.wrapperExecutionAllowedNow === false && r?.tempConfigCreationAllowedNow === false && r?.hermesExecutionAllowedNow === false && r?.researchRuntimeAdapterAllowedNow === false && r?.researchExecutionAllowedNow === false && r?.canProceedToHermesWrapperNoToolModeVerificationPlanning === true && r?.canProceedToHermesWrapperNoToolModeVerification === false && r?.canRunResearchNow === false }
function validApproval(r: any) { const d = r?.hermesWrapperNoToolModeImplementationApprovalDecision; return r?.status === 'wrapper_no_tool_mode_implementation_approval_granted' && r?.decision === 'hermes_wrapper_no_tool_mode_implementation_approved_for_next_gate' && r?.implementationApprovalStatus === 'approved_for_implementation_only' && d?.wrapperImplementationApproved === true && d?.wrapperExecutionApproved === false && d?.tempConfigCreationApproved === false && d?.researchRuntimeAdapterApproved === false && d?.researchExecutionApproved === false }
function buildRisks() { return { risks: ['static_scan_false_negative','serializer_declares_safe_but_schema_unknown','command_envelope_accidentally_runnable','docs_string_confused_with_executable_string','cjs_runtime_imports_hidden_exec_surface','temp_config_path_becomes_real_too_early','verification_executes_wrapper_by_mistake','future_adapter_uses_wrapper_without_verification','hidden_defaults_not_detected','no_tool_mode_overclaimed'].map((riskId) => ({ riskId, severity: ['command_envelope_accidentally_runnable','verification_executes_wrapper_by_mistake','future_adapter_uses_wrapper_without_verification','hidden_defaults_not_detected','no_tool_mode_overclaimed'].includes(riskId) ? 'high' : 'medium', mitigation: 'Require a separate verification approval gate and keep all execution/network/credential/model capabilities false in this planning gate.', blocksVerificationApproval: ['command_envelope_accidentally_runnable','verification_executes_wrapper_by_mistake','hidden_defaults_not_detected','no_tool_mode_overclaimed'].includes(riskId), blocksRuntimeAdapter: true })) } }
export function evaluateFactoryHermesWrapperNoToolModeVerificationPlanning(input: FactoryHermesWrapperNoToolModeVerificationPlanningInput) {
  const ok = validImplementation(input.implementationResult) && validApproval(input.implementationApprovalResult) && input.adapterApprovalResult?.canProceedToResearchRuntimeAdapter !== true && input.adapterApprovalResult?.canRunResearchNow !== true
  const planningId = `hermes-wrapper-no-tool-mode-verification-planning:75b300f:${input.plannedAt}`
  const status: FactoryHermesWrapperNoToolModeVerificationPlanningStatus = ok ? 'wrapper_no_tool_mode_verification_plan_created' : 'wrapper_no_tool_mode_verification_plan_blocked'
  const decision: FactoryHermesWrapperNoToolModeVerificationPlanningDecision = ok ? 'hermes_wrapper_no_tool_mode_verification_plan_created_for_approval' : 'hermes_wrapper_no_tool_mode_verification_plan_blocked_invalid_implementation'
  const wrapperStaticSafetyScanPlan = { planId: `${planningId}:static-safety-scan`, targetFiles: input.codeInspection?.targetFiles || TARGET_FILES, forbiddenRuntimePatterns: FORBIDDEN_PATTERNS, allowedDocumentationOnlyPatterns: ['Hermes references in documentation','future command shape labels in docs'], scanExecutionAllowedNow: false, futureVerificationGateRequired: true, purpose: 'verify wrapper code has no execution/network/env/tooling surface', plannedChecks: ['scan source TS','scan CJS','scan scripts','separate docs strings from source runtime','fail if dangerous source runtime pattern appears'] }
  const wrapperConfigSerializerVerificationPlan = { planId: `${planningId}:config-serializer`, executionAllowedNow: false, requiresSeparateVerificationApproval: true, futureChecks: ['serializer exists','serializer is pure','serializer does not write files','serializer returns virtual config','serializedOnly true','containsSecrets false','containsCredentialValues false','containsEnvDump false','runnable false if schema exactness is unknown','no default toolsets','MCP disabled when schema permits','empty toolsets controlled when schema permits','no real config path','no project root config mutation'] }
  const wrapperCommandEnvelopeVerificationPlan = { planId: `${planningId}:command-envelope`, executionAllowedNow: false, requiresSeparateVerificationApproval: true, futureChecks: ['command envelope builder exists','builder does not execute','no real prompt','no credential values','no env dump','executionAllowed false','hermesExecutionAllowed false','wrapperExecutionAllowed false','networkAllowed false','modelCallsAllowed false','credentialAccessAllowed false','toolsetsEnabled false','runtimeAdapterAllowed false','researchExecutionAllowed false','no child process usage','no runnable command string'] }
  const wrapperTempConfigVirtualVerificationPlan = { planId: `${planningId}:temp-config-virtual`, executionAllowedNow: false, requiresSeparateVerificationApproval: true, futureChecks: ['virtual config candidate can be generated in memory','no real config write','tempConfigCreationAllowedNow remains false','planned path under .codex-temp only as string','no filesystem mutation','no secrets','no credential values','no env dump','no default toolsets','no MCP if schema permits','non-runnable when exact schema is unknown'] }
  const wrapperNoHermesExecutionVerificationPlan = { planId: `${planningId}:no-hermes-execution`, executionAllowedNow: false, requiresSeparateVerificationApproval: true, futureChecks: ['Hermes not executed','hermes executable not executed','oneshot not executed','wrapper not run against Hermes','no model call','no network','no DNS','no endpoint tests','no credentials','no run root','no real toolsets','no real result ingestion'] }
  const wrapperVerificationRiskRegister = buildRisks()
  const wrapperNoToolModeVerificationApprovalEnvelope = { envelopeId: `${planningId}:approval-envelope`, toolId: 'hermes_agent' as const, approvedFor: 'wrapper_no_tool_mode_verification_approval_only', selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets' as const, targetNextGate: 'Factory Hermes Wrapper No-Tool Mode Verification Approval Gate v1', verificationScope: ['static safety scan','serializer verification','command envelope verification','virtual temp config verification','no Hermes execution verification'], verificationExecutionAllowedNow: false, wrapperExecutionAllowedNow: false, hermesExecutionAllowedNow: false, tempConfigCreationAllowedNow: false, researchRuntimeAdapterAllowedNow: false, researchExecutionAllowedNow: false }
  const hermesWrapperNoToolModeVerificationPlanCandidate = { planCandidateId: `${planningId}:candidate`, toolId: 'hermes_agent' as const, selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets' as const, wrapperStaticSafetyScanPlan, wrapperConfigSerializerVerificationPlan, wrapperCommandEnvelopeVerificationPlan, wrapperTempConfigVirtualVerificationPlan, wrapperNoHermesExecutionVerificationPlan, wrapperVerificationRiskRegister, wrapperNoToolModeVerificationApprovalEnvelope, verificationExecutionAllowedNow: false, wrapperExecutionAllowedNow: false, tempConfigCreationAllowedNow: false, hermesExecutionAllowedNow: false, researchRuntimeAdapterAllowedNow: false, researchExecutionAllowedNow: false, futureVerificationRequiresApproval: true, futureRuntimeAdapterRetryRequiresApproval: true, canProceedToHermesWrapperNoToolModeVerificationApproval: ok, canProceedToHermesWrapperNoToolModeVerification: false, canProceedToResearchRuntimeAdapterApprovalRetry: false, canRunResearchNow: false }
  return { planningId, planningKind: FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_PLANNING_KIND, planningVersion: FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', wrapperImplementationRef: input.implementationResult?.implementationId, wrapperImplementationApprovalRef: input.implementationApprovalResult?.approvalId, selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets', wrapperStaticSafetyScanPlan, wrapperConfigSerializerVerificationPlan, wrapperCommandEnvelopeVerificationPlan, wrapperTempConfigVirtualVerificationPlan, wrapperNoHermesExecutionVerificationPlan, wrapperVerificationRiskRegister, wrapperNoToolModeVerificationApprovalEnvelope, hermesWrapperNoToolModeVerificationPlanCandidate, wrapperNoToolModeVerificationPlanningReceipt: { receiptId: `${planningId}:receipt`, planningId, toolId: 'hermes_agent', plannedBy: input.plannedBy, plannedAt: input.plannedAt, decision, verificationPlanningStatus: ok ? 'plan_candidate_created' : 'blocked', scope: 'hermes_wrapper_no_tool_mode_verification_planning_only', approvedNextGate: 'Factory Hermes Wrapper No-Tool Mode Verification Approval Gate v1', limitations: ['Planning only. Verification execution, wrapper execution, temp config creation, Hermes execution, prompts, models, network, credentials, adapter approval, ingestion, and findings remain blocked.'], notAuthorizedActions: VERIFICATION_PLANNING_NOT_AUTHORIZED_ACTIONS }, checks: [], blockers: ok ? [] : [{ blockerId: 'invalid_wrapper_no_tool_mode_implementation', message: 'Wrapper implementation or implementation approval is not valid for verification planning.' }], warnings: [], status, decision, verificationPlanningStatus: ok ? 'plan_candidate_created' : 'blocked', canProceedToHermesWrapperNoToolModeVerificationApproval: ok, canProceedToHermesWrapperNoToolModeVerification: false, canProceedToResearchRuntimeAdapterApprovalRetry: false, canProceedToResearchRuntimeAdapter: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canMutateFilesystemNow: false, canUseFindings: false, recommendedNextStep: ok ? 'Proceed to Factory Hermes Wrapper No-Tool Mode Verification Approval Gate v1; verification execution remains blocked.' : 'Return to wrapper no-tool mode implementation.' }
}
export function validateFactoryHermesWrapperNoToolModeVerificationPlanningInput(input: FactoryHermesWrapperNoToolModeVerificationPlanningInput): FactoryHermesWrapperNoToolModeVerificationPlanningValidationResult { const errors: string[] = []; const warnings: string[] = []; if (!input?.plannedAt) errors.push('plannedAt required.'); if (!input?.plannedBy) errors.push('plannedBy required.'); if (!input?.implementationResult) errors.push('implementation result required.'); if (!input?.implementationApprovalResult) errors.push('implementation approval required.'); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryHermesWrapperNoToolModeVerificationPlanningResult(result: any): FactoryHermesWrapperNoToolModeVerificationPlanningValidationResult { const errors: string[] = []; const warnings: string[] = []; if (result.planningKind !== FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_PLANNING_KIND) errors.push('kind mismatch.'); if (result.planningVersion !== FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_PLANNING_VERSION) errors.push('version mismatch.'); if (result.status !== 'wrapper_no_tool_mode_verification_plan_created') errors.push('status mismatch.'); if (result.decision !== 'hermes_wrapper_no_tool_mode_verification_plan_created_for_approval') errors.push('decision mismatch.'); for (const key of ['wrapperStaticSafetyScanPlan','wrapperConfigSerializerVerificationPlan','wrapperCommandEnvelopeVerificationPlan','wrapperTempConfigVirtualVerificationPlan','wrapperNoHermesExecutionVerificationPlan','wrapperVerificationRiskRegister','wrapperNoToolModeVerificationApprovalEnvelope','hermesWrapperNoToolModeVerificationPlanCandidate','wrapperNoToolModeVerificationPlanningReceipt']) if (!result[key]) errors.push(`${key} required.`); for (const key of ['canProceedToHermesWrapperNoToolModeVerification','canProceedToResearchRuntimeAdapterApprovalRetry','canProceedToResearchRuntimeAdapter','canRunResearchNow','canExecuteHermesNow','canPassPromptNow','canUseNetworkNow','canUseCredentialsNow','canReadEnvSecretsNow','canCallModelsNow','canEnableToolsetsNow','canMutateFilesystemNow','canUseFindings']) if (result[key] !== false) errors.push(`${key} must be false.`); if (result.canProceedToHermesWrapperNoToolModeVerificationApproval !== true) errors.push('verification approval next gate must be true.'); return { ok: errors.length === 0, errors, warnings } }
export const serializeFactoryHermesWrapperNoToolModeVerificationPlanningResult = (result: any): string => `${JSON.stringify(result, null, 2)}\n`
export const parseFactoryHermesWrapperNoToolModeVerificationPlanningResult = (json: string): any => JSON.parse(json)
export const summarizeFactoryHermesWrapperNoToolModeVerificationPlanningResult = (result: any) => ({ planningId: result.planningId, status: result.status, decision: result.decision, verificationPlanningStatus: result.verificationPlanningStatus, selectedWrapperStrategy: result.selectedWrapperStrategy, riskCount: result.wrapperVerificationRiskRegister?.risks?.length ?? 0, canProceedToHermesWrapperNoToolModeVerificationApproval: result.canProceedToHermesWrapperNoToolModeVerificationApproval, canRunResearchNow: result.canRunResearchNow, nextStep: result.recommendedNextStep })
