import { DEFAULT_FACTORY_HERMES_RESEARCH_EXECUTION_POLICY_CHAIN_PLANNING_POLICY, DEEP_SOURCE_REVIEW_REF, FACTORY_HERMES_RESEARCH_EXECUTION_POLICY_CHAIN_PLANNING_KIND, FACTORY_HERMES_RESEARCH_EXECUTION_POLICY_CHAIN_PLANNING_NEXT_STEP, FACTORY_HERMES_RESEARCH_EXECUTION_POLICY_CHAIN_PLANNING_VERSION, NOT_AUTHORIZED_ACTIONS } from './hermes-research-execution-policy-chain-planning.defaults.ts'
import type { FactoryHermesResearchExecutionPolicyChainPlanningInput, FactoryHermesResearchExecutionPolicyChainPlanningResult, FactoryHermesResearchExecutionPolicyGatePlan, FactoryHermesResearchExecutionPolicyItem } from './hermes-research-execution-policy-chain-planning.types.ts'

export function buildRequiredPolicies(): FactoryHermesResearchExecutionPolicyItem[] {
  return [
    ['prompt_policy', 'Prompt Policy', 'Define the first permitted prompt, max length, forbidden content, no secrets/personal data, harmless objective and expected behavior.'],
    ['model_provider_policy', 'Model Provider Policy', 'Select allowed provider/model, control fallback and forbid hidden provider default or env auto-resolve without approval.'],
    ['credentials_policy', 'Credentials Policy', 'Define allowed credentials, source, injection, prohibited env vars, no .env read without gate and log masking.'],
    ['network_policy', 'Network Policy', 'Define if network is allowed, exact destinations, no wildcards, browser/web tool restrictions and timeouts.'],
    ['toolsets_policy', 'Toolsets Policy', 'Define allowed/prohibited toolsets and how to disable web/browser/terminal/MCP/default hidden toolsets.'],
    ['output_contract_policy', 'Output Contract Policy', 'Define stdout/plain text or JSON, usage-file role, size limits, truncation and what counts as findings.'],
    ['result_ingestion_contract', 'Result Ingestion Contract', 'Define real output ingestion, health/log/finding separation, confidence and evidence preservation.'],
    ['timeout_kill_switch_policy', 'Timeout / Kill Switch Policy', 'Define max timeout, kill behavior, no automatic retries and global kill switch.'],
    ['filesystem_mutation_policy', 'Filesystem Mutation Policy', 'Define allowed writes, usage-file/log paths, no source mutation and no python-env mutation.'],
    ['research_execution_boundary_policy', 'Research Execution Boundary Policy', 'Define exact command, args, shell:false, cwd, sanitized env, allowed writes and forbidden actions.'],
  ].map(([policyId, policyName, purpose]) => ({ policyId, policyName, purpose, requiredDecisions: [`Lean must approve ${policyName}.`], missingData: [`${policyName} details are not approved yet.`], futureGate: `Factory Hermes ${policyName} Planning Gate v1` }))
}

export function buildGateSequence(): FactoryHermesResearchExecutionPolicyGatePlan[] {
  const names = ['Prompt Policy Planning', 'Model Provider Policy Planning', 'Credentials Policy Planning', 'Network Policy Planning', 'Toolsets Policy Planning', 'Output Contract Planning', 'Research Execution Boundary Planning', 'Research Execution Approval', 'Research Execution Runtime Adapter', 'Research Execution Result Ingestion', 'Research Execution JEFE Review']
  return names.map((name, i) => ({ gateId: `gate_${i + 1}`, gateName: `Factory Hermes ${name} Gate v1`, purpose: `Plan or enforce ${name} before bounded Hermes oneshot research.`, inputs: ['Prior approved artifact'], outputs: ['Governed receipt/envelope/result'], allowedActions: ['Read approved artifacts', 'Create planning/approval artifacts'], forbiddenActions: NOT_AUTHORIZED_ACTIONS, riskItControls: `${name} risk`, nextGate: names[i + 1] ? `Factory Hermes ${names[i + 1]} Gate v1` : undefined }))
}

function base(input: FactoryHermesResearchExecutionPolicyChainPlanningInput): FactoryHermesResearchExecutionPolicyChainPlanningResult {
  return { planningId: `hermes-research-execution-policy-chain-planning:75b300f:${input.plannedAt}`, planningKind: FACTORY_HERMES_RESEARCH_EXECUTION_POLICY_CHAIN_PLANNING_KIND, planningVersion: FACTORY_HERMES_RESEARCH_EXECUTION_POLICY_CHAIN_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', currentCommandShape: 'oneshot_real_with_provider_model', currentExecutionStatus: 'blocked_until_policy_chain', requiredPolicies: buildRequiredPolicies(), proposedGateSequence: buildGateSequence(), checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_deep_source_review', canProceedToPromptPolicyPlanning: false, canProceedToResearchExecutionApproval: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canCallModelsNow: false, canUseFindings: false, recommendedNextStep: FACTORY_HERMES_RESEARCH_EXECUTION_POLICY_CHAIN_PLANNING_NEXT_STEP }
}

export function evaluateFactoryHermesResearchExecutionPolicyChainPlanning(input: FactoryHermesResearchExecutionPolicyChainPlanningInput): FactoryHermesResearchExecutionPolicyChainPlanningResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_RESEARCH_EXECUTION_POLICY_CHAIN_PLANNING_POLICY, ...(input.policy || {}) }
  const out = base(input)
  const deep = input.deepSourceReview
  const planning = input.researchExecutionPlanningResult
  if (!deep) return { ...out, blockers: [{ blockerId: 'blocked_missing_deep_source_review', message: 'Deep source review is required.' }] }
  if (policy.requireDeepSourceKeepBlockedRecommendation && deep.recommendedDefault !== 'KEEP_BLOCKED_UNTIL_POLICY_CHAIN') return { ...out, decision: 'blocked_deep_source_review_not_policy_chain', blockers: [{ blockerId: 'blocked_deep_source_review_not_policy_chain', message: 'Deep source review does not recommend policy-chain blocking.' }] }
  const real = deep.commandContractCandidates?.find((c: any) => c.id === 'oneshot_real_with_provider_model')
  const mock = deep.commandContractCandidates?.find((c: any) => c.id === 'oneshot_mock_or_offline')
  if (!real || real.recommendation !== 'requires_policy_chain' || !mock || mock.recommendation !== 'not_available') return { ...out, decision: 'blocked_deep_source_review_not_policy_chain', blockers: [{ blockerId: 'blocked_deep_source_review_not_policy_chain', message: 'Required command-shape findings are missing.' }] }
  if (!planning || planning.status !== 'manual_review_required' || planning.decision !== 'hermes_research_execution_requires_manual_command_review' || planning.canProceedToResearchExecutionApproval !== false) return { ...out, decision: 'blocked_research_execution_planning_not_manual_review', blockers: [{ blockerId: 'blocked_research_execution_planning_not_manual_review', message: 'Research execution planning must be manual_review_required.' }] }
  if (planning.canRunResearchNow !== false || planning.canExecuteHermesNow !== false || planning.canPassPromptNow !== false || planning.canUseNetworkNow !== false || planning.canUseCredentialsNow !== false || planning.canCallModelsNow !== false || planning.canUseFindings !== false) return { ...out, decision: 'blocked_unsafe_prior_execution_state', blockers: [{ blockerId: 'blocked_unsafe_prior_execution_state', message: 'Prior planning contains unsafe now-permissions.' }] }
  const receipt = { receiptId: `${out.planningId}:receipt`, planningId: out.planningId, toolId: 'hermes_agent' as const, plannedBy: input.plannedBy, plannedAt: input.plannedAt, decision: 'hermes_research_execution_policy_chain_plan_created' as const, scope: 'hermes_research_execution_policy_chain_planning_only' as const, approvedNextGate: 'Factory Hermes Prompt Policy Planning Gate v1' as const, limitations: ['Planning only; no Hermes execution.', 'No prompts, network, credentials, models or toolsets are enabled now.', 'Research execution approval remains blocked until every policy gate is approved.'], notAuthorizedActions: NOT_AUTHORIZED_ACTIONS }
  const plan = { planId: `${out.planningId}:chain-plan`, toolId: 'hermes_agent' as const, sourceDecisionRef: DEEP_SOURCE_REVIEW_REF, commandShapeUnderConsideration: 'oneshot_real_with_provider_model' as const, executionModeTarget: 'future_bounded_oneshot' as const, requiredPolicies: out.requiredPolicies, proposedGateSequence: out.proposedGateSequence, globalConstraints: { noExecutionUntilAllPoliciesApproved: true as const, noPromptUntilPromptPolicyApproved: true as const, noCredentialsUntilCredentialsPolicyApproved: true as const, noNetworkUntilNetworkPolicyApproved: true as const, noModelsUntilModelProviderPolicyApproved: true as const, noToolsetsUntilToolsetsPolicyApproved: true as const, noFindingsUntilResultIngestionAndJEFEReview: true as const }, recommendedDefault: 'KEEP_BLOCKED_UNTIL_POLICY_CHAIN' as const, canProceedToPromptPolicyPlanning: true as const, canProceedToResearchExecutionApproval: false as const, canRunResearchNow: false as const }
  return { ...out, status: 'policy_chain_plan_created', decision: 'hermes_research_execution_policy_chain_plan_created', researchExecutionPolicyChainPlanningReceipt: receipt, hermesResearchExecutionPolicyChainPlan: plan, canProceedToPromptPolicyPlanning: true }
}
