const fs = require('node:fs/promises');
const path = require('node:path');
const { resolveFactoryHermesResearchJefeReviewPaths, assertJefeReviewPathContained } = require('./hermes-research-jefe-review.path.cjs');
const NEXT = 'Proceed to Factory Hermes Entrypoint Materialization Planning Gate v1; do not materialize, retry adapter, or execute Hermes now.';
const actions = ['materialize_entrypoint_now', 'install_project_now', 'retry_adapter_now', 'execute_hermes_now', 'execute_selected_interface_now', 'execute_python_now', 'execute_uv_now', 'execute_pip_now', 'execute_setup_py_now', 'use_network_now', 'call_models_now', 'access_credentials_now', 'treat_as_research_result', 'use_findings_now', 'mutate_project_files_now', 'deploy_now'];
function evaluateFactoryHermesResearchJefeReview(input) {
  const i = input.ingestionResult; const rec = i?.hermesResearchResultIngestionRecord; const id = `hermes-research-jefe-review:75b300f:${input.reviewedAt}`;
  const base = { jefeReviewId: id, jefeReviewKind: 'factory-hermes-research-jefe-review', jefeReviewVersion: '1.0', reviewedAt: input.reviewedAt, reviewedBy: input.reviewedBy, toolId: 'hermes_agent', selectedCandidateId: i?.selectedCandidateId || rec?.selectedCandidateId || '', commandName: i?.commandName || rec?.commandName || '', pythonEntrypoint: i?.pythonEntrypoint || rec?.pythonEntrypoint || '', ingestionRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-result-ingestion-result.json', adapterRunRef: i?.adapterRunRef || rec?.adapterRunRef || '', adapterDecision: i?.adapterDecision || rec?.adapterDecision || '', classification: i?.classification || rec?.classification || '', normalizedOutcome: rec?.normalizedOutcome || '', checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_ingestion_result', canProceedToEntrypointMaterializationPlanning: false, canMaterializeEntrypointNow: false, canRetryAdapterNow: false, canTreatAsResearchResult: false, canUseFindings: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: NEXT };
  if (!i || !rec) return { ...base, blockers: [{ blockerId: 'blocked_missing_ingestion_result', message: 'Ingestion result is required.' }] };
  if (!input.humanApprovalRef) return { ...base, status: 'human_review_required', decision: 'blocked_missing_human_approval', blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] };
  if (i.status !== 'ingested' || i.canTreatAsResearchResult !== false || i.canUseFindings !== false || i.adapterDecision !== 'blocked_executable_missing') return { ...base, decision: 'blocked_ingestion_not_reviewable', blockers: [{ blockerId: 'blocked_ingestion_not_reviewable', message: 'Ingestion result is not reviewable.' }] };
  const receipt = { receiptId: `${id}:receipt`, jefeReviewId: id, toolId: 'hermes_agent', reviewedBy: input.reviewedBy, reviewedAt: input.reviewedAt, humanApprovalRef: input.humanApprovalRef, adapterDecision: i.adapterDecision, classification: i.classification, normalizedOutcome: rec.normalizedOutcome, decision: 'hermes_research_jefe_review_approved_entrypoint_materialization_planning', scope: 'hermes_research_jefe_review_only', approvedNextGate: 'Factory Hermes Entrypoint Materialization Planning Gate v1', limitations: ['Approval is for planning only.', 'No entrypoint materialization is authorized now.', 'No adapter retry or Hermes execution is authorized.'], notAuthorizedActions: actions };
  const reviewRecord = { recordId: `${id}:record`, jefeReviewId: id, toolId: 'hermes_agent', selectedCandidateId: base.selectedCandidateId, commandName: base.commandName, pythonEntrypoint: base.pythonEntrypoint, ingestionRef: base.ingestionRef, adapterRunRef: base.adapterRunRef, adapterDecision: base.adapterDecision, classification: base.classification, normalizedOutcome: base.normalizedOutcome, jefeAssessment: 'controlled block is valid and expected given no-install-project strategy', rootCause: 'package entrypoint wrapper missing because project package was not installed', approvedNextPlanning: 'Factory Hermes Entrypoint Materialization Planning Gate v1', safetyConclusion: 'no research result, no findings, no Hermes execution, no model/network/credential use', canProceedToEntrypointMaterializationPlanning: true, canMaterializeEntrypointNow: false, canRetryAdapterNow: false };
  const envelope = { envelopeId: `${id}:envelope`, jefeReviewId: id, toolId: 'hermes_agent', selectedCandidateId: base.selectedCandidateId, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', missingExecutableRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/Scripts/hermes.exe', sourceRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/source', pythonEnvRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env', currentInstallMethod: 'uv sync --locked --no-install-project --no-dev --project', suspectedRepairFamily: 'entrypoint_materialization', allowedNextGate: 'Factory Hermes Entrypoint Materialization Planning Gate v1', materializationAllowedNow: false, adapterRetryAllowedNow: false, hermesExecutionAllowedNow: false, networkAllowedNow: false, credentialsAllowedNow: false, modelCallsAllowedNow: false, requiredPlanningQuestions: ['Should materialization use uv sync --locked --no-dev --project without --no-install-project?', 'Can the project package be installed into existing python-env without setup.py execution?', 'Does uv install project trigger build hooks?', 'How to preserve no pip/setup.py/direct python execution?', 'How to verify console script wrapper without launching Hermes beyond --help?'], requiredFutureGates: ['Factory Hermes Entrypoint Materialization Planning Gate v1', 'Factory Hermes Entrypoint Materialization Approval Gate v1', 'Factory Hermes Entrypoint Materialization Runtime Adapter v1', 'Factory Hermes Entrypoint Materialization Verification Gate v1', 'Factory Hermes Research Runtime Adapter Retry Gate v1'] };
  return { ...base, status: 'approved_for_entrypoint_materialization_planning', decision: 'hermes_research_jefe_review_approved_entrypoint_materialization_planning', researchJefeReviewReceipt: receipt, hermesResearchJefeReviewRecord: reviewRecord, approvedEntrypointMaterializationPlanningEnvelope: envelope, canProceedToEntrypointMaterializationPlanning: true };
}
async function readJson(file) { return JSON.parse(await fs.readFile(file, 'utf8')); }
async function executeFactoryHermesResearchJefeReview(input = {}) {
  const paths = resolveFactoryHermesResearchJefeReviewPaths();
  assertJefeReviewPathContained(paths.installRoot, path.join(paths.root, '.codex-temp'));
  assertJefeReviewPathContained(paths.jefeReviewResult, paths.installRoot);
  const ingestionResult = await readJson(paths.ingestionResult);
  const adapterResult = await readJson(paths.adapterResult);
  const approvalResult = await readJson(paths.approvalResult);
  const boundaryResult = await readJson(paths.boundaryResult);
  await readJson(paths.interfaceSelectionResult);
  const pythonInstallResult = await readJson(paths.pythonInstallResult);
  const pythonInstallVerificationResult = await readJson(paths.pythonInstallVerificationResult);
  if (!['success'].includes(pythonInstallResult.status) || pythonInstallVerificationResult.status !== 'verified') throw new Error('Python install artifacts are not verified for JEFE review.');
  const result = evaluateFactoryHermesResearchJefeReview({ reviewedAt: input.reviewedAt || '2026-07-21T22:00:00.000Z', reviewedBy: input.reviewedBy || 'factory-hermes-research-jefe-review-smoke', humanApprovalRef: input.humanApprovalRef || 'human-review/hermes-research-jefe-review-v1', ingestionResult, adapterResult, approvalResult, boundaryResult });
  await fs.writeFile(paths.jefeReviewResult, JSON.stringify(result, null, 2));
  return result;
}
module.exports = { executeFactoryHermesResearchJefeReview };
