export type FactoryHermesPythonInstallVerificationVersion = '1.0'
export type FactoryHermesPythonInstallVerificationKind = 'factory-hermes-python-install-verification'
export type FactoryHermesPythonInstallVerificationStatus = 'verified' | 'blocked' | 'failed'
export type FactoryHermesPythonInstallVerificationDecision = 'hermes_python_install_verified' | 'blocked_missing_python_install_manifest' | 'blocked_missing_python_install_result' | 'blocked_invalid_python_install_manifest' | 'blocked_invalid_python_install_result' | 'blocked_python_env_missing' | 'blocked_python_env_outside_codex_temp' | 'blocked_uv_verification_missing' | 'blocked_uv_not_verified' | 'blocked_insecure_python_install_result' | 'request_hermes_python_install_repair'
export type FactoryHermesPythonInstallVerificationArtifactStatus = 'present' | 'missing' | 'valid' | 'invalid' | 'verified'
export interface FactoryHermesPythonInstallVerificationInput { verifiedAt: string; verifiedBy: string; expectedAuditedHead?: string; installRootRef?: string; sourceRootRef?: string; pythonEnvRootRef?: string; policy?: Partial<FactoryHermesPythonInstallVerificationPolicy> }
export interface FactoryHermesPythonInstallVerificationPolicy { requirePythonInstallManifest: boolean; requirePythonInstallResult: boolean; requireUvVerificationResult: boolean; requirePythonEnvRootUnderCodexTemp: boolean; requireInstallRootUnderCodexTemp: boolean; requireSourceRootUnderInstallRoot: boolean; requirePythonEnvPresent: boolean; requirePyvenvCfg: boolean; requirePythonExecutablePresent: boolean; requireSitePackagesPresent: boolean; requirePythonInstallSuccess: boolean; requireVerifiedUvUsed: boolean; requireNoHermesExecution: boolean; requireNoHermesScripts: boolean; requireNoPipExecution: boolean; requireNoPythonDirectExecution: boolean; requireNoSetupPyExecution: boolean; forbidUvRun: boolean; forbidUvPip: boolean; forbidPipExecution: boolean; forbidPythonDirectExecution: boolean; forbidSetupPyExecution: boolean; forbidHermesExecution: boolean; forbidHermesScripts: boolean; forbidShell: boolean; forbidCmd: boolean; forbidPowerShell: boolean; forbidDownloadInThisGate: boolean; forbidExtractionInThisGate: boolean; forbidPackageFileMutation: boolean; forbidCredentials: boolean; forbidModelCalls: boolean; forbidDeploy: boolean; requireJefeReviewNext: boolean; requireResearchRuntimePlanningFuture: boolean }
export interface FactoryHermesPythonInstallVerificationCheck { checkId: string; ok: boolean; message: string }
export interface FactoryHermesPythonInstallVerificationBlocker { blockerId: string; message: string }
export interface FactoryHermesPythonInstallVerificationWarning { warningId: string; message: string }
export interface FactoryHermesPythonInstallVerificationResult { pythonInstallVerificationId: string; pythonInstallVerificationKind: FactoryHermesPythonInstallVerificationKind; pythonInstallVerificationVersion: FactoryHermesPythonInstallVerificationVersion; verifiedAt: string; verifiedBy: string; toolId: 'hermes_agent'; auditedHead: string; installRootRef: string; sourceRootRef: string; pythonEnvRootRef: string; uvExecutableRef: string; uvVerificationRef: string; pythonInstallManifestRef: string; pythonInstallResultRef: string; pythonInstallVerificationResultRef: string; manifestStatus: string; installResultStatus: string; pythonEnvStatus: string; pyvenvCfgStatus: string; pythonExecutableStatus: string; sitePackagesStatus: string; uvVerificationStatus: string; checksumStatus: string; pythonInstallStatus: string; venvStatus: string; uvStatus: string; pipStatus: 'not_executed'; pythonDirectStatus: 'not_executed'; setupPyStatus: 'not_executed'; hermesExecutionStatus: 'not_allowed'; scriptsStatus: 'not_executed' | 'not_allowed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; projectMutationStatus: 'not_allowed'; deployStatus: 'not_allowed'; commandResults: Array<{ kind: string; shell: false }>; pyvenvCfgPreview?: string; pythonExecutableSha256?: string; pythonExecutableSizeBytes?: number; sitePackagesEntryCount?: number; checks: FactoryHermesPythonInstallVerificationCheck[]; blockers: FactoryHermesPythonInstallVerificationBlocker[]; warnings: FactoryHermesPythonInstallVerificationWarning[]; status: FactoryHermesPythonInstallVerificationStatus; decision: FactoryHermesPythonInstallVerificationDecision; canProceedToJefeReview: boolean; canProceedToResearchRuntimePlanning: false; canExecuteHermes: false; canRunHermesScripts: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesPythonInstallVerificationValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesPythonInstallVerificationSummary { pythonInstallVerificationId: string; toolId: 'hermes_agent'; auditedHead: string; pythonEnvRootRef: string; manifestStatus: string; installResultStatus: string; pythonEnvStatus: string; pyvenvCfgStatus: string; pythonExecutableStatus: string; sitePackagesStatus: string; uvVerificationStatus: string; pythonInstallStatus: string; pipStatus: 'not_executed'; pythonDirectStatus: 'not_executed'; setupPyStatus: 'not_executed'; hermesExecutionStatus: 'not_allowed'; canProceedToJefeReview: boolean; canExecuteHermes: false; nextStep: string }
