import type { FactoryHermesResearchRuntimeBoundaryResult, FactoryHermesResearchRuntimeBoundaryContract } from '../hermes-research-runtime-boundary/index.ts'
import type { FactoryHermesResearchRuntimeSelectedInterface } from '../hermes-research-runtime-interface-selection/index.ts'

export type FactoryHermesResearchRuntimeApprovalVersion = '1.0'
export type FactoryHermesResearchRuntimeApprovalKind = 'factory-hermes-research-runtime-approval'
export type FactoryHermesResearchRuntimeApprovalStatus = 'approved_for_adapter_candidate' | 'blocked' | 'human_review_required'
export type FactoryHermesResearchRuntimeApprovalDecision = 'hermes_research_runtime_approved_for_adapter_candidate' | 'blocked_missing_boundary_contract' | 'blocked_boundary_not_created' | 'blocked_boundary_allows_execution_now' | 'blocked_boundary_allows_network_now' | 'blocked_boundary_allows_credentials_now' | 'blocked_boundary_allows_model_calls_now' | 'blocked_missing_human_approval' | 'request_boundary_repair_before_approval'
export interface FactoryHermesResearchRuntimeApprovalInput { approvedAt: string; approvedBy: string; humanApprovalRef?: string; boundaryResult?: FactoryHermesResearchRuntimeBoundaryResult; approvalNotes?: string; policy?: Partial<FactoryHermesResearchRuntimeApprovalPolicy> }
export interface FactoryHermesResearchRuntimeApprovalPolicy { requireBoundaryContract: boolean; requireBoundaryContractCreated: boolean; requireHumanApprovalRef: boolean; requireSelectedInterface: boolean; requireShellFalseFutureRuntime: boolean; requireCommandsAllowedNowEmpty: boolean; requireNetworkBlockedNow: boolean; requireCredentialsBlockedNow: boolean; requireModelCallsBlockedNow: boolean; requireResultIngestionFuture: boolean; requireJefeReviewFuture: boolean; requireRuntimeAdapterNext: boolean; forbidRuntimeCreationInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidHermesScriptsInThisGate: boolean; forbidPythonExecutionInThisGate: boolean; forbidUvExecutionInThisGate: boolean; forbidPipExecutionInThisGate: boolean; forbidSetupPyExecutionInThisGate: boolean; forbidNetworkInThisGate: boolean; forbidCredentialsInThisGate: boolean; forbidModelCallsInThisGate: boolean; forbidProjectMutationInThisGate: boolean; forbidDeployInThisGate: boolean; forbidDirectExecutionOutsideAdapter: boolean }
export interface FactoryHermesResearchRuntimeApprovalReceipt { receiptId: string; approvalId: string; toolId: 'hermes_agent'; auditedHead: string; approvedBy: string; approvedAt: string; humanApprovalRef: string; selectedCandidateId: string; decision: FactoryHermesResearchRuntimeApprovalDecision; scope: 'hermes_research_runtime_adapter_candidate_only'; approvedNextGate: 'Factory Hermes Research Runtime Adapter v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesResearchRuntimeAdapterEnvelope { envelopeId: string; approvalId: string; toolId: 'hermes_agent'; auditedHead: string; selectedCandidateId: string; selectedInterface: FactoryHermesResearchRuntimeSelectedInterface; boundaryContractRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-boundary-result.json'; boundaryContractSummary: Partial<FactoryHermesResearchRuntimeBoundaryContract>; approvedNextGate: 'Factory Hermes Research Runtime Adapter v1'; adapterReadinessStatus: 'approved_for_adapter_candidate'; executionAuthorizationScope: 'future_runtime_adapter_only'; directExecutionNow: false; futureRuntimeCanExecuteSelectedInterfaceUnderBoundary: true; futureRuntimeNetworkAllowed: false; futureRuntimeCredentialsAllowed: false; futureRuntimeModelCallsAllowed: false; futureRuntimeProjectMutationAllowed: false; futureRuntimeDeployAllowed: false; requiredAdapterControls: string[]; requiredNextGates: string[]; canProceedToResearchRuntimeAdapter: true; canCreateRuntimeNow: false; canExecuteHermesNow: false; canExecuteHermesOutsideAdapter: false; recommendedNextStep: string }
export interface FactoryHermesResearchRuntimeApprovalCheck { checkId: string; ok: boolean; message: string }
export interface FactoryHermesResearchRuntimeApprovalBlocker { blockerId: string; message: string }
export interface FactoryHermesResearchRuntimeApprovalWarning { warningId: string; message: string }
export interface FactoryHermesResearchRuntimeApprovalResult { approvalId: string; approvalKind: FactoryHermesResearchRuntimeApprovalKind; approvalVersion: FactoryHermesResearchRuntimeApprovalVersion; approvedAt: string; approvedBy: string; toolId: 'hermes_agent'; auditedHead: string; selectedCandidateId: string; commandName?: string; pythonEntrypoint?: string; selectedInterface?: FactoryHermesResearchRuntimeSelectedInterface; boundaryResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-boundary-result.json'; researchRuntimeApprovalReceipt?: FactoryHermesResearchRuntimeApprovalReceipt; approvedHermesResearchRuntimeAdapterEnvelope?: FactoryHermesResearchRuntimeAdapterEnvelope; checks: FactoryHermesResearchRuntimeApprovalCheck[]; blockers: FactoryHermesResearchRuntimeApprovalBlocker[]; warnings: FactoryHermesResearchRuntimeApprovalWarning[]; status: FactoryHermesResearchRuntimeApprovalStatus; decision: FactoryHermesResearchRuntimeApprovalDecision; canProceedToResearchRuntimeAdapter: boolean; canCreateRuntimeNow: false; canExecuteHermesNow: false; canExecuteHermesOutsideAdapter: false; canRunHermesScripts: false; canUseNetworkNow: false; canUseCredentialsNow: false; canCallModelsNow: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesResearchRuntimeApprovalValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesResearchRuntimeApprovalSummary { approvalId: string; selectedCandidateId: string; commandName: string; pythonEntrypoint: string; status: FactoryHermesResearchRuntimeApprovalStatus; decision: FactoryHermesResearchRuntimeApprovalDecision; canProceedToResearchRuntimeAdapter: boolean; canCreateRuntimeNow: false; canExecuteHermesNow: false; futureRuntimeNetworkAllowed: false; futureRuntimeCredentialsAllowed: false; futureRuntimeModelCallsAllowed: false; approvedNextGate?: string; nextStep: string }
