import { DEFAULT_FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_POLICY, FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_KIND, FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_NEXT_STEP, FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_VERSION } from './hermes-research-runtime-approval.defaults.ts'
import type { FactoryHermesResearchRuntimeApprovalInput, FactoryHermesResearchRuntimeApprovalResult } from './hermes-research-runtime-approval.types.ts'

const requiredAdapterControls = ['shell:false', 'timeout', 'killSwitch', 'processTreeKill', 'sanitized stdout/stderr', 'bounded cwd', 'bounded filesystem writes', 'result ingestion', 'JEFE review']
const requiredNextGates = ['Factory Hermes Research Runtime Adapter v1', 'Factory Hermes Research Result Ingestion Gate v1', 'Factory Hermes Research JEFE Review Gate v1']
export function evaluateFactoryHermesResearchRuntimeApproval(input: FactoryHermesResearchRuntimeApprovalInput): FactoryHermesResearchRuntimeApprovalResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_POLICY, ...(input.policy || {}) }
  const b = input.boundaryResult
  const c = b?.hermesResearchRuntimeBoundaryContract
  const selectedInterface = b?.selectedInterface
  const id = `hermes-research-runtime-approval:75b300f:${input.approvedAt}`
  const base = { approvalId: id, approvalKind: FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_KIND, approvalVersion: FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_VERSION, approvedAt: input.approvedAt, approvedBy: input.approvedBy, toolId: 'hermes_agent' as const, auditedHead: b?.auditedHead || '', selectedCandidateId: b?.selectedCandidateId || '', commandName: selectedInterface?.commandName, pythonEntrypoint: selectedInterface?.pythonEntrypoint, selectedInterface, boundaryResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-boundary-result.json' as const, checks: [], blockers: [], warnings: [], canCreateRuntimeNow: false as const, canExecuteHermesNow: false as const, canExecuteHermesOutsideAdapter: false as const, canRunHermesScripts: false as const, canUseNetworkNow: false as const, canUseCredentialsNow: false as const, canCallModelsNow: false as const, canMutateProjectFiles: false as const, canDeploy: false as const, recommendedNextStep: FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_NEXT_STEP }
  if (!b || !c) return { ...base, status: 'blocked', decision: 'blocked_missing_boundary_contract', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_missing_boundary_contract', message: 'Boundary contract result is required.' }] }
  if (b.status !== 'boundary_contract_created' || b.decision !== 'hermes_research_runtime_boundary_contract_created' || b.canProceedToResearchRuntimeApproval !== true) return { ...base, status: 'blocked', decision: 'blocked_boundary_not_created', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_not_created', message: 'Boundary contract is not created.' }] }
  if (b.canCreateRuntimeNow !== false || b.canExecuteHermes !== false || c.commandBoundary.commandsAllowedNow.length !== 0) return { ...base, status: 'blocked', decision: 'blocked_boundary_allows_execution_now', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_allows_execution_now', message: 'Boundary allows immediate execution.' }] }
  if (b.canUseNetwork !== false || c.networkBoundary.networkAllowedNow !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_allows_network_now', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_allows_network_now', message: 'Boundary allows network now.' }] }
  if (b.canUseCredentials !== false || c.credentialBoundary.credentialsAllowedNow !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_allows_credentials_now', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_allows_credentials_now', message: 'Boundary allows credentials now.' }] }
  if (b.canCallModels !== false || c.modelBoundary.modelCallsAllowedNow !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_allows_model_calls_now', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_allows_model_calls_now', message: 'Boundary allows model calls now.' }] }
  if (policy.requireHumanApprovalRef && !input.humanApprovalRef) return { ...base, status: 'human_review_required', decision: 'blocked_missing_human_approval', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] }
  const receipt = { receiptId: `${id}:receipt`, approvalId: id, toolId: 'hermes_agent' as const, auditedHead: b.auditedHead, approvedBy: input.approvedBy, approvedAt: input.approvedAt, humanApprovalRef: input.humanApprovalRef || '', selectedCandidateId: b.selectedCandidateId, decision: 'hermes_research_runtime_approved_for_adapter_candidate' as const, scope: 'hermes_research_runtime_adapter_candidate_only' as const, approvedNextGate: 'Factory Hermes Research Runtime Adapter v1' as const, limitations: ['Approval is only for a future adapter candidate.', 'No runtime is created in this gate.', 'No direct Hermes execution is authorized.'], notAuthorizedActions: [...FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_NOT_AUTHORIZED_ACTIONS] }
  if (!selectedInterface?.commandName || !selectedInterface.pythonEntrypoint) return { ...base, status: 'blocked', decision: 'request_boundary_repair_before_approval', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'missing_selected_interface_identity', message: 'Selected interface commandName and pythonEntrypoint are required.' }] }
  const envelope = { envelopeId: `${id}:envelope`, approvalId: id, toolId: 'hermes_agent' as const, auditedHead: b.auditedHead, selectedCandidateId: b.selectedCandidateId, selectedInterface, boundaryContractRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-boundary-result.json' as const, boundaryContractSummary: { contractId: c.contractId, commandName: selectedInterface.commandName, pythonEntrypoint: selectedInterface.pythonEntrypoint, commandBoundary: c.commandBoundary, networkBoundary: c.networkBoundary, credentialBoundary: c.credentialBoundary, modelBoundary: c.modelBoundary, safetyBoundary: c.safetyBoundary }, approvedNextGate: 'Factory Hermes Research Runtime Adapter v1' as const, adapterReadinessStatus: 'approved_for_adapter_candidate' as const, executionAuthorizationScope: 'future_runtime_adapter_only' as const, directExecutionNow: false as const, futureRuntimeCanExecuteSelectedInterfaceUnderBoundary: true as const, futureRuntimeNetworkAllowed: false as const, futureRuntimeCredentialsAllowed: false as const, futureRuntimeModelCallsAllowed: false as const, futureRuntimeProjectMutationAllowed: false as const, futureRuntimeDeployAllowed: false as const, requiredAdapterControls, requiredNextGates, canProceedToResearchRuntimeAdapter: true as const, canCreateRuntimeNow: false as const, canExecuteHermesNow: false as const, canExecuteHermesOutsideAdapter: false as const, recommendedNextStep: FACTORY_HERMES_RESEARCH_RUNTIME_APPROVAL_NEXT_STEP }
  return { ...base, status: 'approved_for_adapter_candidate', decision: 'hermes_research_runtime_approved_for_adapter_candidate', researchRuntimeApprovalReceipt: receipt, approvedHermesResearchRuntimeAdapterEnvelope: envelope, canProceedToResearchRuntimeAdapter: true }
}
