import { FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_KIND, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_NEXT_STEP, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_VERSION } from './hermes-entrypoint-materialization-approval.defaults.ts'
import type { FactoryHermesEntrypointMaterializationApprovalInput, FactoryHermesEntrypointMaterializationApprovalResult } from './hermes-entrypoint-materialization-approval.types.ts'
export function evaluateFactoryHermesEntrypointMaterializationApproval(input: FactoryHermesEntrypointMaterializationApprovalInput): FactoryHermesEntrypointMaterializationApprovalResult {
  const p = input.materializationPlanningResult; const plan = p?.hermesEntrypointMaterializationPlanCandidate; const method = p?.selectedMethodCandidate?.methodId || ''; const buildBackend = String(plan?.buildSystemSummary?.buildBackend || ''); const setupPyPresent = Boolean(plan?.setupPyPresent); const id = `hermes-entrypoint-materialization-approval:75b300f:${input.approvedAt}`
  const base: FactoryHermesEntrypointMaterializationApprovalResult = { approvalId: id, approvalKind: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_KIND, approvalVersion: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_VERSION, approvedAt: input.approvedAt, approvedBy: input.approvedBy, toolId: 'hermes_agent', selectedCandidateId: p?.selectedCandidateId || '', commandName: p?.commandName || '', pythonEntrypoint: p?.pythonEntrypoint || '', missingExecutableRef: p?.missingExecutableRef || '', sourceRootRef: p?.sourceRootRef || '', pythonEnvRootRef: p?.pythonEnvRootRef || '', uvExecutableRef: plan?.uvExecutableRef || '', selectedMethodCandidate: method, setupPyPresent, buildBackend, checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_materialization_plan', canProceedToEntrypointMaterializationRuntime: false, canMaterializeEntrypointNow: false, canRetryAdapterNow: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_NEXT_STEP }
  if (!p || !plan) return { ...base, blockers: [{ blockerId: 'blocked_missing_materialization_plan', message: 'Planning result is required.' }] }
  if (p.status !== 'plan_candidate_created' || p.decision !== 'hermes_entrypoint_materialization_plan_candidate_created' || p.canProceedToEntrypointMaterializationApproval !== true || p.canMaterializeEntrypointNow !== false || p.canRetryAdapterNow !== false) return { ...base, decision: 'blocked_materialization_plan_not_candidate', blockers: [{ blockerId: 'blocked_materialization_plan_not_candidate', message: 'Planning result is not an approvable candidate.' }] }
  if (method !== 'uv_sync_install_project_locked_existing_env' || plan.selectedMethodCandidate?.usesPip || plan.selectedMethodCandidate?.usesSetupPyDirectly || plan.proposedRuntimeCommand?.shell !== false || plan.proposedRuntimeCommand?.args?.includes('--no-install-project')) return { ...base, decision: 'blocked_unsafe_materialization_method', blockers: [{ blockerId: 'blocked_unsafe_materialization_method', message: 'Materialization method is unsafe.' }] }
  if (!input.humanApprovalRef) return { ...base, status: 'human_review_required', decision: 'blocked_missing_human_approval', blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] }
  if (setupPyPresent && !input.riskAcceptanceNotes) return { ...base, status: 'manual_review_required', decision: 'blocked_build_hook_risk_requires_manual_review', blockers: [{ blockerId: 'blocked_build_hook_risk_requires_manual_review', message: 'setup.py/build backend risk acceptance is required.' }] }
  const receipt = { receiptId: `${id}:receipt`, approvalId: id, toolId: 'hermes_agent' as const, approvedBy: input.approvedBy, approvedAt: input.approvedAt, humanApprovalRef: input.humanApprovalRef, selectedCandidateId: p.selectedCandidateId, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', selectedMethodCandidate: method, setupPyPresent, buildBackend, riskAcceptanceNotes: input.riskAcceptanceNotes || '', decision: 'hermes_entrypoint_materialization_approved_for_runtime_candidate' as const, scope: 'hermes_entrypoint_materialization_runtime_candidate_only' as const, approvedNextGate: 'Factory Hermes Entrypoint Materialization Runtime Adapter v1' as const, limitations: ['Approval is for a future runtime candidate only.', 'No uv sync or materialization is authorized in this gate.', 'setup.py direct execution remains forbidden.'], notAuthorizedActions: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_NOT_AUTHORIZED_ACTIONS }
  const envelope = { envelopeId: `${id}:envelope`, approvalId: id, toolId: 'hermes_agent' as const, selectedCandidateId: p.selectedCandidateId, commandName: 'hermes' as const, pythonEntrypoint: 'hermes_cli.main:main' as const, expectedExecutableRef: p.missingExecutableRef, missingExecutableRef: p.missingExecutableRef, sourceRootRef: p.sourceRootRef, pythonEnvRootRef: p.pythonEnvRootRef, uvExecutableRef: plan.uvExecutableRef, selectedMethodCandidate: 'uv_sync_install_project_locked_existing_env' as const, approvedRuntimeCommand: { executableRef: plan.uvExecutableRef, args: ['sync', '--locked', '--no-dev', '--project', '<sourceRoot>'], cwd: p.sourceRootRef, shell: false as const, timeoutMs: 300000 as const }, approvedEnvPolicy: { UV_PROJECT_ENVIRONMENT: p.pythonEnvRootRef, UV_CACHE_DIR: '.codex-temp/external-tools/uv/cache/', UV_NO_PROGRESS: '1' as const, PYTHONNOUSERSITE: '1' as const, PIP_CONFIG_FILE: 'NUL' as const, sanitized: true as const }, allowedWriteRoots: [p.pythonEnvRootRef, '.codex-temp/external-tools/uv/cache/', '.codex-temp/external-tools/hermes-agent/install/75b300f/entrypoint-materialization-logs/'], forbiddenActions: ['pip', 'python direct', 'setup.py direct', 'hermes execution', 'adapter retry', 'network', 'credentials', 'model calls'], buildRiskAcceptance: { setupPyPresent: true as const, buildBackend: 'setuptools.build_meta' as const, acceptedOnlyForUvSyncProjectInstall: true as const, setupPyDirectExecutionAllowed: false as const }, materializationAllowedNow: false as const, futureRuntimeMayMaterializeEntrypointUnderEnvelope: true as const, adapterRetryAllowedNow: false as const, hermesExecutionAllowedNow: false as const, networkAllowedNow: false as const, credentialsAllowedNow: false as const, modelCallsAllowedNow: false as const, canProceedToEntrypointMaterializationRuntime: true as const, recommendedNextStep: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_APPROVAL_NEXT_STEP }
  return { ...base, status: 'approved_for_runtime_candidate', decision: 'hermes_entrypoint_materialization_approved_for_runtime_candidate', approvalReceipt: receipt, approvedEntrypointMaterializationRuntimeEnvelope: envelope, canProceedToEntrypointMaterializationRuntime: true }
}
