import type { FactoryMemoryRecordDraft } from '../memory-admission/index.ts'
import type { FactoryMemoryWriteApprovalResult } from '../memory-write-approval/index.ts'
export type FactoryMemoryPersistenceVersion = '1.0'
export type FactoryMemoryPersistenceKind = 'factory-memory-persistence'
export type FactoryMemoryPersistenceStatus = 'blocked' | 'rejected' | 'changes_required' | 'human_review_required' | 'ready_for_memory_runtime_persistence' | 'planned_not_persisted'
export type FactoryMemoryPersistenceDecision = 'blocked' | 'reject_memory_write_approval' | 'request_memory_persistence_changes' | 'human_review_required' | 'approve_memory_persistence_plan'
export interface FactoryMemoryPersistencePolicy { requireWriteApprovalResult: true; requireApprovedDecision: true; requireApprovalReceipt: true; requireApprovedMemoryEnvelope: true; requireAtLeastOneRecordDraft: true; requireProjectScopedRecordsOnly: true; requireValidNamespaces: true; requireLineage: true; requireNoSecrets: true; requireNoRawEvidence: true; requireCanonicalPayload: true; requireFingerprint: true; requireIdempotencyKey: true; requireAtomicWritePlan: true; requireRollbackPlan: true; forbidMemoryRuntimeWriteInThisGate: true; forbidEmbeddingsCreation: true; forbidGlobalPromotion: true; forbidCodexTaskCreation: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; requireRelativeLogicalTargets: true; forbidAbsoluteLogicalTargets: true; forbidPathTraversal: true }
export interface FactoryMemoryPersistenceInput { memoryWriteApprovalResult: FactoryMemoryWriteApprovalResult; createdAt: string; plannedBy: string; policy?: Partial<FactoryMemoryPersistencePolicy>; storageNamespace?: string; logicalRootSuggestion?: string }
export interface FactoryMemoryCanonicalPayload { memoryRecordId: string; memoryRecordKind: string; memoryRecordVersion: string; namespace: string; projectNamespace: string; scope: string; source: FactoryMemoryRecordDraft['source']; title: string; summary: string; canonicalFacts: FactoryMemoryRecordDraft['canonicalFacts']; references: FactoryMemoryRecordDraft['references']; lineage: FactoryMemoryRecordDraft['lineage']; tags: string[]; retentionPolicy: string; promotionPolicy: FactoryMemoryRecordDraft['promotionPolicy']; stalePolicy: FactoryMemoryRecordDraft['stalePolicy']; replacementPolicy: FactoryMemoryRecordDraft['replacementPolicy']; safety: { containsSecrets: false; containsRawEvidence: false; globalPromotionAllowed: false; codexTaskAllowed: false; projectCreationAllowed: false; repositoryCreationAllowed: false; deployAllowed: false } }
export interface FactoryMemoryPersistenceTarget { logicalTarget: string; logicalMetadataTarget: string; logicalIndexTarget: string; projectScoped: true }
export interface FactoryMemoryPersistenceAtomicWritePlan { planId: string; logicalTarget: string; logicalTempTarget: string; logicalMetadataTarget: string; logicalBackupTarget?: string; steps: ('ensure_project_memory_namespace' | 'write_temp_memory_record' | 'validate_temp_memory_record' | 'atomic_promote_temp_to_target' | 'write_memory_metadata' | 'update_project_memory_index' | 'verify_memory_readback')[]; notExecuted: true; memoryWritePerformed: false; futureRuntimeAdapterRequired: true; humanReviewRequiredBeforeExecution: true }
export interface FactoryMemoryPersistenceRollbackPlan { rollbackId: string; triggerConditions: string[]; steps: ('remove_temp_memory_record' | 'preserve_failed_memory_payload_for_review' | 'restore_previous_memory_record_if_backup_exists' | 'mark_memory_persistence_failed' | 'require_human_review')[]; notExecuted: true; rollbackExecuted: false }
export interface FactoryMemoryRecordPersistencePlan { recordPlanId: string; sourceMemoryRecordId: string; memoryRecordKind: string; namespace: string; projectNamespace: string; target: FactoryMemoryPersistenceTarget; canonicalPayload: FactoryMemoryCanonicalPayload; fingerprint: { algorithm: 'fnv1a-32'; value: string; cryptographic: false }; idempotencyKey: string; atomicWritePlan: FactoryMemoryPersistenceAtomicWritePlan; rollbackPlan: FactoryMemoryPersistenceRollbackPlan; persistenceStatus: 'planned_not_persisted'; embeddingsStatus: 'not_allowed'; codexTaskStatus: 'not_allowed'; globalPromotionStatus: 'not_allowed'; warnings: string[]; blockers: string[] }
export interface FactoryMemoryPersistenceManifest { manifestId: string; manifestKind: 'factory-memory-persistence-manifest'; manifestVersion: '1.0'; sourceApprovalId: string; sourceAdmissionId: string; generatedAt: string; generatedBy: string; recordsCount: number; namespaces: string[]; fingerprints: string[]; idempotencyKeys: string[]; targetCount: number; memoryRuntimeStatus: 'not_executable'; memoryPersistenceStatus: 'not_persisted'; embeddingsStatus: 'not_allowed'; codexTaskStatus: 'not_allowed'; globalPromotionStatus: 'not_allowed' }
export interface FactoryMemoryPersistenceCheck { checkId: string; passed: boolean; message: string }
export interface FactoryMemoryPersistenceBlocker { blockerId: string; recordId?: string; reason: string }
export interface FactoryMemoryPersistenceWarning { warningId: string; recordId?: string; message: string }
export interface FactoryMemoryPersistenceSummary { persistenceId: string; sourceApprovalId: string; sourceAdmissionId: string; decision: FactoryMemoryPersistenceDecision; status: FactoryMemoryPersistenceStatus; recordPlansCount: number; namespaces: string[]; fingerprintsCount: number; idempotencyKeysCount: number; canWriteMemoryRuntime: false; embeddingsStatus: 'not_allowed'; codexTaskStatus: 'not_allowed'; recommendedNextStep: string }
export interface FactoryMemoryPersistenceResult { persistenceId: string; persistenceKind: FactoryMemoryPersistenceKind; persistenceVersion: FactoryMemoryPersistenceVersion; createdAt: string; plannedBy: string; sourceApprovalId: string; sourceAdmissionId: string; status: FactoryMemoryPersistenceStatus; decision: FactoryMemoryPersistenceDecision; manifest?: FactoryMemoryPersistenceManifest; recordPlans: FactoryMemoryRecordPersistencePlan[]; checks: FactoryMemoryPersistenceCheck[]; blockers: FactoryMemoryPersistenceBlocker[]; warnings: FactoryMemoryPersistenceWarning[]; summary: FactoryMemoryPersistenceSummary; canWriteMemoryRuntime: false; canCreateEmbeddings: false; canPromoteGlobalMemory: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryPersistenceValidationResult { ok: boolean; errors: string[]; warnings: string[] }
