export type FactoryHermesBuildDependencyCacheVerificationVersion = '1.0'
export type FactoryHermesBuildDependencyCacheVerificationKind = 'factory-hermes-build-dependency-cache-verification'
export type FactoryHermesBuildDependencyCacheVerificationStatus = 'verified' | 'warning_verified' | 'blocked'
export type FactoryHermesBuildDependencyCacheVerificationDecision = 'hermes_build_dependency_cache_verified_for_materialization_retry' | 'blocked_missing_cache_runtime_result' | 'blocked_cache_runtime_not_success' | 'blocked_cache_metadata_missing' | 'blocked_cache_dependency_not_verified' | 'blocked_unexpected_source_mutation' | 'blocked_unexpected_materialization_during_cache_runtime' | 'blocked_boundary_violation_detected' | 'request_cache_runtime_repair_before_verification'
export interface FactoryHermesBuildDependencyCacheVerificationInput { verifiedAt: string; verifiedBy: string; cacheRuntimeResult?: any; cacheRuntimeManifest?: any; cacheMetadataRecord?: any; cacheCommandSummary?: any; cacheInspection?: any; sourceInspection?: any; approvalResult?: any; policy?: Record<string, unknown>; verificationNotes?: string }
export interface FactoryHermesBuildDependencyCacheVerificationReceipt { receiptId: string; verificationId: string; toolId: 'hermes_agent'; verifiedBy: string; verifiedAt: string; missingBuildDependency: string; lockedPackageName: string; lockedPackageVersion: string; cacheStatus: string; tempEnvStatus: string; metadataStatus: string; sourceMutationStatus: string; decision: FactoryHermesBuildDependencyCacheVerificationDecision; scope: 'hermes_build_dependency_cache_verification_only'; approvedNextGate: 'Factory Hermes Entrypoint Materialization Runtime Retry Gate v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesBuildDependencyCacheVerificationResult { verificationId: string; verificationKind: FactoryHermesBuildDependencyCacheVerificationKind; verificationVersion: FactoryHermesBuildDependencyCacheVerificationVersion; verifiedAt: string; verifiedBy: string; toolId: 'hermes_agent'; missingBuildDependency: string; lockedPackageName: string; lockedPackageVersion: string; selectedMethodCandidate: string; cacheStatus: string; tempEnvStatus: string; metadataStatus: string; sourceMutationStatus: string; cacheVerificationReceipt?: FactoryHermesBuildDependencyCacheVerificationReceipt; hermesBuildDependencyCacheVerificationRecord?: any; approvedEntrypointMaterializationRuntimeRetryEnvelope?: any; checks: any[]; blockers: any[]; warnings: any[]; status: FactoryHermesBuildDependencyCacheVerificationStatus; decision: FactoryHermesBuildDependencyCacheVerificationDecision; canProceedToEntrypointMaterializationRuntimeRetry: boolean; canRetryMaterializationNow: false; canExecuteHermes: false; canRunHermesScripts: false; canUseNetworkNow: false; canUseNetworkInMaterializationRetry: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesBuildDependencyCacheVerificationValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesBuildDependencyCacheVerificationSummary { verificationId: string; missingBuildDependency: string; lockedPackageVersion: string; status: FactoryHermesBuildDependencyCacheVerificationStatus; decision: FactoryHermesBuildDependencyCacheVerificationDecision; sourceMutationStatus: string; canProceedToEntrypointMaterializationRuntimeRetry: boolean; canRetryMaterializationNow: false; nextStep: string }
