import { FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_VERIFICATION_KIND, FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_VERIFICATION_NEXT_STEP, FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_VERIFICATION_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_VERIFICATION_VERSION } from './hermes-build-dependency-cache-verification.defaults.ts'
import type { FactoryHermesBuildDependencyCacheVerificationInput, FactoryHermesBuildDependencyCacheVerificationResult } from './hermes-build-dependency-cache-verification.types.ts'

function base(input: FactoryHermesBuildDependencyCacheVerificationInput): FactoryHermesBuildDependencyCacheVerificationResult {
  const r = input.cacheRuntimeResult || {}
  return { verificationId: `hermes-build-dependency-cache-verification:75b300f:${input.verifiedAt}`, verificationKind: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_VERIFICATION_KIND, verificationVersion: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_VERIFICATION_VERSION, verifiedAt: input.verifiedAt, verifiedBy: input.verifiedBy, toolId: 'hermes_agent', missingBuildDependency: r.missingBuildDependency || '', lockedPackageName: r.lockedPackageName || '', lockedPackageVersion: r.lockedPackageVersion || '', selectedMethodCandidate: r.selectedMethodCandidate || '', cacheStatus: r.cacheStatus || '', tempEnvStatus: r.tempEnvStatus || '', metadataStatus: r.metadataStatus || '', sourceMutationStatus: 'unknown', checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_cache_runtime_result', canProceedToEntrypointMaterializationRuntimeRetry: false, canRetryMaterializationNow: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetworkNow: false, canUseNetworkInMaterializationRetry: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_VERIFICATION_NEXT_STEP }
}

export function evaluateFactoryHermesBuildDependencyCacheVerification(input: FactoryHermesBuildDependencyCacheVerificationInput): FactoryHermesBuildDependencyCacheVerificationResult {
  const r = input.cacheRuntimeResult; const meta = input.cacheMetadataRecord; const out = base(input)
  if (!r) return { ...out, blockers: [{ blockerId: 'blocked_missing_cache_runtime_result', message: 'Cache runtime result is required.' }] }
  if (r.status !== 'success' || r.decision !== 'hermes_build_dependency_cache_prefetch_completed' || r.cacheStatus !== 'prefetched' || r.canProceedToBuildDependencyCacheVerification !== true) return { ...out, decision: 'blocked_cache_runtime_not_success', blockers: [{ blockerId: 'blocked_cache_runtime_not_success', message: 'Cache runtime did not complete successfully.' }] }
  if (!meta || meta.packageName !== 'setuptools' || meta.lockedPackageVersion !== '81.0.0' || meta.networkScope !== 'cache_prefetch_only') return { ...out, decision: 'blocked_cache_metadata_missing', blockers: [{ blockerId: 'blocked_cache_metadata_missing', message: 'Cache metadata is missing or incomplete.' }] }
  const unsafe = r.materializationStatus !== 'not_attempted' || r.adapterRetryStatus !== 'not_attempted' || r.hermesExecutionStatus !== 'not_executed' || r.pipStatus !== 'not_executed' || r.pythonDirectStatus !== 'not_executed' || r.setupPyDirectStatus !== 'not_executed' || r.credentialsStatus !== 'not_allowed' || r.modelCallStatus !== 'not_allowed'
  if (unsafe) return { ...out, decision: 'blocked_boundary_violation_detected', blockers: [{ blockerId: 'blocked_boundary_violation_detected', message: 'Runtime result violates safety boundary.' }] }
  const hashesUnchanged = JSON.stringify(r.beforeState?.sourceKeyHashes || {}) === JSON.stringify(r.afterState?.sourceKeyHashes || {})
  const materialized = r.afterState?.realPythonEnvHermesExeExists === true
  if (materialized) return { ...out, decision: 'blocked_unexpected_materialization_during_cache_runtime', blockers: [{ blockerId: 'blocked_unexpected_materialization_during_cache_runtime', message: 'Real python env hermes.exe appeared during cache runtime.' }] }
  const sourceEntries = r.afterState?.sourceSuspiciousEntries || []
  const blockingMutation = !hashesUnchanged || sourceEntries.some((x: string) => ['dist', 'build', '.venv'].includes(x))
  if (blockingMutation) return { ...out, decision: 'blocked_unexpected_source_mutation', sourceMutationStatus: 'unexpected_source_mutation', blockers: [{ blockerId: 'blocked_unexpected_source_mutation', message: 'Source mutation exceeded allowed metadata warning.' }] }
  const warningEntries = sourceEntries.filter((x: string) => x === 'hermes_agent.egg-info' || x === '.codex-temp')
  const warnings = warningEntries.map((x: string) => ({ warningId: x === 'hermes_agent.egg-info' ? 'source_metadata_egg_info_created_by_cache_runtime' : 'source_nested_codex_temp_left_from_repaired_runtime_attempt', message: x }))
  const decision = 'hermes_build_dependency_cache_verified_for_materialization_retry' as const
  const sourceMutationStatus = warningEntries.length ? 'metadata_warning_only' : 'unchanged'
  const receipt = { receiptId: `${out.verificationId}:receipt`, verificationId: out.verificationId, toolId: 'hermes_agent' as const, verifiedBy: input.verifiedBy, verifiedAt: input.verifiedAt, missingBuildDependency: r.missingBuildDependency, lockedPackageName: r.lockedPackageName, lockedPackageVersion: r.lockedPackageVersion, cacheStatus: r.cacheStatus, tempEnvStatus: r.tempEnvStatus, metadataStatus: r.metadataStatus, sourceMutationStatus, decision, scope: 'hermes_build_dependency_cache_verification_only' as const, approvedNextGate: 'Factory Hermes Entrypoint Materialization Runtime Retry Gate v1' as const, limitations: ['Verification only.', 'No materialization retry, uv execution, network use or Hermes execution is authorized now.'], notAuthorizedActions: FACTORY_HERMES_BUILD_DEPENDENCY_CACHE_VERIFICATION_NOT_AUTHORIZED_ACTIONS }
  const record = { recordId: `${out.verificationId}:record`, verificationId: out.verificationId, toolId: 'hermes_agent', missingBuildDependency: r.missingBuildDependency, lockedPackageName: 'setuptools', lockedPackageVersion: '81.0.0', selectedMethodCandidate: r.selectedMethodCandidate, cacheRuntimeResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-runtime-result.json', cacheRuntimeManifestRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-runtime-manifest.json', metadataRecordRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-metadata/build-dependency-cache-record.json', cacheVerification: { cacheStatus: r.cacheStatus, metadataStatus: r.metadataStatus, tempEnvStatus: r.tempEnvStatus, uvCacheRootRef: r.uvCacheRootRef, metadataRootRef: r.metadataRootRef, recordedHashes: meta.recordedHashes || [], recordedSourceUrls: meta.recordedSourceUrls || [], recordedHosts: meta.recordedHosts || [] }, safetyVerification: { noHermesExecution: true, noSelectedInterfaceExecution: true, noMaterializationRetry: true, noResearchAdapterRetry: true, noPip: true, noPythonDirect: true, noSetupPyDirect: true, noUvRun: true, noUvPip: true, noUvVenv: true, noCredentials: true, noModelCalls: true }, sourceVerification: { keyFileHashesUnchanged: true, eggInfoWarning: warningEntries.includes('hermes_agent.egg-info'), unexpectedSourceMutation: false }, materializationRetryReadiness: { buildDependencyCacheVerified: true, futureMaterializationRuntimeMustUseUvOffline: true, futureMaterializationRuntimeMayRetryUnderSeparateGate: true }, canProceedToEntrypointMaterializationRuntimeRetry: true, canRetryMaterializationNow: false }
  const envelope = { envelopeId: `${out.verificationId}:envelope`, verificationId: out.verificationId, toolId: 'hermes_agent', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', expectedExecutableRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/Scripts/hermes.exe', sourceRootRef: r.sourceRootRef, pythonEnvRootRef: r.pythonEnvRootRef, uvExecutableRef: r.uvExecutableRef, uvCacheRootRef: r.uvCacheRootRef, verifiedBuildDependency: { packageName: 'setuptools', lockedPackageVersion: '81.0.0', versionConstraint: 'setuptools>=77,<83', cacheStatus: 'prefetched' }, retryMethodCandidate: 'uv_sync_install_project_locked_existing_env', approvedNextGate: 'Factory Hermes Entrypoint Materialization Runtime Retry Gate v1', retryAllowedNow: false, futureRetryMayExecuteUvSyncOffline: true, futureRetryMustUseUvOffline: true, futureRetryMustNotUseNetwork: true, futureRetryMustNotExecuteHermes: true, futureRetryMustNotUsePip: true, futureRetryMustNotExecutePythonDirect: true, futureRetryMustNotExecuteSetupPyDirect: true, requiredFutureGates: ['Factory Hermes Entrypoint Materialization Runtime Retry Gate v1', 'Factory Hermes Entrypoint Materialization Verification Gate v1', 'Factory Hermes Research Runtime Adapter Retry Gate v1'] }
  return { ...out, status: warnings.length ? 'warning_verified' : 'verified', decision, sourceMutationStatus, cacheVerificationReceipt: receipt, hermesBuildDependencyCacheVerificationRecord: record, approvedEntrypointMaterializationRuntimeRetryEnvelope: envelope, warnings, canProceedToEntrypointMaterializationRuntimeRetry: true }
}
