const fs = require('node:fs/promises');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { assertWrapperNoToolModePlanningPathContained, resolveFactoryHermesWrapperNoToolModePlanningPaths } = require('./hermes-wrapper-no-tool-mode-planning.path.cjs');
async function readJson(file) { const text = await fs.readFile(file, 'utf8'); if (!text.trim()) throw new Error(`json_file_empty: ${file}`); return JSON.parse(text); }
async function readText(file) { try { return await fs.readFile(file, 'utf8'); } catch { return ''; } }
function inspect(texts) { const joined = Object.values(texts).join('\n'); return { sourceFilesInspected: Object.keys(texts), runOneshotAcceptsToolsetsArgument: joined.includes('def run_oneshot') && joined.includes('toolsets:'), explicitToolsetValidationExists: joined.includes('_validate_explicit_toolsets'), runAgentHasAIAgent: joined.includes('AIAgent'), configDefaultsRisk: joined.includes('_get_platform_tools') || joined.includes('platform_toolsets') }; }
async function executeFactoryHermesWrapperNoToolModePlanning(input = {}) { const paths = resolveFactoryHermesWrapperNoToolModePlanningPaths(); for (const target of Object.entries(paths).filter(([k]) => !['repoRoot', 'installRoot', 'sourceRoot'].includes(k)).map(([, v]) => v)) assertWrapperNoToolModePlanningPathContained(target, paths.installRoot); const texts = { 'hermes_cli/main.py': await readText(paths.main), 'hermes_cli/oneshot.py': await readText(paths.oneshot), 'hermes_cli/tools_config.py': await readText(paths.toolsConfig), 'hermes_cli/config.py': await readText(paths.config), 'hermes_cli/runtime_provider.py': await readText(paths.runtimeProvider), 'hermes_cli/auth.py': await readText(paths.auth), 'toolsets.py': await readText(paths.toolsets), 'run_agent.py': await readText(paths.runAgent), 'README.md': await readText(paths.readme), 'pyproject.toml': await readText(paths.pyproject) }; const { evaluateFactoryHermesWrapperNoToolModePlanning } = await import(pathToFileURL(path.join(paths.repoRoot, 'src', 'factory', 'hermes-wrapper-no-tool-mode-planning', 'index.ts')).href); const result = evaluateFactoryHermesWrapperNoToolModePlanning({ plannedAt: input.plannedAt || '2026-07-23T01:00:00.000Z', plannedBy: input.plannedBy || 'factory-hermes-wrapper-no-tool-mode-planning-smoke', runtimeSelectionRevisionPlanningResult: input.runtimeSelectionRevisionPlanningResult || await readJson(paths.revisionPlanningResult), toolsetDisableVerificationApprovalResult: input.toolsetDisableVerificationApprovalResult || await readJson(paths.toolsetApprovalResult), researchRuntimeAdapterApprovalResult: input.researchRuntimeAdapterApprovalResult || await readJson(paths.adapterApprovalResult), runtimeSelectionDecisionResult: input.runtimeSelectionDecisionResult || await readJson(paths.runtimeSelectionDecisionResult), sourceInspection: input.sourceInspection || inspect(texts) }); await fs.mkdir(path.dirname(paths.wrapperPlanningResult), { recursive: true }); await fs.writeFile(paths.wrapperPlanningResult, `${JSON.stringify(result, null, 2)}\n`); return result; }
module.exports = { executeFactoryHermesWrapperNoToolModePlanning };
