export type FactoryHermesEntrypointMaterializationPlanningVersion = '1.0'
export type FactoryHermesEntrypointMaterializationPlanningKind = 'factory-hermes-entrypoint-materialization-planning'
export type FactoryHermesEntrypointMaterializationPlanningStatus = 'plan_candidate_created' | 'manual_review_required' | 'blocked'
export type FactoryHermesEntrypointMaterializationPlanningDecision = 'hermes_entrypoint_materialization_plan_candidate_created' | 'hermes_entrypoint_materialization_requires_manual_build_hook_review' | 'blocked_missing_research_jefe_review' | 'blocked_jefe_review_not_approved_for_materialization_planning' | 'blocked_source_missing' | 'blocked_pyproject_missing' | 'blocked_script_declaration_missing' | 'blocked_python_env_missing' | 'request_entrypoint_materialization_review'
export interface FactoryHermesEntrypointMaterializationPlanningInput { plannedAt: string; plannedBy: string; humanApprovalRef?: string; researchJefeReviewResult?: any; sourceInspection?: any; policy?: Partial<FactoryHermesEntrypointMaterializationPlanningPolicy>; planningNotes?: string }
export interface FactoryHermesEntrypointMaterializationPlanningPolicy { requireResearchJefeReviewApproved: boolean; requireSourceInspection: boolean; requirePyproject: boolean; requireProjectScriptHermes: boolean; requirePythonEnvRootUnderCodexTemp: boolean; requireSourceRootUnderCodexTemp: boolean; requireUvVerified: boolean; requirePythonInstallVerified: boolean; requireApprovalNext: boolean; forbidMaterializationInThisGate: boolean; forbidAdapterRetryInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidHermesScriptsInThisGate: boolean; forbidUvExecutionInThisGate: boolean; forbidPipExecutionInThisGate: boolean; forbidPythonExecutionInThisGate: boolean; forbidSetupPyExecutionInThisGate: boolean; forbidNetworkInThisGate: boolean; forbidCredentialsInThisGate: boolean; forbidModelCallsInThisGate: boolean; forbidProjectMutationInThisGate: boolean; forbidDeployInThisGate: boolean; requireRuntimeAdapterFuture: boolean; requireVerificationFuture: boolean; requireAdapterRetryFuture: boolean }
export interface FactoryHermesEntrypointMaterializationMethodCandidate { methodId: string; status: 'candidate_only' | 'not_recommended_for_now' | 'forbidden'; description: string; risks: string[]; usesPip: boolean; usesSetupPyDirectly: boolean; usesUv: boolean }
export interface FactoryHermesEntrypointMaterializationPlanCandidate { planCandidateId: string; toolId: 'hermes_agent'; selectedCandidateId: string; commandName: 'hermes'; pythonEntrypoint: 'hermes_cli.main:main'; missingExecutableRef: string; expectedExecutableRef: string; sourceRootRef: string; pythonEnvRootRef: string; uvExecutableRef: string; selectedMethodCandidate: FactoryHermesEntrypointMaterializationMethodCandidate; methodCandidates: FactoryHermesEntrypointMaterializationMethodCandidate[]; buildSystemSummary: Record<string, unknown>; projectScriptsSummary: Record<string, string>; setupPyPresent: boolean; riskAssessment: string[]; proposedRuntimeCommand: { executableRef: string; args: string[]; shell: false; cwd: string; envPolicy: 'sanitized_uv_project_environment'; timeoutMsDefault: 300000 }; proposedFilesystemPolicy: { allowedReadRoots: string[]; allowedWriteRoots: string[]; forbiddenRoots: string[] }; proposedNetworkPolicy: { networkAllowedNow: false; futureRuntimeNetworkDefault: false; controlledFailureIfNetworkRequired: true }; proposedVerification: string[]; requiredNextGates: string[] }
export interface FactoryHermesEntrypointMaterializationPlanningReceipt { receiptId: string; planningId: string; toolId: 'hermes_agent'; plannedBy: string; plannedAt: string; selectedCandidateId: string; commandName: string; pythonEntrypoint: string; decision: FactoryHermesEntrypointMaterializationPlanningDecision; scope: 'hermes_entrypoint_materialization_planning_only'; approvedNextGate: 'Factory Hermes Entrypoint Materialization Approval Gate v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesEntrypointMaterializationPlanningCheck { checkId: string; ok: boolean; message: string }
export interface FactoryHermesEntrypointMaterializationPlanningBlocker { blockerId: string; message: string }
export interface FactoryHermesEntrypointMaterializationPlanningWarning { warningId: string; message: string }
export interface FactoryHermesEntrypointMaterializationPlanningResult { planningId: string; planningKind: FactoryHermesEntrypointMaterializationPlanningKind; planningVersion: FactoryHermesEntrypointMaterializationPlanningVersion; plannedAt: string; plannedBy: string; toolId: 'hermes_agent'; selectedCandidateId: string; commandName: string; pythonEntrypoint: string; missingExecutableRef: string; sourceRootRef: string; pythonEnvRootRef: string; currentInstallMethod: string; sourceInspectionSummary: Record<string, unknown>; methodCandidates: FactoryHermesEntrypointMaterializationMethodCandidate[]; selectedMethodCandidate?: FactoryHermesEntrypointMaterializationMethodCandidate; entrypointMaterializationPlanningReceipt?: FactoryHermesEntrypointMaterializationPlanningReceipt; hermesEntrypointMaterializationPlanCandidate?: FactoryHermesEntrypointMaterializationPlanCandidate; checks: FactoryHermesEntrypointMaterializationPlanningCheck[]; blockers: FactoryHermesEntrypointMaterializationPlanningBlocker[]; warnings: FactoryHermesEntrypointMaterializationPlanningWarning[]; status: FactoryHermesEntrypointMaterializationPlanningStatus; decision: FactoryHermesEntrypointMaterializationPlanningDecision; canProceedToEntrypointMaterializationApproval: boolean; canMaterializeEntrypointNow: false; canRetryAdapterNow: false; canExecuteHermes: false; canRunHermesScripts: false; canUseNetwork: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesEntrypointMaterializationPlanningValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesEntrypointMaterializationPlanningSummary { planningId: string; commandName: string; pythonEntrypoint: string; status: FactoryHermesEntrypointMaterializationPlanningStatus; decision: FactoryHermesEntrypointMaterializationPlanningDecision; selectedMethodCandidate?: string; canProceedToEntrypointMaterializationApproval: boolean; canMaterializeEntrypointNow: false; canRetryAdapterNow: false; nextStep: string }
