import { FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_PLANNING_KIND, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_PLANNING_NEXT_STEP, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_PLANNING_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_PLANNING_VERSION } from './hermes-entrypoint-materialization-planning.defaults.ts'
import type { FactoryHermesEntrypointMaterializationMethodCandidate, FactoryHermesEntrypointMaterializationPlanningInput, FactoryHermesEntrypointMaterializationPlanningResult } from './hermes-entrypoint-materialization-planning.types.ts'
const sourceRootRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/source'
const pythonEnvRootRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env'
const missingExecutableRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/Scripts/hermes.exe'
const uvExecutableRef = '.codex-temp/external-tools/uv/bin/uv.exe'
const methodCandidates: FactoryHermesEntrypointMaterializationMethodCandidate[] = [
  { methodId: 'uv_sync_install_project_locked_existing_env', status: 'candidate_only', description: 'Future controlled uv sync without --no-install-project into existing env.', risks: ['PEP 517 build backend may run.', 'Network must stay blocked unless separately approved.', 'Writes must stay inside python-env and uv cache.'], usesPip: false, usesSetupPyDirectly: false, usesUv: true },
  { methodId: 'direct_python_module_boundary_revision', status: 'not_recommended_for_now', description: 'Change boundary to invoke Python module directly.', risks: ['Requires direct Python execution and boundary change.'], usesPip: false, usesSetupPyDirectly: false, usesUv: false },
  { methodId: 'manual_wrapper_generation', status: 'not_recommended_for_now', description: 'Generate wrapper manually.', risks: ['Bypasses packaging metadata.'], usesPip: false, usesSetupPyDirectly: false, usesUv: false },
  { methodId: 'pip_install_project', status: 'forbidden', description: 'Use pip install.', risks: ['pip is forbidden by current governance.'], usesPip: true, usesSetupPyDirectly: false, usesUv: false },
  { methodId: 'setup_py_install', status: 'forbidden', description: 'Run setup.py directly.', risks: ['setup.py direct execution is forbidden.'], usesPip: false, usesSetupPyDirectly: true, usesUv: false },
]
function base(input: FactoryHermesEntrypointMaterializationPlanningInput): FactoryHermesEntrypointMaterializationPlanningResult { const j = input.researchJefeReviewResult || {}; return { planningId: `hermes-entrypoint-materialization-planning:75b300f:${input.plannedAt}`, planningKind: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_PLANNING_KIND, planningVersion: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', selectedCandidateId: j.selectedCandidateId || '', commandName: j.commandName || '', pythonEntrypoint: j.pythonEntrypoint || '', missingExecutableRef, sourceRootRef, pythonEnvRootRef, currentInstallMethod: 'uv sync --locked --no-install-project --no-dev --project', sourceInspectionSummary: input.sourceInspection || {}, methodCandidates, checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_research_jefe_review', canProceedToEntrypointMaterializationApproval: false, canMaterializeEntrypointNow: false, canRetryAdapterNow: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_PLANNING_NEXT_STEP } }
export function evaluateFactoryHermesEntrypointMaterializationPlanning(input: FactoryHermesEntrypointMaterializationPlanningInput): FactoryHermesEntrypointMaterializationPlanningResult {
  const j = input.researchJefeReviewResult; const s = input.sourceInspection; const out = base(input)
  if (!j) return { ...out, blockers: [{ blockerId: 'blocked_missing_research_jefe_review', message: 'Research JEFE Review result is required.' }] }
  if (j.status !== 'approved_for_entrypoint_materialization_planning' || j.decision !== 'hermes_research_jefe_review_approved_entrypoint_materialization_planning' || j.canProceedToEntrypointMaterializationPlanning !== true || j.canMaterializeEntrypointNow !== false || j.canRetryAdapterNow !== false) return { ...out, decision: 'blocked_jefe_review_not_approved_for_materialization_planning', blockers: [{ blockerId: 'blocked_jefe_review_not_approved_for_materialization_planning', message: 'JEFE Review did not approve planning.' }] }
  if (!s?.sourceRootExists) return { ...out, decision: 'blocked_source_missing', blockers: [{ blockerId: 'blocked_source_missing', message: 'Hermes source root is missing.' }] }
  if (!s.pyprojectPresent) return { ...out, decision: 'blocked_pyproject_missing', blockers: [{ blockerId: 'blocked_pyproject_missing', message: 'pyproject.toml is missing.' }] }
  if (s.projectScripts?.hermes !== 'hermes_cli.main:main') return { ...out, decision: 'blocked_script_declaration_missing', blockers: [{ blockerId: 'blocked_script_declaration_missing', message: 'pyproject project.scripts hermes declaration is missing.' }] }
  if (!s.pythonEnvExists) return { ...out, decision: 'blocked_python_env_missing', blockers: [{ blockerId: 'blocked_python_env_missing', message: 'python-env is missing.' }] }
  const selected = methodCandidates[0]
  const id = out.planningId
  const receipt = { receiptId: `${id}:receipt`, planningId: id, toolId: 'hermes_agent' as const, plannedBy: input.plannedBy, plannedAt: input.plannedAt, selectedCandidateId: j.selectedCandidateId, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', decision: 'hermes_entrypoint_materialization_plan_candidate_created' as const, scope: 'hermes_entrypoint_materialization_planning_only' as const, approvedNextGate: 'Factory Hermes Entrypoint Materialization Approval Gate v1' as const, limitations: ['Planning only.', 'No uv sync or project install is authorized now.', 'No adapter retry or Hermes execution is authorized.'], notAuthorizedActions: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_PLANNING_NOT_AUTHORIZED_ACTIONS }
  const plan = { planCandidateId: `${id}:candidate`, toolId: 'hermes_agent' as const, selectedCandidateId: j.selectedCandidateId, commandName: 'hermes' as const, pythonEntrypoint: 'hermes_cli.main:main' as const, missingExecutableRef, expectedExecutableRef: missingExecutableRef, sourceRootRef, pythonEnvRootRef, uvExecutableRef, selectedMethodCandidate: selected, methodCandidates, buildSystemSummary: s.buildSystem || {}, projectScriptsSummary: s.projectScripts || {}, setupPyPresent: Boolean(s.setupPyPresent), riskAssessment: ['setuptools.build_meta may invoke build hooks.', 'setup.py exists and requires manual approval before any runtime.', 'Network remains blocked by default.'], proposedRuntimeCommand: { executableRef: uvExecutableRef, args: ['sync', '--locked', '--no-dev', '--project', '<sourceRoot>'], shell: false as const, cwd: sourceRootRef, envPolicy: 'sanitized_uv_project_environment' as const, timeoutMsDefault: 300000 as const }, proposedFilesystemPolicy: { allowedReadRoots: [sourceRootRef, pythonEnvRootRef, '.codex-temp/external-tools/uv/cache'], allowedWriteRoots: [pythonEnvRootRef, '.codex-temp/external-tools/uv/cache', '.codex-temp/external-tools/hermes-agent/install/75b300f/entrypoint-materialization-logs'], forbiddenRoots: ['repo root', '.env', 'user home', 'system dirs'] }, proposedNetworkPolicy: { networkAllowedNow: false as const, futureRuntimeNetworkDefault: false as const, controlledFailureIfNetworkRequired: true as const }, proposedVerification: ['expected hermes.exe exists', 'no adapter retry until verification', 'run no Hermes during materialization', 'later verification may run hermes.exe --help under adapter rules'], requiredNextGates: ['Factory Hermes Entrypoint Materialization Approval Gate v1', 'Factory Hermes Entrypoint Materialization Runtime Adapter v1', 'Factory Hermes Entrypoint Materialization Verification Gate v1', 'Factory Hermes Research Runtime Adapter Retry Gate v1', 'Factory Hermes Research Result Ingestion Gate v2 or retry ingestion'] }
  return { ...out, status: 'plan_candidate_created', decision: 'hermes_entrypoint_materialization_plan_candidate_created', selectedMethodCandidate: selected, entrypointMaterializationPlanningReceipt: receipt, hermesEntrypointMaterializationPlanCandidate: plan, canProceedToEntrypointMaterializationApproval: true }
}
