export type FactoryHermesBuildDependencyCacheRuntimeVersion = '1.0'
export type FactoryHermesBuildDependencyCacheRuntimeKind = 'factory-hermes-build-dependency-cache-runtime'
export type FactoryHermesBuildDependencyCacheRuntimeStatus = 'success' | 'blocked' | 'failed' | 'controlled_failure'
export type FactoryHermesBuildDependencyCacheRuntimeDecision = 'hermes_build_dependency_cache_prefetch_completed' | 'blocked_missing_cache_approval' | 'blocked_approved_cache_policy_invalid' | 'blocked_uv_not_verified' | 'blocked_source_missing' | 'failed_uv_cache_prefetch' | 'failed_cache_metadata_missing' | 'failed_cache_prefetch_unexpected_project_mutation' | 'request_cache_runtime_repair'
export interface FactoryHermesBuildDependencyCacheCommandResult { commandKind: string; executableRef: string; args: string[]; cwdRef: string; shell: false; timeoutMs: number; envRefs: Record<string, string | undefined>; stdoutPreview: string; stderrPreview: string; exitCode: number | null; timedOut: boolean; started: boolean; completed: boolean }
export interface FactoryHermesBuildDependencyCacheRuntimeManifest { manifestKind: string; manifestVersion: FactoryHermesBuildDependencyCacheRuntimeVersion; toolId: 'hermes_agent'; missingBuildDependency: string; lockedPackageName: string; lockedPackageVersion: string | null; selectedMethodCandidate: string; commandSummary: FactoryHermesBuildDependencyCacheCommandResult | null; networkScope: string; nextRequiredGate: string }
export interface FactoryHermesBuildDependencyCacheRuntimeInput { executedAt: string; executedBy: string; approvalResult?: any; dryRun?: boolean; policy?: Record<string, unknown>; runtimeNotes?: string }
export interface FactoryHermesBuildDependencyCacheRuntimeResult { cacheRunId: string; cacheKind: FactoryHermesBuildDependencyCacheRuntimeKind; cacheVersion: FactoryHermesBuildDependencyCacheRuntimeVersion; executedAt: string; executedBy: string; toolId: 'hermes_agent'; missingBuildDependency: string; lockedPackageName: string; lockedPackageVersion: string | null; selectedMethodCandidate: string; uvExecutableRef: string; uvCacheRootRef: string; metadataRootRef: string; tempEnvRootRef: string; sourceRootRef: string; pythonEnvRootRef: string; commandResults: FactoryHermesBuildDependencyCacheCommandResult[]; beforeState: any; afterState: any; cacheStatus: string; tempEnvStatus: string; uvStatus: string; networkStatus: string; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; pipStatus: 'not_executed'; pythonDirectStatus: 'not_executed'; setupPyDirectStatus: 'not_executed'; hermesExecutionStatus: 'not_executed'; scriptsStatus: 'not_executed'; materializationStatus: 'not_attempted'; adapterRetryStatus: 'not_attempted'; metadataStatus: string; status: FactoryHermesBuildDependencyCacheRuntimeStatus; decision: FactoryHermesBuildDependencyCacheRuntimeDecision; blockers: any[]; warnings: any[]; checks: any[]; canProceedToBuildDependencyCacheVerification: boolean; canRetryMaterializationNow: false; canExecuteHermes: false; canUseCredentials: false; canCallModels: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesBuildDependencyCacheRuntimeValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesBuildDependencyCacheRuntimeSummary { cacheRunId: string; missingBuildDependency: string; lockedPackageVersion: string | null; status: FactoryHermesBuildDependencyCacheRuntimeStatus; decision: FactoryHermesBuildDependencyCacheRuntimeDecision; cacheStatus: string; tempEnvStatus: string; networkStatus: string; canProceedToBuildDependencyCacheVerification: boolean; canRetryMaterializationNow: false; nextStep: string }
