const fs = require('node:fs/promises');
const path = require('node:path');
const { resolveFactoryHermesEntrypointMaterializationPlanningPaths, assertPlanningPathContained } = require('./hermes-entrypoint-materialization-planning.path.cjs');
const { inspectHermesEntrypointMaterializationSource } = require('./hermes-entrypoint-materialization-planning.inspect.cjs');
async function readJson(file) { return JSON.parse(await fs.readFile(file, 'utf8')); }
function evaluate(input) {
  const j = input.researchJefeReviewResult; const s = input.sourceInspection; const id = `hermes-entrypoint-materialization-planning:75b300f:${input.plannedAt}`;
  const sourceRootRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/source'; const pythonEnvRootRef = '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env'; const missingExecutableRef = `${pythonEnvRootRef}/Scripts/hermes.exe`; const uvExecutableRef = '.codex-temp/external-tools/uv/bin/uv.exe';
  const methods = [{ methodId: 'uv_sync_install_project_locked_existing_env', status: 'candidate_only', usesPip: false, usesSetupPyDirectly: false, usesUv: true }, { methodId: 'direct_python_module_boundary_revision', status: 'not_recommended_for_now', usesPip: false, usesSetupPyDirectly: false, usesUv: false }, { methodId: 'manual_wrapper_generation', status: 'not_recommended_for_now', usesPip: false, usesSetupPyDirectly: false, usesUv: false }, { methodId: 'pip_install_project', status: 'forbidden', usesPip: true, usesSetupPyDirectly: false, usesUv: false }, { methodId: 'setup_py_install', status: 'forbidden', usesPip: false, usesSetupPyDirectly: true, usesUv: false }];
  const base = { planningId: id, planningKind: 'factory-hermes-entrypoint-materialization-planning', planningVersion: '1.0', plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', selectedCandidateId: j?.selectedCandidateId || '', commandName: j?.commandName || '', pythonEntrypoint: j?.pythonEntrypoint || '', missingExecutableRef, sourceRootRef, pythonEnvRootRef, currentInstallMethod: 'uv sync --locked --no-install-project --no-dev --project', sourceInspectionSummary: s || {}, methodCandidates: methods, checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_research_jefe_review', canProceedToEntrypointMaterializationApproval: false, canMaterializeEntrypointNow: false, canRetryAdapterNow: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: 'Proceed to Factory Hermes Entrypoint Materialization Approval Gate v1; do not run uv sync or materialize now.' };
  if (!j || j.status !== 'approved_for_entrypoint_materialization_planning') return { ...base, decision: 'blocked_jefe_review_not_approved_for_materialization_planning', blockers: [{ blockerId: 'blocked_jefe_review_not_approved_for_materialization_planning', message: 'JEFE Review did not approve planning.' }] };
  if (!s?.sourceRootExists) return { ...base, decision: 'blocked_source_missing', blockers: [{ blockerId: 'blocked_source_missing', message: 'Source missing.' }] };
  if (!s.pyprojectPresent) return { ...base, decision: 'blocked_pyproject_missing', blockers: [{ blockerId: 'blocked_pyproject_missing', message: 'pyproject missing.' }] };
  if (s.projectScripts?.hermes !== 'hermes_cli.main:main') return { ...base, decision: 'blocked_script_declaration_missing', blockers: [{ blockerId: 'blocked_script_declaration_missing', message: 'hermes script missing.' }] };
  if (!s.pythonEnvExists) return { ...base, decision: 'blocked_python_env_missing', blockers: [{ blockerId: 'blocked_python_env_missing', message: 'python-env missing.' }] };
  const selected = methods[0]; const actions = ['materialize_entrypoint_now', 'install_project_now', 'execute_uv_now', 'execute_uv_sync_now', 'execute_python_now', 'execute_pip_now', 'execute_setup_py_now', 'execute_hermes_now', 'retry_adapter_now', 'use_network_now', 'call_models_now', 'access_credentials_now', 'mutate_project_files_now', 'deploy_now'];
  const receipt = { receiptId: `${id}:receipt`, planningId: id, toolId: 'hermes_agent', plannedBy: input.plannedBy, plannedAt: input.plannedAt, selectedCandidateId: j.selectedCandidateId, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', decision: 'hermes_entrypoint_materialization_plan_candidate_created', scope: 'hermes_entrypoint_materialization_planning_only', approvedNextGate: 'Factory Hermes Entrypoint Materialization Approval Gate v1', limitations: ['Planning only.', 'No uv sync now.'], notAuthorizedActions: actions };
  const plan = { planCandidateId: `${id}:candidate`, toolId: 'hermes_agent', selectedCandidateId: j.selectedCandidateId, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', missingExecutableRef, expectedExecutableRef: missingExecutableRef, sourceRootRef, pythonEnvRootRef, uvExecutableRef, selectedMethodCandidate: selected, methodCandidates: methods, buildSystemSummary: s.buildSystem, projectScriptsSummary: s.projectScripts, setupPyPresent: Boolean(s.setupPyPresent), riskAssessment: ['setuptools.build_meta may invoke build hooks.', 'setup.py exists.', 'Network remains blocked by default.'], proposedRuntimeCommand: { executableRef: uvExecutableRef, args: ['sync', '--locked', '--no-dev', '--project', '<sourceRoot>'], shell: false, cwd: sourceRootRef, envPolicy: 'sanitized_uv_project_environment', timeoutMsDefault: 300000 }, proposedFilesystemPolicy: { allowedReadRoots: [sourceRootRef, pythonEnvRootRef, '.codex-temp/external-tools/uv/cache'], allowedWriteRoots: [pythonEnvRootRef, '.codex-temp/external-tools/uv/cache', '.codex-temp/external-tools/hermes-agent/install/75b300f/entrypoint-materialization-logs'], forbiddenRoots: ['repo root', '.env', 'user home', 'system dirs'] }, proposedNetworkPolicy: { networkAllowedNow: false, futureRuntimeNetworkDefault: false, controlledFailureIfNetworkRequired: true }, proposedVerification: ['expected hermes.exe exists', 'no adapter retry until verification', 'run no Hermes during materialization', 'later verification may run hermes.exe --help under adapter rules'], requiredNextGates: ['Factory Hermes Entrypoint Materialization Approval Gate v1', 'Factory Hermes Entrypoint Materialization Runtime Adapter v1', 'Factory Hermes Entrypoint Materialization Verification Gate v1', 'Factory Hermes Research Runtime Adapter Retry Gate v1', 'Factory Hermes Research Result Ingestion Gate v2 or retry ingestion'] };
  return { ...base, status: 'plan_candidate_created', decision: 'hermes_entrypoint_materialization_plan_candidate_created', selectedMethodCandidate: selected, entrypointMaterializationPlanningReceipt: receipt, hermesEntrypointMaterializationPlanCandidate: plan, canProceedToEntrypointMaterializationApproval: true };
}
async function executeFactoryHermesEntrypointMaterializationPlanning(input = {}) {
  const paths = resolveFactoryHermesEntrypointMaterializationPlanningPaths(); assertPlanningPathContained(paths.installRoot, path.join(paths.root, '.codex-temp')); assertPlanningPathContained(paths.planningResult, paths.installRoot);
  const researchJefeReviewResult = await readJson(paths.jefeReviewResult); const sourceInspection = inspectHermesEntrypointMaterializationSource(paths);
  const result = evaluate({ plannedAt: input.plannedAt || '2026-07-21T23:00:00.000Z', plannedBy: input.plannedBy || 'factory-hermes-entrypoint-materialization-planning-smoke', researchJefeReviewResult, sourceInspection });
  await fs.writeFile(paths.planningResult, JSON.stringify(result, null, 2)); return result;
}
module.exports = { executeFactoryHermesEntrypointMaterializationPlanning, inspectHermesEntrypointMaterializationSource, evaluateFactoryHermesEntrypointMaterializationPlanning: evaluate };
