const fs = require('node:fs/promises');
const { resolveFactoryHermesBuildDependencyCacheApprovalPaths, assertApprovalPathContained } = require('./hermes-build-dependency-cache-approval.path.cjs');

const NEXT = 'Proceed to Factory Hermes Build Dependency Cache Runtime Adapter v1; do not cache dependencies, enable network, execute uv, retry materialization, or execute Hermes in this gate.';
const NOT_AUTH = ['cache_build_dependency_now', 'enable_network_now', 'execute_uv_now', 'execute_uv_sync_now', 'execute_uv_pip_now', 'execute_python_now', 'execute_pip_now', 'execute_setup_py_now', 'execute_hermes_now', 'retry_materialization_now', 'retry_adapter_now', 'use_network_now', 'call_models_now', 'access_credentials_now', 'mutate_project_files_now', 'deploy_now'];
function lockedVersion(plan) { const text = JSON.stringify(plan?.sourceInspectionSummary?.uvLockSetuptoolsSummary || []); return (text.match(/setuptools-([0-9]+\.[0-9]+\.[0-9]+)/u) || text.match(/==([0-9]+\.[0-9]+\.[0-9]+)/u))?.[1] || null; }
function base(input) { const p = input.buildDependencyCachePlanningResult || {}; const c = p.hermesBuildDependencyCachePlanCandidate || {}; return { approvalId: `hermes-build-dependency-cache-approval:75b300f:${input.approvedAt}`, approvalKind: 'factory-hermes-build-dependency-cache-approval', approvalVersion: '1.0', approvedAt: input.approvedAt, approvedBy: input.approvedBy, toolId: 'hermes_agent', selectedCandidateId: p.selectedCandidateId || c.selectedCandidateId || '', commandName: p.commandName || c.commandName || '', pythonEntrypoint: p.pythonEntrypoint || c.pythonEntrypoint || '', missingBuildDependency: p.missingBuildDependency || c.missingBuildDependency || '', lockedPackageName: 'setuptools', lockedPackageVersion: lockedVersion(p), buildBackend: p.buildBackend || c.buildBackend || '', setupPyPresent: p.setupPyPresent === true || c.setupPyPresent === true, uvExecutableRef: p.uvExecutableRef || c.uvExecutableRef || '.codex-temp/external-tools/uv/bin/uv.exe', uvCacheRootRef: p.uvCacheRootRef || c.uvCacheRootRef || '.codex-temp/external-tools/uv/cache/', sourceRootRef: p.sourceRootRef || c.sourceRootRef || '.codex-temp/external-tools/hermes-agent/install/75b300f/source', pythonEnvRootRef: p.pythonEnvRootRef || c.pythonEnvRootRef || '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env', selectedMethodCandidate: p.selectedMethodCandidate || c.selectedMethodCandidate || '', checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_cache_plan', canProceedToBuildDependencyCacheRuntime: false, canCacheBuildDependenciesNow: false, canEnableNetworkNow: false, canRetryMaterializationNow: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetworkNow: false, canUseNetworkInFutureRuntime: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: NEXT }; }
function evaluateFactoryHermesBuildDependencyCacheApproval(input) {
  const p = input.buildDependencyCachePlanningResult; const out = base(input); const candidate = p?.hermesBuildDependencyCachePlanCandidate;
  if (!p) return { ...out, blockers: [{ blockerId: 'blocked_missing_cache_plan', message: 'Build dependency cache planning result is required.' }] };
  if (p.status !== 'plan_candidate_created' || p.decision !== 'hermes_build_dependency_cache_plan_candidate_created' || p.canProceedToBuildDependencyCacheApproval !== true || !candidate) return { ...out, decision: 'blocked_cache_plan_not_candidate', blockers: [{ blockerId: 'blocked_cache_plan_not_candidate', message: 'Planning result is not a valid candidate.' }] };
  if (out.selectedMethodCandidate !== 'uv_controlled_build_dependency_cache_prefetch') return { ...out, decision: 'blocked_unsafe_cache_method', blockers: [{ blockerId: 'blocked_unsafe_cache_method', message: 'Unsafe cache method.' }] };
  if (!/setuptools/iu.test(out.missingBuildDependency)) return { ...out, decision: 'blocked_missing_package_identity', blockers: [{ blockerId: 'blocked_missing_package_identity', message: 'Missing setuptools identity.' }] };
  if (candidate.proposedArtifactPolicy?.requireHashCapture !== true || candidate.proposedArtifactPolicy?.requirePackageNameVersionRecord !== true || candidate.proposedArtifactPolicy?.requireDownloadUrlRecord !== true) return { ...out, decision: 'blocked_missing_hash_policy', blockers: [{ blockerId: 'blocked_missing_hash_policy', message: 'Hash policy required.' }] };
  if (!input.humanApprovalRef) return { ...out, status: 'human_review_required', decision: 'blocked_missing_human_approval', blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] };
  if (!input.networkRiskAcceptanceNotes) return { ...out, decision: 'blocked_missing_network_risk_acceptance', blockers: [{ blockerId: 'blocked_missing_network_risk_acceptance', message: 'networkRiskAcceptanceNotes required.' }] };
  if (!input.hashVerificationPolicyNotes) return { ...out, decision: 'blocked_missing_hash_policy', blockers: [{ blockerId: 'blocked_missing_hash_policy', message: 'hashVerificationPolicyNotes required.' }] };
  const decision = 'hermes_build_dependency_cache_approved_for_runtime_candidate';
  const receipt = { receiptId: `${out.approvalId}:receipt`, approvalId: out.approvalId, toolId: 'hermes_agent', approvedBy: input.approvedBy, approvedAt: input.approvedAt, humanApprovalRef: input.humanApprovalRef, missingBuildDependency: out.missingBuildDependency, lockedPackageName: out.lockedPackageName, lockedPackageVersion: out.lockedPackageVersion, selectedMethodCandidate: out.selectedMethodCandidate, networkRiskAcceptanceNotes: input.networkRiskAcceptanceNotes, packageIndexPolicyNotes: input.packageIndexPolicyNotes || '', hashVerificationPolicyNotes: input.hashVerificationPolicyNotes, decision, scope: 'hermes_build_dependency_cache_runtime_candidate_only', approvedNextGate: 'Factory Hermes Build Dependency Cache Runtime Adapter v1', limitations: ['Future runtime candidate only.', 'No cache, network, uv, retry or Hermes execution authorized now.'], notAuthorizedActions: NOT_AUTH };
  const env = { envelopeId: `${out.approvalId}:envelope`, approvalId: out.approvalId, toolId: 'hermes_agent', selectedCandidateId: out.selectedCandidateId, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', missingBuildDependency: out.missingBuildDependency, lockedPackageName: 'setuptools', lockedPackageVersion: out.lockedPackageVersion, versionConstraint: out.missingBuildDependency, buildBackend: 'setuptools.build_meta', setupPyPresent: out.setupPyPresent, uvExecutableRef: out.uvExecutableRef, uvCacheRootRef: out.uvCacheRootRef, sourceRootRef: out.sourceRootRef, pythonEnvRootRef: out.pythonEnvRootRef, metadataRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-metadata/', tempEnvRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-temp-env/', selectedMethodCandidate: 'uv_controlled_build_dependency_cache_prefetch', approvedRuntimeNetworkScope: 'cache_prefetch_only', networkAllowedNow: false, futureRuntimeMayUseNetworkForCachePrefetch: true, futureRuntimeNetworkMustBeDisabledAfterCache: true, futureMaterializationRuntimeMustRemainOffline: true, allowedFutureHostsCandidate: [], approvedRuntimeCommandPolicy: { commandsAllowedNow: [], futureRuntimeAllowedCommandFamilies: ['uv_cache_prefetch_only'], forbiddenCommandFamilies: ['pip', 'python direct', 'setup.py direct', 'hermes', 'uv run', 'uv pip', 'uv venv against real pythonEnv'] }, approvedEnvPolicy: { sanitized: true, noCredentials: true, noEnvRead: true, UV_CACHE_DIR: '.codex-temp/external-tools/uv/cache/', UV_NO_PROGRESS: '1', PYTHONNOUSERSITE: '1', NO_COLOR: '1' }, approvedWriteRoots: [out.uvCacheRootRef, '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-metadata/', '.codex-temp/external-tools/hermes-agent/install/75b300f/build-dependency-cache-temp-env/'], forbiddenWriteRoots: ['project repo', '.env', 'user home', 'system dirs', 'real pythonEnvRoot except read-only unless explicitly approved later'], requiredMetadata: ['package name', 'resolved version', 'constraint', 'source URL or index record', 'hashes', 'cache paths', 'no credentials'], cacheAllowedNow: false, futureRuntimeMayCacheBuildDependencyUnderEnvelope: true, materializationRetryAllowedNow: false, hermesExecutionAllowedNow: false, networkAllowedNowForThisGate: false, credentialsAllowedNow: false, modelCallsAllowedNow: false, canProceedToBuildDependencyCacheRuntime: true, recommendedNextStep: NEXT };
  return { ...out, status: 'approved_for_runtime_candidate', decision, approvalReceipt: receipt, approvedBuildDependencyCacheRuntimeEnvelope: env, canProceedToBuildDependencyCacheRuntime: true, canUseNetworkInFutureRuntime: true };
}
async function executeFactoryHermesBuildDependencyCacheApproval(input = {}) { const paths = resolveFactoryHermesBuildDependencyCacheApprovalPaths(); for (const target of [paths.planningResult, paths.approvalResult]) assertApprovalPathContained(target, paths.installRoot); const runInput = { approvedAt: input.approvedAt || '2026-07-22T01:00:00.000Z', approvedBy: input.approvedBy || 'factory-hermes-build-dependency-cache-approval-smoke', humanApprovalRef: input.humanApprovalRef || 'human-review/hermes-build-dependency-cache-approval-v1', networkRiskAcceptanceNotes: input.networkRiskAcceptanceNotes || 'Approve future network use only inside Build Dependency Cache Runtime Adapter for controlled cache prefetch of setuptools>=77,<83; no credentials, no models, no Hermes, no materialization retry in this gate.', packageIndexPolicyNotes: input.packageIndexPolicyNotes || 'Future runtime must derive allowed hosts from locked package URL/package index policy and reject wildcards.', hashVerificationPolicyNotes: input.hashVerificationPolicyNotes || 'Future runtime must record package version, URL/source record and hashes; cache must be verified before materialization retry.', buildDependencyCachePlanningResult: input.buildDependencyCachePlanningResult || JSON.parse(await fs.readFile(paths.planningResult, 'utf8')) }; const result = evaluateFactoryHermesBuildDependencyCacheApproval(runInput); await fs.writeFile(paths.approvalResult, `${JSON.stringify(result, null, 2)}\n`, 'utf8'); return result; }
module.exports = { evaluateFactoryHermesBuildDependencyCacheApproval, executeFactoryHermesBuildDependencyCacheApproval };
