import type { FactoryMemoryRegistryIndex } from '../memory-registry/index.ts'
export type FactoryMemoryRegistryIntegrityVersion = '1.0'
export type FactoryMemoryRegistryIntegrityKind = 'factory-memory-registry-integrity'
export type FactoryMemoryRegistryIntegrityStatus = 'clean' | 'warning' | 'blocked'
export type FactoryMemoryRegistryIntegrityFindingSeverity = 'info' | 'warning' | 'error' | 'critical'
export type FactoryMemoryRegistryIntegrityFindingKind = 'missing_memory_record_file' | 'missing_memory_metadata_file' | 'fingerprint_mismatch' | 'idempotency_mismatch' | 'metadata_record_mismatch' | 'registry_metadata_mismatch' | 'registry_record_mismatch' | 'project_index_missing' | 'project_index_stale' | 'project_index_record_missing' | 'registry_index_missing' | 'registry_index_stale' | 'unsafe_path' | 'unsafe_flags' | 'duplicate_fingerprint' | 'duplicate_idempotency_key' | 'conflicting_memory_identity' | 'orphan_metadata' | 'orphan_record' | 'invalid_entry' | 'unknown_warning'
export interface FactoryMemoryRegistryIntegrityPolicy { requireStorageRootInsideCodexTemp: true; requireRegistryIndex: false; requireProjectIndexForCleanEntry: true; requireRecordFile: true; requireMetadataFile: true; requireFingerprintMatch: true; requireIdempotencyKeyMatch: true; requireRegistryMetadataConsistency: true; requireProjectIndexConsistency: true; requireFlagsSafe: true; requirePathContainment: true; requireNoDuplicateCriticalConflicts: true; requireNoMissingRecord: true; requireNoMissingMetadata: true; requireNoTamperingSignals: true; forbidEmbeddingsCreation: true; forbidCodexTaskCreation: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; allowMemoryReadOnlyIfClean: true; allowCodexTaskUse: false }
export interface FactoryMemoryRegistryIntegrityInput { storageRoot: string; registryIndex?: FactoryMemoryRegistryIndex; checkedAt: string; checkedBy: string; policy?: Partial<FactoryMemoryRegistryIntegrityPolicy> }
export interface FactoryMemoryRegistryIntegrityFinding { findingId: string; registryEntryId?: string; kind: FactoryMemoryRegistryIntegrityFindingKind; severity: FactoryMemoryRegistryIntegrityFindingSeverity; message: string }
export interface FactoryMemoryRegistryIntegrityEntryResult { registryEntryId: string; memoryRecordId: string; memoryRecordKind: string; memoryRecordVersion: string; namespace: string; projectNamespace: string; logicalTarget: string; metadataLogicalTarget: string; expectedFingerprint: string; recalculatedFingerprint?: string; expectedIdempotencyKey: string; recalculatedIdempotencyKey?: string; recordExists: boolean; metadataExists: boolean; recordMatchesMetadata: boolean; registryMatchesMetadata: boolean; registryMatchesRecord: boolean; fingerprintMatches: boolean; idempotencyMatches: boolean; projectIndexContainsRecord: boolean; flagsSafe: boolean; pathContained: boolean; status: FactoryMemoryRegistryIntegrityStatus; findings: FactoryMemoryRegistryIntegrityFinding[]; canUseForMemoryRead: boolean; canUseForCodexTask: false; canCreateEmbeddings: false; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false }
export interface FactoryMemoryRegistryIntegrityProjectIndexResult { projectNamespace: string; logicalPath: string; exists: boolean; parseable: boolean; flagsSafe: boolean; recordsExpected: number; recordsFound: number; status: FactoryMemoryRegistryIntegrityStatus; findings: FactoryMemoryRegistryIntegrityFinding[] }
export interface FactoryMemoryRegistryIntegrityRegistryIndexResult { logicalPath: string; exists: boolean; parseable: boolean; entriesExpected: number; entriesFound: number; stale: boolean; status: FactoryMemoryRegistryIntegrityStatus; findings: FactoryMemoryRegistryIntegrityFinding[] }
export interface FactoryMemoryRegistryIntegritySummary { totalEntries: number; statusCounts: Record<string, number>; severityCounts: Record<string, number>; criticalFindings: number; cleanEntries: number; blockedEntries: number; canUseForMemoryRead: number; canUseForCodexTask: 0; recommendedNextStep: string }
export interface FactoryMemoryRegistryIntegrityReport { integrityKind: FactoryMemoryRegistryIntegrityKind; integrityVersion: FactoryMemoryRegistryIntegrityVersion; generatedAt: string; checkedBy: string; storageRoot: string; sourceRegistryIndexRef?: string; status: FactoryMemoryRegistryIntegrityStatus; entries: FactoryMemoryRegistryIntegrityEntryResult[]; projectIndexes: FactoryMemoryRegistryIntegrityProjectIndexResult[]; registryIndex: FactoryMemoryRegistryIntegrityRegistryIndexResult; findings: FactoryMemoryRegistryIntegrityFinding[]; blockers: string[]; warnings: string[]; summary: FactoryMemoryRegistryIntegritySummary; canUseForCodexTask: false; canCreateEmbeddings: false; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryRegistryIntegrityValidationResult { ok: boolean; errors: string[]; warnings: string[] }
