import type { FactoryExternalToolProvisioningApprovalResult } from '../external-tool-provisioning-approval/index.ts'

export type FactoryUvProvisioningRuntimeVersion = '1.0'
export type FactoryUvProvisioningRuntimeKind = 'factory-uv-provisioning-runtime'
export type FactoryUvProvisioningRuntimeStatus = 'success' | 'blocked' | 'failed'
export type FactoryUvProvisioningRuntimeDecision = 'uv_found_on_system_path_verified' | 'uv_provisioned_locally_with_checksum_verified' | 'blocked_invalid_tool_provisioning_envelope' | 'blocked_unsupported_platform' | 'blocked_no_supported_artifact' | 'blocked_checksum_unavailable' | 'failed_release_metadata_download' | 'failed_artifact_download' | 'failed_checksum_verification' | 'failed_zip_extraction' | 'failed_uv_version_check' | 'request_uv_provisioning_repair'
export type FactoryUvProvisioningRuntimeCommandKind = 'uv_version_system_path' | 'uv_version_local'

export interface FactoryUvProvisioningRuntimeInput { externalToolProvisioningApprovalResult?: FactoryExternalToolProvisioningApprovalResult; executedAt: string; executedBy: string; targetPlatform?: string; policy?: Partial<FactoryUvProvisioningRuntimePolicy>; dryRun?: boolean }
export interface FactoryUvProvisioningRuntimePolicy { requireApprovedToolProvisioningEnvelope: boolean; requireToolIdUv: boolean; requireInstallRootUnderCodexTemp: boolean; requireOfficialReleaseSource: boolean; requireChecksumVerification: boolean; requireNoShell: boolean; requireNoCredentials: boolean; requireNoProjectPackageMutation: boolean; allowSystemPathExistingUv: boolean; allowLocalUvBinaryUnderCodexTemp: boolean; allowDownloadFromOfficialGitHubRelease: boolean; allowDownloadFromReleasesAstralMirror: boolean; allowUvVersionOnly: boolean; forbidUvVenv: boolean; forbidUvSync: boolean; forbidUvRun: boolean; forbidUvPip: boolean; forbidPipExecution: boolean; forbidPythonExecution: boolean; forbidSetupPyExecution: boolean; forbidHermesExecution: boolean; forbidHermesScripts: boolean; forbidShell: boolean; forbidCmd: boolean; forbidPowerShell: boolean; forbidCurl: boolean; forbidWget: boolean; forbidGlobalInstall: boolean; forbidPathMutation: boolean; forbidPackageFileMutation: boolean; forbidCredentials: boolean; forbidModelCalls: boolean; forbidDeploy: boolean; requireProvisioningManifest: boolean; requireProvisioningResultJson: boolean; requireFutureUvVerificationGate: boolean; requireFutureHermesPythonRuntimeRetry: boolean }
export interface FactoryUvProvisioningRuntimeCommandResult { kind: FactoryUvProvisioningRuntimeCommandKind; commandRef: string; args: string[]; exitCode: number | null; shell: false; stdout: string; stderr: string; timedOut: boolean }
export interface FactoryUvProvisioningRuntimeDownloadResult { releaseTag?: string; artifactName?: string; artifactUrlHost?: string; checksumUrlHost?: string; artifactPathRef?: string; checksumPathRef?: string; artifactSha256?: string; checksumSha256?: string; status: string }
export interface FactoryUvProvisioningRuntimeManifest { manifestKind: 'factory-uv-provisioning-manifest'; manifestVersion: FactoryUvProvisioningRuntimeVersion; toolId: 'uv'; toolName: 'uv'; targetPlatform: string; sourceReleaseProvider: string; releaseTag?: string; artifactName?: string; artifactUrlHost?: string; checksumUrlHost?: string; artifactSha256?: string; checksumSha256?: string; installRootRef: string; executableRef: string; uvVersionOutput?: string; commandSummary: Array<{ kind: string; exitCode: number | null; shell: false }>; installStatus: string; downloadStatus: string; extractionStatus: string; verificationStatus: string; executionStatus: string; shellStatus: 'not_allowed'; pipStatus: 'not_executed'; pythonStatus: 'not_executed'; setupPyStatus: 'not_executed'; hermesExecutionStatus: 'not_allowed'; scriptsStatus: 'not_executed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; projectMutationStatus: 'not_allowed'; installedAt: string; installedBy: string; nextRequiredGate: 'UV Provisioning Verification Gate v1' }
export interface FactoryUvProvisioningRuntimeCheck { checkId: string; ok: boolean; message: string }
export interface FactoryUvProvisioningRuntimeBlocker { blockerId: string; message: string }
export interface FactoryUvProvisioningRuntimeWarning { warningId: string; message: string }
export interface FactoryUvProvisioningRuntimeResult { uvProvisioningRuntimeId: string; uvProvisioningRuntimeKind: FactoryUvProvisioningRuntimeKind; uvProvisioningRuntimeVersion: FactoryUvProvisioningRuntimeVersion; executedAt: string; executedBy: string; toolId: 'uv'; toolName: 'uv'; targetPlatform: string; installRootRef: string; executableRef?: string; resolvedVersion?: string; sourceUrlRef?: string; checksumUrlRef?: string; checksumSha256?: string; artifactSha256?: string; releaseTag?: string; artifactName?: string; downloadStatus: string; extractionStatus: string; verificationStatus: string; installStatus: string; executionStatus: string; shellStatus: 'not_allowed'; pipStatus: 'not_executed'; pythonStatus: 'not_executed'; setupPyStatus: 'not_executed'; hermesExecutionStatus: 'not_allowed'; scriptsStatus: 'not_executed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; projectMutationStatus: 'not_allowed'; deployStatus: 'not_allowed'; commandResults: FactoryUvProvisioningRuntimeCommandResult[]; checks: FactoryUvProvisioningRuntimeCheck[]; blockers: FactoryUvProvisioningRuntimeBlocker[]; warnings: FactoryUvProvisioningRuntimeWarning[]; status: FactoryUvProvisioningRuntimeStatus; decision: FactoryUvProvisioningRuntimeDecision; canExecuteUvForVersionCheck: boolean; canExecuteUvForProjectOps: false; canExecuteHermes: false; canRunHermesScripts: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryUvProvisioningRuntimeValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryUvProvisioningRuntimeSummary { uvProvisioningRuntimeId: string; toolId: 'uv'; targetPlatform: string; releaseTag?: string; installRootRef: string; executableRef?: string; installStatus: string; downloadStatus: string; extractionStatus: string; verificationStatus: string; executionStatus: string; shellStatus: 'not_allowed'; pipStatus: 'not_executed'; pythonStatus: 'not_executed'; setupPyStatus: 'not_executed'; hermesExecutionStatus: 'not_allowed'; canExecuteUvForProjectOps: false; nextStep: string }
