import { FACTORY_UV_PROVISIONING_RUNTIME_KIND, FACTORY_UV_PROVISIONING_RUNTIME_VERSION } from './uv-provisioning-runtime.defaults.ts'
import type { FactoryUvProvisioningRuntimeInput, FactoryUvProvisioningRuntimeResult, FactoryUvProvisioningRuntimeValidationResult } from './uv-provisioning-runtime.types.ts'

const secretKeyPattern = /password|passwd|secret|token|api[_-]?key|credential/iu
const secretValuePattern = /(password|passwd|secret|token|api[_-]?key|credential)\s*[:=]/iu
const forbiddenKinds = ['uv_venv', 'uv_sync', 'uv_run', 'uv_pip', 'pip', 'python', 'setup_py', 'hermes']
function hasSecrets(value: unknown): boolean { if (typeof value === 'string') return secretValuePattern.test(value); if (Array.isArray(value)) return value.some(hasSecrets); if (value && typeof value === 'object') return Object.entries(value).some(([key, child]) => secretKeyPattern.test(key) || hasSecrets(child)); return false }
export function validateFactoryUvProvisioningRuntimeInput(input: FactoryUvProvisioningRuntimeInput): FactoryUvProvisioningRuntimeValidationResult { const errors: string[] = []; const warnings: string[] = []; const approval = input.externalToolProvisioningApprovalResult; if (!approval) errors.push('externalToolProvisioningApprovalResult is required.'); if (!approval?.approvedToolProvisioningEnvelope) errors.push('approvedToolProvisioningEnvelope is required.'); if (approval?.toolId !== 'uv') errors.push('toolId must be uv.'); if (!input.executedAt) errors.push('executedAt is required.'); if (!input.executedBy) errors.push('executedBy is required.'); if (hasSecrets(input.executedBy) || hasSecrets(input.targetPlatform) || hasSecrets(input.policy ?? {})) errors.push('Input appears to contain secret-shaped material.'); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryUvProvisioningRuntimeResult(result: FactoryUvProvisioningRuntimeResult): FactoryUvProvisioningRuntimeValidationResult { const errors: string[] = []; const warnings: string[] = []; if (result.uvProvisioningRuntimeKind !== FACTORY_UV_PROVISIONING_RUNTIME_KIND) errors.push('Invalid kind.'); if (result.uvProvisioningRuntimeVersion !== FACTORY_UV_PROVISIONING_RUNTIME_VERSION) errors.push('Invalid version.'); if (result.toolId !== 'uv') errors.push('toolId must be uv.'); if (!result.installRootRef.startsWith('.codex-temp/external-tools/uv/')) errors.push('installRootRef must be under .codex-temp/external-tools/uv/.'); if (result.status === 'success' && !result.executableRef) errors.push('success requires executableRef.'); if (result.status === 'success' && result.verificationStatus !== 'uv_version_checked') errors.push('success requires uv_version_checked.'); if (result.downloadStatus === 'downloaded' && !result.checksumSha256) errors.push('downloaded result requires checksumSha256.'); if (result.downloadStatus === 'downloaded' && result.artifactSha256 !== result.checksumSha256) errors.push('downloaded artifact checksum mismatch.'); if (result.shellStatus !== 'not_allowed') errors.push('shellStatus must be not_allowed.'); if (result.pipStatus !== 'not_executed') errors.push('pipStatus must be not_executed.'); if (result.pythonStatus !== 'not_executed') errors.push('pythonStatus must be not_executed.'); if (result.setupPyStatus !== 'not_executed') errors.push('setupPyStatus must be not_executed.'); if (result.hermesExecutionStatus !== 'not_allowed') errors.push('hermesExecutionStatus must be not_allowed.'); if (result.scriptsStatus !== 'not_executed') errors.push('scriptsStatus must be not_executed.'); if (result.canExecuteUvForProjectOps !== false || result.canExecuteHermes !== false || result.canRunHermesScripts !== false || result.canUseCredentials !== false || result.canCallModels !== false || result.canMutateProjectFiles !== false || result.canDeploy !== false) errors.push('Dangerous capability flags must remain false.'); if (result.commandResults.some((command) => forbiddenKinds.includes(command.kind))) errors.push('Forbidden command kind present.'); if (result.commandResults.some((command) => command.shell !== false)) errors.push('All command results must have shell false.'); if (!result.recommendedNextStep) errors.push('recommendedNextStep is required.'); return { ok: errors.length === 0, errors, warnings } }
