export type FactoryHermesWrapperNoToolModeImplementationPlanningVersion = '1.0'
export type FactoryHermesWrapperNoToolModeImplementationPlanningKind = 'factory-hermes-wrapper-no-tool-mode-implementation-planning'
export type FactoryHermesWrapperNoToolModeImplementationPlanningStatus = 'wrapper_no_tool_mode_implementation_plan_created' | 'wrapper_no_tool_mode_implementation_plan_blocked'
export type FactoryHermesWrapperNoToolModeImplementationPlanningDecision = 'hermes_wrapper_no_tool_mode_implementation_plan_created_for_approval' | 'hermes_wrapper_no_tool_mode_implementation_plan_blocked_invalid_approval'
export interface FactoryHermesWrapperNoToolModeImplementationPlanningInput { plannedAt: string; plannedBy: string; wrapperNoToolModeApprovalResult?: any; wrapperNoToolModePlanningResult?: any; sourceInspection?: any; policy?: Partial<FactoryHermesWrapperNoToolModeImplementationPlanningPolicy>; planningNotes?: string }
export interface FactoryHermesWrapperNoToolModeImplementationPlanningPolicy { requireWrapperNoToolModeApproval: boolean; requireImplementationPlanningOnly: boolean; requireArchitecturePlan: boolean; requireTempConfigPlan: boolean; requireNoToolEnforcementPlan: boolean; requireValidationPlan: boolean; requireRiskRegister: boolean; requireNoWrapperImplementationInThisGate: boolean; requireNoTempConfigCreationInThisGate: boolean; requireNoSourceMutationInThisGate: boolean; requireNoExecutionInThisGate: boolean; requireNoPromptPassingInThisGate: boolean; requireNoNetworkInThisGate: boolean; requireNoCredentialUseInThisGate: boolean; requireNoModelCallsInThisGate: boolean; requireNoToolsetEnablementInThisGate: boolean; forbidResearchRuntimeAdapterApprovalInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidResearchExecutionInThisGate: boolean; forbidUsingFindingsInThisGate: boolean; forbidDeployInThisGate: boolean }
export interface FactoryHermesWrapperImplementationArchitecturePlan { plannedWrapperName: 'hermes_wrapper_no_tool_mode'; implementationAllowedNow: false; implementationGateRequired: true; sourceMutationAllowed: false; hermesSourceReadOnly: true; wrapperLocationCandidates: string[]; responsibilities: string[]; nonResponsibilities: string[] }
export interface FactoryHermesWrapperTempConfigPlan { tempConfigStrategy: 'wrapper_temp_config_no_toolsets'; tempConfigAllowedNow: false; tempConfigImplementationGateRequired: true; plannedTempConfigRoot: string; plannedTempConfigFile: 'config.yaml'; configMustBeGeneratedUnderCodexTemp: true; configMustNotContainSecrets: true; configMustNotContainCredentialValues: true; configMustNotContainEnvDump: true; configMustNotUseProjectRoot: true; configMustNotModifyHermesSource: true; configMustDisableOrEmptyCliToolsets: true; configMustDisableMcp: true; configMustAvoidHiddenDefaults: true; configMustBeReferencedExplicitlyByWrapper: true; configValidationRequiredBeforeRuntime: true; exactConfigSchemaKnown: boolean | 'unknown'; emptyToolsetsInConfigSupported: boolean | 'unknown'; configPathSelectionMethodKnown: boolean | 'unknown' }
export interface FactoryHermesWrapperNoToolEnforcementPlan { enforcementGoal: string; enforcementAllowedNow: false; futureWrapperMustFailIf: string[]; disallowedTools: string[]; enforcementEvidenceRequired: string[] }
export interface FactoryHermesWrapperValidationPlan { validations: Array<{ validationId: string; objective: string; executionAllowedNow: false; requiresSeparateApproval?: true }> }
export interface FactoryHermesWrapperImplementationRiskRegister { risks: Array<{ riskId: string; severity: 'low' | 'medium' | 'high'; mitigation: string; blocksImplementationApproval: boolean; blocksRuntimeAdapter: boolean }> }
export interface FactoryHermesWrapperNoToolModeImplementationPlanningReceipt { receiptId: string; planningId: string; toolId: 'hermes_agent'; plannedBy: string; plannedAt: string; decision: FactoryHermesWrapperNoToolModeImplementationPlanningDecision; scope: 'hermes_wrapper_no_tool_mode_implementation_planning_only'; approvedNextGate: 'Factory Hermes Wrapper No-Tool Mode Implementation Approval Gate v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesWrapperNoToolModeImplementationPlanCandidate { planCandidateId: string; toolId: 'hermes_agent'; selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets'; wrapperImplementationArchitecturePlan: FactoryHermesWrapperImplementationArchitecturePlan; wrapperTempConfigPlan: FactoryHermesWrapperTempConfigPlan; wrapperNoToolEnforcementPlan: FactoryHermesWrapperNoToolEnforcementPlan; wrapperValidationPlan: FactoryHermesWrapperValidationPlan; wrapperImplementationRiskRegister: FactoryHermesWrapperImplementationRiskRegister; wrapperImplementationAllowedNow: false; wrapperExecutionAllowedNow: false; tempConfigCreationAllowedNow: false; sourceMutationAllowedNow: false; researchRuntimeAdapterAllowedNow: false; researchExecutionAllowedNow: false; futureImplementationRequiresApproval: true; futureVerificationRequiresApproval: true; canProceedToHermesWrapperNoToolModeImplementationApproval: boolean; canProceedToHermesWrapperNoToolModeImplementation: false; canProceedToResearchRuntimeAdapterApprovalRetry: false; canRunResearchNow: false }
export interface FactoryHermesWrapperNoToolModeImplementationPlanningResult { planningId: string; planningKind: FactoryHermesWrapperNoToolModeImplementationPlanningKind; planningVersion: FactoryHermesWrapperNoToolModeImplementationPlanningVersion; plannedAt: string; plannedBy: string; toolId: 'hermes_agent'; wrapperApprovalRef?: string; wrapperPlanningRef?: string; selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets'; wrapperImplementationArchitecturePlan: FactoryHermesWrapperImplementationArchitecturePlan; wrapperTempConfigPlan: FactoryHermesWrapperTempConfigPlan; wrapperNoToolEnforcementPlan: FactoryHermesWrapperNoToolEnforcementPlan; wrapperValidationPlan: FactoryHermesWrapperValidationPlan; wrapperImplementationRiskRegister: FactoryHermesWrapperImplementationRiskRegister; wrapperNoToolModeImplementationPlanningReceipt: FactoryHermesWrapperNoToolModeImplementationPlanningReceipt; hermesWrapperNoToolModeImplementationPlanCandidate: FactoryHermesWrapperNoToolModeImplementationPlanCandidate; checks: any[]; blockers: any[]; warnings: any[]; status: FactoryHermesWrapperNoToolModeImplementationPlanningStatus; decision: FactoryHermesWrapperNoToolModeImplementationPlanningDecision; implementationPlanningStatus: 'plan_candidate_created' | 'blocked'; canProceedToHermesWrapperNoToolModeImplementationApproval: boolean; canProceedToHermesWrapperNoToolModeImplementation: false; canProceedToResearchRuntimeAdapterApprovalRetry: false; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false; canExecuteHermesNow: false; canPassPromptNow: false; canUseNetworkNow: false; canUseCredentialsNow: false; canReadEnvSecretsNow: false; canCallModelsNow: false; canEnableToolsetsNow: false; canMutateFilesystemNow: false; canUseFindings: false; recommendedNextStep: string }
export interface FactoryHermesWrapperNoToolModeImplementationPlanningValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesWrapperNoToolModeImplementationPlanningSummary { planningId: string; status: FactoryHermesWrapperNoToolModeImplementationPlanningStatus; decision: FactoryHermesWrapperNoToolModeImplementationPlanningDecision; selectedWrapperStrategy: string; riskCount: number; canProceedToHermesWrapperNoToolModeImplementationApproval: boolean; canRunResearchNow: false; canExecuteHermesNow: false; nextStep: string }
