import type { FactoryHermesRuntimeSelectionRevisionPlanningKind, FactoryHermesRuntimeSelectionRevisionPlanningPolicy, FactoryHermesRuntimeSelectionRevisionPlanningVersion } from './hermes-runtime-selection-revision-planning.types.ts'

export const FACTORY_HERMES_RUNTIME_SELECTION_REVISION_PLANNING_KIND: FactoryHermesRuntimeSelectionRevisionPlanningKind = 'factory-hermes-runtime-selection-revision-planning'
export const FACTORY_HERMES_RUNTIME_SELECTION_REVISION_PLANNING_VERSION: FactoryHermesRuntimeSelectionRevisionPlanningVersion = '1.0'
export const RUNTIME_SELECTION_REVISION_PLANNING_NEXT_STEP = 'Proceed to Factory Hermes Wrapper No-Tool Mode Planning Gate v1 or Runtime Selection Revision Decision Gate v1; no Hermes execution is authorized.'
export const RUNTIME_SELECTION_REVISION_NOT_AUTHORIZED_ACTIONS = ['approve_research_runtime_adapter_now', 'execute_hermes_now', 'execute_oneshot_now', 'pass_prompt_now', 'run_research_now', 'call_models_now', 'use_network_now', 'access_credentials_now', 'read_env_secrets_now', 'enable_toolsets_now', 'mutate_filesystem_now', 'create_runtime_run_root_now', 'ingest_real_output_now', 'promote_findings_now', 'execute_uv_now', 'execute_python_now', 'execute_pip_now', 'execute_setup_py_now', 'deploy_now']
export const DEFAULT_FACTORY_HERMES_RUNTIME_SELECTION_REVISION_PLANNING_POLICY: FactoryHermesRuntimeSelectionRevisionPlanningPolicy = {
  requireToolsetDisableApprovalBlocked: true, requireAdapterApprovalBlocked: true, requireBlockedRuntimeSelectionSummary: true, requireRevisionOptions: true, requireDecisionPack: true, requireWrapperPlanningRecommendation: true, requireNoExecutionInThisGate: true, requireNoPromptPassingInThisGate: true, requireNoNetworkInThisGate: true, requireNoCredentialUseInThisGate: true, requireNoModelCallsInThisGate: true, requireNoToolsetEnablementInThisGate: true, forbidResearchRuntimeAdapterApprovalInThisGate: true, forbidHermesExecutionInThisGate: true, forbidResearchExecutionInThisGate: true, forbidUsingFindingsInThisGate: true, forbidDeployInThisGate: true,
}
