export type FactoryHermesRuntimeSelectionRevisionPlanningVersion = '1.0'
export type FactoryHermesRuntimeSelectionRevisionPlanningKind = 'factory-hermes-runtime-selection-revision-planning'
export type FactoryHermesRuntimeSelectionRevisionPlanningStatus = 'runtime_selection_revision_plan_created' | 'blocked'
export type FactoryHermesRuntimeSelectionRevisionPlanningDecision = 'hermes_runtime_selection_revision_plan_created_toolset_mode_blocked' | 'blocked_invalid_toolset_disable_verification_approval' | 'blocked_invalid_research_runtime_adapter_approval' | 'blocked_invalid_previous_runtime_selection'
export type FactoryHermesRuntimeSelectionRevisionStatus = 'manual_revision_required' | 'blocked'

export interface FactoryHermesRuntimeSelectionRevisionPlanningInput { plannedAt: string; plannedBy: string; toolsetDisableVerificationApprovalResult?: any; toolsetDisableVerificationPlanningResult?: any; researchRuntimeAdapterApprovalResult?: any; runtimeSelectionDecisionResult?: any; runtimeSelectionPlanningResult?: any; toolsetsPolicyPlanningResult?: any; finalExecutionApprovalResult?: any; policy?: Partial<FactoryHermesRuntimeSelectionRevisionPlanningPolicy>; planningNotes?: string }
export interface FactoryHermesRuntimeSelectionRevisionPlanningPolicy { requireToolsetDisableApprovalBlocked: boolean; requireAdapterApprovalBlocked: boolean; requireBlockedRuntimeSelectionSummary: boolean; requireRevisionOptions: boolean; requireDecisionPack: boolean; requireWrapperPlanningRecommendation: boolean; requireNoExecutionInThisGate: boolean; requireNoPromptPassingInThisGate: boolean; requireNoNetworkInThisGate: boolean; requireNoCredentialUseInThisGate: boolean; requireNoModelCallsInThisGate: boolean; requireNoToolsetEnablementInThisGate: boolean; forbidResearchRuntimeAdapterApprovalInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidResearchExecutionInThisGate: boolean; forbidUsingFindingsInThisGate: boolean; forbidDeployInThisGate: boolean }
export interface FactoryHermesBlockedRuntimeSelectionSummary { previousProvider: 'openai'; previousModel: 'gpt-4o-mini'; previousCredentialRef: 'OPENAI_API_KEY'; previousHost: 'api.openai.com'; previousToolsetMode: 'no_toolsets_text_only'; previousRunRoot: string; blockedReason: 'toolset_mode_not_supported'; noToolModeProven: false; noSafeProbeShape: true; adapterApprovalBlocked: true; runtimeAdapterApproved: false; researchExecutionAllowed: false }
export interface FactoryHermesRuntimeSelectionRevisionOption { optionId: string; status: string; description: string; risk: 'low' | 'medium' | 'high' | 'unacceptable' | 'invalid_selection' | 'unsafe_without_proven_command_shape'; enablesRuntimeAdapter: boolean | 'not_now'; recommendedIfNoWrapper?: boolean; nextGate?: string; reason?: string }
export interface FactoryHermesRuntimeSelectionRevisionDecisionPack { packId: string; pendingDecisions: Array<{ decisionId: string; label: string; status: 'pending_human_decision'; risk: string; impact: string; recommended: boolean; blockedUntilChosen: boolean }> }
export interface FactoryHermesRuntimeSelectionRevisionRecommendation { pathId: 'plan_wrapper_enforced_no_tool_mode'; reason: string; nextGate: 'Factory Hermes Wrapper No-Tool Mode Planning Gate v1'; executionAllowedNow: false }
export interface FactoryHermesRuntimeSelectionRevisionPlanCandidate { planCandidateId: string; toolId: 'hermes_agent'; blockedRuntimeSelectionSummary: FactoryHermesBlockedRuntimeSelectionSummary; revisionOptions: FactoryHermesRuntimeSelectionRevisionOption[]; runtimeSelectionRevisionDecisionPack: FactoryHermesRuntimeSelectionRevisionDecisionPack; recommendedRevisionPath: FactoryHermesRuntimeSelectionRevisionRecommendation; currentRuntimeSelectionInvalidForAdapter: true; selectedToolsetModeInvalidForAdapter: true; directHermesRuntimeAdapterBlocked: true; wrapperPlanningRecommended: true; executionAllowedNow: false; runtimeAdapterAllowedNow: false; researchExecutionAllowedNow: false; canProceedToHermesWrapperNoToolModePlanning: true; canProceedToRuntimeSelectionRevisionDecision: true; canProceedToResearchRuntimeAdapterApprovalRetry: false; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false }
export interface FactoryHermesRuntimeSelectionRevisionPlanningReceipt { receiptId: string; planningId: string; toolId: 'hermes_agent'; plannedBy: string; plannedAt: string; decision: FactoryHermesRuntimeSelectionRevisionPlanningDecision; scope: 'hermes_runtime_selection_revision_planning_only'; approvedNextGate: 'Factory Hermes Wrapper No-Tool Mode Planning Gate v1'; alternateNextGate: 'Factory Hermes Runtime Selection Revision Decision Gate v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesRuntimeSelectionRevisionPlanningCheck { checkId: string; message: string }
export interface FactoryHermesRuntimeSelectionRevisionPlanningBlocker { blockerId: string; message: string }
export interface FactoryHermesRuntimeSelectionRevisionPlanningWarning { warningId: string; message: string }

export interface FactoryHermesRuntimeSelectionRevisionPlanningResult {
  planningId: string; planningKind: FactoryHermesRuntimeSelectionRevisionPlanningKind; planningVersion: FactoryHermesRuntimeSelectionRevisionPlanningVersion; plannedAt: string; plannedBy: string; toolId: 'hermes_agent'; blockedAdapterApprovalRef?: string; blockedToolsetApprovalRef?: string; previousRuntimeSelectionRef?: string; blockedRuntimeSelectionSummary: FactoryHermesBlockedRuntimeSelectionSummary; revisionOptions: FactoryHermesRuntimeSelectionRevisionOption[]; runtimeSelectionRevisionDecisionPack: FactoryHermesRuntimeSelectionRevisionDecisionPack; recommendedRevisionPath: FactoryHermesRuntimeSelectionRevisionRecommendation; runtimeSelectionRevisionPlanningReceipt: FactoryHermesRuntimeSelectionRevisionPlanningReceipt; hermesRuntimeSelectionRevisionPlanCandidate: FactoryHermesRuntimeSelectionRevisionPlanCandidate; checks: FactoryHermesRuntimeSelectionRevisionPlanningCheck[]; blockers: FactoryHermesRuntimeSelectionRevisionPlanningBlocker[]; warnings: FactoryHermesRuntimeSelectionRevisionPlanningWarning[]; status: FactoryHermesRuntimeSelectionRevisionPlanningStatus; decision: FactoryHermesRuntimeSelectionRevisionPlanningDecision; revisionStatus: FactoryHermesRuntimeSelectionRevisionStatus; canProceedToHermesWrapperNoToolModePlanning: boolean; canProceedToRuntimeSelectionRevisionDecision: boolean; canProceedToResearchRuntimeAdapterApprovalRetry: false; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false; canExecuteHermesNow: false; canPassPromptNow: false; canUseNetworkNow: false; canUseCredentialsNow: false; canReadEnvSecretsNow: false; canCallModelsNow: false; canEnableToolsetsNow: false; canMutateFilesystemNow: false; canUseFindings: false; recommendedNextStep: string
}
export interface FactoryHermesRuntimeSelectionRevisionPlanningValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesRuntimeSelectionRevisionPlanningSummary { planningId: string; status: FactoryHermesRuntimeSelectionRevisionPlanningStatus; decision: FactoryHermesRuntimeSelectionRevisionPlanningDecision; revisionStatus: FactoryHermesRuntimeSelectionRevisionStatus; recommendedRevisionPath: string; canProceedToHermesWrapperNoToolModePlanning: boolean; canProceedToRuntimeSelectionRevisionDecision: boolean; canProceedToResearchRuntimeAdapterApprovalRetry: false; canRunResearchNow: false; nextStep: string }
