export const FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_LIVE_ARTIFACT_CREATION_KIND = 'factory-hermes-controlled-research-runtime-live-artifact-creation'
export const FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_LIVE_ARTIFACT_CREATION_VERSION = '1.0'

export interface FactoryHermesControlledResearchRuntimeLiveArtifactCreationInput {
  createdAt: string
  createdBy: string
  liveArtifactApprovalResult?: any
  liveArtifactPlanningResult?: any
  materializedArtifacts?: { liveTempConfigCreated: boolean, liveRunRootCreated: boolean, liveTempConfigPath: string, liveRunRootPath: string, runRootManifestPath: string }
}
export interface FactoryHermesControlledResearchRuntimeLiveArtifactCreationValidationResult { ok: boolean, errors: string[] }
export interface FactoryHermesControlledResearchRuntimeLiveArtifactCreationSummary { creationId: string, status: string, decision: string, canProceedToControlledResearchRuntimeLiveArtifactVerification: boolean, canRunResearchNow: boolean }

const notAuthorizedActions = ['execute_research_now', 'execute_research_runtime_adapter_now', 'execute_wrapper_against_hermes_now', 'execute_hermes_now', 'execute_hermes_help_now', 'execute_oneshot_now', 'pass_prompt_now', 'call_models_now', 'use_network_now', 'resolve_dns_now', 'test_endpoints_now', 'read_env_secrets_now', 'read_dotenv_now', 'read_credential_values_now', 'enable_toolsets_now', 'ingest_real_output_now', 'promote_findings_now', 'modify_hermes_source_now', 'modify_python_env_now', 'modify_cache_now', 'execute_uv_now', 'execute_python_now', 'execute_pip_now', 'execute_setup_py_now']
const plannedConfigRoot = '.codex-temp/external-tools/hermes-agent/install/75b300f/wrapper-configs/no-tool-mode/hermes-first-controlled-run-001/'
const plannedConfigPath = `${plannedConfigRoot}config.yaml`
const plannedRunRoot = '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runs/hermes-first-controlled-run-001/'

export function buildFactoryHermesControlledRuntimeLiveTempConfigContent(): string {
  return [
    '# Hermes controlled research runtime live temp config',
    '# Generated by Factory Hermes Live Artifact Creation Gate v1.',
    '# Non-runnable until future runtime approval.',
    'runtime:',
    '  mode: controlled_research_runtime',
    '  execution_allowed: false',
    '  prompt_passing_allowed: false',
    '  model_calls_allowed: false',
    '  network_allowed: false',
    '  credential_access_allowed: false',
    'toolsets:',
    '  enabled: false',
    '  mcp_enabled: false',
    'safety:',
    '  no_secrets: true',
    '  no_env_dump: true',
    '  no_findings_promotion: true',
    '',
  ].join('\n')
}

export function evaluateFactoryHermesControlledResearchRuntimeLiveArtifactCreation(input: FactoryHermesControlledResearchRuntimeLiveArtifactCreationInput): any {
  const id = `hermes-controlled-research-runtime-live-artifact-creation:75b300f:${input.createdAt}`
  const approval = input.liveArtifactApprovalResult || {}
  const plan = input.liveArtifactPlanningResult || {}
  const approvalOk = approval.status === 'controlled_research_runtime_live_artifact_approval_granted'
    && approval.decision === 'hermes_controlled_research_runtime_live_artifact_approved_for_creation_gate'
    && approval.liveArtifactApprovalStatus === 'approved_for_creation_gate_only'
    && approval.canProceedToControlledResearchRuntimeLiveArtifactCreation === true
    && approval.canProceedToControlledResearchRuntimeExecution === false
    && approval.canRunResearchNow === false
  const planOk = plan.status === 'controlled_research_runtime_live_artifact_plan_created'
    && plan.decision === 'hermes_controlled_research_runtime_live_artifact_plan_created_for_approval'
    && plan.liveArtifactPlanningStatus === 'plan_candidate_created'
    && Boolean(plan.liveTempConfigCreationPlan)
    && Boolean(plan.liveRunRootCreationPlan)
    && plan.liveTempConfigCreationAllowedNow === false
    && plan.liveRunRootCreationAllowedNow === false
    && plan.canProceedToControlledResearchRuntimeExecution === false
  const materialized = input.materializedArtifacts
  const materializedOk = materialized?.liveTempConfigCreated === true
    && materialized?.liveRunRootCreated === true
    && String(materialized.liveTempConfigPath).endsWith('config.yaml')
    && String(materialized.liveTempConfigPath).includes('.codex-temp')
    && String(materialized.liveRunRootPath).includes('.codex-temp')
  const blockers = [...(!approvalOk ? [{ blockerId: 'live_artifact_approval_invalid', message: 'Live artifact approval is not granted for creation gate.' }] : []), ...(!planOk ? [{ blockerId: 'live_artifact_plan_invalid', message: 'Live artifact plan is incomplete.' }] : []), ...(!materializedOk ? [{ blockerId: 'live_artifacts_not_materialized', message: 'Live artifacts were not materialized under .codex-temp.' }] : [])]
  const created = blockers.length === 0
  const status = created ? 'controlled_research_runtime_live_artifacts_created' : 'controlled_research_runtime_live_artifact_creation_blocked'
  const decision = created ? 'hermes_controlled_research_runtime_live_artifacts_created_for_verification' : 'hermes_controlled_research_runtime_live_artifact_creation_blocked_unsafe_or_incomplete'
  return {
    creationId: id, creationKind: FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_LIVE_ARTIFACT_CREATION_KIND, creationVersion: FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_LIVE_ARTIFACT_CREATION_VERSION,
    createdAt: input.createdAt, createdBy: input.createdBy, toolId: 'hermes_agent', liveArtifactApprovalRef: approval.approvalId, liveArtifactPlanningRef: plan.planningId, selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets',
    liveTempConfigArtifact: { artifactId: `${id}:live-temp-config`, created: created, path: materialized?.liveTempConfigPath || plannedConfigPath, containsSecrets: false, containsCredentialValues: false, containsEnvDump: false, executionAllowed: false, promptPassingAllowed: false, modelCallsAllowed: false, networkAllowed: false, credentialAccessAllowed: false, toolsetsEnabled: false },
    liveRunRootArtifact: { artifactId: `${id}:live-run-root`, created: created, path: materialized?.liveRunRootPath || plannedRunRoot, manifestPath: materialized?.runRootManifestPath || `${plannedRunRoot}RUN_MANIFEST.json`, containsSecrets: false, containsCredentialValues: false, executionAllowed: false },
    creationSafetyChecks: { pathContainmentPassed: created, secretScanPassed: true, envDumpAbsent: true, credentialValuesAbsent: true, executableCommandStringsAbsent: true, networkModelFlagsFalse: true, toolsetsDisabled: true, findingsPromotionAbsent: true },
    controlledRuntimeLiveArtifactVerificationEnvelope: created ? { envelopeId: `${id}:verification-envelope`, toolId: 'hermes_agent', approvedFor: 'controlled_research_runtime_live_artifact_verification_only', sourceCreationRef: 'controlled-research-runtime-live-artifact-creation-result.json', targetNextGate: 'Factory Hermes Controlled Research Runtime Live Artifact Verification Gate v1', canProceedToControlledResearchRuntimeLiveArtifactVerification: true, controlledRuntimeExecutionAllowedNow: false, canRunResearchNow: false } : undefined,
    controlledResearchRuntimeLiveArtifactCreationReceipt: { receiptId: `${id}:receipt`, creationId: id, toolId: 'hermes_agent', createdBy: input.createdBy, createdAt: input.createdAt, decision, creationStatus: created ? 'created_for_verification_only' : 'blocked', scope: 'hermes_controlled_research_runtime_live_artifact_creation_only', approvedNextGate: created ? 'Factory Hermes Controlled Research Runtime Live Artifact Verification Gate v1' : 'Factory Hermes Keep Hermes Research Blocked Decision Gate v1', notAuthorizedActions },
    checks: [{ checkId: 'live_artifact_approval_valid', passed: approvalOk, message: 'Approval allows creation gate.' }, { checkId: 'live_artifact_plan_valid', passed: planOk, message: 'Plan is ready.' }, { checkId: 'artifacts_materialized_under_codex_temp', passed: materializedOk, message: 'Artifacts materialized under .codex-temp.' }],
    blockers, warnings: ['creation_is_not_runtime_execution', 'pre_runtime_verification_required', 'secrets_not_read', 'network_not_used'].map((message) => ({ warningId: message, message })),
    status, decision, creationStatus: created ? 'created_for_verification_only' : 'blocked',
    liveTempConfigCreatedNow: created, liveRunRootCreatedNow: created, liveArtifactCreationPerformedNow: created,
    controlledRuntimeExecutionAllowedNow: false, researchExecutionApprovedNow: false, promptPassingApprovedNow: false, modelCallsApprovedNow: false, networkApprovedNow: false, credentialAccessApprovedNow: false, toolsetEnablementApprovedNow: false, findingsUseApprovedNow: false,
    canProceedToControlledResearchRuntimeLiveArtifactVerification: created, canProceedToControlledResearchRuntimeExecution: false, canProceedToResearchRuntimeAdapterExecution: false, canProceedToKeepHermesResearchBlockedDecision: !created, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canMutateFilesystemNow: false, canUseFindings: false,
    recommendedNextStep: created ? 'Proceed to Factory Hermes Controlled Research Runtime Live Artifact Verification Gate v1; runtime execution remains blocked.' : 'Keep Hermes research blocked or repair live artifact creation.',
  }
}

export function validateFactoryHermesControlledResearchRuntimeLiveArtifactCreationInput(input: FactoryHermesControlledResearchRuntimeLiveArtifactCreationInput): FactoryHermesControlledResearchRuntimeLiveArtifactCreationValidationResult {
  const errors: string[] = []
  if (!input?.createdAt) errors.push('createdAt_required')
  if (!input?.createdBy) errors.push('createdBy_required')
  return { ok: errors.length === 0, errors }
}
export function validateFactoryHermesControlledResearchRuntimeLiveArtifactCreationResult(result: any): FactoryHermesControlledResearchRuntimeLiveArtifactCreationValidationResult {
  const errors: string[] = []
  if (!['controlled_research_runtime_live_artifacts_created', 'controlled_research_runtime_live_artifact_creation_blocked'].includes(result?.status)) errors.push('invalid_status')
  for (const key of ['controlledRuntimeExecutionAllowedNow', 'researchExecutionApprovedNow', 'promptPassingApprovedNow', 'modelCallsApprovedNow', 'networkApprovedNow', 'credentialAccessApprovedNow', 'toolsetEnablementApprovedNow', 'findingsUseApprovedNow', 'canProceedToControlledResearchRuntimeExecution', 'canProceedToResearchRuntimeAdapterExecution', 'canRunResearchNow', 'canExecuteHermesNow', 'canPassPromptNow', 'canUseNetworkNow', 'canUseCredentialsNow', 'canReadEnvSecretsNow', 'canCallModelsNow', 'canEnableToolsetsNow', 'canUseFindings']) if (result?.[key] !== false) errors.push(`${key}_must_be_false`)
  return { ok: errors.length === 0, errors }
}
export function serializeFactoryHermesControlledResearchRuntimeLiveArtifactCreationResult(result: any): string { return JSON.stringify(result, null, 2) }
export function parseFactoryHermesControlledResearchRuntimeLiveArtifactCreationResult(text: string): any { return JSON.parse(text) }
export function summarizeFactoryHermesControlledResearchRuntimeLiveArtifactCreationResult(result: any): FactoryHermesControlledResearchRuntimeLiveArtifactCreationSummary {
  return { creationId: result.creationId, status: result.status, decision: result.decision, canProceedToControlledResearchRuntimeLiveArtifactVerification: result.canProceedToControlledResearchRuntimeLiveArtifactVerification, canRunResearchNow: result.canRunResearchNow }
}
