const fs = require('node:fs/promises');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { assertWrapperNoToolModeVerificationPlanningPathContained, resolveFactoryHermesWrapperNoToolModeVerificationPlanningPaths } = require('./hermes-wrapper-no-tool-mode-verification-planning.path.cjs');
async function readJson(file) { const text = await fs.readFile(file, 'utf8'); if (!text.trim()) throw new Error(`json_file_empty: ${file}`); return JSON.parse(text); }
async function listFiles(dir) { const entries = await fs.readdir(dir, { withFileTypes: true }); const out = []; for (const entry of entries) { const full = path.join(dir, entry.name); if (entry.isDirectory()) out.push(...await listFiles(full)); else out.push(full); } return out; }
async function inspectWrapperCode(paths) { const targetFiles = []; for (const root of paths.wrapperCodeRoots) targetFiles.push(...await listFiles(root)); return { targetFiles: targetFiles.map((file) => path.relative(paths.repoRoot, file).replaceAll(path.sep, '/')), inspectionMode: 'read_only_text_inventory', verificationExecuted: false }; }
async function executeFactoryHermesWrapperNoToolModeVerificationPlanning(input = {}) { const paths = resolveFactoryHermesWrapperNoToolModeVerificationPlanningPaths(); for (const [key, value] of Object.entries(paths)) { if (key === 'repoRoot' || key === 'installRoot' || key === 'wrapperCodeRoots') continue; assertWrapperNoToolModeVerificationPlanningPathContained(value, paths.installRoot); } const moduleUrl = pathToFileURL(path.join(paths.repoRoot, 'src', 'factory', 'hermes-wrapper-no-tool-mode-verification-planning', 'index.ts')).href; const mod = await import(moduleUrl); const result = mod.evaluateFactoryHermesWrapperNoToolModeVerificationPlanning({ plannedAt: input.plannedAt || '2026-07-23T06:00:00.000Z', plannedBy: input.plannedBy || 'factory-hermes-wrapper-no-tool-mode-verification-planning-smoke', implementationResult: input.implementationResult || await readJson(paths.implementationResult), implementationApprovalResult: input.implementationApprovalResult || await readJson(paths.implementationApprovalResult), implementationPlanningResult: input.implementationPlanningResult || await readJson(paths.implementationPlanningResult), wrapperApprovalResult: input.wrapperApprovalResult || await readJson(paths.wrapperApprovalResult), wrapperPlanningResult: input.wrapperPlanningResult || await readJson(paths.wrapperPlanningResult), adapterApprovalResult: input.adapterApprovalResult || await readJson(paths.adapterApprovalResult), codeInspection: input.codeInspection || await inspectWrapperCode(paths) }); await fs.mkdir(path.dirname(paths.verificationPlanningResult), { recursive: true }); await fs.writeFile(paths.verificationPlanningResult, mod.serializeFactoryHermesWrapperNoToolModeVerificationPlanningResult(result)); return result; }
module.exports = { executeFactoryHermesWrapperNoToolModeVerificationPlanning };
