import type { FactoryExternalToolProvisioningToolProfile } from '../external-tool-provisioning.types.ts'

export const UV_TOOL_PROFILE_V1: FactoryExternalToolProvisioningToolProfile = {
  toolId: 'uv',
  toolName: 'uv',
  toolCategory: 'python_package_manager_runtime',
  purpose: 'Provide isolated Python environment provisioning for governed external tools, starting with Hermes.',
  requiredFor: ['Hermes Python Install Runtime Adapter v1'],
  versionRequirement: '>=0.4.0',
  officialSources: ['Astral uv official releases', 'Astral uv documentation'],
  allowedFutureCommands: ['uv --version', 'uv venv <envRoot>', 'uv sync --locked --no-install-project --no-dev --project <sourceRoot>'],
  forbiddenCommands: ['uv run', 'uv pip install', 'uv tool', 'pip', 'python -m pip', 'setup.py', 'shell/cmd/PowerShell', 'curl/wget/irm/iwr', 'any Hermes script'],
  allowedInstallRoots: ['.codex-temp/external-tools/uv/', '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/'],
  provisioningMethods: [
    {
      methodId: 'system_path_existing_uv',
      description: 'Use only if uv already exists on PATH and passes a future verification gate. No install in this gate.',
      requiresShell: false,
      requiresCredentials: false,
      downloadsBinary: false,
      officialSourceDeclared: true,
      checksumStrategyDeclared: true,
      executableRef: 'PATH:uv',
      requiresFutureVerificationGate: true,
    },
    {
      methodId: 'local_uv_binary_under_codex_temp',
      description: 'Future local uv binary provisioned under .codex-temp/external-tools/uv/ after explicit approval, official source and checksum verification.',
      requiresShell: false,
      requiresCredentials: false,
      downloadsBinary: true,
      officialSourceDeclared: true,
      checksumStrategyDeclared: true,
      installRootRef: '.codex-temp/external-tools/uv/',
      executableRef: '.codex-temp/external-tools/uv/uv',
      requiresFutureVerificationGate: true,
    },
    {
      methodId: 'blocked_no_uv_available',
      description: 'Known current blocked state from Hermes Python Install Runtime Adapter v1.',
      requiresShell: false,
      requiresCredentials: false,
      downloadsBinary: false,
      officialSourceDeclared: true,
      checksumStrategyDeclared: true,
      requiresFutureVerificationGate: true,
    },
  ],
  preferredMethod: 'system_path_existing_uv',
  fallbackMethod: 'local_uv_binary_under_codex_temp',
  currentKnownStatus: {
    status: 'missing_from_path_based_on_previous_runtime',
    source: 'Factory Hermes Python Install Runtime Adapter v1 result',
    decision: 'blocked_uv_executable_not_found',
  },
}
