import { FACTORY_EXTERNAL_TOOL_GOVERNANCE_KIND, FACTORY_EXTERNAL_TOOL_GOVERNANCE_VERSION } from './external-tool-governance.defaults.ts'
import type { FactoryExternalToolProfile, FactoryExternalToolRegistry, FactoryExternalToolValidationResult } from './external-tool-governance.types.ts'

const categories = ['market_research', 'web_research', 'coding_agent', 'unit_testing', 'api_mocking', 'e2e_testing', 'security_scanning', 'dependency_scanning', 'accessibility', 'performance', 'prompt_eval', 'ci_cd', 'dependency_maintenance', 'observability', 'analytics', 'monetization']
const lifecycles = ['planned', 'profiled', 'source_checkout_planned', 'source_checked_out', 'source_checkout_failed', 'install_planned', 'installed', 'runtime_boundary_planned', 'runtime_ready', 'adapter_planned', 'adapter_ready', 'disabled', 'blocked']
const modes = ['profile_only', 'source_checkout_audit', 'local_cli', 'dev_dependency', 'ci_workflow', 'runtime_adapter', 'external_platform', 'manual_review_only']
export function validateFactoryExternalToolProfile(profile: FactoryExternalToolProfile): FactoryExternalToolValidationResult { const errors: string[] = []; const warnings: string[] = []; if (!profile?.toolId) errors.push('toolId is required.'); if (!categories.includes(profile?.category)) errors.push(`Invalid category for ${profile?.toolId}.`); if (!lifecycles.includes(profile?.lifecycleStatus)) errors.push(`Invalid lifecycle for ${profile?.toolId}.`); if (!modes.includes(profile?.integrationMode)) errors.push(`Invalid integration mode for ${profile?.toolId}.`); if (profile.executionAllowedNow) errors.push(`${profile.toolId} executionAllowedNow must be false.`); if (profile.credentialsAllowedNow) errors.push(`${profile.toolId} credentialsAllowedNow must be false.`); if (profile.installAllowedNow && !profile.integrationPlan) errors.push(`${profile.toolId} installAllowedNow requires an integration plan.`); if (profile.lifecycleStatus === 'runtime_ready' && !profile.runtimeBoundary) errors.push(`${profile.toolId} runtime_ready requires runtimeBoundary.`); if (profile.lifecycleStatus === 'adapter_ready' && !profile.adapterRef) errors.push(`${profile.toolId} adapter_ready requires adapterRef.`); if (profile.toolId === 'hermes-agent' && (profile.executionAllowedNow || profile.installAllowedNow)) errors.push('Hermes cannot be executable or installable in this block.'); if (profile.toolId === 'codex' && profile.executionAllowedNow) errors.push('Codex execution must remain false.'); if (['playwright', 'vitest', 'msw'].includes(profile.toolId) && profile.lifecycleStatus === 'installed') errors.push(`${profile.toolId} must not be marked installed by this block.`); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryExternalToolRegistry(registry: FactoryExternalToolRegistry): FactoryExternalToolValidationResult { const errors: string[] = []; const warnings: string[] = []; if (registry?.registryKind !== FACTORY_EXTERNAL_TOOL_GOVERNANCE_KIND || registry.registryVersion !== FACTORY_EXTERNAL_TOOL_GOVERNANCE_VERSION) errors.push('Registry kind/version is invalid.'); if (!Array.isArray(registry?.tools)) errors.push('tools must be an array.'); else registry.tools.forEach((tool) => errors.push(...validateFactoryExternalToolProfile(tool).errors)); const ids = new Set(registry?.tools?.map((tool) => tool.toolId)); for (const required of ['hermes-agent', 'codex', 'playwright', 'vitest', 'msw', 'gitleaks', 'semgrep', 'codeql', 'trivy', 'promptfoo']) if (!ids.has(required)) errors.push(`Missing required tool ${required}.`); return { ok: errors.length === 0, errors, warnings } }

