import { validateFactoryMemoryRecordDraft } from '../memory-admission/index.ts'
import { FACTORY_MEMORY_WRITE_APPROVAL_DECISIONS, FACTORY_MEMORY_WRITE_APPROVAL_KIND, FACTORY_MEMORY_WRITE_APPROVAL_STATUSES, FACTORY_MEMORY_WRITE_APPROVAL_VERSION, createFactoryMemoryWriteApprovalPolicy } from './memory-write-approval.defaults.ts'
import type { FactoryMemoryWriteApprovalInput, FactoryMemoryWriteApprovalResult, FactoryMemoryWriteApprovalValidationResult } from './memory-write-approval.types.ts'

export function validateFactoryMemoryWriteApprovalInput(input: FactoryMemoryWriteApprovalInput): FactoryMemoryWriteApprovalValidationResult { const errors: string[] = []; const warnings: string[] = []; const policy = createFactoryMemoryWriteApprovalPolicy(input?.policy); if (!input?.admissionResult) errors.push('admissionResult is required.'); if (!input?.createdAt?.trim()) errors.push('createdAt is required.'); if (!input?.reviewedBy?.trim()) errors.push('reviewedBy is required.'); if (policy.requireHumanApproval && !input?.humanApprovalRef?.trim()) errors.push('humanApprovalRef is required.'); if (input?.admissionResult?.recordDrafts.some((record) => record.containsSecrets !== false)) errors.push('Admission contains a record with secrets.'); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryMemoryWriteApprovalResult(result: FactoryMemoryWriteApprovalResult): FactoryMemoryWriteApprovalValidationResult {
  const errors: string[] = []; const warnings = result?.warnings?.map((warning) => warning.message) ?? []; const approved = result?.status === 'approved_candidate'
  if (result?.approvalKind !== FACTORY_MEMORY_WRITE_APPROVAL_KIND || result?.approvalVersion !== FACTORY_MEMORY_WRITE_APPROVAL_VERSION) errors.push('Approval kind or version is invalid.'); if (!result?.approvalId?.trim()) errors.push('approvalId is required.'); if (!FACTORY_MEMORY_WRITE_APPROVAL_DECISIONS.includes(result?.decision) || !FACTORY_MEMORY_WRITE_APPROVAL_STATUSES.includes(result?.status)) errors.push('Decision or status is invalid.'); if (result?.canWriteMemoryRuntime !== false || result?.canPromoteGlobalMemory !== false || result?.canCreateCodexTask !== false || result?.canExecuteCodex !== false || result?.canCreateProject !== false || result?.canCreateRepository !== false || result?.canDeploy !== false) errors.push('Runtime, global, Codex and creation/deploy capabilities must remain disabled.'); if (approved && (!result.approvalReceipt || !result.approvedMemoryEnvelope)) errors.push('Approved result requires receipt and envelope.'); if (approved && (result.approvedMemoryEnvelope?.memoryPersistenceStatus !== 'not_persisted' || result.approvedMemoryEnvelope.memoryRuntimeStatus !== 'not_executable' || result.approvedMemoryEnvelope.codexTaskStatus !== 'not_allowed')) errors.push('Approved envelope statuses are unsafe.'); for (const record of result?.approvedRecordDrafts ?? []) { errors.push(...validateFactoryMemoryRecordDraft(record).errors) } if (!approved && !result?.blockers?.length && !result?.reasons?.length) errors.push('Non-approved result requires blockers or reasons.'); if (!result?.recommendedNextStep?.trim()) errors.push('recommendedNextStep is required.'); return { ok: errors.length === 0, errors, warnings }
}
