import { validateFactoryMemoryRecordDraft } from '../memory-admission/index.ts'
import { FACTORY_MEMORY_WRITE_APPROVAL_KIND, FACTORY_MEMORY_WRITE_APPROVAL_VERSION, createFactoryMemoryWriteApprovalPolicy } from './memory-write-approval.defaults.ts'
import type { FactoryMemoryWriteApprovalBlocker, FactoryMemoryWriteApprovalDecision, FactoryMemoryWriteApprovalInput, FactoryMemoryWriteApprovalResult, FactoryMemoryWriteApprovalStatus } from './memory-write-approval.types.ts'

const token = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'unknown'
const unsafeRecord = (record: NonNullable<FactoryMemoryWriteApprovalInput['admissionResult']>['recordDrafts'][number]) => record.containsSecrets !== false || record.containsRawEvidence !== false || record.globalPromotionAllowed !== false || record.scope !== 'project' || record.codexTaskAllowed !== false || record.projectCreationAllowed !== false || record.repositoryCreationAllowed !== false || record.deployAllowed !== false || !validateFactoryMemoryRecordDraft(record).ok

export function evaluateFactoryMemoryWriteApproval(input: FactoryMemoryWriteApprovalInput): FactoryMemoryWriteApprovalResult {
  const policy = createFactoryMemoryWriteApprovalPolicy(input?.policy); const admission = input?.admissionResult; const createdAt = input?.createdAt ?? ''; const reviewedBy = input?.reviewedBy ?? ''; const sourceAdmissionId = admission?.admissionId ?? 'missing-admission'; const approvalId = `memory-write-approval:${token(sourceAdmissionId)}:${token(createdAt)}`
  const checks = [{ checkId: 'admission-present', passed: Boolean(admission), message: 'Admission result must be present.' }, { checkId: 'reviewer-present', passed: Boolean(reviewedBy.trim()), message: 'Reviewer identity must be present.' }, { checkId: 'human-approval-present', passed: Boolean(input?.humanApprovalRef?.trim()), message: 'Human approval is required.' }]
  const requirements = checks.map((check) => ({ requirementId: check.checkId, satisfied: check.passed, message: check.message })); const blockers: FactoryMemoryWriteApprovalBlocker[] = []; const warnings = (admission?.warnings ?? []).map((warning) => ({ warningId: warning.warningId, recordId: warning.entryId, message: warning.message })); const reasons: string[] = []
  let decision: FactoryMemoryWriteApprovalDecision; let status: FactoryMemoryWriteApprovalStatus
  if (!admission) { decision = 'blocked'; status = 'blocked'; reasons.push('Admission result is required.'); blockers.push({ blockerId: 'missing-admission', reason: reasons[0], critical: true }) }
  else {
    const unsafe = admission.recordDrafts.filter(unsafeRecord); const criticalFinding = admission.findings.some((finding) => finding.severity === 'critical'); const unresolvedContradiction = admission.decisions.some((item) => item.decision === 'possible_contradiction') || admission.findings.some((finding) => finding.kind === 'possible_contradiction')
    for (const record of unsafe) blockers.push({ blockerId: `unsafe-record:${record.memoryRecordId}`, recordId: record.memoryRecordId, reason: 'Record violates project-memory safety or validation requirements.', critical: true })
    if (criticalFinding) blockers.push({ blockerId: 'critical-admission-finding', reason: 'Admission contains a critical finding.', critical: true })
    if (unsafe.length || criticalFinding || admission.blockers.length || admission.blockedEntries.length || admission.rejectedEntries.length) { decision = 'block_memory_write'; status = 'blocked'; reasons.push('Admission contains unsafe, rejected, blocked or critical material.') }
    else if (!admission.recordDrafts.length && admission.summary.admittedCount === 0) { decision = 'reject_memory_admission'; status = 'rejected'; reasons.push('Memory admission produced no admitted record drafts.'); blockers.push({ blockerId: 'no-admitted-record-drafts', reason: reasons[0], critical: false }) }
    else if (!admission.recordDrafts.length) { decision = 'request_memory_changes'; status = 'changes_required'; reasons.push('Admission record drafts are inconsistent with its admitted summary and require review.'); blockers.push({ blockerId: 'inconsistent-record-drafts', reason: reasons[0], critical: false }) }
    else if (unresolvedContradiction) { decision = 'request_memory_changes'; status = 'changes_required'; reasons.push('Unresolved memory contradiction requires governed changes.'); blockers.push({ blockerId: 'unresolved-contradiction', reason: reasons[0], critical: true }) }
    else if (!input.humanApprovalRef?.trim() || !reviewedBy.trim()) { decision = 'human_review_required'; status = 'awaiting_human_review'; reasons.push('Explicit human approval and reviewer identity are required.'); blockers.push({ blockerId: 'human-review-required', reason: reasons[0], critical: false }) }
    else { decision = 'approve_project_memory_for_persistence_candidate'; status = 'approved_candidate'; reasons.push('Project-scoped record drafts passed governed human review.') }
  }
  const approved = decision === 'approve_project_memory_for_persistence_candidate' ? structuredClone(admission?.recordDrafts ?? []) : []; const blocked = decision === 'block_memory_write' || decision === 'blocked' || decision === 'request_memory_changes' ? structuredClone(admission?.recordDrafts ?? []) : []; const rejected = decision === 'reject_memory_admission' ? structuredClone(admission?.recordDrafts ?? []) : []
  const nextStep = decision === 'approve_project_memory_for_persistence_candidate' ? 'Submit the approved envelope to a future Factory Memory Persistence Gate; do not execute Codex.' : decision === 'human_review_required' ? 'Obtain explicit human review before preparing a memory persistence candidate.' : 'Resolve memory blockers and resubmit through Memory Admission and human review.'
  const result: FactoryMemoryWriteApprovalResult = { approvalId, approvalKind: FACTORY_MEMORY_WRITE_APPROVAL_KIND, approvalVersion: FACTORY_MEMORY_WRITE_APPROVAL_VERSION, createdAt, reviewedBy, reviewerRole: input?.reviewerRole, sourceAdmissionId, status, decision, requirements, approvedRecordDrafts: approved, rejectedRecordDrafts: rejected, blockedRecordDrafts: blocked, checks, blockers, warnings, reasons, summary: { approvalId, sourceAdmissionId, decision, status, approvedCount: approved.length, rejectedCount: rejected.length, blockedCount: blocked.length, receiptPresent: false, envelopePresent: false, memoryPersistenceStatus: 'not_applicable', codexTaskStatus: 'not_allowed', recommendedNextStep: nextStep }, canWriteMemoryRuntime: false, canPromoteGlobalMemory: false, canCreateCodexTask: false, canExecuteCodex: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: nextStep }
  if (decision === 'approve_project_memory_for_persistence_candidate' && admission && input.humanApprovalRef) { result.approvalReceipt = { receiptId: `memory-write-receipt:${token(approvalId)}`, approvalId, sourceAdmissionId, reviewedBy, reviewedAt: createdAt, humanApprovalRef: input.humanApprovalRef, decision, scope: 'project_memory_persistence_candidate', limitations: ['Approval is a persistence candidate only.', 'No runtime write or global promotion is authorized.'], notAuthorizedActions: ['write_memory_runtime', 'promote_global_memory', 'create_codex_task', 'execute_codex', 'create_project', 'create_repository', 'deploy', 'publish', 'access_secrets', 'create_embeddings'] }; result.approvedMemoryEnvelope = { envelopeId: `memory-envelope:${token(approvalId)}`, approvalId, sourceAdmissionId, recordDrafts: approved, validation: { ok: true, errors: [], warnings: warnings.map((warning) => warning.message) }, memoryPersistenceStatus: 'not_persisted', memoryRuntimeStatus: 'not_executable', globalPromotionStatus: 'not_allowed', codexTaskStatus: 'not_allowed', repositoryStatus: 'not_created', deployStatus: 'not_allowed', recommendedNextStep: nextStep }; result.summary = { ...result.summary, receiptPresent: true, envelopePresent: true, memoryPersistenceStatus: 'not_persisted' } }
  void policy; return result
}
