import type { FactoryMemoryAdmissionResult, FactoryMemoryRecordDraft } from '../memory-admission/index.ts'

export type FactoryMemoryWriteApprovalVersion = '1.0'
export type FactoryMemoryWriteApprovalKind = 'factory-memory-write-approval'
export type FactoryMemoryWriteApprovalDecision = 'reject_memory_admission' | 'request_memory_changes' | 'human_review_required' | 'approve_project_memory_for_persistence_candidate' | 'block_memory_write' | 'blocked'
export type FactoryMemoryWriteApprovalStatus = 'rejected' | 'changes_required' | 'awaiting_human_review' | 'approved_candidate' | 'blocked'
export interface FactoryMemoryWriteApprovalReviewer { reviewedBy: string; reviewerRole?: string; humanApprovalRef?: string }
export interface FactoryMemoryWriteApprovalPolicy { requireAdmissionResult: true; requireHumanApproval: true; requireReviewerIdentity: true; requireAtLeastOneRecordDraft: true; requireProjectScopedRecordsOnly: true; rejectGlobalPromotionByDefault: true; rejectContradictionsWithoutResolution: true; rejectBlockedEntries: true; rejectRejectedEntries: true; rejectCriticalFindings: true; requireNoSecrets: true; requireNoRawEvidence: true; requireNamespacesValid: true; requireLineage: true; requireRetentionPolicy: true; requirePromotionPolicy: true; requireStalePolicy: true; allowProjectMemoryPersistenceCandidateOnly: true; forbidMemoryRuntimeWriteInThisGate: true; forbidGlobalPromotion: true; forbidCodexTaskCreation: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true }
export interface FactoryMemoryWriteApprovalInput { admissionResult: FactoryMemoryAdmissionResult; createdAt: string; reviewedBy: string; reviewerRole?: string; humanApprovalRef?: string; policy?: Partial<FactoryMemoryWriteApprovalPolicy>; reviewNotes?: string[] }
export interface FactoryMemoryWriteApprovalRequirement { requirementId: string; satisfied: boolean; message: string }
export interface FactoryMemoryWriteApprovalCheck { checkId: string; passed: boolean; message: string }
export interface FactoryMemoryWriteApprovalBlocker { blockerId: string; recordId?: string; reason: string; critical: boolean }
export interface FactoryMemoryWriteApprovalWarning { warningId: string; recordId?: string; message: string }
export interface FactoryMemoryWriteApprovalReceipt { receiptId: string; approvalId: string; sourceAdmissionId: string; reviewedBy: string; reviewedAt: string; humanApprovalRef: string; decision: 'approve_project_memory_for_persistence_candidate'; scope: 'project_memory_persistence_candidate'; limitations: string[]; notAuthorizedActions: ('write_memory_runtime' | 'promote_global_memory' | 'create_codex_task' | 'execute_codex' | 'create_project' | 'create_repository' | 'deploy' | 'publish' | 'access_secrets' | 'create_embeddings')[] }
export interface FactoryMemoryApprovedEnvelope { envelopeId: string; approvalId: string; sourceAdmissionId: string; recordDrafts: FactoryMemoryRecordDraft[]; validation: { ok: boolean; errors: string[]; warnings: string[] }; memoryPersistenceStatus: 'not_persisted'; memoryRuntimeStatus: 'not_executable'; globalPromotionStatus: 'not_allowed'; codexTaskStatus: 'not_allowed'; repositoryStatus: 'not_created'; deployStatus: 'not_allowed'; recommendedNextStep: string }
export interface FactoryMemoryWriteApprovalSummary { approvalId: string; sourceAdmissionId: string; decision: FactoryMemoryWriteApprovalDecision; status: FactoryMemoryWriteApprovalStatus; approvedCount: number; rejectedCount: number; blockedCount: number; receiptPresent: boolean; envelopePresent: boolean; memoryPersistenceStatus: 'not_persisted' | 'not_applicable'; codexTaskStatus: 'not_allowed'; recommendedNextStep: string }
export interface FactoryMemoryWriteApprovalResult { approvalId: string; approvalKind: FactoryMemoryWriteApprovalKind; approvalVersion: FactoryMemoryWriteApprovalVersion; createdAt: string; reviewedBy: string; reviewerRole?: string; sourceAdmissionId: string; status: FactoryMemoryWriteApprovalStatus; decision: FactoryMemoryWriteApprovalDecision; requirements: FactoryMemoryWriteApprovalRequirement[]; approvedRecordDrafts: FactoryMemoryRecordDraft[]; rejectedRecordDrafts: FactoryMemoryRecordDraft[]; blockedRecordDrafts: FactoryMemoryRecordDraft[]; checks: FactoryMemoryWriteApprovalCheck[]; blockers: FactoryMemoryWriteApprovalBlocker[]; warnings: FactoryMemoryWriteApprovalWarning[]; reasons: string[]; approvalReceipt?: FactoryMemoryWriteApprovalReceipt; approvedMemoryEnvelope?: FactoryMemoryApprovedEnvelope; summary: FactoryMemoryWriteApprovalSummary; canWriteMemoryRuntime: false; canPromoteGlobalMemory: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryWriteApprovalValidationResult { ok: boolean; errors: string[]; warnings: string[] }
