export type FactoryHermesToolsetDisableVerificationPlanningVersion = '1.0'
export type FactoryHermesToolsetDisableVerificationPlanningKind = 'factory-hermes-toolset-disable-verification-planning'
export type FactoryHermesToolsetDisableVerificationPlanningStatus = 'toolset_disable_verification_plan_created' | 'blocked'
export type FactoryHermesToolsetDisableVerificationPlanningDecision = 'hermes_toolset_disable_verification_plan_created_static_no_tool_mode_verified' | 'hermes_toolset_disable_verification_plan_created_runtime_probe_or_selection_revision_required' | 'hermes_toolset_disable_verification_plan_created_no_tool_mode_not_supported_selection_revision_required' | 'blocked_invalid_adapter_approval'
export type FactoryHermesToolsetStaticVerificationStatus = 'verified' | 'inconclusive_or_not_supported' | 'not_supported'

export interface FactoryHermesToolsetDisableVerificationPlanningInput { plannedAt: string; plannedBy: string; researchRuntimeAdapterApprovalResult?: any; runtimeSelectionDecisionResult?: any; toolsetsPolicyPlanningResult?: any; sourceInspection?: any; policy?: Partial<FactoryHermesToolsetDisableVerificationPlanningPolicy>; planningNotes?: string }
export interface FactoryHermesToolsetDisableVerificationPlanningPolicy { requireAdapterApprovalBlockedByToolset: boolean; requireSourceInspection: boolean; requireStaticMap: boolean; requireNoToolModeProofForRetry: boolean; requireBlockIfNoToolModeUnproven: boolean; requireNoExecutionInThisGate: boolean; requireNoPromptPassingInThisGate: boolean; requireNoNetworkInThisGate: boolean; requireNoCredentialUseInThisGate: boolean; requireNoModelCallsInThisGate: boolean; requireNoToolsetEnablementInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidResearchExecutionInThisGate: boolean; forbidUsingFindingsInThisGate: boolean; forbidDeployInThisGate: boolean }
export interface FactoryHermesToolsetLoadingStaticMap { cliToolsetsArg: any; validationPath: any; defaultToolsetsPath: any; noMcpSentinel: any; agentConstruction: any }
export interface FactoryHermesToolsetDisableEvidence { noToolModeProven: boolean; noToolModeSyntax: string | null; proofLevel: 'verified_static' | 'inconclusive' | 'contradicted' | 'not_supported'; evidenceItems: string[]; contradictions: string[]; risks: string[] }
export interface FactoryHermesToolsetDisableVerificationCandidate { candidateId: string; status: string; objective?: string; allowedNow: false; requiresApprovalGate: boolean; options?: string[] }
export interface FactoryHermesToolsetDisableVerificationRecommendation { recommendationId: string; recommendedNextGate: string; rationale: string; noExecutionAuthorized: true }
export interface FactoryHermesToolsetDisableVerificationPlanningReceipt { receiptId: string; planningId: string; toolId: 'hermes_agent'; plannedBy: string; plannedAt: string; decision: FactoryHermesToolsetDisableVerificationPlanningDecision; scope: 'hermes_toolset_disable_verification_planning_only'; approvedNextGate: string; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesToolsetDisableVerificationPlanningCheck { checkId: string; message: string }
export interface FactoryHermesToolsetDisableVerificationPlanningBlocker { blockerId: string; message: string }
export interface FactoryHermesToolsetDisableVerificationPlanningWarning { warningId: string; message: string }

export interface FactoryHermesToolsetDisableVerificationPlanningResult {
  planningId: string; planningKind: FactoryHermesToolsetDisableVerificationPlanningKind; planningVersion: FactoryHermesToolsetDisableVerificationPlanningVersion; plannedAt: string; plannedBy: string; toolId: 'hermes_agent'; adapterApprovalDecisionRef?: string; selectedToolsetMode: 'no_toolsets_text_only'; toolsetLoadingStaticMap?: FactoryHermesToolsetLoadingStaticMap; toolsetDisableEvidence?: FactoryHermesToolsetDisableEvidence; toolsetDisableVerificationCandidates: FactoryHermesToolsetDisableVerificationCandidate[]; toolsetDisableVerificationRecommendation?: FactoryHermesToolsetDisableVerificationRecommendation; toolsetDisableVerificationPlanningReceipt?: FactoryHermesToolsetDisableVerificationPlanningReceipt; checks: FactoryHermesToolsetDisableVerificationPlanningCheck[]; blockers: FactoryHermesToolsetDisableVerificationPlanningBlocker[]; warnings: FactoryHermesToolsetDisableVerificationPlanningWarning[]; status: FactoryHermesToolsetDisableVerificationPlanningStatus; decision: FactoryHermesToolsetDisableVerificationPlanningDecision; staticVerificationStatus: FactoryHermesToolsetStaticVerificationStatus; canProceedToToolsetDisableVerificationApproval: boolean; canProceedToResearchRuntimeAdapterApprovalRetry: boolean; canProceedToRuntimeSelectionRevisionPlanning: boolean; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false; canExecuteHermesNow: false; canPassPromptNow: false; canUseNetworkNow: false; canUseCredentialsNow: false; canReadEnvSecretsNow: false; canCallModelsNow: false; canEnableToolsetsNow: false; canMutateFilesystemNow: false; canUseFindings: false; recommendedNextStep: string
}
export interface FactoryHermesToolsetDisableVerificationPlanningValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesToolsetDisableVerificationPlanningSummary { planningId: string; status: FactoryHermesToolsetDisableVerificationPlanningStatus; decision: FactoryHermesToolsetDisableVerificationPlanningDecision; staticVerificationStatus: FactoryHermesToolsetStaticVerificationStatus; noToolModeProven: boolean; canProceedToToolsetDisableVerificationApproval: boolean; canProceedToResearchRuntimeAdapterApprovalRetry: boolean; canRunResearchNow: false; nextStep: string }
