const fs = require('node:fs/promises');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { assertToolsetDisablePlanningPathContained, resolveFactoryHermesToolsetDisableVerificationPlanningPaths } = require('./hermes-toolset-disable-verification-planning.path.cjs');
async function readJson(file) { const text = await fs.readFile(file, 'utf8'); if (!text.trim()) throw new Error(`json_file_empty: ${file}`); return JSON.parse(text); }
async function readText(file) { try { return await fs.readFile(file, 'utf8'); } catch { return ''; } }
function inspect(texts) { const joined = texts.join('\n'); return { hasToolsetsArg: joined.includes('--toolsets'), hasValidateExplicitToolsets: joined.includes('_validate_explicit_toolsets'), hasRejectsNoValidToolsets: joined.includes('--toolsets did not contain any valid toolsets'), hasUseConfigToolsets: joined.includes('use_config_toolsets') && joined.includes('_get_platform_tools'), hasNoMcp: joined.includes('no_mcp'), hasAgentEnabledToolsets: joined.includes('enabled_toolsets') || joined.includes('enabled_toolsets=toolsets_list') }; }
async function executeFactoryHermesToolsetDisableVerificationPlanning(input = {}) { const paths = resolveFactoryHermesToolsetDisableVerificationPlanningPaths(); for (const target of [paths.adapterApprovalResult, paths.runtimeSelectionDecisionResult, paths.toolsetsPolicyPlanningResult, paths.boundaryPlanningResult, paths.planningResult, paths.oneshot, paths.main, paths.toolsConfig, paths.config, paths.readme, paths.pyproject]) assertToolsetDisablePlanningPathContained(target, paths.installRoot); const { evaluateFactoryHermesToolsetDisableVerificationPlanning } = await import(pathToFileURL(path.join(paths.repoRoot, 'src', 'factory', 'hermes-toolset-disable-verification-planning', 'index.ts')).href); const plannedAt = input.plannedAt || '2026-07-22T22:00:00.000Z'; const plannedBy = input.plannedBy || 'factory-hermes-toolset-disable-verification-planning-smoke'; const sourceInspection = input.sourceInspection || inspect([await readText(paths.oneshot), await readText(paths.main), await readText(paths.toolsConfig), await readText(paths.config), await readText(paths.readme), await readText(paths.pyproject)]); const result = evaluateFactoryHermesToolsetDisableVerificationPlanning({ plannedAt, plannedBy, researchRuntimeAdapterApprovalResult: input.researchRuntimeAdapterApprovalResult || await readJson(paths.adapterApprovalResult), runtimeSelectionDecisionResult: input.runtimeSelectionDecisionResult || await readJson(paths.runtimeSelectionDecisionResult), toolsetsPolicyPlanningResult: input.toolsetsPolicyPlanningResult || await readJson(paths.toolsetsPolicyPlanningResult), sourceInspection }); await fs.mkdir(path.dirname(paths.planningResult), { recursive: true }); await fs.writeFile(paths.planningResult, `${JSON.stringify(result, null, 2)}\n`); return result; }
module.exports = { executeFactoryHermesToolsetDisableVerificationPlanning };
