export type FactoryHermesWrapperNoToolModeApprovalVersion = '1.0'
export type FactoryHermesWrapperNoToolModeApprovalKind = 'factory-hermes-wrapper-no-tool-mode-approval'
export type FactoryHermesWrapperNoToolModeApprovalStatus = 'wrapper_no_tool_mode_approval_granted' | 'wrapper_no_tool_mode_approval_blocked'
export type FactoryHermesWrapperNoToolModeApprovalDecision = 'hermes_wrapper_no_tool_mode_approved_for_implementation_planning' | 'hermes_wrapper_no_tool_mode_approval_blocked_no_safe_wrapper_plan'
export type FactoryHermesWrapperNoToolModeApprovalStatusValue = 'approved_for_implementation_planning' | 'blocked'
export interface FactoryHermesWrapperNoToolModeApprovalInput { evaluatedAt: string; evaluatedBy: string; wrapperNoToolModePlanningResult?: any; runtimeSelectionRevisionPlanningResult?: any; toolsetDisableVerificationApprovalResult?: any; researchRuntimeAdapterApprovalResult?: any; runtimeSelectionDecisionResult?: any; finalExecutionApprovalResult?: any; policy?: Partial<FactoryHermesWrapperNoToolModeApprovalPolicy>; approvalNotes?: string }
export interface FactoryHermesWrapperNoToolModeApprovalPolicy { requireWrapperPlanningCreated: boolean; requireRuntimeSelectionRevisionBlocked: boolean; requireToolsetDisableApprovalBlocked: boolean; requireNoSourceMutationNow: boolean; requireNoWrapperImplementationNow: boolean; requireNoWrapperExecutionNow: boolean; requireNoRuntimeAdapterNow: boolean; requireNoResearchExecutionNow: boolean; forbidHermesExecutionInThisGate: boolean; forbidPromptPassingInThisGate: boolean; forbidNetworkInThisGate: boolean; forbidCredentialsInThisGate: boolean; forbidModelCallsInThisGate: boolean; forbidToolsetsInThisGate: boolean }
export interface FactoryHermesApprovedWrapperNoToolModeImplementationPlanningEnvelope { envelopeId: string; toolId: 'hermes_agent'; approvedFor: 'wrapper_no_tool_mode_implementation_planning_only'; selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets'; purpose: string; sourceMutationAllowed: false; hermesSourceReadOnly: true; wrapperImplementationAllowedNow: false; wrapperExecutionAllowedNow: false; researchRuntimeAdapterAllowedNow: false; researchExecutionAllowedNow: false; designConstraints: string[]; futureImplementationPlanningMustDefine: string[]; recommendedNextGate: 'Factory Hermes Wrapper No-Tool Mode Implementation Planning Gate v1' }
export interface FactoryHermesWrapperNoToolModeApprovalDecisionRecord { decisionId: string; toolId: 'hermes_agent'; approvalStatus: FactoryHermesWrapperNoToolModeApprovalStatusValue; decision: FactoryHermesWrapperNoToolModeApprovalDecision; reason: string; wrapperPlanningValidated: boolean; implementationPlanningApproved: boolean; wrapperImplementationApproved: false; wrapperExecutionApproved: false; researchRuntimeAdapterApproved: false; researchExecutionApproved: false; canProceedToHermesWrapperNoToolModeImplementationPlanning: boolean; requiredNextGate: string }
export interface FactoryHermesWrapperNoToolModeApprovalReceipt { receiptId: string; approvalId: string; toolId: 'hermes_agent'; evaluatedBy: string; evaluatedAt: string; decision: FactoryHermesWrapperNoToolModeApprovalDecision; approvalStatus: FactoryHermesWrapperNoToolModeApprovalStatusValue; scope: 'hermes_wrapper_no_tool_mode_approval_only'; approvedNextGate: string; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesWrapperNoToolModeApprovalBlockerPlan { blockerPlanId: string; toolId: 'hermes_agent'; blockerType: 'no_safe_wrapper_plan'; blockers: string[]; resolutionOptions: string[]; recommendedConservativeNextGate: 'Factory Hermes Keep Hermes Research Blocked Decision Gate v1' }
export interface FactoryHermesWrapperNoToolModeApprovalResult { approvalId: string; approvalKind: FactoryHermesWrapperNoToolModeApprovalKind; approvalVersion: FactoryHermesWrapperNoToolModeApprovalVersion; evaluatedAt: string; evaluatedBy: string; toolId: 'hermes_agent'; wrapperPlanningRef?: string; runtimeSelectionRevisionRef?: string; approvedWrapperNoToolModeImplementationPlanningEnvelope?: FactoryHermesApprovedWrapperNoToolModeImplementationPlanningEnvelope; hermesWrapperNoToolModeApprovalDecision: FactoryHermesWrapperNoToolModeApprovalDecisionRecord; wrapperNoToolModeApprovalReceipt: FactoryHermesWrapperNoToolModeApprovalReceipt; approvalBlockerPlan?: FactoryHermesWrapperNoToolModeApprovalBlockerPlan; checks: any[]; blockers: any[]; warnings: any[]; status: FactoryHermesWrapperNoToolModeApprovalStatus; decision: FactoryHermesWrapperNoToolModeApprovalDecision; approvalStatus: FactoryHermesWrapperNoToolModeApprovalStatusValue; canProceedToHermesWrapperNoToolModeImplementationPlanning: boolean; canProceedToHermesWrapperNoToolModeImplementation: false; canProceedToKeepHermesResearchBlockedDecision: boolean; canProceedToResearchRuntimeAdapterApprovalRetry: false; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false; canExecuteHermesNow: false; canPassPromptNow: false; canUseNetworkNow: false; canUseCredentialsNow: false; canReadEnvSecretsNow: false; canCallModelsNow: false; canEnableToolsetsNow: false; canMutateFilesystemNow: false; canUseFindings: false; recommendedNextStep: string }
export interface FactoryHermesWrapperNoToolModeApprovalValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesWrapperNoToolModeApprovalSummary { approvalId: string; status: FactoryHermesWrapperNoToolModeApprovalStatus; decision: FactoryHermesWrapperNoToolModeApprovalDecision; approvalStatus: FactoryHermesWrapperNoToolModeApprovalStatusValue; selectedWrapperStrategy: string | null; canProceedToHermesWrapperNoToolModeImplementationPlanning: boolean; canProceedToHermesWrapperNoToolModeImplementation: false; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false; canExecuteHermesNow: false; canPassPromptNow: false; nextStep: string }
