export type FactoryHermesPythonInstallJefeReviewVersion = '1.0'
export type FactoryHermesPythonInstallJefeReviewKind = 'factory-hermes-python-install-jefe-review'
export type FactoryHermesPythonInstallJefeReviewStatus = 'approved' | 'blocked' | 'human_review_required' | 'changes_required'
export type FactoryHermesPythonInstallJefeReviewDecision = 'hermes_python_install_jefe_review_approved_for_research_runtime_planning' | 'blocked_missing_python_install_verification' | 'blocked_python_install_not_verified' | 'blocked_verification_allows_hermes_execution' | 'blocked_missing_human_approval' | 'request_python_install_repair_before_review'
export interface FactoryHermesPythonInstallJefeReviewInput { reviewedAt: string; reviewedBy: string; reviewerRole?: string; humanApprovalRef?: string; pythonInstallVerificationResult?: any; policy?: Partial<FactoryHermesPythonInstallJefeReviewPolicy>; reviewNotes?: string }
export interface FactoryHermesPythonInstallJefeReviewPolicy { requirePythonInstallVerification: boolean; requireVerificationStatusVerified: boolean; requireVerificationDecisionHermesPythonInstallVerified: boolean; requireHumanApprovalRef: boolean; requireReviewerIdentity: boolean; requireAuditedHead: boolean; requireUvVerification: boolean; requirePythonEnvRootUnderCodexTemp: boolean; requireNoHermesExecution: boolean; requireNoHermesScripts: boolean; requireNoPipExecution: boolean; requireNoPythonDirectExecution: boolean; requireNoSetupPyExecution: boolean; requireCanProceedToJefeReview: boolean; forbidHermesExecutionInThisGate: boolean; forbidHermesScriptsInThisGate: boolean; forbidUvProjectOpsInThisGate: boolean; forbidPipExecutionInThisGate: boolean; forbidPythonExecutionInThisGate: boolean; forbidSetupPyExecutionInThisGate: boolean; forbidCredentialsInThisGate: boolean; forbidModelCallsInThisGate: boolean; forbidProjectMutationInThisGate: boolean; forbidDeployInThisGate: boolean; requireResearchRuntimePlanningGateNext: boolean; forbidDirectResearchRuntimeExecution: boolean }
export interface FactoryHermesPythonInstallJefeReviewCheck { checkId: string; ok: boolean; message: string }
export interface FactoryHermesPythonInstallJefeReviewBlocker { blockerId: string; message: string }
export interface FactoryHermesPythonInstallJefeReviewWarning { warningId: string; message: string }
export interface FactoryHermesPythonInstallJefeReviewReceipt { receiptId: string; jefeReviewId: string; toolId: 'hermes_agent'; auditedHead: string; reviewedBy: string; reviewedAt: string; humanApprovalRef: string; decision: FactoryHermesPythonInstallJefeReviewDecision; scope: 'hermes_python_install_readiness_for_research_runtime_planning'; approvedNextGate: 'Factory Hermes Research Runtime Planning Gate v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesPythonInstallReadinessEnvelope { envelopeId: string; jefeReviewId: string; toolId: 'hermes_agent'; auditedHead: string; sourceRootRef: string; installRootRef: string; pythonEnvRootRef: string; uvExecutableRef: string; uvVerificationRef: string; pythonInstallVerificationRef: string; verificationSummary: Record<string, unknown>; approvedNextGate: 'Factory Hermes Research Runtime Planning Gate v1'; pythonInstallReadinessStatus: 'approved_for_planning_only'; hermesExecutionStatus: 'not_allowed'; scriptsStatus: 'not_allowed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; projectMutationStatus: 'not_allowed'; deployStatus: 'not_allowed'; canProceedToResearchRuntimePlanning: true; canExecuteHermes: false; canRunHermesScripts: false; recommendedNextStep: string }
export interface FactoryHermesPythonInstallJefeReviewResult { jefeReviewId: string; jefeReviewKind: FactoryHermesPythonInstallJefeReviewKind; jefeReviewVersion: FactoryHermesPythonInstallJefeReviewVersion; reviewedAt: string; reviewedBy: string; toolId: 'hermes_agent'; auditedHead: string; installRootRef: string; sourceRootRef: string; pythonEnvRootRef: string; uvExecutableRef: string; uvVerificationRef: string; pythonInstallVerificationRef: string; verificationStatus: string; verificationDecision: string; reviewReceipt?: FactoryHermesPythonInstallJefeReviewReceipt; approvedHermesPythonInstallReadinessEnvelope?: FactoryHermesPythonInstallReadinessEnvelope; checks: FactoryHermesPythonInstallJefeReviewCheck[]; blockers: FactoryHermesPythonInstallJefeReviewBlocker[]; warnings: FactoryHermesPythonInstallJefeReviewWarning[]; status: FactoryHermesPythonInstallJefeReviewStatus; decision: FactoryHermesPythonInstallJefeReviewDecision; canProceedToResearchRuntimePlanning: boolean; canExecuteHermes: false; canRunHermesScripts: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesPythonInstallJefeReviewValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesPythonInstallJefeReviewSummary { jefeReviewId: string; toolId: 'hermes_agent'; auditedHead: string; verificationStatus: string; decision: FactoryHermesPythonInstallJefeReviewDecision; status: FactoryHermesPythonInstallJefeReviewStatus; canProceedToResearchRuntimePlanning: boolean; canExecuteHermes: false; approvedNextGate?: string; nextStep: string }
