import { FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_KIND, FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_NEXT_STEP, FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_VERSION, DEFAULT_FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_POLICY } from './hermes-python-install-jefe-review.defaults.ts'
import type { FactoryHermesPythonInstallJefeReviewInput, FactoryHermesPythonInstallJefeReviewResult } from './hermes-python-install-jefe-review.types.ts'

const dangerous = (v: any) => v?.pipStatus !== 'not_executed' || v?.pythonDirectStatus !== 'not_executed' || v?.setupPyStatus !== 'not_executed' || v?.hermesExecutionStatus !== 'not_allowed' || !['not_executed', 'not_allowed'].includes(v?.scriptsStatus) || v?.canExecuteHermes === true || v?.canRunHermesScripts === true || v?.canUseCredentials === true || v?.canCallModels === true || v?.canDeploy === true

export function evaluateFactoryHermesPythonInstallJefeReview(input: FactoryHermesPythonInstallJefeReviewInput): FactoryHermesPythonInstallJefeReviewResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_POLICY, ...input.policy }
  const v = input.pythonInstallVerificationResult
  const base = { jefeReviewId: `hermes-python-install-jefe-review:75b300f:${input.reviewedAt}`, jefeReviewKind: FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_KIND, jefeReviewVersion: FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_VERSION, reviewedAt: input.reviewedAt, reviewedBy: input.reviewedBy, toolId: 'hermes_agent' as const, auditedHead: v?.auditedHead || '', installRootRef: v?.installRootRef || '', sourceRootRef: v?.sourceRootRef || '', pythonEnvRootRef: v?.pythonEnvRootRef || '', uvExecutableRef: v?.uvExecutableRef || '', uvVerificationRef: v?.uvVerificationRef || '', pythonInstallVerificationRef: v?.pythonInstallVerificationResultRef || '', verificationStatus: v?.status || 'missing', verificationDecision: v?.decision || 'missing', checks: [], blockers: [], warnings: [], canExecuteHermes: false as const, canRunHermesScripts: false as const, canUseCredentials: false as const, canCallModels: false as const, canMutateProjectFiles: false as const, canDeploy: false as const, recommendedNextStep: FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_NEXT_STEP }
  if (!v) return { ...base, status: 'blocked', decision: 'blocked_missing_python_install_verification', canProceedToResearchRuntimePlanning: false, blockers: [{ blockerId: 'blocked_missing_python_install_verification', message: 'Python install verification result is required.' }] }
  if (v.status !== 'verified' || v.decision !== 'hermes_python_install_verified' || v.canProceedToJefeReview !== true) return { ...base, status: 'blocked', decision: 'blocked_python_install_not_verified', canProceedToResearchRuntimePlanning: false, blockers: [{ blockerId: 'blocked_python_install_not_verified', message: 'Python install verification is not verified for JEFE review.' }] }
  if (v.canExecuteHermes === true) return { ...base, status: 'blocked', decision: 'blocked_verification_allows_hermes_execution', canProceedToResearchRuntimePlanning: false, blockers: [{ blockerId: 'blocked_verification_allows_hermes_execution', message: 'Verification must not allow Hermes execution.' }] }
  if (dangerous(v)) return { ...base, status: 'changes_required', decision: 'request_python_install_repair_before_review', canProceedToResearchRuntimePlanning: false, blockers: [{ blockerId: 'request_python_install_repair_before_review', message: 'Verification contains unsafe execution or capability status.' }] }
  if (policy.requireHumanApprovalRef && !input.humanApprovalRef) return { ...base, status: 'human_review_required', decision: 'blocked_missing_human_approval', canProceedToResearchRuntimePlanning: false, blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] }
  const reviewReceipt = { receiptId: `${base.jefeReviewId}:receipt`, jefeReviewId: base.jefeReviewId, toolId: 'hermes_agent' as const, auditedHead: v.auditedHead, reviewedBy: input.reviewedBy, reviewedAt: input.reviewedAt, humanApprovalRef: input.humanApprovalRef || '', decision: 'hermes_python_install_jefe_review_approved_for_research_runtime_planning' as const, scope: 'hermes_python_install_readiness_for_research_runtime_planning' as const, approvedNextGate: 'Factory Hermes Research Runtime Planning Gate v1' as const, limitations: ['Planning only.', 'Hermes execution remains forbidden.', 'No model calls or credentials.'], notAuthorizedActions: FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_NOT_AUTHORIZED_ACTIONS }
  const approvedHermesPythonInstallReadinessEnvelope = { envelopeId: `${base.jefeReviewId}:readiness-envelope`, jefeReviewId: base.jefeReviewId, toolId: 'hermes_agent' as const, auditedHead: v.auditedHead, sourceRootRef: v.sourceRootRef, installRootRef: v.installRootRef, pythonEnvRootRef: v.pythonEnvRootRef, uvExecutableRef: v.uvExecutableRef, uvVerificationRef: v.uvVerificationRef, pythonInstallVerificationRef: v.pythonInstallVerificationResultRef, verificationSummary: { status: v.status, decision: v.decision, pythonInstallStatus: v.pythonInstallStatus, pythonEnvStatus: v.pythonEnvStatus, uvVerificationStatus: v.uvVerificationStatus }, approvedNextGate: 'Factory Hermes Research Runtime Planning Gate v1' as const, pythonInstallReadinessStatus: 'approved_for_planning_only' as const, hermesExecutionStatus: 'not_allowed' as const, scriptsStatus: 'not_allowed' as const, credentialsStatus: 'not_allowed' as const, modelCallStatus: 'not_allowed' as const, projectMutationStatus: 'not_allowed' as const, deployStatus: 'not_allowed' as const, canProceedToResearchRuntimePlanning: true as const, canExecuteHermes: false as const, canRunHermesScripts: false as const, recommendedNextStep: FACTORY_HERMES_PYTHON_INSTALL_JEFE_REVIEW_NEXT_STEP }
  return { ...base, status: 'approved', decision: 'hermes_python_install_jefe_review_approved_for_research_runtime_planning', reviewReceipt, approvedHermesPythonInstallReadinessEnvelope, canProceedToResearchRuntimePlanning: true }
}
