import type { FactoryMemoryReadAdmissionResult } from '../memory-read-admission/index.ts'
export type FactoryMemoryReadRuntimeVersion = '1.0'
export type FactoryMemoryReadRuntimeKind = 'factory-memory-read-runtime'
export type FactoryMemoryReadRuntimeStatus = 'success' | 'partial' | 'blocked' | 'failed'
export type FactoryMemoryReadRuntimeReadStatus = 'read' | 'blocked' | 'missing' | 'invalid'
export interface FactoryMemoryReadRuntimePolicy { requireStorageRootInsideCodexTemp: true; requireReadAdmissionApproved: true; requireReadCandidates: true; requireCandidateSafeReferences: true; requireMetadataReadback: true; requireFingerprintMatch: true; requireIdempotencyKeyMatch: true; requireProjectScopedMemory: true; rejectGlobalMemory: true; rejectCriticalCandidateBlockers: true; rejectUnsafeFlags: true; requireNoSecrets: true; requireNoRawEvidence: true; minimizeReadPayload: true; allowFullMemoryRecordReadback: true; allowCanonicalPayloadReadback: false; allowContextAssembly: false; allowCodexTaskCreation: false; forbidEmbeddingsCreation: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; forbidRecordMutation: true; forbidMetadataMutation: true; forbidIndexMutation: true }
export interface FactoryMemoryReadRuntimeInput { memoryReadAdmissionResult: FactoryMemoryReadAdmissionResult; storageRoot: string; executedAt: string; executedBy: string; policy?: Partial<FactoryMemoryReadRuntimePolicy>; maxRecords?: number; requireMetadataReadback?: boolean }
export interface FactoryMemoryReadRuntimeCheck { checkId: string; passed: boolean; message: string }
export interface FactoryMemoryReadRuntimeBlocker { blockerId: string; readItemId?: string; message: string }
export interface FactoryMemoryReadRuntimeWarning { warningId: string; readItemId?: string; message: string }
export interface FactoryMemoryReadRuntimeMetadataReadback { metadataKind: string; metadataVersion: string; memoryRecordId: string; memoryRecordKind: string; namespace: string; projectNamespace: string; fingerprint: string; idempotencyKey: string; logicalTarget: string; writtenAt: string; writtenBy: string; notExecutable: true; embeddingsCreated: false; codexTaskCreated: false; globalPromotionAllowed: false; projectCreated: false; repositoryCreated: false; deployed: false }
export interface FactoryMemoryReadRuntimeReadResult { exists: boolean; parsed: boolean; verified: boolean; sanitizedError?: string }
export interface FactoryMemoryReadRuntimeReadItem { readItemId: string; sourceReadCandidateId: string; memoryRecordId: string; memoryRecordKind: string; memoryRecordVersion: string; namespace: string; projectNamespace: string; logicalTarget: string; metadataLogicalTarget: string; fingerprint: string; idempotencyKey: string; readStatus: FactoryMemoryReadRuntimeReadStatus; safeMemoryRecord?: Record<string, unknown>; metadataReadback?: FactoryMemoryReadRuntimeMetadataReadback; readResult: FactoryMemoryReadRuntimeReadResult; readbackChecks: FactoryMemoryReadRuntimeCheck[]; warnings: FactoryMemoryReadRuntimeWarning[]; blockers: FactoryMemoryReadRuntimeBlocker[]; containsFullMemoryRecord: boolean; containsCanonicalPayload: false; containsRawEvidence: false; containsSecrets: false; canAssembleContext: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateEmbeddings: false; canCreateProject: false; canCreateRepository: false; canDeploy: false }
export interface FactoryMemoryReadRuntimeResult { runtimeReadId: string; runtimeReadKind: FactoryMemoryReadRuntimeKind; runtimeReadVersion: FactoryMemoryReadRuntimeVersion; executedAt: string; executedBy: string; sourceReadAdmissionId: string; readPurpose: string; status: FactoryMemoryReadRuntimeStatus; readItems: FactoryMemoryReadRuntimeReadItem[]; recordsRead: number; recordsBlocked: number; recordsMissing: number; checks: FactoryMemoryReadRuntimeCheck[]; blockers: FactoryMemoryReadRuntimeBlocker[]; warnings: FactoryMemoryReadRuntimeWarning[]; canAssembleContext: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateEmbeddings: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryReadRuntimeValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryMemoryReadRuntimeSummary { runtimeReadId: string; sourceReadAdmissionId: string; readPurpose: string; status: FactoryMemoryReadRuntimeStatus; recordsRead: number; recordsBlocked: number; recordsMissing: number; namespaces: string[]; canAssembleContext: false; canCreateCodexTask: false; canCreateEmbeddings: false; recommendedNextStep: string }
