import type { FactoryMemoryReadRuntimeResult } from '../memory-read-runtime/index.ts'

export type FactoryMemoryContextAssemblyVersion = '1.0'
export type FactoryMemoryContextAssemblyKind = 'factory-memory-context-assembly'
export type FactoryMemoryContextPurpose = 'jefe_review_context' | 'factory_planning_context' | 'memory_audit_context' | 'codex_task_context_candidate' | 'human_review_context'
export type FactoryMemoryContextScope = 'project'
export type FactoryMemoryContextItemStatus = 'candidate' | 'warning_candidate' | 'blocked' | 'rejected'
export type FactoryMemoryContextPackageStatus = 'candidate_not_approved' | 'blocked' | 'rejected' | 'human_review_required'
export type FactoryMemoryContextAssemblyDecision = 'blocked' | 'reject_context_assembly' | 'request_memory_read_repair' | 'human_review_required' | 'approve_context_package_candidate'
export interface FactoryMemoryContextAssemblyPolicy { requireReadRuntimeResult: true; requireSuccessfulReadItems: true; requireProjectScopedMemory: true; rejectGlobalMemoryByDefault: true; rejectBlockedReadItems: true; rejectMissingFingerprint: true; rejectMissingIdempotencyKey: true; rejectCanonicalPayload: true; rejectRawEvidence: true; rejectSecrets: true; rejectPromptInstructions: true; requireSafeReferencesOnly: true; requireLineage: true; requireFreshness: false; allowWarningReadItems: true; allowMinimalFactsOnly: true; maxItemsDefault: number; maxApproxCharsDefault: number; requireHumanReviewForCodexTaskContextCandidate: true; allowCodexTaskCreation: false; allowCodexExecution: false; allowEmbeddingsCreation: false; allowProjectCreation: false; allowRepositoryCreation: false; allowDeploy: false }
export interface FactoryMemoryContextAssemblyInput { memoryReadRuntimeResult: FactoryMemoryReadRuntimeResult; assembledAt: string; assembledBy: string; contextPurpose: FactoryMemoryContextPurpose; projectNamespace?: string; maxItems?: number; maxApproxChars?: number; allowedMemoryRecordKinds?: string[]; policy?: Partial<FactoryMemoryContextAssemblyPolicy>; humanReviewRef?: string }
export interface FactoryMemoryContextAssemblyCheck { checkId: string; passed: boolean; message: string }
export interface FactoryMemoryContextAssemblyBlocker { blockerId: string; readItemId?: string; message: string }
export interface FactoryMemoryContextAssemblyWarning { warningId: string; readItemId?: string; message: string }
export interface FactoryMemoryContextItemCandidate { contextItemId: string; sourceReadItemId: string; memoryRecordId: string; memoryRecordKind: string; memoryRecordVersion: string; namespace: string; projectNamespace: string; fingerprint: string; idempotencyKey: string; contextPurpose: FactoryMemoryContextPurpose; contextScope: FactoryMemoryContextScope; status: FactoryMemoryContextItemStatus; title: string; summary: string; facts: unknown; safeReferences: Array<Record<string, string>>; lineage: Record<string, unknown>; freshness: Record<string, unknown>; retention: Record<string, unknown>; relevance: number; priority: number; approxChars: number; warnings: string[]; blockers: string[]; containsFullMemoryRecord: false; containsCanonicalPayload: false; containsRawEvidence: false; containsSecrets: false; containsPromptInstructions: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateEmbeddings: false; canCreateProject: false; canCreateRepository: false; canDeploy: false }
export interface FactoryMemoryContextPackageCandidate { contextPackageId: string; contextPackageKind: FactoryMemoryContextAssemblyKind; contextPackageVersion: FactoryMemoryContextAssemblyVersion; contextPurpose: FactoryMemoryContextPurpose; projectNamespace: string; items: FactoryMemoryContextItemCandidate[]; itemCount: number; approxChars: number; maxApproxChars: number; sourceReadRuntimeId: string; sourceReadAdmissionId: string; assemblyNotes: string[]; warnings: FactoryMemoryContextAssemblyWarning[]; blockers: FactoryMemoryContextAssemblyBlocker[]; status: FactoryMemoryContextPackageStatus; contextAssemblyStatus: 'candidate_not_approved'; codexTaskStatus: 'not_allowed'; codexExecutionStatus: 'not_allowed'; embeddingsStatus: 'not_allowed'; deployStatus: 'not_allowed'; recommendedNextStep: string }
export interface FactoryMemoryContextAssemblySummary { assemblyId: string; sourceReadRuntimeId: string; contextPurpose: FactoryMemoryContextPurpose; decision: FactoryMemoryContextAssemblyDecision; status: string; itemCount: number; approxChars: number; namespaces: string[]; canCreateCodexTask: false; canExecuteCodex: false; recommendedNextStep: string }
export interface FactoryMemoryContextAssemblyResult { assemblyId: string; assemblyKind: FactoryMemoryContextAssemblyKind; assemblyVersion: FactoryMemoryContextAssemblyVersion; assembledAt: string; assembledBy: string; sourceReadRuntimeId: string; sourceReadAdmissionId: string; contextPurpose: FactoryMemoryContextPurpose; decision: FactoryMemoryContextAssemblyDecision; status: 'blocked' | 'rejected' | 'repair_required' | 'human_review_required' | 'context_package_candidate_ready'; packageCandidate?: FactoryMemoryContextPackageCandidate; rejectedReadItems: string[]; blockedReadItems: string[]; checks: FactoryMemoryContextAssemblyCheck[]; blockers: FactoryMemoryContextAssemblyBlocker[]; warnings: FactoryMemoryContextAssemblyWarning[]; summary: FactoryMemoryContextAssemblySummary; canCreateCodexTask: false; canExecuteCodex: false; canCreateEmbeddings: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryContextAssemblyValidationResult { ok: boolean; errors: string[]; warnings: string[] }

