import { FACTORY_MEMORY_CONTEXT_ASSEMBLY_KIND, FACTORY_MEMORY_CONTEXT_ASSEMBLY_VERSION, createFactoryMemoryContextAssemblyPolicy } from './memory-context-assembly.defaults.ts'
import type { FactoryMemoryContextAssemblyInput, FactoryMemoryContextAssemblyResult, FactoryMemoryContextItemCandidate } from './memory-context-assembly.types.ts'

const token = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'unknown'
const forbiddenKey = /secret|token|password|credential|apikey|api_key|raw.?evidence|canonical.?payload|prompt.?instruction/i
const approx = (value: unknown) => JSON.stringify(value ?? '').length
const safeString = (value: unknown, max = 600): string => String(value ?? '').slice(0, max)
const hasForbidden = (value: unknown): boolean => Array.isArray(value) ? value.some(hasForbidden) : Boolean(value && typeof value === 'object' && Object.entries(value as Record<string, unknown>).some(([key, item]) => {
  if (!forbiddenKey.test(key)) return hasForbidden(item)
  if (typeof item === 'boolean') return item
  if (item === undefined || item === null) return false
  if (typeof item === 'string') return item.trim().length > 0
  return true
}))
const minimize = (value: unknown, maxString = 800): unknown => {
  if (typeof value === 'string') return value.length > maxString ? `${value.slice(0, maxString)}...` : value
  if (typeof value === 'number' || typeof value === 'boolean' || value === null) return value
  if (Array.isArray(value)) return value.slice(0, 12).map((item) => minimize(item, maxString))
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([key, item]) => item !== undefined && !forbiddenKey.test(key)).slice(0, 24).map(([key, item]) => [key, minimize(item, maxString)]))
  return undefined
}
const safeRefs = (refs: unknown, fallback: { logicalTarget?: string; metadataLogicalTarget?: string; fingerprint: string; idempotencyKey: string; sourceReadItemId: string; sourceReadAdmissionId: string; sourceReadRuntimeId: string }) => {
  const values = Array.isArray(refs) ? refs : []
  const mapped = values.map((ref) => ref && typeof ref === 'object' ? Object.fromEntries(Object.entries(ref as Record<string, unknown>).filter(([key, value]) => typeof value === 'string' && !String(value).match(/^[a-z]:[\\/]|^\//iu) && !String(value).includes('..') && /path|target|ref|fingerprint|idempotency/i.test(key)).map(([key, value]) => [key, String(value)])) : {}).filter((ref) => Object.keys(ref).length)
  return [...mapped, { logicalTarget: fallback.logicalTarget ?? '', metadataLogicalTarget: fallback.metadataLogicalTarget ?? '', fingerprint: fallback.fingerprint, idempotencyKey: fallback.idempotencyKey, sourceReadItemId: fallback.sourceReadItemId, sourceReadAdmissionId: fallback.sourceReadAdmissionId, sourceReadRuntimeId: fallback.sourceReadRuntimeId }]
}
const invalidReadItem = (item: FactoryMemoryContextAssemblyInput['memoryReadRuntimeResult']['readItems'][number]) => item.readStatus !== 'read' || item.blockers.length > 0 || !item.safeMemoryRecord || !item.fingerprint || !item.idempotencyKey || item.containsCanonicalPayload || item.containsRawEvidence || item.containsSecrets || item.canAssembleContext || item.canCreateCodexTask || item.canExecuteCodex || item.canCreateEmbeddings || item.canCreateProject || item.canCreateRepository || item.canDeploy || hasForbidden(item.safeMemoryRecord)

export function createFactoryMemoryContextAssemblyPlan(input: FactoryMemoryContextAssemblyInput): FactoryMemoryContextAssemblyResult {
  const policy = createFactoryMemoryContextAssemblyPolicy(input?.policy); const runtime = input?.memoryReadRuntimeResult; const assembledAt = input?.assembledAt ?? ''; const assembledBy = input?.assembledBy ?? ''; const contextPurpose = input?.contextPurpose ?? 'human_review_context'; const assemblyId = `memory-context-assembly:${token(runtime?.runtimeReadId ?? 'missing-runtime')}:${token(assembledAt)}`
  const checks = [{ checkId: 'runtime-present', passed: Boolean(runtime), message: 'Memory read runtime result is required.' }, { checkId: 'assembler-present', passed: Boolean(assembledAt && assembledBy), message: 'assembledAt and assembledBy are required.' }, { checkId: 'runtime-success', passed: Boolean(runtime && ['success', 'partial'].includes(runtime.status)), message: 'Runtime status must be success or partial.' }]
  const blockers = checks.filter((check) => !check.passed).map((check) => ({ blockerId: check.checkId, message: check.message })); const warnings: FactoryMemoryContextAssemblyResult['warnings'] = []; const rejectedReadItems: string[] = []; const blockedReadItems: string[] = []
  if (!runtime || blockers.length) return { assemblyId, assemblyKind: FACTORY_MEMORY_CONTEXT_ASSEMBLY_KIND, assemblyVersion: FACTORY_MEMORY_CONTEXT_ASSEMBLY_VERSION, assembledAt, assembledBy, sourceReadRuntimeId: runtime?.runtimeReadId ?? '', sourceReadAdmissionId: runtime?.sourceReadAdmissionId ?? '', contextPurpose, decision: 'blocked', status: 'blocked', rejectedReadItems, blockedReadItems, checks, blockers, warnings, summary: { assemblyId, sourceReadRuntimeId: runtime?.runtimeReadId ?? '', contextPurpose, decision: 'blocked', status: 'blocked', itemCount: 0, approxChars: 0, namespaces: [], canCreateCodexTask: false, canExecuteCodex: false, recommendedNextStep: 'Repair memory read runtime prerequisites before context assembly.' }, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: 'Repair memory read runtime prerequisites before context assembly.' }
  if (contextPurpose === 'codex_task_context_candidate' && !input.humanReviewRef?.trim()) { blockers.push({ blockerId: 'human-review-required', message: 'Human review is required for Codex task context candidates.' }); return { assemblyId, assemblyKind: FACTORY_MEMORY_CONTEXT_ASSEMBLY_KIND, assemblyVersion: FACTORY_MEMORY_CONTEXT_ASSEMBLY_VERSION, assembledAt, assembledBy, sourceReadRuntimeId: runtime.runtimeReadId, sourceReadAdmissionId: runtime.sourceReadAdmissionId, contextPurpose, decision: 'human_review_required', status: 'human_review_required', rejectedReadItems, blockedReadItems, checks, blockers, warnings, summary: { assemblyId, sourceReadRuntimeId: runtime.runtimeReadId, contextPurpose, decision: 'human_review_required', status: 'human_review_required', itemCount: 0, approxChars: 0, namespaces: [], canCreateCodexTask: false, canExecuteCodex: false, recommendedNextStep: 'Obtain human review before preparing a Codex Task Contract Gate context candidate.' }, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: 'Obtain human review before preparing a Codex Task Contract Gate context candidate.' } }
  const maxItems = input.maxItems ?? policy.maxItemsDefault; const maxApproxChars = input.maxApproxChars ?? policy.maxApproxCharsDefault
  const items = runtime.readItems.filter((item) => {
    const allowed = !input.allowedMemoryRecordKinds?.length || input.allowedMemoryRecordKinds.includes(item.memoryRecordKind); const projectMatch = !input.projectNamespace || input.projectNamespace === item.projectNamespace
    if (!allowed || !projectMatch || invalidReadItem(item)) { (item.readStatus === 'read' ? blockedReadItems : rejectedReadItems).push(item.readItemId); return false }
    return true
  }).map((item): FactoryMemoryContextItemCandidate => {
    const record = item.safeMemoryRecord ?? {}; const facts = minimize((record as Record<string, unknown>).canonicalFacts); const freshness = minimize((record as Record<string, unknown>).freshness ?? { freshnessStatus: 'unknown' }) as Record<string, unknown>; const retention = minimize((record as Record<string, unknown>).retentionPolicy ?? (record as Record<string, unknown>).retention ?? { readOnly: true }) as Record<string, unknown>; const priority = Number((record as Record<string, unknown>).priority ?? 5); const contextItemId = `context-item:${token(item.memoryRecordId)}:${token(item.fingerprint)}`
    const candidate: FactoryMemoryContextItemCandidate = { contextItemId, sourceReadItemId: item.readItemId, memoryRecordId: item.memoryRecordId, memoryRecordKind: item.memoryRecordKind, memoryRecordVersion: item.memoryRecordVersion, namespace: item.namespace, projectNamespace: item.projectNamespace, fingerprint: item.fingerprint, idempotencyKey: item.idempotencyKey, contextPurpose, contextScope: 'project', status: item.warnings.length ? 'warning_candidate' : 'candidate', title: safeString((record as Record<string, unknown>).title), summary: safeString((record as Record<string, unknown>).summary, 1000), facts, safeReferences: safeRefs((record as Record<string, unknown>).references, { logicalTarget: item.logicalTarget, metadataLogicalTarget: item.metadataLogicalTarget, fingerprint: item.fingerprint, idempotencyKey: item.idempotencyKey, sourceReadItemId: item.readItemId, sourceReadAdmissionId: runtime.sourceReadAdmissionId, sourceReadRuntimeId: runtime.runtimeReadId }), lineage: { ...((minimize((record as Record<string, unknown>).lineage) as Record<string, unknown>) ?? {}), memoryRecordId: item.memoryRecordId, sourceReadItemId: item.readItemId, sourceReadAdmissionId: runtime.sourceReadAdmissionId, sourceReadRuntimeId: runtime.runtimeReadId }, freshness, retention, relevance: 1, priority, approxChars: 0, warnings: item.warnings.map((warning) => warning.message), blockers: [], containsFullMemoryRecord: false, containsCanonicalPayload: false, containsRawEvidence: false, containsSecrets: false, containsPromptInstructions: false, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false }
    return { ...candidate, approxChars: approx({ title: candidate.title, summary: candidate.summary, facts: candidate.facts, safeReferences: candidate.safeReferences, lineage: candidate.lineage }) }
  }).sort((a, b) => a.priority - b.priority || String(b.freshness.freshnessStatus ?? '').localeCompare(String(a.freshness.freshnessStatus ?? '')) || a.memoryRecordKind.localeCompare(b.memoryRecordKind) || a.memoryRecordId.localeCompare(b.memoryRecordId))
  const selected: FactoryMemoryContextItemCandidate[] = []; let total = 0
  for (const item of items.slice(0, maxItems)) { if (total + item.approxChars > maxApproxChars) { warnings.push({ warningId: 'context-budget-applied', readItemId: item.sourceReadItemId, message: 'Context budget applied before adding this item.' }); continue } selected.push(item); total += item.approxChars }
  if (!selected.length) { const next = runtime.status === 'success' || runtime.status === 'partial' ? 'Repair memory read items or filters before context assembly.' : 'Repeat Memory Read Runtime after memory repair.'; return { assemblyId, assemblyKind: FACTORY_MEMORY_CONTEXT_ASSEMBLY_KIND, assemblyVersion: FACTORY_MEMORY_CONTEXT_ASSEMBLY_VERSION, assembledAt, assembledBy, sourceReadRuntimeId: runtime.runtimeReadId, sourceReadAdmissionId: runtime.sourceReadAdmissionId, contextPurpose, decision: runtime.status === 'success' || runtime.status === 'partial' ? 'reject_context_assembly' : 'request_memory_read_repair', status: runtime.status === 'success' || runtime.status === 'partial' ? 'rejected' : 'repair_required', rejectedReadItems, blockedReadItems, checks, blockers, warnings, summary: { assemblyId, sourceReadRuntimeId: runtime.runtimeReadId, contextPurpose, decision: 'reject_context_assembly', status: 'rejected', itemCount: 0, approxChars: 0, namespaces: [], canCreateCodexTask: false, canExecuteCodex: false, recommendedNextStep: next }, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: next } }
  const recommendedNextStep = contextPurpose === 'codex_task_context_candidate' ? 'Submit the context package candidate to a future Codex Task Contract Gate after separate approval; Codex remains disabled.' : 'Submit the context package candidate to a future Context Approval Gate before any downstream handoff.'
  const packageCandidate = { contextPackageId: `context-package:${token(runtime.runtimeReadId)}:${token(contextPurpose)}`, contextPackageKind: FACTORY_MEMORY_CONTEXT_ASSEMBLY_KIND, contextPackageVersion: FACTORY_MEMORY_CONTEXT_ASSEMBLY_VERSION, contextPurpose, projectNamespace: input.projectNamespace ?? selected[0]?.projectNamespace ?? '', items: selected, itemCount: selected.length, approxChars: total, maxApproxChars, sourceReadRuntimeId: runtime.runtimeReadId, sourceReadAdmissionId: runtime.sourceReadAdmissionId, assemblyNotes: ['Candidate package only; not a final prompt and not executable.'], warnings, blockers: [], status: 'candidate_not_approved' as const, contextAssemblyStatus: 'candidate_not_approved' as const, codexTaskStatus: 'not_allowed' as const, codexExecutionStatus: 'not_allowed' as const, embeddingsStatus: 'not_allowed' as const, deployStatus: 'not_allowed' as const, recommendedNextStep }
  const summary = { assemblyId, sourceReadRuntimeId: runtime.runtimeReadId, contextPurpose, decision: 'approve_context_package_candidate' as const, status: 'context_package_candidate_ready', itemCount: selected.length, approxChars: total, namespaces: [...new Set(selected.map((item) => item.namespace))], canCreateCodexTask: false as const, canExecuteCodex: false as const, recommendedNextStep }
  return { assemblyId, assemblyKind: FACTORY_MEMORY_CONTEXT_ASSEMBLY_KIND, assemblyVersion: FACTORY_MEMORY_CONTEXT_ASSEMBLY_VERSION, assembledAt, assembledBy, sourceReadRuntimeId: runtime.runtimeReadId, sourceReadAdmissionId: runtime.sourceReadAdmissionId, contextPurpose, decision: 'approve_context_package_candidate', status: 'context_package_candidate_ready', packageCandidate, rejectedReadItems, blockedReadItems, checks, blockers, warnings, summary, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep }
}
