export type FactoryMemoryRegistryVersion = '1.0'
export type FactoryMemoryRegistryKind = 'factory-memory-registry'
export type FactoryMemoryRegistryEntryStatus = 'ready' | 'warning' | 'blocked' | 'orphaned'
export interface FactoryMemoryRegistryInput { storageRoot: string; generatedAt: string; generatedBy: string; policy?: Partial<FactoryMemoryRegistryPolicy> }
export interface FactoryMemoryRegistryPolicy { requireStorageRootInsideCodexTemp: true; requireMetadataForEntry: true; requireRecordReadback: true; requireProjectMemoryIndex: false; requireFingerprint: true; requireIdempotencyKey: true; requireNotExecutable: true; requireEmbeddingsNotCreated: true; requireCodexTaskNotCreated: true; requireProjectNotCreated: true; requireRepositoryNotCreated: true; requireDeployNotAllowed: true; detectDuplicateFingerprints: true; detectDuplicateIdempotencyKeys: true; detectConflictingNamespaces: true; detectOrphanMetadata: true; detectOrphanRecords: true; forbidPathTraversal: true; forbidAbsoluteLogicalTargets: true; allowRegistryIndexWrite: true; registryIndexWriteUnderStorageRootOnly: true; forbidEmbeddingsCreation: true; forbidCodexTaskCreation: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true }
export interface FactoryMemoryRegistryMetadata { metadataKind: string; metadataVersion: string; runtimePersistenceId: string; sourcePersistenceId: string; sourceApprovalId: string; sourceAdmissionId: string; memoryRecordId: string; memoryRecordKind: string; namespace: string; projectNamespace: string; fingerprint: string; idempotencyKey: string; logicalTarget: string; writtenAt: string; writtenBy: string }
export interface FactoryMemoryRegistryEntry { registryEntryId: string; memoryRecordId: string; memoryRecordKind: string; memoryRecordVersion: string; namespace: string; projectNamespace: string; projectSlugOrId: string; logicalTarget: string; metadataLogicalTarget: string; absoluteTargetPath?: string; absoluteMetadataPath?: string; fingerprint: string; idempotencyKey: string; sourcePersistenceId: string; sourceApprovalId: string; sourceAdmissionId: string; writtenAt: string; writtenBy: string; status: FactoryMemoryRegistryEntryStatus; validation: { ok: boolean; errors: string[]; warnings: string[] }; notExecutable: true; embeddingsCreated: false; codexTaskCreated: false; canExecuteCodex: false; globalPromotionAllowed: false; projectCreated: false; repositoryCreated: false; deployed: false; warnings: string[]; blockers: string[] }
export interface FactoryMemoryRegistryProjectIndexRef { projectNamespace: string; logicalPath: string; absolutePath?: string; valid: boolean; recordsCount: number; warnings: string[] }
export interface FactoryMemoryRegistryDuplicate { field: 'fingerprint' | 'idempotencyKey'; value: string; registryEntryIds: string[] }
export interface FactoryMemoryRegistryConflict { field: 'memoryRecordId' | 'namespace' | 'projectNamespace'; value: string; registryEntryIds: string[]; details: string }
export interface FactoryMemoryRegistryOrphan { orphanKind: 'metadata_without_record' | 'record_without_metadata'; logicalPath: string; relatedLogicalPath: string; projectSlugOrId: string }
export interface FactoryMemoryRegistrySummary { totalEntries: number; statusCounts: Record<string, number>; projectIndexesCount: number; duplicateCount: number; conflictCount: number; orphanCount: number; readyCount: number; blockedCount: number; recommendedNextStep: string }
export interface FactoryMemoryRegistryIndex { registryKind: FactoryMemoryRegistryKind; registryVersion: FactoryMemoryRegistryVersion; generatedAt: string; generatedBy: string; storageRoot: string; entries: FactoryMemoryRegistryEntry[]; projectIndexes: FactoryMemoryRegistryProjectIndexRef[]; duplicates: FactoryMemoryRegistryDuplicate[]; conflicts: FactoryMemoryRegistryConflict[]; orphans: FactoryMemoryRegistryOrphan[]; warnings: string[]; blockers: string[]; summary: FactoryMemoryRegistrySummary; recommendedNextStep: string }
export interface FactoryMemoryRegistryQuery { byProjectNamespace?: string; byNamespace?: string; byMemoryRecordId?: string; byMemoryRecordKind?: string; byFingerprint?: string; byIdempotencyKey?: string; byStatus?: FactoryMemoryRegistryEntryStatus; latestOnly?: boolean; readyForNextStepOnly?: boolean }
export interface FactoryMemoryRegistryQueryResult { query: FactoryMemoryRegistryQuery; matches: FactoryMemoryRegistryEntry[]; warnings: string[]; blockers: string[]; summary: { matchesCount: number; namespaces: string[]; statuses: Record<string, number>; recommendedNextStep: string }; canCreateCodexTask: false; canExecuteCodex: false; canCreateEmbeddings: false; canCreateProject: false; canCreateRepository: false; canDeploy: false }
export interface FactoryMemoryRegistryValidationResult { ok: boolean; errors: string[]; warnings: string[] }
