import type { FactoryHermesRuntimeSelectionPlanningKind, FactoryHermesRuntimeSelectionPlanningPolicy, FactoryHermesRuntimeSelectionPlanningVersion } from './hermes-runtime-selection-planning.types.ts'

export const FACTORY_HERMES_RUNTIME_SELECTION_PLANNING_KIND: FactoryHermesRuntimeSelectionPlanningKind = 'factory-hermes-runtime-selection-planning'
export const FACTORY_HERMES_RUNTIME_SELECTION_PLANNING_VERSION: FactoryHermesRuntimeSelectionPlanningVersion = '1.0'
export const FACTORY_HERMES_RUNTIME_SELECTION_PLANNING_NEXT_STEP = 'Proceed to Factory Hermes Runtime Selection Decision Gate v1; no final values are selected now.'
export const DEFAULT_FACTORY_HERMES_RUNTIME_SELECTION_PLANNING_POLICY: FactoryHermesRuntimeSelectionPlanningPolicy = {
  requireResearchExecutionApprovalBlocked: true, requireRuntimeSelectionRequirements: true, requirePromptCandidateFromPromptPolicy: true, requireProviderCandidatesFromProviderPolicy: true, requireCredentialRefsOnly: true, requireNoSecretValues: true, requireNoFinalSelectionInThisGate: true, requireHumanDecisionPack: true, requireRuntimeSelectionDecisionNext: true, forbidExecutionInThisGate: true, forbidFinalRuntimeSelectionInThisGate: true, forbidPromptPassingInThisGate: true, forbidHermesExecutionInThisGate: true, forbidResearchExecutionInThisGate: true, forbidNetworkInThisGate: true, forbidModelCallsInThisGate: true, forbidCredentialUseInThisGate: true, forbidToolsetEnablementInThisGate: true, forbidFilesystemMutationInThisGate: true, forbidDeployInThisGate: true,
}
export const RUNTIME_SELECTION_NOT_AUTHORIZED_ACTIONS = ['select_final_runtime_values_now', 'approve_execution_now', 'approve_runtime_adapter_now', 'execute_oneshot_now', 'pass_prompt_now', 'run_research_now', 'execute_hermes_now', 'call_models_now', 'use_network_now', 'access_credentials_now', 'read_env_secrets_now', 'enable_toolsets_now', 'mutate_filesystem_now', 'create_runtime_run_root_now', 'ingest_real_output_now', 'promote_findings_now', 'execute_uv_now', 'execute_python_now', 'execute_pip_now', 'execute_setup_py_now', 'deploy_now']
