import { FACTORY_HERMES_RESEARCH_EXECUTION_PLANNING_QUESTIONS, FACTORY_HERMES_RESEARCH_EXECUTION_REQUIRED_FUTURE_GATES, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_ADAPTER_RETRY_REF, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_INGESTION_REF, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_KIND, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_NEXT_STEP, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_VERSION } from './hermes-research-jefe-review-v2.defaults.ts'
import type { FactoryHermesResearchJefeReviewV2Input, FactoryHermesResearchJefeReviewV2Result } from './hermes-research-jefe-review-v2.types.ts'

function base(input: FactoryHermesResearchJefeReviewV2Input): FactoryHermesResearchJefeReviewV2Result {
  const i = input.researchResultIngestionV2Result || {}
  return { jefeReviewId: `hermes-research-jefe-review-v2:75b300f:${input.reviewedAt}`, jefeReviewKind: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_KIND, jefeReviewVersion: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_VERSION, reviewedAt: input.reviewedAt, reviewedBy: input.reviewedBy, toolId: 'hermes_agent', commandName: i.commandName || '', pythonEntrypoint: i.pythonEntrypoint || '', executableRef: i.executableRef || '', executableSha256: i.executableSha256 || '', helpProbeStatus: i.helpProbeStatus || '', ingestionClassification: i.classification || '', ingestionNormalizedOutcome: i.normalizedOutcome || '', checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_ingestion_v2', canProceedToResearchExecutionPlanning: false, canRunResearchNow: false, canExecuteHermesNow: false, canTreatHelpAsResearchResult: false, canTreatAsResearchResult: false, canUseFindings: false, canUseNetworkNow: false, canUseCredentials: false, canCallModelsNow: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_NEXT_STEP }
}
function hasBoundaryViolation(i: any): boolean { return i.canExecuteHermes !== false || i.canUseNetwork !== false || i.canUseCredentials !== false || i.canCallModels !== false || i.canUseFindings !== false || i.canTreatAsResearchResult !== false }
function makeReceipt(id: string, input: FactoryHermesResearchJefeReviewV2Input, i: any) { return { receiptId: `${id}:receipt`, jefeReviewId: id, toolId: 'hermes_agent' as const, reviewedBy: input.reviewedBy, reviewedAt: input.reviewedAt, humanApprovalRef: input.humanApprovalRef || '', ingestionDecision: i.decision, helpProbeStatus: i.helpProbeStatus, classification: i.classification, normalizedOutcome: i.normalizedOutcome, decision: 'hermes_research_jefe_review_v2_approved_research_execution_planning' as const, scope: 'hermes_research_jefe_review_v2_only' as const, approvedNextGate: 'Factory Hermes Research Execution Planning Gate v1' as const, limitations: ['Approval is for planning only.', 'No research runtime, prompt passing, model calls, network or credentials are authorized now.', 'Help output remains operational evidence only and cannot be findings.'], notAuthorizedActions: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_NOT_AUTHORIZED_ACTIONS } }
function makeRecord(id: string, i: any) { return { recordId: `${id}:record`, jefeReviewId: id, toolId: 'hermes_agent' as const, commandName: 'hermes' as const, pythonEntrypoint: 'hermes_cli.main:main' as const, executableRef: i.executableRef, executableSha256: i.executableSha256 || '', ingestionV2ResultRef: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_INGESTION_REF, adapterRetryResultRef: FACTORY_HERMES_RESEARCH_JEFE_REVIEW_V2_ADAPTER_RETRY_REF, ingestionDecision: i.decision, helpProbeStatus: i.helpProbeStatus, classification: i.classification, normalizedOutcome: i.normalizedOutcome, jefeAssessment: 'Hermes entrypoint is operational at help-probe level only.', operationalConclusion: 'Help probe succeeded and proves CLI is callable under boundary.', researchConclusion: 'No research was performed and no findings may be used.', approvedNextPlanning: 'Factory Hermes Research Execution Planning Gate v1' as const, safetyConclusion: 'no network, no credentials, no model calls, no research prompt, no uv/pip/python/setup execution', canProceedToResearchExecutionPlanning: true, canRunResearchNow: false as const, canExecuteHermesNow: false as const, canUseFindings: false as const } }
function makeEnvelope(id: string, i: any) { return { envelopeId: `${id}:research-execution-planning-envelope`, jefeReviewId: id, toolId: 'hermes_agent' as const, commandName: 'hermes' as const, pythonEntrypoint: 'hermes_cli.main:main' as const, executableRef: i.executableRef, executableSha256: i.executableSha256 || '', selectedInterface: { interfaceType: 'package_entrypoint' as const, commandName: 'hermes' as const, pythonEntrypoint: 'hermes_cli.main:main' as const }, currentVerifiedCapability: 'help_probe_only' as const, currentVerifiedCommand: 'hermes.exe --help' as const, allowedNextGate: 'Factory Hermes Research Execution Planning Gate v1' as const, researchExecutionAllowedNow: false as const, hermesExecutionAllowedNow: false as const, networkAllowedNow: false as const, credentialsAllowedNow: false as const, modelCallsAllowedNow: false as const, promptPassingAllowedNow: false as const, requiredPlanningQuestions: FACTORY_HERMES_RESEARCH_EXECUTION_PLANNING_QUESTIONS, requiredFutureGates: FACTORY_HERMES_RESEARCH_EXECUTION_REQUIRED_FUTURE_GATES } }
export function evaluateFactoryHermesResearchJefeReviewV2(input: FactoryHermesResearchJefeReviewV2Input): FactoryHermesResearchJefeReviewV2Result {
  const i = input.researchResultIngestionV2Result
  const out = base(input)
  if (!i) return { ...out, blockers: [{ blockerId: 'blocked_missing_ingestion_v2', message: 'Research result ingestion v2 result is required.' }] }
  if (!input.humanApprovalRef) return { ...out, status: 'human_review_required', decision: 'blocked_missing_human_approval', blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] }
  if (i.status !== 'ingested' || i.canProceedToResearchJefeReviewV2 !== true) return { ...out, decision: 'blocked_ingestion_v2_not_reviewable', blockers: [{ blockerId: 'blocked_ingestion_v2_not_reviewable', message: 'Ingestion v2 is not reviewable.' }] }
  if (i.classification !== 'controlled_help_probe_success' || i.normalizedOutcome !== 'hermes_help_probe_succeeded' || i.helpProbeStatus !== 'succeeded') return { ...out, decision: 'blocked_help_probe_not_success', blockers: [{ blockerId: 'blocked_help_probe_not_success', message: 'Help probe success is required.' }] }
  if (i.canTreatAsResearchResult !== false || i.canUseFindings !== false) return { ...out, decision: 'blocked_help_probe_claims_research_result', blockers: [{ blockerId: 'blocked_help_probe_claims_research_result', message: 'Help probe cannot be research result or findings.' }] }
  if (hasBoundaryViolation(i)) return { ...out, decision: 'blocked_boundary_violation_detected', blockers: [{ blockerId: 'blocked_boundary_violation_detected', message: 'Ingestion v2 safety boundary was violated.' }] }
  const id = out.jefeReviewId
  return { ...out, status: 'approved_for_research_execution_planning', decision: 'hermes_research_jefe_review_v2_approved_research_execution_planning', researchJefeReviewV2Receipt: makeReceipt(id, input, i), hermesResearchJefeReviewV2Record: makeRecord(id, i), approvedResearchExecutionPlanningEnvelope: makeEnvelope(id, i), canProceedToResearchExecutionPlanning: true }
}
