const fs = require('node:fs/promises');
const path = require('node:path');
const { resolveFactoryHermesResearchRuntimeBoundaryPaths, assertBoundaryPathContained } = require('./hermes-research-runtime-boundary.path.cjs');

const KIND = 'factory-hermes-research-runtime-boundary';
const VERSION = '1.0';
const NEXT = 'Proceed to Factory Hermes Research Runtime Approval Gate v1; runtime creation and Hermes execution remain forbidden.';
const notAuthorizedActions = ['execute_hermes_now', 'run_hermes_scripts_now', 'execute_selected_interface_now', 'execute_python_now', 'execute_uv_now', 'execute_pip_now', 'execute_setup_py_now', 'call_models_now', 'access_credentials_now', 'use_network_now', 'scrape_now', 'create_runtime_now', 'deploy_now', 'mutate_project_files_now'];
const nextGates = ['Factory Hermes Research Runtime Approval Gate v1', 'Factory Hermes Research Runtime Adapter v1', 'Factory Hermes Research Result Ingestion Gate v1', 'Factory Hermes Research JEFE Review Gate v1'];
async function readJson(file) { return JSON.parse(await fs.readFile(file, 'utf8')); }
function buildContract(id, s) {
  const selected = s.selectedInterface;
  const installRoot = s.selectedHermesResearchRuntimeInterfaceEnvelope?.installRootRef || '.codex-temp/external-tools/hermes-agent/install/75b300f';
  const sourceRoot = s.selectedHermesResearchRuntimeInterfaceEnvelope?.sourceRootRef || selected.futureWorkingDirectory;
  const pyEnv = s.selectedHermesResearchRuntimeInterfaceEnvelope?.pythonEnvRootRef || '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/';
  return { contractId: `${id}:contract`, toolId: 'hermes_agent', auditedHead: s.auditedHead, selectedCandidateId: s.selectedCandidateId, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', futureExecutableCandidateWindows: selected.futureExecutableCandidateWindows, filesystemBoundary: { allowedReadRootsFuture: [sourceRoot, pyEnv.replace(/\/$/, '')], allowedWriteRootsFuture: [`${installRoot}/research-runtime-output/`, `${installRoot}/research-runtime-temp/`], forbiddenRoots: ['repo root except explicit artifacts', '.env', 'user home', 'desktop/documents/downloads', 'Program Files', 'AppData except explicit .codex-temp roots', 'system directories'], projectMutationAllowedNow: false, projectMutationAllowedFuture: false, writeRequiresRuntimeApproval: true }, commandBoundary: { commandsAllowedNow: [], futureCommandCandidate: { executableRef: 'python-env/Scripts/hermes.exe', argsPolicy: 'boundary_defined_only', shell: false, cwd: sourceRoot, timeoutMsDefault: 60000, timeoutMsMax: 300000, stdinPolicy: 'controlled_or_disabled', stdoutPolicy: 'captured_sanitized_truncated', stderrPolicy: 'captured_sanitized_truncated' }, forbiddenCommands: ['shell', 'cmd.exe', 'powershell', 'pip', 'python -m pip', 'setup.py', 'uv pip', 'uv run unrestricted', 'curl', 'wget', 'arbitrary scripts'], noCommandExecutionInThisGate: true }, networkBoundary: { networkAllowedNow: false, networkAllowedFutureDefault: false, futureNetworkRequiresSeparateApproval: true, allowedDomainsFuture: [], blockAllByDefault: true, scrapingAllowedNow: false, scrapingAllowedFutureRequiresApproval: true }, credentialBoundary: { credentialsAllowedNow: false, credentialsAllowedFutureDefault: false, futureCredentialsRequireSeparateApproval: true, envReadAllowedNow: false, envReadAllowedFutureDefault: false, secretNamesAllowedFuture: [] }, modelBoundary: { modelCallsAllowedNow: false, modelCallsAllowedFutureDefault: false, futureModelCallsRequireSeparateApproval: true, allowedProvidersFuture: [], allowedModelsFuture: [] }, ioBoundary: { inputContractFuture: { researchQuestion: 'required', allowedSources: 'required', forbiddenSources: 'required', constraints: 'required', maxRuntimeMs: 'required', outputSchema: 'required' }, outputContractFuture: { structuredFindings: true, evidence: true, warnings: true, confidence: true, rawLogsSanitized: true, exitStatus: true }, rawLogLimitBytes: 262144, stdoutLimitBytes: 131072, stderrLimitBytes: 131072 }, safetyBoundary: { killSwitchRequired: true, timeoutRequired: true, maxRuntimeMsHardLimit: 300000, processTreeKillRequired: true, retryPolicy: 'disabled_by_default', logSanitizationRequired: true, resultIngestionRequired: true, jefeReviewRequired: true }, nextRequiredGates: nextGates };
}
function evaluate(input) {
  const s = input.interfaceSelectionResult;
  const id = `hermes-research-runtime-boundary:75b300f:${input.boundedAt}`;
  const base = { boundaryId: id, boundaryKind: KIND, boundaryVersion: VERSION, boundedAt: input.boundedAt, boundedBy: input.boundedBy, toolId: 'hermes_agent', auditedHead: s?.auditedHead || '', selectedCandidateId: s?.selectedCandidateId || '', selectedInterface: s?.selectedInterface, checks: [], blockers: [], warnings: [], canCreateRuntimeNow: false, canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: NEXT };
  if (!s) return { ...base, status: 'blocked', decision: 'blocked_missing_interface_selection', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_missing_interface_selection', message: 'Interface selection result is required.' }] };
  if (s.status !== 'selected' || s.decision !== 'hermes_research_runtime_interface_selected_for_boundary_planning' || s.canProceedToResearchRuntimeBoundary !== true || s.canExecuteHermes !== false || !s.selectedInterface) return { ...base, status: 'blocked', decision: 'blocked_interface_not_selected', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_interface_not_selected', message: 'Interface is not selected.' }] };
  if (!input.humanApprovalRef) return { ...base, status: 'human_review_required', decision: 'blocked_missing_human_approval', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] };
  const contract = buildContract(id, s);
  const receipt = { receiptId: `${id}:receipt`, boundaryId: id, toolId: 'hermes_agent', auditedHead: s.auditedHead, boundedBy: input.boundedBy, boundedAt: input.boundedAt, humanApprovalRef: input.humanApprovalRef, selectedCandidateId: s.selectedCandidateId, decision: 'hermes_research_runtime_boundary_contract_created', scope: 'hermes_research_runtime_boundary_contract_only', approvedNextGate: 'Factory Hermes Research Runtime Approval Gate v1', limitations: ['Boundary contract only.', 'No runtime is created.', 'No Hermes, Python, uv, network, credentials or model execution.'], notAuthorizedActions };
  return { ...base, status: 'boundary_contract_created', decision: 'hermes_research_runtime_boundary_contract_created', researchRuntimeBoundaryReceipt: receipt, hermesResearchRuntimeBoundaryContract: contract, canProceedToResearchRuntimeApproval: true };
}
async function executeFactoryHermesResearchRuntimeBoundary(input = {}) {
  const paths = resolveFactoryHermesResearchRuntimeBoundaryPaths();
  assertBoundaryPathContained(paths.installRoot, path.join(paths.root, '.codex-temp'));
  assertBoundaryPathContained(paths.boundaryResult, paths.installRoot);
  const interfaceSelectionResult = await readJson(paths.interfaceSelectionResult);
  const result = evaluate({ boundedAt: input.boundedAt || '2026-07-21T18:00:00.000Z', boundedBy: input.boundedBy || 'factory-hermes-research-runtime-boundary-smoke', humanApprovalRef: input.humanApprovalRef || 'human-review/hermes-research-runtime-boundary-v1', interfaceSelectionResult });
  await fs.writeFile(paths.boundaryResult, JSON.stringify(result, null, 2));
  return result;
}
module.exports = { executeFactoryHermesResearchRuntimeBoundary, evaluateFactoryHermesResearchRuntimeBoundary: evaluate };
