import { FACTORY_MEMORY_CONTEXT_APPROVAL_KIND, FACTORY_MEMORY_CONTEXT_APPROVAL_VERSION, createFactoryMemoryContextApprovalPolicy } from './memory-context-approval.defaults.ts'
import type { FactoryMemoryContextApprovalInput, FactoryMemoryContextApprovalResult, FactoryMemoryContextApprovalValidationResult } from './memory-context-approval.types.ts'

const decisions = ['blocked', 'reject_context_package', 'request_context_changes', 'human_review_required', 'approve_context_package_for_handoff_candidate']
const statuses = ['blocked', 'rejected', 'changes_required', 'human_review_required', 'approved_context_candidate']
const hasDanger = (result: FactoryMemoryContextApprovalResult) => Boolean(result.approvedPackageCandidate?.items.some((item) => item.containsFullMemoryRecord || item.containsCanonicalPayload || item.containsRawEvidence || item.containsSecrets || item.containsPromptInstructions || item.canCreateCodexTask || item.canExecuteCodex || item.canCreateEmbeddings || item.canCreateProject || item.canCreateRepository || item.canDeploy))
export function validateFactoryMemoryContextApprovalInput(input: FactoryMemoryContextApprovalInput): FactoryMemoryContextApprovalValidationResult { const errors: string[] = []; const warnings: string[] = []; const policy = createFactoryMemoryContextApprovalPolicy(input?.policy); if (!input?.memoryContextAssemblyResult) errors.push('memoryContextAssemblyResult is required.'); if (!input?.reviewedAt) errors.push('reviewedAt is required.'); if (!input?.reviewedBy) errors.push('reviewedBy is required.'); if (policy.requireHumanApproval && !input?.humanApprovalRef) errors.push('humanApprovalRef is required.'); if (JSON.stringify(input ?? {}).match(/"?(secret|password|token|credential)"?\s*:\s*"[^"]+"/iu)) errors.push('Input appears to contain a secret value.'); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryMemoryContextApprovalResult(result: FactoryMemoryContextApprovalResult): FactoryMemoryContextApprovalValidationResult { const errors: string[] = []; const warnings: string[] = []; if (result?.approvalKind !== FACTORY_MEMORY_CONTEXT_APPROVAL_KIND || result.approvalVersion !== FACTORY_MEMORY_CONTEXT_APPROVAL_VERSION) errors.push('Approval kind/version is invalid.'); if (!result?.approvalId) errors.push('approvalId is required.'); if (!decisions.includes(result?.decision)) errors.push('Decision is invalid.'); if (!statuses.includes(result?.status)) errors.push('Status is invalid.'); if (result.canCreateCodexTask || result.canExecuteCodex || result.canCreateEmbeddings || result.canCreateProject || result.canCreateRepository || result.canDeploy) errors.push('Approval result must not enable downstream actions.'); if (result.decision === 'approve_context_package_for_handoff_candidate' && (!result.approvalReceipt || !result.approvedContextEnvelope)) errors.push('Approved result requires receipt and envelope.'); if (result.approvedContextEnvelope && (result.approvedContextEnvelope.codexTaskStatus !== 'not_allowed' || result.approvedContextEnvelope.codexExecutionStatus !== 'not_allowed' || result.approvedContextEnvelope.embeddingsStatus !== 'not_allowed')) errors.push('Approved envelope must keep Codex and embeddings disabled.'); if (hasDanger(result)) errors.push('Approved package contains dangerous material or capabilities.'); if (result.decision !== 'approve_context_package_for_handoff_candidate' && !result.blockers.length && !result.reasons.length) errors.push('Rejected or blocked result requires blockers or reasons.'); if (!result.recommendedNextStep) errors.push('recommendedNextStep is required.'); return { ok: errors.length === 0, errors, warnings } }

