import { validateFactoryMemoryContextPackageCandidate } from '../memory-context-assembly/index.ts'
import { FACTORY_MEMORY_CONTEXT_APPROVAL_KIND, FACTORY_MEMORY_CONTEXT_APPROVAL_VERSION, createFactoryMemoryContextApprovalPolicy } from './memory-context-approval.defaults.ts'
import type { FactoryMemoryContextPackageCandidate } from '../memory-context-assembly/index.ts'
import type { FactoryMemoryContextApprovalBlocker, FactoryMemoryContextApprovalDecision, FactoryMemoryContextApprovalInput, FactoryMemoryContextApprovalResult, FactoryMemoryContextApprovalStatus } from './memory-context-approval.types.ts'

const token = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'unknown'
const dangerousItem = (item: FactoryMemoryContextPackageCandidate['items'][number]) => item.blockers.length > 0 || item.containsFullMemoryRecord || item.containsCanonicalPayload || item.containsRawEvidence || item.containsSecrets || item.containsPromptInstructions || item.canCreateCodexTask || item.canExecuteCodex || item.canCreateEmbeddings || item.canCreateProject || item.canCreateRepository || item.canDeploy
const dangerousPackage = (pkg: FactoryMemoryContextPackageCandidate | undefined) => !pkg || pkg.blockers.length > 0 || pkg.contextAssemblyStatus !== 'candidate_not_approved' || pkg.codexTaskStatus !== 'not_allowed' || pkg.codexExecutionStatus !== 'not_allowed' || pkg.embeddingsStatus !== 'not_allowed' || pkg.deployStatus !== 'not_allowed' || pkg.approxChars > pkg.maxApproxChars || !validateFactoryMemoryContextPackageCandidate(pkg).ok || pkg.items.some(dangerousItem)

export function evaluateFactoryMemoryContextApproval(input: FactoryMemoryContextApprovalInput): FactoryMemoryContextApprovalResult {
  const policy = createFactoryMemoryContextApprovalPolicy(input?.policy); const assembly = input?.memoryContextAssemblyResult; const pkg = assembly?.packageCandidate; const reviewedAt = input?.reviewedAt ?? ''; const reviewedBy = input?.reviewedBy ?? ''; const sourceAssemblyId = assembly?.assemblyId ?? 'missing-assembly'; const approvalId = `memory-context-approval:${token(sourceAssemblyId)}:${token(reviewedAt)}`
  const checks = [{ checkId: 'assembly-present', passed: Boolean(assembly), message: 'Assembly result is required.' }, { checkId: 'reviewer-present', passed: Boolean(reviewedBy.trim()), message: 'Reviewer identity is required.' }, { checkId: 'human-approval-present', passed: Boolean(input?.humanApprovalRef?.trim()), message: 'Human approval is required.' }]
  const blockers: FactoryMemoryContextApprovalBlocker[] = []; const warnings = (assembly?.warnings ?? []).map((warning) => ({ warningId: warning.warningId, itemId: warning.readItemId, message: warning.message })); const reasons: string[] = []
  let decision: FactoryMemoryContextApprovalDecision; let status: FactoryMemoryContextApprovalStatus
  if (!assembly) { decision = 'blocked'; status = 'blocked'; reasons.push('Assembly result is required.'); blockers.push({ blockerId: 'missing-assembly', message: reasons[0], critical: true }) }
  else if (!pkg) { decision = 'blocked'; status = 'blocked'; reasons.push('Package candidate is required.'); blockers.push({ blockerId: 'missing-package-candidate', message: reasons[0], critical: true }) }
  else if (assembly.decision !== 'approve_context_package_candidate' || assembly.status !== 'context_package_candidate_ready') { decision = 'reject_context_package'; status = 'rejected'; reasons.push('Assembly result is not approved as a package candidate.'); blockers.push({ blockerId: 'assembly-not-approved', message: reasons[0] }) }
  else if (dangerousPackage(pkg)) { decision = pkg.blockers.length || pkg.items.some((item) => item.blockers.length) ? 'request_context_changes' : 'blocked'; status = decision === 'request_context_changes' ? 'changes_required' : 'blocked'; reasons.push('Context package contains blockers, unsafe material, budget violations or dangerous capabilities.'); blockers.push({ blockerId: 'unsafe-context-package', message: reasons[0], critical: true }); for (const item of pkg.items.filter(dangerousItem)) blockers.push({ blockerId: `unsafe-context-item:${item.contextItemId}`, itemId: item.contextItemId, message: 'Context item is unsafe for approval.', critical: true }) }
  else if (!reviewedBy.trim() || !input.humanApprovalRef?.trim() || (assembly.contextPurpose === 'codex_task_context_candidate' && !input.humanApprovalRef?.trim())) { decision = 'human_review_required'; status = 'human_review_required'; reasons.push('Explicit human approval and reviewer identity are required.'); blockers.push({ blockerId: 'human-review-required', message: reasons[0] }) }
  else { decision = 'approve_context_package_for_handoff_candidate'; status = 'approved_context_candidate'; reasons.push('Context package candidate passed governed review.') }
  const nextStep = decision === 'approve_context_package_for_handoff_candidate' ? 'Submit approved context envelope to a future Codex Task Contract Gate; Codex remains disabled until a separate task contract is approved.' : decision === 'human_review_required' ? 'Obtain explicit human review before context handoff approval.' : 'Repair or reassemble the context package before requesting approval again.'
  const result: FactoryMemoryContextApprovalResult = { approvalId, approvalKind: FACTORY_MEMORY_CONTEXT_APPROVAL_KIND, approvalVersion: FACTORY_MEMORY_CONTEXT_APPROVAL_VERSION, reviewedAt, reviewedBy, reviewerRole: input?.reviewerRole, sourceAssemblyId, sourceReadRuntimeId: assembly?.sourceReadRuntimeId ?? '', sourceReadAdmissionId: assembly?.sourceReadAdmissionId ?? '', contextPurpose: assembly?.contextPurpose ?? '', decision, status, approvedPackageCandidate: decision === 'approve_context_package_for_handoff_candidate' && pkg ? structuredClone(pkg) : undefined, rejectedPackageCandidate: ['reject_context_package', 'request_context_changes', 'blocked'].includes(decision) && pkg ? structuredClone(pkg) : undefined, checks, blockers, warnings, reasons, summary: { approvalId, sourceAssemblyId, contextPurpose: assembly?.contextPurpose ?? '', decision, status, receiptPresent: false, envelopePresent: false, itemCount: pkg?.itemCount ?? 0, approxChars: pkg?.approxChars ?? 0, codexTaskStatus: 'not_allowed', codexExecutionStatus: 'not_allowed', embeddingsStatus: 'not_allowed', recommendedNextStep: nextStep }, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: nextStep }
  if (decision === 'approve_context_package_for_handoff_candidate' && assembly && pkg && input.humanApprovalRef) { result.approvalReceipt = { receiptId: `memory-context-receipt:${token(approvalId)}`, approvalId, sourceAssemblyId, sourceReadRuntimeId: assembly.sourceReadRuntimeId, sourceReadAdmissionId: assembly.sourceReadAdmissionId, reviewedBy, reviewedAt, humanApprovalRef: input.humanApprovalRef, contextPurpose: assembly.contextPurpose, decision, scope: 'context_package_handoff_candidate', limitations: ['Approval is only a context handoff candidate.', 'No Codex Task, model call, prompt finalization or execution is authorized.'], notAuthorizedActions: ['create_codex_task', 'execute_codex', 'create_embeddings', 'create_project', 'create_repository', 'deploy', 'publish', 'access_secrets', 'call_model', 'assemble_final_prompt'] }; result.approvedContextEnvelope = { envelopeId: `memory-context-envelope:${token(approvalId)}`, approvalId, sourceAssemblyId, sourceReadRuntimeId: assembly.sourceReadRuntimeId, sourceReadAdmissionId: assembly.sourceReadAdmissionId, contextPurpose: assembly.contextPurpose, packageCandidate: structuredClone(pkg), validation: validateFactoryMemoryContextPackageCandidate(pkg), contextApprovalStatus: 'approved_candidate', contextRuntimeStatus: 'not_executable', codexTaskStatus: 'not_allowed', codexExecutionStatus: 'not_allowed', embeddingsStatus: 'not_allowed', projectStatus: 'not_created', repositoryStatus: 'not_created', deployStatus: 'not_allowed', recommendedNextStep: nextStep }; result.summary = { ...result.summary, receiptPresent: true, envelopePresent: true } }
  void policy; return result
}
