import type { FactoryMemoryContextAssemblyResult, FactoryMemoryContextPackageCandidate } from '../memory-context-assembly/index.ts'

export type FactoryMemoryContextApprovalVersion = '1.0'
export type FactoryMemoryContextApprovalKind = 'factory-memory-context-approval'
export type FactoryMemoryContextApprovalDecision = 'blocked' | 'reject_context_package' | 'request_context_changes' | 'human_review_required' | 'approve_context_package_for_handoff_candidate'
export type FactoryMemoryContextApprovalStatus = 'blocked' | 'rejected' | 'changes_required' | 'human_review_required' | 'approved_context_candidate'
export interface FactoryMemoryContextApprovalReviewer { reviewedBy: string; reviewerRole?: string }
export interface FactoryMemoryContextApprovalPolicy { requireAssemblyResult: true; requirePackageCandidate: true; requireApprovedAssemblyDecision: true; requireHumanApproval: true; requireReviewerIdentity: true; requireCandidateNotPreviouslyApproved: true; rejectPackageBlockers: true; rejectItemBlockers: true; rejectCanonicalPayload: true; rejectRawEvidence: true; rejectSecrets: true; rejectPromptInstructions: true; rejectFullMemoryRecordByDefault: true; requireSafeReferencesOnly: true; requireLineage: true; requireBudgetRespected: true; allowWarningItems: true; allowContextPackageHandoffCandidateOnly: true; forbidCodexTaskCreation: true; forbidCodexExecution: true; forbidEmbeddingsCreation: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true }
export interface FactoryMemoryContextApprovalInput { memoryContextAssemblyResult: FactoryMemoryContextAssemblyResult; reviewedAt: string; reviewedBy: string; reviewerRole?: string; humanApprovalRef?: string; approvalScope?: string; policy?: Partial<FactoryMemoryContextApprovalPolicy>; reviewNotes?: string[] }
export interface FactoryMemoryContextApprovalCheck { checkId: string; passed: boolean; message: string }
export interface FactoryMemoryContextApprovalBlocker { blockerId: string; itemId?: string; message: string; critical?: boolean }
export interface FactoryMemoryContextApprovalWarning { warningId: string; itemId?: string; message: string }
export interface FactoryMemoryContextApprovalReceipt { receiptId: string; approvalId: string; sourceAssemblyId: string; sourceReadRuntimeId: string; sourceReadAdmissionId: string; reviewedBy: string; reviewedAt: string; humanApprovalRef: string; contextPurpose: string; decision: FactoryMemoryContextApprovalDecision; scope: 'context_package_handoff_candidate'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryMemoryApprovedContextEnvelope { envelopeId: string; approvalId: string; sourceAssemblyId: string; sourceReadRuntimeId: string; sourceReadAdmissionId: string; contextPurpose: string; packageCandidate: FactoryMemoryContextPackageCandidate; validation: { ok: boolean; errors: string[]; warnings: string[] }; contextApprovalStatus: 'approved_candidate'; contextRuntimeStatus: 'not_executable'; codexTaskStatus: 'not_allowed'; codexExecutionStatus: 'not_allowed'; embeddingsStatus: 'not_allowed'; projectStatus: 'not_created'; repositoryStatus: 'not_created'; deployStatus: 'not_allowed'; recommendedNextStep: string }
export interface FactoryMemoryContextApprovalSummary { approvalId: string; sourceAssemblyId: string; contextPurpose: string; decision: FactoryMemoryContextApprovalDecision; status: FactoryMemoryContextApprovalStatus; receiptPresent: boolean; envelopePresent: boolean; itemCount: number; approxChars: number; codexTaskStatus: string; codexExecutionStatus: string; embeddingsStatus: string; recommendedNextStep: string }
export interface FactoryMemoryContextApprovalResult { approvalId: string; approvalKind: FactoryMemoryContextApprovalKind; approvalVersion: FactoryMemoryContextApprovalVersion; reviewedAt: string; reviewedBy: string; reviewerRole?: string; sourceAssemblyId: string; sourceReadRuntimeId: string; sourceReadAdmissionId: string; contextPurpose: string; decision: FactoryMemoryContextApprovalDecision; status: FactoryMemoryContextApprovalStatus; approvedPackageCandidate?: FactoryMemoryContextPackageCandidate; rejectedPackageCandidate?: FactoryMemoryContextPackageCandidate; checks: FactoryMemoryContextApprovalCheck[]; blockers: FactoryMemoryContextApprovalBlocker[]; warnings: FactoryMemoryContextApprovalWarning[]; reasons: string[]; approvalReceipt?: FactoryMemoryContextApprovalReceipt; approvedContextEnvelope?: FactoryMemoryApprovedContextEnvelope; summary: FactoryMemoryContextApprovalSummary; canCreateCodexTask: false; canExecuteCodex: false; canCreateEmbeddings: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryContextApprovalValidationResult { ok: boolean; errors: string[]; warnings: string[] }

