import { DEFAULT_FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_POLICY, FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_KIND, FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_NEXT_STEP, FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_VERSION } from './hermes-research-runtime-interface-selection.defaults.ts'
import type { FactoryHermesResearchRuntimeInterfaceSelectionInput, FactoryHermesResearchRuntimeInterfaceSelectionResult, FactoryHermesResearchRuntimeSelectedInterface } from './hermes-research-runtime-interface-selection.types.ts'

const selectedInterface: FactoryHermesResearchRuntimeSelectedInterface = { candidateId: 'pyproject-console-script-1', interfaceType: 'package_entrypoint', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', sourceDeclarationRef: 'pyproject.toml [project.scripts]', futureExecutableCandidateWindows: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/Scripts/hermes.exe', futureWorkingDirectory: '.codex-temp/external-tools/hermes-agent/install/75b300f/source', confidence: 'high', selectionReason: 'Unique real package entrypoint declared in pyproject and documented as the primary CLI.', limitations: ['CLI may be interactive.', 'Boundary must define stdin/stdout/timeouts.', 'No network, credentials or model calls by default.'] }
function base(input: FactoryHermesResearchRuntimeInterfaceSelectionInput): Omit<FactoryHermesResearchRuntimeInterfaceSelectionResult, 'status' | 'decision' | 'canProceedToResearchRuntimeBoundary'> {
  return { interfaceSelectionId: `hermes-research-runtime-interface-selection:75b300f:${input.selectedAt}`, interfaceSelectionKind: FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_KIND, interfaceSelectionVersion: FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_VERSION, selectedAt: input.selectedAt, selectedBy: input.selectedBy, toolId: 'hermes_agent', auditedHead: input.planningResult?.auditedHead || '', selectedCandidateId: input.selectedCandidateId || '', checks: [], blockers: [], warnings: [], canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_NEXT_STEP }
}
export function evaluateFactoryHermesResearchRuntimeInterfaceSelection(input: FactoryHermesResearchRuntimeInterfaceSelectionInput): FactoryHermesResearchRuntimeInterfaceSelectionResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_POLICY, ...(input.policy || {}) }
  const b = base(input)
  const p = input.planningResult
  if (!p) return { ...b, status: 'blocked', decision: 'blocked_missing_planning_result', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_missing_planning_result', message: 'Planning result is required.' }] }
  if (!['manual_selection_required', 'plan_candidate_created'].includes(p.status) || (p.status === 'manual_selection_required' && p.decision !== 'hermes_research_runtime_plan_requires_manual_interface_selection') || p.canExecuteHermes !== false || p.canUseNetwork !== false || p.canUseCredentials !== false || p.canCallModels !== false) return { ...b, auditedHead: p.auditedHead, status: 'blocked', decision: 'blocked_planning_not_manual_selection_required', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_planning_not_manual_selection_required', message: 'Planning result is not eligible for interface selection.' }] }
  if (!input.selectedCandidateId) return { ...b, auditedHead: p.auditedHead, status: 'blocked', decision: 'blocked_selected_candidate_not_found', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'missing_selected_candidate_id', message: 'selectedCandidateId is required.' }] }
  const candidate = p.interfaceCandidates.find((c) => c.candidateId === input.selectedCandidateId)
  if (!candidate) return { ...b, auditedHead: p.auditedHead, status: 'blocked', decision: 'blocked_selected_candidate_not_found', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_selected_candidate_not_found', message: 'Selected candidate is not present in planning result.' }] }
  if (input.selectedCandidateId !== 'pyproject-console-script-1') return { ...b, auditedHead: p.auditedHead, status: 'blocked', decision: 'blocked_selected_candidate_not_recommended', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_selected_candidate_not_recommended', message: 'Selected candidate is not the Lean/JEFE recommended interface.' }] }
  if (policy.requireHighConfidenceForAutoBoundary && selectedInterface.confidence !== 'high') return { ...b, auditedHead: p.auditedHead, status: 'blocked', decision: 'blocked_candidate_low_confidence', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_candidate_low_confidence', message: 'Selected candidate is not high confidence.' }] }
  if (policy.requireHumanApprovalRef && !input.humanApprovalRef) return { ...b, auditedHead: p.auditedHead, status: 'human_review_required', decision: 'blocked_missing_human_approval', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] }
  const receipt = { receiptId: `${b.interfaceSelectionId}:receipt`, interfaceSelectionId: b.interfaceSelectionId, toolId: 'hermes_agent' as const, auditedHead: p.auditedHead, selectedBy: input.selectedBy, selectedAt: input.selectedAt, humanApprovalRef: input.humanApprovalRef || '', selectedCandidateId: input.selectedCandidateId, selectedInterfaceType: selectedInterface.interfaceType, decision: 'hermes_research_runtime_interface_selected_for_boundary_planning' as const, scope: 'hermes_research_runtime_interface_selection_only' as const, approvedNextGate: 'Factory Hermes Research Runtime Boundary Contract v1' as const, limitations: selectedInterface.limitations, notAuthorizedActions: [...FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_NOT_AUTHORIZED_ACTIONS] }
  const envelope = { envelopeId: `${b.interfaceSelectionId}:envelope`, interfaceSelectionId: b.interfaceSelectionId, toolId: 'hermes_agent' as const, auditedHead: p.auditedHead, selectedCandidateId: input.selectedCandidateId, selectedInterface, sourceRootRef: p.sourceRootRef, installRootRef: p.installRootRef, pythonEnvRootRef: p.pythonEnvRootRef, planningResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-planning-result.json' as const, dossierRef: '.codex-temp/hermes-research-runtime-interface-selection-dossier-v1/INTERFACE_SELECTION_DOSSIER.md' as const, approvedNextGate: 'Factory Hermes Research Runtime Boundary Contract v1' as const, interfaceReadinessStatus: 'selected_for_boundary_only' as const, hermesExecutionStatus: 'not_allowed' as const, scriptsStatus: 'not_allowed' as const, networkStatus: 'not_allowed' as const, credentialsStatus: 'not_allowed' as const, modelCallStatus: 'not_allowed' as const, projectMutationStatus: 'not_allowed' as const, deployStatus: 'not_allowed' as const, canProceedToResearchRuntimeBoundary: true as const, canExecuteHermes: false as const, canRunHermesScripts: false as const, canUseNetwork: false as const, canUseCredentials: false as const, canCallModels: false as const, recommendedNextStep: FACTORY_HERMES_RESEARCH_RUNTIME_INTERFACE_SELECTION_NEXT_STEP }
  return { ...b, auditedHead: p.auditedHead, status: 'selected', decision: 'hermes_research_runtime_interface_selected_for_boundary_planning', selectedInterface, interfaceSelectionReceipt: receipt, selectedHermesResearchRuntimeInterfaceEnvelope: envelope, canProceedToResearchRuntimeBoundary: true }
}
