import type { FactoryHermesResearchRuntimePlanningResult } from '../hermes-research-runtime-planning/index.ts'

export type FactoryHermesResearchRuntimeInterfaceSelectionVersion = '1.0'
export type FactoryHermesResearchRuntimeInterfaceSelectionKind = 'factory-hermes-research-runtime-interface-selection'
export type FactoryHermesResearchRuntimeInterfaceSelectionStatus = 'selected' | 'blocked' | 'human_review_required'
export type FactoryHermesResearchRuntimeInterfaceSelectionDecision = 'hermes_research_runtime_interface_selected_for_boundary_planning' | 'blocked_missing_planning_result' | 'blocked_planning_not_manual_selection_required' | 'blocked_selected_candidate_not_found' | 'blocked_selected_candidate_not_recommended' | 'blocked_candidate_low_confidence' | 'blocked_missing_human_approval' | 'request_manual_interface_review'
export interface FactoryHermesResearchRuntimeInterfaceSelectionPolicy { requirePlanningResult: boolean; requireManualSelectionRequiredOrPlanCandidate: boolean; requireSelectedCandidateId: boolean; requireCandidateExists: boolean; requireHumanApprovalRef: boolean; requireHighConfidenceForAutoBoundary: boolean; requirePackageEntrypointPreferred: boolean; requireBoundaryContractNext: boolean; forbidExecutionInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidHermesScriptsInThisGate: boolean; forbidUvExecutionInThisGate: boolean; forbidPipExecutionInThisGate: boolean; forbidPythonExecutionInThisGate: boolean; forbidSetupPyExecutionInThisGate: boolean; forbidNetworkInThisGate: boolean; forbidCredentialsInThisGate: boolean; forbidModelCallsInThisGate: boolean; forbidProjectMutationInThisGate: boolean; forbidDeployInThisGate: boolean }
export interface FactoryHermesResearchRuntimeInterfaceSelectionInput { selectedAt: string; selectedBy: string; selectedCandidateId: string; humanApprovalRef?: string; planningResult?: FactoryHermesResearchRuntimePlanningResult; dossierSummary?: string; selectionNotes?: string; policy?: Partial<FactoryHermesResearchRuntimeInterfaceSelectionPolicy> }
export interface FactoryHermesResearchRuntimeSelectedInterface { candidateId: 'pyproject-console-script-1'; interfaceType: 'package_entrypoint'; commandName: 'hermes'; pythonEntrypoint: 'hermes_cli.main:main'; sourceDeclarationRef: 'pyproject.toml [project.scripts]'; futureExecutableCandidateWindows: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/Scripts/hermes.exe'; futureWorkingDirectory: '.codex-temp/external-tools/hermes-agent/install/75b300f/source'; confidence: 'high'; selectionReason: string; limitations: string[] }
export interface FactoryHermesResearchRuntimeInterfaceSelectionReceipt { receiptId: string; interfaceSelectionId: string; toolId: 'hermes_agent'; auditedHead: string; selectedBy: string; selectedAt: string; humanApprovalRef: string; selectedCandidateId: string; selectedInterfaceType: string; decision: FactoryHermesResearchRuntimeInterfaceSelectionDecision; scope: 'hermes_research_runtime_interface_selection_only'; approvedNextGate: 'Factory Hermes Research Runtime Boundary Contract v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesResearchRuntimeSelectedInterfaceEnvelope { envelopeId: string; interfaceSelectionId: string; toolId: 'hermes_agent'; auditedHead: string; selectedCandidateId: string; selectedInterface: FactoryHermesResearchRuntimeSelectedInterface; sourceRootRef: string; installRootRef: string; pythonEnvRootRef: string; planningResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-planning-result.json'; dossierRef: '.codex-temp/hermes-research-runtime-interface-selection-dossier-v1/INTERFACE_SELECTION_DOSSIER.md'; approvedNextGate: 'Factory Hermes Research Runtime Boundary Contract v1'; interfaceReadinessStatus: 'selected_for_boundary_only'; hermesExecutionStatus: 'not_allowed'; scriptsStatus: 'not_allowed'; networkStatus: 'not_allowed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; projectMutationStatus: 'not_allowed'; deployStatus: 'not_allowed'; canProceedToResearchRuntimeBoundary: true; canExecuteHermes: false; canRunHermesScripts: false; canUseNetwork: false; canUseCredentials: false; canCallModels: false; recommendedNextStep: string }
export interface FactoryHermesResearchRuntimeInterfaceSelectionCheck { checkId: string; ok: boolean; message: string }
export interface FactoryHermesResearchRuntimeInterfaceSelectionBlocker { blockerId: string; message: string }
export interface FactoryHermesResearchRuntimeInterfaceSelectionWarning { warningId: string; message: string }
export interface FactoryHermesResearchRuntimeInterfaceSelectionResult { interfaceSelectionId: string; interfaceSelectionKind: FactoryHermesResearchRuntimeInterfaceSelectionKind; interfaceSelectionVersion: FactoryHermesResearchRuntimeInterfaceSelectionVersion; selectedAt: string; selectedBy: string; toolId: 'hermes_agent'; auditedHead: string; selectedCandidateId: string; selectedInterface?: FactoryHermesResearchRuntimeSelectedInterface; interfaceSelectionReceipt?: FactoryHermesResearchRuntimeInterfaceSelectionReceipt; selectedHermesResearchRuntimeInterfaceEnvelope?: FactoryHermesResearchRuntimeSelectedInterfaceEnvelope; checks: FactoryHermesResearchRuntimeInterfaceSelectionCheck[]; blockers: FactoryHermesResearchRuntimeInterfaceSelectionBlocker[]; warnings: FactoryHermesResearchRuntimeInterfaceSelectionWarning[]; status: FactoryHermesResearchRuntimeInterfaceSelectionStatus; decision: FactoryHermesResearchRuntimeInterfaceSelectionDecision; canProceedToResearchRuntimeBoundary: boolean; canExecuteHermes: false; canRunHermesScripts: false; canUseNetwork: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesResearchRuntimeInterfaceSelectionValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesResearchRuntimeInterfaceSelectionSummary { interfaceSelectionId: string; selectedCandidateId: string; commandName?: string; pythonEntrypoint?: string; status: FactoryHermesResearchRuntimeInterfaceSelectionStatus; decision: FactoryHermesResearchRuntimeInterfaceSelectionDecision; canProceedToResearchRuntimeBoundary: boolean; canExecuteHermes: false; approvedNextGate?: string; nextStep: string }
