import { DEFAULT_FACTORY_HERMES_MODEL_PROVIDER_POLICY_PLANNING_POLICY, FACTORY_HERMES_MODEL_PROVIDER_POLICY_PLANNING_KIND, FACTORY_HERMES_MODEL_PROVIDER_POLICY_PLANNING_NEXT_STEP, FACTORY_HERMES_MODEL_PROVIDER_POLICY_PLANNING_VERSION, MODEL_PROVIDER_NOT_AUTHORIZED_ACTIONS, MODEL_PROVIDER_REQUIRED_NEXT_POLICIES } from './hermes-model-provider-policy-planning.defaults.ts'
import type { FactoryHermesModelProviderCandidate, FactoryHermesModelProviderPolicyPlanningInput, FactoryHermesModelProviderPolicyPlanningResult } from './hermes-model-provider-policy-planning.types.ts'

export function buildProviderCandidates(inspection?: any, deep?: any): FactoryHermesModelProviderCandidate[] {
  const names = new Set<string>(inspection?.providersObserved || [])
  const envs = new Set<string>([...(inspection?.credentialEnvRefsObserved || []), ...(deep?.providerModelFindings?.credentialEnvNamesObserved || [])])
  const candidates: FactoryHermesModelProviderCandidate[] = []
  if (names.has('openai') || envs.has('OPENAI_API_KEY')) candidates.push({ providerId: 'openai', providerName: 'openai', status: 'candidate_requires_credentials_policy', credentialRefsExpected: ['OPENAI_API_KEY'], modelRequired: true, networkRequiredLikely: true, modelCallsRequiredLikely: true, canUseNow: false })
  if (names.has('anthropic') || envs.has('ANTHROPIC_API_KEY')) candidates.push({ providerId: 'anthropic', providerName: 'anthropic', status: 'candidate_requires_credentials_policy', credentialRefsExpected: ['ANTHROPIC_API_KEY'], modelRequired: true, networkRequiredLikely: true, modelCallsRequiredLikely: true, canUseNow: false })
  if (names.has('gemini') || names.has('google') || envs.has('GEMINI_API_KEY') || envs.has('GOOGLE_API_KEY')) candidates.push({ providerId: 'gemini_google', providerName: 'gemini/google', status: 'candidate_requires_credentials_policy', credentialRefsExpected: ['GEMINI_API_KEY', 'GOOGLE_API_KEY'], modelRequired: true, networkRequiredLikely: true, modelCallsRequiredLikely: true, canUseNow: false })
  candidates.push({ providerId: 'local_offline_mock', providerName: 'local/offline/mock', status: inspection?.mockOfflineProviderFound ? 'candidate_requires_credentials_policy' : 'not_available', credentialRefsExpected: [], modelRequired: true, networkRequiredLikely: false, modelCallsRequiredLikely: false, canUseNow: false, reason: inspection?.mockOfflineProviderFound ? 'Source inspection needs future proof before use.' : 'No contractual local/offline/mock provider was proven.' })
  candidates.push({ providerId: 'default_from_env_or_config', providerName: 'default_from_env_or_config', status: 'forbidden_without_explicit_approval', credentialRefsExpected: ['HERMES_INFERENCE_PROVIDER', 'HERMES_INFERENCE_MODEL'], modelRequired: true, networkRequiredLikely: true, modelCallsRequiredLikely: true, canUseNow: false, reason: 'Hidden provider/model fallback from env or config is not allowed.' })
  return candidates
}

function buildModelRules() {
  return [
    { ruleId: 'explicit_provider', ruleName: 'Explicit provider rule', requirements: ['Provider must be explicit in future approval.', 'No implicit env/config default.', 'No fallback provider unless approved.'] },
    { ruleId: 'explicit_model', ruleName: 'Explicit model rule', requirements: ['Model must be explicit in future approval.', 'No implicit env/config default.', 'No model fallback unless approved.'] },
    { ruleId: 'provider_allowlist', ruleName: 'Provider allowlist', requirements: ['Future provider must be from approved allowlist.', 'Current candidates are listed but not executable.'] },
    { ruleId: 'model_allowlist', ruleName: 'Model allowlist', requirements: ['Future model must be exact string selected in future gate.', 'No wildcard model.', 'No latest aliases unless explicitly approved.'] },
    { ruleId: 'credential_dependency', ruleName: 'Credential dependency', requirements: ['Provider policy does not approve credentials.', 'Credentials Policy Planning must come next.'] },
    { ruleId: 'network_dependency', ruleName: 'Network dependency', requirements: ['Provider policy does not approve network.', 'Network Policy Planning must approve endpoint/network scope later.'] },
    { ruleId: 'model_call_dependency', ruleName: 'Model call dependency', requirements: ['Provider policy does not approve model calls now.', 'Model calls can only happen in a future runtime after the full chain.'] },
    { ruleId: 'logging', ruleName: 'Logging', requirements: ['Provider/model may be logged as metadata.', 'Credential values must never be logged.', 'No env dump.'] },
    { ruleId: 'candidate_status', ruleName: 'Candidate status', requirements: ['Provider/model are candidate only.', 'Not approved for execution.'] },
  ]
}

function base(input: FactoryHermesModelProviderPolicyPlanningInput): FactoryHermesModelProviderPolicyPlanningResult {
  return { planningId: `hermes-model-provider-policy-planning:75b300f:${input.plannedAt}`, planningKind: FACTORY_HERMES_MODEL_PROVIDER_POLICY_PLANNING_KIND, planningVersion: FACTORY_HERMES_MODEL_PROVIDER_POLICY_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', commandShapeUnderConsideration: 'oneshot_real_with_provider_model', futureCommandShape: 'hermes.exe --oneshot "<PROMPT>" --provider <PROVIDER> --model <MODEL>', providerCandidates: [], selectedProviderCandidate: null, selectedModelCandidate: null, checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_prompt_policy_planning', canProceedToCredentialsPolicyPlanning: false, canProceedToResearchExecutionApproval: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canCallModelsNow: false, canUseFindings: false, recommendedNextStep: FACTORY_HERMES_MODEL_PROVIDER_POLICY_PLANNING_NEXT_STEP }
}

export function evaluateFactoryHermesModelProviderPolicyPlanning(input: FactoryHermesModelProviderPolicyPlanningInput): FactoryHermesModelProviderPolicyPlanningResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_MODEL_PROVIDER_POLICY_PLANNING_POLICY, ...(input.policy || {}) }
  const out = base(input)
  const prompt = input.promptPolicyPlanningResult
  const chain = input.policyChainPlanningResult
  const deep = input.deepSourceReview
  const inspection = input.providerSourceInspection
  if (!prompt) return { ...out, blockers: [{ blockerId: 'blocked_missing_prompt_policy_planning', message: 'Prompt policy planning result is required.' }] }
  if (prompt.status !== 'prompt_policy_plan_created' || prompt.decision !== 'hermes_prompt_policy_plan_created' || prompt.canProceedToModelProviderPolicyPlanning !== true || prompt.canProceedToResearchExecutionApproval !== false || prompt.canRunResearchNow !== false || prompt.canExecuteHermesNow !== false || prompt.canPassPromptNow !== false || prompt.canUseNetworkNow !== false || prompt.canUseCredentialsNow !== false || prompt.canCallModelsNow !== false || prompt.hermesPromptPolicyPlanCandidate?.promptCandidate?.candidateOnly !== true || prompt.hermesPromptPolicyPlanCandidate?.promptCandidate?.notApprovedForExecutionYet !== true) return { ...out, decision: 'blocked_prompt_policy_not_ready_for_model_provider_policy', blockers: [{ blockerId: 'blocked_prompt_policy_not_ready_for_model_provider_policy', message: 'Prompt policy planning is not ready.' }] }
  if (policy.requirePolicyChainPlanning && (!chain || chain.status !== 'policy_chain_plan_created' || !chain.requiredPolicies?.some((p: any) => p.policyName === 'Model Provider Policy') || !chain.proposedGateSequence?.some((g: any) => g.gateName === 'Factory Hermes Model Provider Policy Planning Gate v1'))) return { ...out, decision: 'blocked_policy_chain_not_ready_for_model_provider_policy', blockers: [{ blockerId: 'blocked_policy_chain_not_ready_for_model_provider_policy', message: 'Policy chain is missing Model Provider Policy planning.' }] }
  if (deep) {
    const real = deep.commandContractCandidates?.find((c: any) => c.id === 'oneshot_real_with_provider_model')
    if (real?.recommendation !== 'requires_policy_chain' || deep.providerModelFindings?.providerMockOrOfflineFound !== false) return { ...out, decision: 'blocked_deep_source_review_not_policy_chain', blockers: [{ blockerId: 'blocked_deep_source_review_not_policy_chain', message: 'Deep source review does not support model provider policy planning.' }] }
  }
  if (policy.requireProviderSourceInspection && !inspection) return { ...out, decision: 'blocked_missing_provider_source_inspection', blockers: [{ blockerId: 'blocked_missing_provider_source_inspection', message: 'Provider source inspection is required.' }] }
  const providerCandidates = buildProviderCandidates(inspection, deep)
  if (policy.requireProviderCandidates && providerCandidates.length < 5) return { ...out, decision: 'blocked_missing_provider_source_inspection', blockers: [{ blockerId: 'blocked_missing_provider_source_inspection', message: 'Provider candidates are incomplete.' }] }
  const plan = { planCandidateId: `${out.planningId}:model-provider-policy-plan-candidate`, toolId: 'hermes_agent' as const, commandShapeUnderConsideration: 'oneshot_real_with_provider_model' as const, futureCommandShape: { executable: 'hermes.exe' as const, argsTemplate: ['--oneshot', '<PROMPT>', '--provider', '<PROVIDER>', '--model', '<MODEL>'] as ['--oneshot', '<PROMPT>', '--provider', '<PROVIDER>', '--model', '<MODEL>'], shell: false as const }, providerSelection: { providerSelectionRequired: true as const, selectedProvider: null, selectedModel: null, noImplicitProviderFromEnv: true as const, noImplicitModelFromEnv: true as const, noDefaultFallbackProvider: true as const }, providerCandidates, modelRules: buildModelRules(), credentialDependency: { credentialsNotApprovedHere: true as const, nextGate: 'Factory Hermes Credentials Policy Planning Gate v1' as const }, networkDependency: { networkNotApprovedHere: true as const, futureNetworkPolicyRequired: true as const }, modelCallDependency: { modelCallsNotApprovedHere: true as const, futureRuntimeRequiresFullChain: true as const }, requiredNextPolicies: MODEL_PROVIDER_REQUIRED_NEXT_POLICIES, canProceedToCredentialsPolicyPlanning: true as const, canProceedToResearchExecutionApproval: false as const, canCallModelsNow: false as const }
  const receipt = { receiptId: `${out.planningId}:receipt`, planningId: out.planningId, toolId: 'hermes_agent' as const, plannedBy: input.plannedBy, plannedAt: input.plannedAt, decision: 'hermes_model_provider_policy_plan_created' as const, scope: 'hermes_model_provider_policy_planning_only' as const, approvedNextGate: 'Factory Hermes Credentials Policy Planning Gate v1' as const, limitations: ['Provider and model are not selected for execution.', 'Credentials are not approved and env secrets are not read.', 'Network and model calls remain blocked until future gates.'], notAuthorizedActions: MODEL_PROVIDER_NOT_AUTHORIZED_ACTIONS }
  return { ...out, status: 'model_provider_policy_plan_created', decision: 'hermes_model_provider_policy_plan_created', providerCandidates, selectedProviderCandidate: null, selectedModelCandidate: null, modelProviderPolicyPlanningReceipt: receipt, hermesModelProviderPolicyPlanCandidate: plan, canProceedToCredentialsPolicyPlanning: true }
}
