import { DEFAULT_FACTORY_HERMES_RESEARCH_EXECUTION_APPROVAL_POLICY, FACTORY_HERMES_RESEARCH_EXECUTION_APPROVAL_KIND, FACTORY_HERMES_RESEARCH_EXECUTION_APPROVAL_NEXT_STEP, FACTORY_HERMES_RESEARCH_EXECUTION_APPROVAL_VERSION, NO_EXECUTION_AUTHORIZED_ACTIONS, RESEARCH_EXECUTION_APPROVAL_NOT_AUTHORIZED_ACTIONS } from './hermes-research-execution-approval.defaults.ts'
import type { FactoryHermesResearchExecutionApprovalBlocker, FactoryHermesResearchExecutionApprovalDecision, FactoryHermesResearchExecutionApprovalInput, FactoryHermesResearchExecutionApprovalResult, FactoryHermesRuntimeSelectionRequirement } from './hermes-research-execution-approval.types.ts'

const EXPECTED_MISSING = ['promptApprovalMissing', 'providerSelectionMissing', 'modelSelectionMissing', 'credentialSelectionMissing', 'networkHostApprovalMissing', 'toolsetSelectionApprovalMissing', 'runtimeRunRootApprovalMissing', 'finalExecutionApprovalMissing']

const REQUIREMENT_DETAILS: Record<string, { requirementId: string; expectedFutureEvidence: string[] }> = {
  promptApprovalMissing: { requirementId: 'promptApproval', expectedFutureEvidence: ['exact approved prompt', 'Prompt Policy compliance', 'no secrets, URLs, tools, or personal data'] },
  providerSelectionMissing: { requirementId: 'providerSelection', expectedFutureEvidence: ['explicit approved provider', 'no provider from env/config default'] },
  modelSelectionMissing: { requirementId: 'modelSelection', expectedFutureEvidence: ['explicit approved model', 'no wildcard/latest unless explicitly approved'] },
  credentialSelectionMissing: { requirementId: 'credentialSelection', expectedFutureEvidence: ['approved credential ref', 'credential value not stored in artifacts'] },
  networkHostApprovalMissing: { requirementId: 'networkHostApproval', expectedFutureEvidence: ['exact approved hosts', 'no wildcards', 'no arbitrary internet'] },
  toolsetSelectionApprovalMissing: { requirementId: 'toolsetSelectionApproval', expectedFutureEvidence: ['explicit approved toolset', 'prefer no_toolsets_text_only if supported', 'hidden defaults forbidden'] },
  runtimeRunRootApprovalMissing: { requirementId: 'runtimeRunRootApproval', expectedFutureEvidence: ['specific .codex-temp run root', 'path containment proof'] },
  finalExecutionApprovalMissing: { requirementId: 'finalExecutionApproval', expectedFutureEvidence: ['human/gate final approval before runtime adapter'] },
}

function requirements(missingSelections: any[]): FactoryHermesRuntimeSelectionRequirement[] {
  return missingSelections.map((item) => {
    const details = REQUIREMENT_DETAILS[item.selectionId] || { requirementId: item.selectionId, expectedFutureEvidence: ['future approved evidence required'] }
    return { requirementId: details.requirementId, sourceMissingSelectionId: item.selectionId, requiredBefore: 'research_runtime_adapter', requiredByGate: item.requiredByGate || 'Factory Hermes Runtime Selection Planning Gate v1', status: 'required_not_satisfied', blocksExecutionNow: true, reason: item.reason || 'Runtime selection is required before execution.', expectedFutureEvidence: details.expectedFutureEvidence }
  })
}

function build(input: FactoryHermesResearchExecutionApprovalInput, decision: FactoryHermesResearchExecutionApprovalDecision, boundaryValid: boolean, missingSelections: any[], blockers: FactoryHermesResearchExecutionApprovalBlocker[]): FactoryHermesResearchExecutionApprovalResult {
  const approvalId = `hermes-research-execution-approval:75b300f:${input.approvedAt}`
  const runtimeSelectionRequirements = requirements(missingSelections)
  const canProceed = boundaryValid && runtimeSelectionRequirements.length > 0
  const receipt = { receiptId: `${approvalId}:receipt`, approvalId, toolId: 'hermes_agent' as const, approvedBy: input.approvedBy, approvedAt: input.approvedAt, decision, approvalStatus: 'not_approved' as const, scope: 'hermes_research_execution_approval_evaluation_only' as const, approvedNextGate: 'Factory Hermes Runtime Selection Planning Gate v1' as const, limitations: ['Execution is not approved.', 'Runtime adapter is not approved.', 'Runtime selections must be planned and approved before any retry/final approval.'], notAuthorizedActions: RESEARCH_EXECUTION_APPROVAL_NOT_AUTHORIZED_ACTIONS }
  const decisionRecord = { decisionId: `${approvalId}:decision`, toolId: 'hermes_agent' as const, approvalStatus: 'not_approved' as const, decision, reason: boundaryValid ? 'missing_runtime_selections' as const : 'invalid_boundary' as const, boundaryValidated: boundaryValid, policiesConsolidated: boundaryValid, executionApproved: false as const, runtimeAdapterApproved: false as const, runtimeSelectionPlanningApproved: canProceed, missingRuntimeSelectionCount: missingSelections.length, blockerCount: blockers.length, requiredNextGate: 'Factory Hermes Runtime Selection Planning Gate v1' as const, noExecutionAuthorizedActions: NO_EXECUTION_AUTHORIZED_ACTIONS }
  const blockerPlan = { blockerPlanId: `${approvalId}:blocker-plan`, toolId: 'hermes_agent' as const, blockerType: boundaryValid ? 'missing_runtime_selections' as const : 'invalid_boundary' as const, blockers, resolutionOrder: ['Prompt Runtime Selection Planning', 'Provider/Model Runtime Selection Planning', 'Credential Runtime Selection Planning', 'Network Host Runtime Selection Planning', 'Toolset Runtime Selection Planning', 'Runtime Run Root Selection Planning', 'Final Execution Approval Retry'], nextGateCandidate: 'Factory Hermes Runtime Selection Planning Gate v1' as const, canProceedToRuntimeSelectionPlanning: canProceed, canProceedToResearchRuntimeAdapter: false as const, executionRemainsBlocked: true as const }
  return { approvalId, approvalKind: FACTORY_HERMES_RESEARCH_EXECUTION_APPROVAL_KIND, approvalVersion: FACTORY_HERMES_RESEARCH_EXECUTION_APPROVAL_VERSION, approvedAt: input.approvedAt, approvedBy: input.approvedBy, toolId: 'hermes_agent', commandShapeUnderConsideration: 'oneshot_real_with_provider_model', boundaryDecisionRef: input.researchExecutionBoundaryPlanningResult?.planningId, priorPolicySummary: Object.keys(input.policyPlanningResults || {}), approvalChecks: [], approvalBlockers: blockers, approvalWarnings: [], runtimeSelectionRequirements, researchExecutionApprovalReceipt: receipt, hermesResearchExecutionApprovalDecision: decisionRecord, researchExecutionApprovalBlockerPlan: blockerPlan, status: 'research_execution_approval_blocked', decision, approvalStatus: 'not_approved', canProceedToRuntimeSelectionPlanning: canProceed, canProceedToResearchRuntimeAdapter: false, canProceedToResearchExecutionRuntime: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canMutateFilesystemNow: false, canUseFindings: false, recommendedNextStep: FACTORY_HERMES_RESEARCH_EXECUTION_APPROVAL_NEXT_STEP }
}

export function evaluateFactoryHermesResearchExecutionApproval(input: FactoryHermesResearchExecutionApprovalInput): FactoryHermesResearchExecutionApprovalResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_RESEARCH_EXECUTION_APPROVAL_POLICY, ...(input.approvalPolicy || {}) }
  const boundary = input.researchExecutionBoundaryPlanningResult
  const plan = boundary?.hermesResearchExecutionBoundaryPlanCandidate
  const missing = boundary?.missingRuntimeSelections || []
  const validBoundary = !!boundary && boundary.status === 'research_execution_boundary_plan_created' && boundary.decision === 'hermes_research_execution_boundary_plan_created' && plan?.allPoliciesConsolidated === true && plan?.approvalGateCanEvaluate === true && plan?.finalApprovalRequired === true && plan?.executionAllowedNow === false && plan?.researchExecutionAllowedNow === false && boundary.canProceedToResearchExecutionApproval === true && boundary.canRunResearchNow === false && boundary.canExecuteHermesNow === false && boundary.canPassPromptNow === false && boundary.canUseNetworkNow === false && boundary.canUseCredentialsNow === false && boundary.canReadEnvSecretsNow === false && boundary.canCallModelsNow === false && boundary.canEnableToolsetsNow === false && boundary.canMutateFilesystemNow === false && boundary.canUseFindings === false
  if (policy.requireBoundaryPlanning && !validBoundary) return build(input, 'hermes_research_execution_approval_blocked_invalid_boundary', false, [], [{ blockerId: 'invalid_boundary', message: 'Research execution boundary planning result is missing or invalid.' }])
  const missingIds = new Set(missing.map((item: any) => item.selectionId))
  const missingBlockers = EXPECTED_MISSING.filter((id) => !missingIds.has(id)).map((id) => ({ blockerId: 'missing_expected_runtime_selection', sourceMissingSelectionId: id, message: `${id} is required in boundary missingRuntimeSelections.` }))
  const invalidState = missing.filter((item: any) => item.status !== 'required_before_runtime' || item.blocksExecutionNow !== true).map((item: any) => ({ blockerId: 'invalid_runtime_selection_state', sourceMissingSelectionId: item.selectionId, message: `${item.selectionId} must be required_before_runtime and block execution now.` }))
  const blockers = missing.map((item: any) => ({ blockerId: 'runtime_selection_required', sourceMissingSelectionId: item.selectionId, message: item.reason || `${item.selectionId} is required before runtime.` })).concat(missingBlockers, invalidState)
  return build(input, missingBlockers.length || invalidState.length ? 'hermes_research_execution_approval_blocked_invalid_boundary' : 'hermes_research_execution_approval_blocked_missing_runtime_selections', missingBlockers.length === 0 && invalidState.length === 0, missing, blockers)
}
