import type { FactoryMemoryPersistenceResult } from '../memory-persistence/index.ts'
export type FactoryMemoryPersistenceRuntimeVersion = '1.0'
export type FactoryMemoryPersistenceRuntimeKind = 'factory-memory-persistence-runtime'
export type FactoryMemoryPersistenceRuntimeStatus = 'persisted' | 'idempotent_noop' | 'partial_failed' | 'failed' | 'blocked'
export interface FactoryMemoryPersistenceRuntimePolicy { requireStorageRootInsideCodexTemp: true; requirePersistenceResultReady: true; requireManifest: true; requireRecordPlans: true; requireFingerprint: true; requireIdempotencyKey: true; requireAtomicTempWrite: true; requireReadbackVerification: true; requireMetadataWrite: true; requireProjectMemoryIndexUpdate: true; requireNoSecrets: true; requireNoRawEvidence: true; requireNoEmbeddings: true; requireNoCodexTask: true; requireNoGlobalPromotion: true; requireRelativeLogicalTargets: true; forbidAbsoluteTargets: true; forbidPathTraversal: true; forbidMemoryWriteOutsideStorageRoot: true; forbidEmbeddingsCreation: true; forbidCodexTaskCreation: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; allowIdempotentReplay: true; blockDifferentFingerprintOverwrite: true }
export interface FactoryMemoryPersistenceRuntimeInput { memoryPersistenceResult: FactoryMemoryPersistenceResult; storageRoot: string; executedAt: string; executedBy: string; policy?: Partial<FactoryMemoryPersistenceRuntimePolicy>; allowIdempotentReplay?: boolean }
export interface FactoryMemoryPersistenceRuntimeCheck { checkId: string; passed: boolean; message: string }
export interface FactoryMemoryPersistenceRuntimeBlocker { blockerId: string; recordId?: string; message: string }
export interface FactoryMemoryPersistenceRuntimeWarning { warningId: string; recordId?: string; message: string }
export interface FactoryMemoryPersistenceRuntimeRecordWriteResult { memoryRecordId: string; status: 'written' | 'idempotent_noop' | 'blocked' | 'failed'; targetAbsolutePath: string; metadataAbsolutePath: string; indexAbsolutePath: string; fingerprint: string; idempotencyKey: string; written: boolean; idempotent: boolean; readbackVerified: boolean; rollbackAttempted: boolean; rollbackSucceeded?: boolean; sanitizedError?: string }
export interface FactoryMemoryPersistenceRuntimeWriteResult { written: boolean; idempotent: boolean; readbackVerified: boolean; rollbackAttempted: boolean; rollbackSucceeded?: boolean; sanitizedError?: string }
export interface FactoryMemoryPersistenceRuntimeMetadata { metadataKind: 'factory-memory-record-persistence-metadata'; metadataVersion: '1.0'; runtimePersistenceId: string; sourcePersistenceId: string; sourceApprovalId: string; sourceAdmissionId: string; memoryRecordId: string; memoryRecordKind: string; namespace: string; projectNamespace: string; fingerprint: string; idempotencyKey: string; logicalTarget: string; writtenAt: string; writtenBy: string; notExecutable: true; embeddingsCreated: false; codexTaskCreated: false; globalPromotionAllowed: false; projectCreated: false; repositoryCreated: false; deployed: false }
export interface FactoryMemoryPersistenceRuntimeIndex { indexKind: 'factory-project-memory-index'; indexVersion: '1.0'; projectNamespace: string; generatedAt: string; generatedBy: string; records: { memoryRecordId: string; memoryRecordKind: string; logicalTarget: string; fingerprint: string; idempotencyKey: string; metadataPath: string }[]; fingerprints: string[]; idempotencyKeys: string[]; count: number; embeddingsCreated: false; codexTaskCreated: false; deployed: false }
export interface FactoryMemoryPersistenceRuntimeResult { runtimePersistenceId: string; runtimePersistenceKind: FactoryMemoryPersistenceRuntimeKind; runtimePersistenceVersion: FactoryMemoryPersistenceRuntimeVersion; executedAt: string; executedBy: string; sourcePersistenceId: string; sourceApprovalId: string; sourceAdmissionId: string; storageRoot: string; status: FactoryMemoryPersistenceRuntimeStatus; recordsWritten: number; recordsIdempotent: number; recordsBlocked: number; writeResults: FactoryMemoryPersistenceRuntimeRecordWriteResult[]; indexResult?: { written: boolean; readbackVerified: boolean; indexPaths: string[] }; metadata: FactoryMemoryPersistenceRuntimeMetadata[]; checks: FactoryMemoryPersistenceRuntimeCheck[]; blockers: FactoryMemoryPersistenceRuntimeBlocker[]; warnings: FactoryMemoryPersistenceRuntimeWarning[]; rollbackAttempted: boolean; rollbackSucceeded?: boolean; sanitizedError?: string; canCreateEmbeddings: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryPersistenceRuntimeSummary { runtimePersistenceId: string; sourcePersistenceId: string; status: FactoryMemoryPersistenceRuntimeStatus; recordsWritten: number; recordsIdempotent: number; recordsBlocked: number; fingerprintsCount: number; idempotencyKeysCount: number; embeddingsCreated: false; codexTaskCreated: false; recommendedNextStep: string }
export interface FactoryMemoryPersistenceRuntimeValidationResult { ok: boolean; errors: string[]; warnings: string[] }
