const fs = require('node:fs/promises');
const path = require('node:path');
const { resolveFactoryHermesResearchRuntimeApprovalPaths, assertApprovalPathContained } = require('./hermes-research-runtime-approval.path.cjs');

const KIND = 'factory-hermes-research-runtime-approval';
const VERSION = '1.0';
const NEXT = 'Proceed to Factory Hermes Research Runtime Adapter v1; direct Hermes execution remains forbidden.';
const notAuthorizedActions = ['execute_hermes_now', 'execute_hermes_outside_adapter', 'run_hermes_scripts_now', 'execute_selected_interface_now', 'create_runtime_in_this_gate', 'execute_python_now', 'execute_uv_now', 'execute_pip_now', 'execute_setup_py_now', 'call_models_now', 'access_credentials_now', 'use_network_now', 'scrape_now', 'deploy_now', 'mutate_project_files_now'];
const requiredAdapterControls = ['shell:false', 'timeout', 'killSwitch', 'processTreeKill', 'sanitized stdout/stderr', 'bounded cwd', 'bounded filesystem writes', 'result ingestion', 'JEFE review'];
const requiredNextGates = ['Factory Hermes Research Runtime Adapter v1', 'Factory Hermes Research Result Ingestion Gate v1', 'Factory Hermes Research JEFE Review Gate v1'];
async function readJson(file) { return JSON.parse(await fs.readFile(file, 'utf8')); }
function evaluate(input) {
  const b = input.boundaryResult; const c = b?.hermesResearchRuntimeBoundaryContract; const id = `hermes-research-runtime-approval:75b300f:${input.approvedAt}`;
  const selectedInterface = b?.selectedInterface;
  const base = { approvalId: id, approvalKind: KIND, approvalVersion: VERSION, approvedAt: input.approvedAt, approvedBy: input.approvedBy, toolId: 'hermes_agent', auditedHead: b?.auditedHead || '', selectedCandidateId: b?.selectedCandidateId || '', commandName: selectedInterface?.commandName, pythonEntrypoint: selectedInterface?.pythonEntrypoint, selectedInterface, boundaryResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-boundary-result.json', checks: [], blockers: [], warnings: [], canCreateRuntimeNow: false, canExecuteHermesNow: false, canExecuteHermesOutsideAdapter: false, canRunHermesScripts: false, canUseNetworkNow: false, canUseCredentialsNow: false, canCallModelsNow: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: NEXT };
  if (!b || !c) return { ...base, status: 'blocked', decision: 'blocked_missing_boundary_contract', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_missing_boundary_contract', message: 'Boundary result is required.' }] };
  if (b.status !== 'boundary_contract_created' || b.canProceedToResearchRuntimeApproval !== true) return { ...base, status: 'blocked', decision: 'blocked_boundary_not_created', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_not_created', message: 'Boundary not created.' }] };
  if (b.canCreateRuntimeNow !== false || b.canExecuteHermes !== false || c.commandBoundary.commandsAllowedNow.length !== 0) return { ...base, status: 'blocked', decision: 'blocked_boundary_allows_execution_now', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_allows_execution_now', message: 'Boundary allows execution.' }] };
  if (b.canUseNetwork !== false || c.networkBoundary.networkAllowedNow !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_allows_network_now', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_allows_network_now', message: 'Boundary allows network.' }] };
  if (b.canUseCredentials !== false || c.credentialBoundary.credentialsAllowedNow !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_allows_credentials_now', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_allows_credentials_now', message: 'Boundary allows credentials.' }] };
  if (b.canCallModels !== false || c.modelBoundary.modelCallsAllowedNow !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_allows_model_calls_now', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_boundary_allows_model_calls_now', message: 'Boundary allows model calls.' }] };
  if (!input.humanApprovalRef) return { ...base, status: 'human_review_required', decision: 'blocked_missing_human_approval', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] };
  if (!selectedInterface?.commandName || !selectedInterface.pythonEntrypoint) return { ...base, status: 'blocked', decision: 'request_boundary_repair_before_approval', canProceedToResearchRuntimeAdapter: false, blockers: [{ blockerId: 'missing_selected_interface_identity', message: 'Selected interface commandName and pythonEntrypoint are required.' }] };
  const receipt = { receiptId: `${id}:receipt`, approvalId: id, toolId: 'hermes_agent', auditedHead: b.auditedHead, approvedBy: input.approvedBy, approvedAt: input.approvedAt, humanApprovalRef: input.humanApprovalRef, selectedCandidateId: b.selectedCandidateId, decision: 'hermes_research_runtime_approved_for_adapter_candidate', scope: 'hermes_research_runtime_adapter_candidate_only', approvedNextGate: 'Factory Hermes Research Runtime Adapter v1', limitations: ['Approval is only for a future adapter candidate.', 'No runtime is created in this gate.', 'No direct Hermes execution is authorized.'], notAuthorizedActions };
  const envelope = { envelopeId: `${id}:envelope`, approvalId: id, toolId: 'hermes_agent', auditedHead: b.auditedHead, selectedCandidateId: b.selectedCandidateId, selectedInterface, boundaryContractRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-boundary-result.json', boundaryContractSummary: { contractId: c.contractId, commandName: selectedInterface.commandName, pythonEntrypoint: selectedInterface.pythonEntrypoint, commandBoundary: c.commandBoundary, networkBoundary: c.networkBoundary, credentialBoundary: c.credentialBoundary, modelBoundary: c.modelBoundary, safetyBoundary: c.safetyBoundary }, approvedNextGate: 'Factory Hermes Research Runtime Adapter v1', adapterReadinessStatus: 'approved_for_adapter_candidate', executionAuthorizationScope: 'future_runtime_adapter_only', directExecutionNow: false, futureRuntimeCanExecuteSelectedInterfaceUnderBoundary: true, futureRuntimeNetworkAllowed: false, futureRuntimeCredentialsAllowed: false, futureRuntimeModelCallsAllowed: false, futureRuntimeProjectMutationAllowed: false, futureRuntimeDeployAllowed: false, requiredAdapterControls, requiredNextGates, canProceedToResearchRuntimeAdapter: true, canCreateRuntimeNow: false, canExecuteHermesNow: false, canExecuteHermesOutsideAdapter: false, recommendedNextStep: NEXT };
  return { ...base, status: 'approved_for_adapter_candidate', decision: 'hermes_research_runtime_approved_for_adapter_candidate', researchRuntimeApprovalReceipt: receipt, approvedHermesResearchRuntimeAdapterEnvelope: envelope, canProceedToResearchRuntimeAdapter: true };
}
async function executeFactoryHermesResearchRuntimeApproval(input = {}) {
  const paths = resolveFactoryHermesResearchRuntimeApprovalPaths();
  assertApprovalPathContained(paths.installRoot, path.join(paths.root, '.codex-temp'));
  assertApprovalPathContained(paths.approvalResult, paths.installRoot);
  const boundaryResult = await readJson(paths.boundaryResult);
  const result = evaluate({ approvedAt: input.approvedAt || '2026-07-21T19:00:00.000Z', approvedBy: input.approvedBy || 'factory-hermes-research-runtime-approval-smoke', humanApprovalRef: input.humanApprovalRef || 'human-review/hermes-research-runtime-approval-v1', boundaryResult });
  await fs.writeFile(paths.approvalResult, JSON.stringify(result, null, 2));
  return result;
}
module.exports = { executeFactoryHermesResearchRuntimeApproval, evaluateFactoryHermesResearchRuntimeApproval: evaluate };
