export type FactoryUvProvisioningVerificationVersion = '1.0'
export type FactoryUvProvisioningVerificationKind = 'factory-uv-provisioning-verification'
export type FactoryUvProvisioningVerificationStatus = 'verified' | 'blocked' | 'failed'
export type FactoryUvProvisioningVerificationDecision = 'uv_provisioning_verified' | 'blocked_missing_provisioning_manifest' | 'blocked_missing_provisioning_result' | 'blocked_invalid_provisioning_manifest' | 'blocked_invalid_provisioning_result' | 'blocked_missing_uv_executable' | 'blocked_uv_path_outside_codex_temp' | 'failed_uv_version_recheck' | 'request_uv_provisioning_repair'
export interface FactoryUvProvisioningVerificationInput { verifiedAt: string; verifiedBy: string; expectedReleaseTag?: string; expectedVersionPrefix?: string; uvRootRef?: string; policy?: Partial<FactoryUvProvisioningVerificationPolicy> }
export interface FactoryUvProvisioningVerificationPolicy { requireProvisioningManifest: boolean; requireProvisioningResultJson: boolean; requireUvExecutable: boolean; requireUvRootUnderCodexTemp: boolean; requireExecutableUnderCodexTemp: boolean; requireProvisioningSuccess: boolean; requireChecksumVerified: boolean; requireUvVersionRecheck: boolean; allowUvVersionOnly: boolean; forbidUvVenv: boolean; forbidUvSync: boolean; forbidUvRun: boolean; forbidUvPip: boolean; forbidPipExecution: boolean; forbidPythonExecution: boolean; forbidSetupPyExecution: boolean; forbidHermesExecution: boolean; forbidHermesScripts: boolean; forbidShell: boolean; forbidCmd: boolean; forbidPowerShell: boolean; forbidCurl: boolean; forbidWget: boolean; forbidDownloadInThisGate: boolean; forbidExtractionInThisGate: boolean; forbidGlobalInstall: boolean; forbidPathMutation: boolean; forbidPackageFileMutation: boolean; forbidCredentials: boolean; forbidModelCalls: boolean; forbidDeploy: boolean; requireFutureHermesPythonRuntimeRetryGate: boolean; requireJefeReviewAfterHermesPythonRuntimeRetry: boolean }
export interface FactoryUvProvisioningVerificationCheck { checkId: string; ok: boolean; message: string }
export interface FactoryUvProvisioningVerificationBlocker { blockerId: string; message: string }
export interface FactoryUvProvisioningVerificationWarning { warningId: string; message: string }
export interface FactoryUvProvisioningVerificationCommandResult { kind: 'uv_version_recheck'; commandRef: string; args: string[]; exitCode: number | null; shell: false; stdout: string; stderr: string; timedOut: boolean }
export type FactoryUvProvisioningVerificationArtifactStatus = 'present' | 'missing' | 'valid' | 'invalid' | 'verified'
export interface FactoryUvProvisioningVerificationResult { uvProvisioningVerificationId: string; uvProvisioningVerificationKind: FactoryUvProvisioningVerificationKind; uvProvisioningVerificationVersion: FactoryUvProvisioningVerificationVersion; verifiedAt: string; verifiedBy: string; toolId: 'uv'; toolName: 'uv'; uvRootRef: string; executableRef: string; manifestRef: string; provisioningResultRef: string; verificationResultRef: string; releaseTag?: string; artifact?: string; checksumStatus: string; executableStatus: string; versionCheckStatus: string; installStatus: string; executionStatus: string; shellStatus: 'not_allowed'; pipStatus: 'not_executed'; pythonStatus: 'not_executed'; setupPyStatus: 'not_executed'; hermesExecutionStatus: 'not_allowed'; scriptsStatus: 'not_executed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; projectMutationStatus: 'not_allowed'; deployStatus: 'not_allowed'; commandResults: FactoryUvProvisioningVerificationCommandResult[]; checks: FactoryUvProvisioningVerificationCheck[]; blockers: FactoryUvProvisioningVerificationBlocker[]; warnings: FactoryUvProvisioningVerificationWarning[]; status: FactoryUvProvisioningVerificationStatus; decision: FactoryUvProvisioningVerificationDecision; canUseUvForHermesPythonRuntime: boolean; canExecuteUvForProjectOps: false; canExecuteHermes: false; canRunHermesScripts: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryUvProvisioningVerificationValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryUvProvisioningVerificationSummary { uvProvisioningVerificationId: string; toolId: 'uv'; releaseTag?: string; executableRef: string; checksumStatus: string; executableStatus: string; versionCheckStatus: string; installStatus: string; executionStatus: string; shellStatus: 'not_allowed'; pipStatus: 'not_executed'; pythonStatus: 'not_executed'; setupPyStatus: 'not_executed'; hermesExecutionStatus: 'not_allowed'; canUseUvForHermesPythonRuntime: boolean; canExecuteUvForProjectOps: false; nextStep: string }
