const { readdir, readFile } = require('node:fs/promises')
const path = require('node:path')
const { assertFactoryMemoryRegistryRootAllowed, assertFactoryMemoryRegistryPathContained, isSafeFactoryMemoryRegistryRelativePath } = require('./memory-registry.path.cjs')
async function walk(root) { const files = []; async function visit(dir) { for (const item of await readdir(dir, { withFileTypes: true })) { const absolute = path.join(dir, item.name); if (item.isDirectory()) await visit(absolute); else if (item.isFile()) files.push(absolute) } } try { await visit(root) } catch (error) { if (error.code !== 'ENOENT') throw error } return files }
const logical = (root, absolute) => path.relative(root, absolute).replace(/\\/gu, '/')
const safeFlags = (meta) => meta.notExecutable === true && meta.embeddingsCreated === false && meta.codexTaskCreated === false && meta.globalPromotionAllowed === false && meta.projectCreated === false && meta.repositoryCreated === false && meta.deployed === false
async function readFactoryMemoryRegistryEntries(input) { const storageRoot = assertFactoryMemoryRegistryRootAllowed(input.storageRoot); if (!input.readAt || !input.readBy) throw new Error('readAt and readBy are required.'); const projectsRoot = assertFactoryMemoryRegistryPathContained(storageRoot, 'factory-memory/projects'); const files = await walk(projectsRoot); const metas = files.filter((file) => file.endsWith('.v1.meta.json') && !file.endsWith('.tmp')); const records = files.filter((file) => file.endsWith('.v1.json') && !file.endsWith('.v1.meta.json') && path.basename(file) !== 'index.v1.json' && !file.endsWith('.tmp')); const projectFiles = files.filter((file) => path.basename(file) === 'index.v1.json'); const entries = []; const orphans = []; const warnings = []; const blockers = []
  for (const metaPath of metas) { const metaLogical = logical(storageRoot, metaPath); const recordPath = metaPath.replace(/\.v1\.meta\.json$/u, '.v1.json'); const recordLogical = logical(storageRoot, recordPath); const project = metaLogical.split('/')[2] || 'unknown'; let meta; try { meta = JSON.parse(await readFile(metaPath, 'utf8')) } catch { orphans.push({ orphanKind: 'metadata_without_record', logicalPath: metaLogical, relatedLogicalPath: recordLogical, projectSlugOrId: project }); continue } let record; try { record = JSON.parse(await readFile(recordPath, 'utf8')) } catch (error) { if (error.code === 'ENOENT') { orphans.push({ orphanKind: 'metadata_without_record', logicalPath: metaLogical, relatedLogicalPath: recordLogical, projectSlugOrId: project }); continue } throw error }
    const errors = []; if (!meta.memoryRecordId || !meta.fingerprint || !meta.idempotencyKey) errors.push('Metadata identity, fingerprint and idempotency key are required.'); if (!isSafeFactoryMemoryRegistryRelativePath(meta.logicalTarget) || meta.logicalTarget !== recordLogical) errors.push('Metadata logical target is unsafe or inconsistent.'); if (!safeFlags(meta)) errors.push('Metadata safety flags are invalid.'); const status = errors.length ? 'blocked' : 'ready'; entries.push({ registryEntryId: `memory-registry:${meta.memoryRecordId}:${meta.fingerprint || 'missing'}`, memoryRecordId: meta.memoryRecordId || record.memoryRecordId || '', memoryRecordKind: meta.memoryRecordKind || record.memoryRecordKind || '', memoryRecordVersion: record.memoryRecordVersion || '1.0', namespace: meta.namespace || record.namespace || '', projectNamespace: meta.projectNamespace || record.projectNamespace || '', projectSlugOrId: project, logicalTarget: recordLogical, metadataLogicalTarget: metaLogical, absoluteTargetPath: recordPath, absoluteMetadataPath: metaPath, fingerprint: meta.fingerprint || '', idempotencyKey: meta.idempotencyKey || '', sourcePersistenceId: meta.sourcePersistenceId || '', sourceApprovalId: meta.sourceApprovalId || '', sourceAdmissionId: meta.sourceAdmissionId || '', writtenAt: meta.writtenAt || '', writtenBy: meta.writtenBy || '', status, validation: { ok: errors.length === 0, errors, warnings: [] }, notExecutable: true, embeddingsCreated: false, codexTaskCreated: false, canExecuteCodex: false, globalPromotionAllowed: false, projectCreated: false, repositoryCreated: false, deployed: false, warnings: [], blockers: errors }) }
  const metaRecordSet = new Set(metas.map((file) => file.replace(/\.v1\.meta\.json$/u, '.v1.json'))); for (const recordPath of records) if (!metaRecordSet.has(recordPath)) { const recordLogical = logical(storageRoot, recordPath); orphans.push({ orphanKind: 'record_without_metadata', logicalPath: recordLogical, relatedLogicalPath: recordLogical.replace(/\.v1\.json$/u, '.v1.meta.json'), projectSlugOrId: recordLogical.split('/')[2] || 'unknown' }) }
  const projectIndexes = []; for (const indexPath of projectFiles) { const logicalPath = logical(storageRoot, indexPath); let valid = true; let recordsCount = 0; const indexWarnings = []; try { const index = JSON.parse(await readFile(indexPath, 'utf8')); recordsCount = Array.isArray(index.records) ? index.records.length : 0; if (index.embeddingsCreated !== false || index.codexTaskCreated !== false || index.deployed !== false) { valid = false; indexWarnings.push('Project index has unsafe flags.') } projectIndexes.push({ projectNamespace: index.projectNamespace || `factory/projects/${logicalPath.split('/')[2]}`, logicalPath, absolutePath: indexPath, valid, recordsCount, warnings: indexWarnings }) } catch { projectIndexes.push({ projectNamespace: `factory/projects/${logicalPath.split('/')[2]}`, logicalPath, absolutePath: indexPath, valid: false, recordsCount: 0, warnings: ['Project index is invalid JSON.'] }) } }
  return { storageRoot, readAt: input.readAt, readBy: input.readBy, entries, projectIndexes, orphans, warnings, blockers }
}
module.exports = { readFactoryMemoryRegistryEntries }
