import type { FactoryProjectContractV1, FactoryProjectContractValidationResult } from '../project-contract/index.ts'
import type { FactoryProjectContractCompatibilityResult } from '../project-contract-compatibility/index.ts'

export type FactoryProjectContractApprovalVersion = '1.0'
export type FactoryProjectContractApprovalKind = 'factory-project-contract-approval'
export type FactoryProjectContractApprovalDecision = 'reject_contract_draft' | 'request_contract_changes' | 'human_review_required' | 'approve_contract_for_final_review' | 'approve_contract_for_persistence_candidate' | 'blocked'
export type FactoryProjectContractApprovalStatus = 'approved_candidate' | 'requires_changes' | 'requires_human_review' | 'rejected' | 'blocked'
export type FactoryProjectContractApprovalReviewer = { reviewerId: string; role: 'jefe' | 'human_reviewer' | 'factory_owner'; human: boolean }
export interface FactoryProjectContractApprovalPolicy { requireCompatibleResult: true; requireContractDraft: true; requireContractValidationOk: true; requireHumanApproval: true; requireReviewerIdentity: true; requireNoBlockers: true; requireNoCriticalWarnings: true; requireRuntimeIndependence: true; requireOwnRepository: true; requireOwnRoot: true; forbidJefeRuntimeDependency: true; forbidJefeModuleImports: true; requireEnvironmentVariablesWithoutValues: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; allowPersistenceCandidateOnly: true }
export interface FactoryProjectContractApprovalInput { compatibilityResult: FactoryProjectContractCompatibilityResult; createdAt: string; reviewedBy: string; reviewerRole?: FactoryProjectContractApprovalReviewer['role']; humanApprovalRef?: string; policy?: Partial<FactoryProjectContractApprovalPolicy>; reviewNotes?: string[] }
export interface FactoryProjectContractApprovalRequirement { requirementId: string; description: string; satisfied: boolean; source: 'compatibility' | 'contract' | 'reviewer' | 'approval' }
export interface FactoryProjectContractApprovalCheck { checkId: string; category: 'compatibility' | 'contract' | 'approval' | 'reviewer' | 'independence' | 'repository' | 'environment' | 'execution' | 'warnings'; passed: boolean; message: string }
export interface FactoryProjectContractApprovalBlocker { blockerId: string; category: FactoryProjectContractApprovalCheck['category']; message: string }
export interface FactoryProjectContractApprovalWarning { warningId: string; severity: 'info' | 'warning' | 'critical'; message: string }
export interface FactoryProjectContractApprovalReceipt { receiptId: string; approvalId: string; compatibilityId: string; candidateId: string; reviewedBy: string; reviewedAt: string; humanApprovalRef: string; decision: FactoryProjectContractApprovalDecision; scope: 'contract_persistence_candidate_only'; limitations: string[]; notAuthorizedActions: Array<'execute_codex' | 'create_project' | 'create_repository' | 'deploy' | 'publish' | 'mutate_runtime' | 'access_secrets'> }
export interface FactoryProjectContractApprovedEnvelope { envelopeId: string; approvalId: string; contractDraft: FactoryProjectContractV1; validation: FactoryProjectContractValidationResult; persistenceStatus: 'not_persisted'; runtimeStatus: 'not_executable'; codexStatus: 'not_allowed'; repositoryStatus: 'not_created'; deployStatus: 'not_allowed'; recommendedNextStep: string }
export interface FactoryProjectContractApprovalResult { approvalId: string; approvalKind: FactoryProjectContractApprovalKind; approvalVersion: FactoryProjectContractApprovalVersion; createdAt: string; reviewedBy: string; candidateId: string; compatibilityId: string; opportunityId: string; status: FactoryProjectContractApprovalStatus; decision: FactoryProjectContractApprovalDecision; requirements: FactoryProjectContractApprovalRequirement[]; checks: FactoryProjectContractApprovalCheck[]; blockers: FactoryProjectContractApprovalBlocker[]; warnings: FactoryProjectContractApprovalWarning[]; approvalReceipt?: FactoryProjectContractApprovalReceipt; approvedContractEnvelope?: FactoryProjectContractApprovedEnvelope; canPersistFactoryProjectContract: false; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryProjectContractApprovalValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryProjectContractApprovalSummary { approvalId: string; compatibilityId: string; candidateId: string; decision: FactoryProjectContractApprovalDecision; status: FactoryProjectContractApprovalStatus; receiptPresent: boolean; envelopePresent: boolean; persistenceStatus?: string; codexStatus?: string; recommendedNextStep: string }
