export type FactoryHermesPythonInstallRuntimeRetryVersion = '1.0'
export type FactoryHermesPythonInstallRuntimeRetryKind = 'factory-hermes-python-install-runtime-retry'
export type FactoryHermesPythonInstallRuntimeRetryStatus = 'success' | 'blocked' | 'failed'
export type FactoryHermesPythonInstallRuntimeRetryDecision = 'hermes_python_install_completed_with_verified_uv' | 'hermes_python_install_reused_existing_success_with_verified_uv' | 'hermes_python_install_confirmed_existing_env_with_verified_uv_sync' | 'blocked_uv_not_verified_for_hermes_python_runtime' | 'blocked_invalid_hermes_python_install_inputs' | 'failed_uv_version_check' | 'failed_uv_venv' | 'failed_uv_sync' | 'request_hermes_python_install_runtime_repair'
export interface FactoryHermesPythonInstallRuntimeRetryInput { executedAt: string; executedBy: string }
export interface FactoryHermesPythonInstallRuntimeRetryCommandResult { kind: 'uv_version_recheck_for_hermes' | 'uv_venv_hermes_python_env' | 'uv_sync_hermes_locked_no_install_project'; commandRef: string; args: string[]; cwd: string; shell: false; exitCode: number | null; stdout: string; stderr: string; timedOut: boolean; envRefs?: Record<string, string> }
export interface FactoryHermesPythonInstallRuntimeRetryResult { retryId: string; retryKind: FactoryHermesPythonInstallRuntimeRetryKind; retryVersion: FactoryHermesPythonInstallRuntimeRetryVersion; executedAt: string; executedBy: string; toolId: 'hermes_agent'; auditedHead: string; sourceRootRef: string; installRootRef: string; pythonEnvRootRef: string; uvExecutableRef: string; uvVerificationRef: string; uvVersionOutput?: string; commandResults: FactoryHermesPythonInstallRuntimeRetryCommandResult[]; pythonInstallStatus: string; venvStatus: string; uvStatus: string; pipStatus: 'not_executed'; pythonDirectStatus: 'not_executed'; setupPyStatus: 'not_executed'; hermesExecutionStatus: 'not_allowed'; scriptsStatus: 'not_executed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; projectMutationStatus: 'not_allowed'; deployStatus: 'not_allowed'; status: FactoryHermesPythonInstallRuntimeRetryStatus; decision: FactoryHermesPythonInstallRuntimeRetryDecision; idempotentExistingInstallUsed?: boolean; reusedExistingPythonEnv?: boolean; syncConfirmedExistingEnv?: boolean; previousDecision?: string; blockers: Array<{ blockerId: string; message: string }>; warnings: Array<{ warningId: string; message: string }>; checks: Array<{ checkId: string; ok: boolean; message: string }>; canProceedToPythonInstallVerification: boolean; canExecuteHermes: false; canRunHermesScripts: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesPythonInstallRuntimeRetryValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesPythonInstallRuntimeRetrySummary { retryId: string; status: FactoryHermesPythonInstallRuntimeRetryStatus; decision: FactoryHermesPythonInstallRuntimeRetryDecision; auditedHead: string; pythonEnvRootRef: string; uvExecutableRef: string; pythonInstallStatus: string; venvStatus: string; uvStatus: string; canProceedToPythonInstallVerification: boolean; canExecuteHermes: false; nextStep: string }
