export type FactoryHermesWrapperNoToolModeImplementationVersion = '1.0'
export type FactoryHermesWrapperNoToolModeImplementationKind = 'factory-hermes-wrapper-no-tool-mode-implementation'
export type FactoryHermesWrapperNoToolModeImplementationStatus = 'wrapper_no_tool_mode_implementation_completed' | 'wrapper_no_tool_mode_implementation_blocked'
export type FactoryHermesWrapperNoToolModeImplementationDecision = 'hermes_wrapper_no_tool_mode_implementation_completed_for_verification_planning' | 'hermes_wrapper_no_tool_mode_implementation_blocked_invalid_approval'
export interface FactoryHermesWrapperNoToolModeImplementationInput { implementedAt: string; implementedBy: string; implementationApprovalResult?: any; implementationPlanningResult?: any; runtimeModuleFiles?: string[] }
export interface FactoryHermesWrapperNoToolModeImplementationValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export const FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_IMPLEMENTATION_KIND: FactoryHermesWrapperNoToolModeImplementationKind = 'factory-hermes-wrapper-no-tool-mode-implementation'
export const FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_IMPLEMENTATION_VERSION: FactoryHermesWrapperNoToolModeImplementationVersion = '1.0'
export const IMPLEMENTATION_NOT_AUTHORIZED_ACTIONS = ['execute_wrapper_now','create_temp_config_now','modify_hermes_source_now','approve_research_runtime_adapter_now','execute_hermes_now','execute_oneshot_now','pass_prompt_now','run_research_now','call_models_now','use_network_now','access_credentials_now','read_env_secrets_now','enable_toolsets_now','mutate_runtime_filesystem_now','create_runtime_run_root_now','ingest_real_output_now','promote_findings_now','execute_uv_now','execute_python_now','execute_pip_now','execute_setup_py_now','deploy_now']
function validApproval(r: any) { const d = r?.hermesWrapperNoToolModeImplementationApprovalDecision; const e = r?.approvedWrapperNoToolModeImplementationEnvelope; return r?.status === 'wrapper_no_tool_mode_implementation_approval_granted' && r?.decision === 'hermes_wrapper_no_tool_mode_implementation_approved_for_next_gate' && r?.implementationApprovalStatus === 'approved_for_implementation_only' && r?.selectedWrapperStrategy === 'wrapper_temp_config_no_toolsets' && e?.approvedFor === 'wrapper_no_tool_mode_implementation_only' && d?.wrapperImplementationApproved === true && d?.wrapperExecutionApproved === false && d?.tempConfigCreationApproved === false && d?.researchRuntimeAdapterApproved === false && d?.researchExecutionApproved === false && d?.hermesExecutionApproved === false && d?.modelCallsApproved === false && d?.networkApproved === false && d?.credentialAccessApproved === false && r?.canProceedToHermesWrapperNoToolModeImplementation === true && r?.canRunResearchNow === false }
function validPlanning(r: any) { const c = r?.hermesWrapperNoToolModeImplementationPlanCandidate; return r?.status === 'wrapper_no_tool_mode_implementation_plan_created' && r?.selectedWrapperStrategy === 'wrapper_temp_config_no_toolsets' && r?.wrapperImplementationArchitecturePlan && r?.wrapperTempConfigPlan && r?.wrapperNoToolEnforcementPlan && r?.wrapperValidationPlan && r?.wrapperImplementationRiskRegister && c?.wrapperExecutionAllowedNow === false && c?.tempConfigCreationAllowedNow === false && c?.sourceMutationAllowedNow === false && c?.researchRuntimeAdapterAllowedNow === false && c?.researchExecutionAllowedNow === false }
export function evaluateFactoryHermesWrapperNoToolModeImplementation(input: FactoryHermesWrapperNoToolModeImplementationInput) {
  const ok = validApproval(input.implementationApprovalResult) && validPlanning(input.implementationPlanningResult) && (input.runtimeModuleFiles || []).length >= 2; const implementationId = `hermes-wrapper-no-tool-mode-implementation:75b300f:${input.implementedAt}`; const status = ok ? 'wrapper_no_tool_mode_implementation_completed' : 'wrapper_no_tool_mode_implementation_blocked'; const decision = ok ? 'hermes_wrapper_no_tool_mode_implementation_completed_for_verification_planning' : 'hermes_wrapper_no_tool_mode_implementation_blocked_invalid_approval';
  const wrapperRuntimeModuleManifest = { modulePaths: ['src/factory/hermes-wrapper-no-tool-mode-runtime/index.ts','electron/factory/hermes-wrapper-no-tool-mode-runtime/index.cjs'], exportedFunctions: ['createFactoryHermesWrapperNoToolModeTempConfigCandidate','serializeFactoryHermesWrapperNoToolModeTempConfig','validateFactoryHermesWrapperNoToolModeTempConfig','buildFactoryHermesWrapperNoToolModeCommandEnvelope','buildFactoryHermesWrapperNoToolModeManifest','evaluateFactoryHermesWrapperNoToolModeRuntimeBuild'], implementationType: 'code_only', executionSurface: 'none', hermesSourceMutation: false, dependenciesAdded: false };
  const wrapperRuntimeSafetyManifest = { noChildProcess: true, noSpawnExecFork: true, noFetchHttpNetDns: true, noProcessEnvReads: true, noDotenvReads: true, noCredentialReads: true, noPromptPassing: true, noModelCalls: true, noNetwork: true, noTempConfigWrites: true, noRunRootCreation: true, noHermesExecution: true, noWrapperExecution: true };
  const wrapperNoToolModeConfigSerializerManifest = { serializerExists: true, serializerWritesFiles: false, serializerReturnsVirtualConfigOnly: true, containsSecrets: false, containsCredentialValues: false, containsEnvDump: false, exactConfigSchemaKnown: input.implementationPlanningResult?.wrapperTempConfigPlan?.exactConfigSchemaKnown ?? 'unknown', emptyToolsetsSupport: input.implementationPlanningResult?.wrapperTempConfigPlan?.emptyToolsetsInConfigSupported ?? 'unknown', blocksRunnableModeWhenUnknown: true };
  const wrapperNoToolModeCommandEnvelopeManifest = { commandEnvelopeBuilderExists: true, executionAllowed: false, promptAllowed: false, credentialsAllowed: false, credentialAccessAllowed: false, networkAllowed: false, modelCallsAllowed: false, toolsetsEnabled: false, runtimeAdapterAllowed: false, researchExecutionAllowed: false };
  const wrapperNoToolModeVerificationPlanningEnvelope = { approvedFor: 'wrapper_no_tool_mode_verification_planning_only', nextGate: 'Factory Hermes Wrapper No-Tool Mode Verification Planning Gate v1', verificationStillRequired: ['static module safety scan','serializer validation','command envelope validation','temp config virtual validation','no forbidden imports validation','no Hermes execution validation','future controlled verification approval'] };
  return { implementationId, implementationKind: FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_IMPLEMENTATION_KIND, implementationVersion: FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_IMPLEMENTATION_VERSION, implementedAt: input.implementedAt, implementedBy: input.implementedBy, toolId: 'hermes_agent', selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets', implementationApprovalRef: input.implementationApprovalResult?.approvalId, implementationPlanningRef: input.implementationPlanningResult?.planningId, wrapperRuntimeModuleManifest, wrapperRuntimeSafetyManifest, wrapperNoToolModeConfigSerializerManifest, wrapperNoToolModeCommandEnvelopeManifest, wrapperNoToolModeVerificationPlanningEnvelope, wrapperNoToolModeImplementationReceipt: { receiptId: `${implementationId}:receipt`, implementationId, toolId: 'hermes_agent', implementedBy: input.implementedBy, implementedAt: input.implementedAt, decision, implementationStatus: ok ? 'implemented_code_only_not_executable' : 'blocked', scope: 'hermes_wrapper_no_tool_mode_implementation_code_only', approvedNextGate: 'Factory Hermes Wrapper No-Tool Mode Verification Planning Gate v1', limitations: ['Code only. Verification planning is required before any wrapper use.'], notAuthorizedActions: IMPLEMENTATION_NOT_AUTHORIZED_ACTIONS }, hermesWrapperNoToolModeImplementationResultRecord: { recordId: `${implementationId}:record`, wrapperRuntimeImplemented: ok, wrapperExecutionApproved: false, tempConfigCreationApproved: false, hermesExecutionApproved: false, researchRuntimeAdapterApproved: false, researchExecutionApproved: false }, checks: [], blockers: ok ? [] : [{ blockerId: 'invalid_implementation_approval', message: 'Implementation approval or planning result is not valid.' }], warnings: [], status, decision, implementationStatus: ok ? 'implemented_code_only_not_executable' : 'blocked', wrapperRuntimeImplemented: ok, wrapperExecutionAllowedNow: false, tempConfigCreationAllowedNow: false, hermesExecutionAllowedNow: false, researchRuntimeAdapterAllowedNow: false, researchExecutionAllowedNow: false, canProceedToHermesWrapperNoToolModeVerificationPlanning: ok, canProceedToHermesWrapperNoToolModeVerification: false, canProceedToResearchRuntimeAdapterApprovalRetry: false, canProceedToResearchRuntimeAdapter: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canMutateFilesystemNow: false, canUseFindings: false, recommendedNextStep: ok ? 'Proceed to Factory Hermes Wrapper No-Tool Mode Verification Planning Gate v1.' : 'Return to wrapper implementation approval.' }
}
export function validateFactoryHermesWrapperNoToolModeImplementationInput(input: FactoryHermesWrapperNoToolModeImplementationInput): FactoryHermesWrapperNoToolModeImplementationValidationResult { const errors: string[] = []; const warnings: string[] = []; if (!input?.implementedAt) errors.push('implementedAt required.'); if (!input?.implementedBy) errors.push('implementedBy required.'); if (!input?.implementationApprovalResult) errors.push('implementation approval required.'); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryHermesWrapperNoToolModeImplementationResult(result: any): FactoryHermesWrapperNoToolModeImplementationValidationResult { const errors: string[] = []; const warnings: string[] = []; if (result.status !== 'wrapper_no_tool_mode_implementation_completed') errors.push('status mismatch.'); if (result.decision !== 'hermes_wrapper_no_tool_mode_implementation_completed_for_verification_planning') errors.push('decision mismatch.'); if (result.wrapperRuntimeImplemented !== true) errors.push('runtime module not implemented.'); for (const key of ['wrapperExecutionAllowedNow','tempConfigCreationAllowedNow','hermesExecutionAllowedNow','researchRuntimeAdapterAllowedNow','researchExecutionAllowedNow','canProceedToHermesWrapperNoToolModeVerification','canProceedToResearchRuntimeAdapterApprovalRetry','canProceedToResearchRuntimeAdapter','canRunResearchNow','canExecuteHermesNow','canPassPromptNow','canUseNetworkNow','canUseCredentialsNow','canReadEnvSecretsNow','canCallModelsNow','canEnableToolsetsNow','canMutateFilesystemNow','canUseFindings']) if (result[key] !== false) errors.push(`${key} must be false.`); if (result.canProceedToHermesWrapperNoToolModeVerificationPlanning !== true) errors.push('verification planning must be true.'); return { ok: errors.length === 0, errors, warnings } }
export const serializeFactoryHermesWrapperNoToolModeImplementationResult = (result: any): string => `${JSON.stringify(result, null, 2)}\n`
export const parseFactoryHermesWrapperNoToolModeImplementationResult = (json: string): any => JSON.parse(json)
export const summarizeFactoryHermesWrapperNoToolModeImplementationResult = (result: any) => ({ implementationId: result.implementationId, status: result.status, decision: result.decision, implementationStatus: result.implementationStatus, wrapperRuntimeImplemented: result.wrapperRuntimeImplemented, canProceedToHermesWrapperNoToolModeVerificationPlanning: result.canProceedToHermesWrapperNoToolModeVerificationPlanning, canRunResearchNow: result.canRunResearchNow, nextStep: result.recommendedNextStep })
