export type FactoryHermesWrapperNoToolModeVerificationReviewVersion = '1.0'
export type FactoryHermesWrapperNoToolModeVerificationReviewKind = 'factory-hermes-wrapper-no-tool-mode-verification-review'
export type FactoryHermesWrapperNoToolModeVerificationReviewStatus = 'wrapper_no_tool_mode_verification_review_completed' | 'wrapper_no_tool_mode_verification_review_blocked'
export type FactoryHermesWrapperNoToolModeVerificationReviewDecision = 'hermes_wrapper_no_tool_mode_verification_review_accepted_for_adapter_approval_retry' | 'hermes_wrapper_no_tool_mode_verification_review_blocked'
export interface FactoryHermesWrapperNoToolModeVerificationReviewInput { reviewedAt: string; reviewedBy: string; verificationResult?: any; verificationApprovalResult?: any; verificationPlanningResult?: any; implementationResult?: any; adapterApprovalResult?: any }
export interface FactoryHermesWrapperNoToolModeVerificationReviewValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export const FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_REVIEW_KIND: FactoryHermesWrapperNoToolModeVerificationReviewKind = 'factory-hermes-wrapper-no-tool-mode-verification-review'
export const FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_REVIEW_VERSION: FactoryHermesWrapperNoToolModeVerificationReviewVersion = '1.0'
export const REVIEW_REQUIRED_LIMITATIONS = ['no_real_hermes_execution_tested','no_model_network_or_provider_tested','config_schema_partially_unknown','empty_toolsets_support_unknown','hidden_defaults_may_still_exist_in_real_cli_runtime','wrapper_verified_only_as_code_boundary']
export const REVIEW_REQUIRED_RISKS = ['static_scan_false_negative','serializer_declares_safe_but_schema_unknown','command_envelope_accidentally_runnable','hidden_defaults_not_detected','no_tool_mode_overclaimed','adapter_retry_confuses_review_with_runtime_approval']
export const REVIEW_NOT_AUTHORIZED_ACTIONS = ['proceed_to_research_runtime_adapter_now','execute_wrapper_against_hermes_now','create_temp_config_now','modify_hermes_source_now','execute_hermes_now','execute_oneshot_now','pass_prompt_now','run_research_now','call_models_now','use_network_now','access_credentials_now','read_env_secrets_now','enable_toolsets_now','mutate_runtime_filesystem_now','create_runtime_run_root_now','ingest_real_output_now','promote_findings_now','execute_uv_now','execute_python_now','execute_pip_now','execute_setup_py_now','deploy_now']
function validVerification(r: any) { return r?.status === 'wrapper_no_tool_mode_verification_completed' && r?.decision === 'hermes_wrapper_no_tool_mode_verified_for_review' && r?.verificationStatus === 'verified_code_only_not_runtime_executable' && r?.wrapperVerificationPassed === true && r?.canProceedToHermesWrapperNoToolModeVerificationReview === true && r?.canProceedToResearchRuntimeAdapterApprovalRetry === false && r?.canRunResearchNow === false }
function validPriorBlocks(r: any) { return r?.canProceedToResearchRuntimeAdapterApprovalRetry === false && r?.canProceedToResearchRuntimeAdapter === false && r?.canRunResearchNow === false && r?.canExecuteHermesNow === false && r?.canPassPromptNow === false && r?.canUseNetworkNow === false && r?.canUseCredentialsNow === false && r?.canReadEnvSecretsNow === false && r?.canCallModelsNow === false && r?.canEnableToolsetsNow === false && r?.canMutateFilesystemNow === false && r?.canUseFindings === false }
function accepted(input: FactoryHermesWrapperNoToolModeVerificationReviewInput) { return validVerification(input.verificationResult) && validPriorBlocks(input.verificationResult) && input.verificationApprovalResult?.status === 'wrapper_no_tool_mode_verification_approval_granted' && input.verificationPlanningResult?.status === 'wrapper_no_tool_mode_verification_plan_created' && input.implementationResult?.status === 'wrapper_no_tool_mode_implementation_completed' && input.adapterApprovalResult?.status === 'research_runtime_adapter_approval_blocked' }
export function evaluateFactoryHermesWrapperNoToolModeVerificationReview(input: FactoryHermesWrapperNoToolModeVerificationReviewInput) {
  const passed = accepted(input)
  const reviewId = `hermes-wrapper-no-tool-mode-verification-review:75b300f:${input.reviewedAt}`
  const status: FactoryHermesWrapperNoToolModeVerificationReviewStatus = passed ? 'wrapper_no_tool_mode_verification_review_completed' : 'wrapper_no_tool_mode_verification_review_blocked'
  const decision: FactoryHermesWrapperNoToolModeVerificationReviewDecision = passed ? 'hermes_wrapper_no_tool_mode_verification_review_accepted_for_adapter_approval_retry' : 'hermes_wrapper_no_tool_mode_verification_review_blocked'
  const reviewStatus = passed ? 'accepted_with_limitations' : 'blocked'
  const wrapperVerificationEvidenceReview = { reviewId: `${reviewId}:evidence-review`, verificationId: input.verificationResult?.verificationId, verificationPassed: input.verificationResult?.wrapperVerificationPassed === true, staticSafetyScanPassed: input.verificationResult?.staticSafetyScanPassed === true, configSerializerVerificationPassed: input.verificationResult?.configSerializerVerificationPassed === true, commandEnvelopeVerificationPassed: input.verificationResult?.commandEnvelopeVerificationPassed === true, tempConfigVirtualVerificationPassed: input.verificationResult?.tempConfigVirtualVerificationPassed === true, noHermesExecutionVerificationPassed: input.verificationResult?.noHermesExecutionVerificationPassed === true, evidenceAcceptedForAdapterApprovalRetryGate: passed, evidenceScope: 'code_only_boundary_review_not_runtime_execution' }
  const wrapperVerificationLimitationsReview = { reviewId: `${reviewId}:limitations-review`, acceptedLimitations: REVIEW_REQUIRED_LIMITATIONS, limitationsAccepted: passed, limitationsBlockRuntimeAdapterDirectUse: true, limitationsBlockHermesExecution: true, limitationsBlockResearchExecution: true }
  const wrapperVerificationRiskDispositionRegister = { registerId: `${reviewId}:risk-register`, risks: REVIEW_REQUIRED_RISKS.map((riskId) => ({ riskId, disposition: riskId === 'adapter_retry_confuses_review_with_runtime_approval' ? 'mitigated_by_retry_envelope_and_runtime_block_flags' : 'accepted_for_adapter_approval_retry_only', blocksDirectRuntimeAdapter: true, blocksHermesExecution: true, blocksResearchExecution: true })), reviewAcceptedForRetryOnly: passed }
  const researchRuntimeAdapterApprovalRetryEnvelope = passed ? { envelopeId: `${reviewId}:adapter-approval-retry-envelope`, toolId: 'hermes_agent', approvedFor: 'research_runtime_adapter_approval_retry_gate_only', requiredNextGate: 'Factory Hermes Research Runtime Adapter Approval Retry Gate v1', wrapperReviewAccepted: true, runtimeAdapterApprovedNow: false, researchExecutionApprovedNow: false, hermesExecutionApprovedNow: false, promptPassingApprovedNow: false, modelCallsApprovedNow: false, networkApprovedNow: false, credentialAccessApprovedNow: false, toolsetEnablementApprovedNow: false, filesystemMutationApprovedNow: false, findingsUseApprovedNow: false } : null
  const reviewBlockerPlan = passed ? null : { blockerId: 'wrapper_no_tool_mode_verification_review_blocked', requiredFix: 'Repair verification result evidence or prior gate chain before adapter approval retry can be considered.' }
  return { reviewId, reviewKind: FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_REVIEW_KIND, reviewVersion: FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_VERIFICATION_REVIEW_VERSION, reviewedAt: input.reviewedAt, reviewedBy: input.reviewedBy, toolId: 'hermes_agent', verificationRef: input.verificationResult?.verificationId, wrapperVerificationEvidenceReview, wrapperVerificationLimitationsReview, wrapperVerificationRiskDispositionRegister, researchRuntimeAdapterApprovalRetryEnvelope, wrapperNoToolModeVerificationReviewReceipt: { receiptId: `${reviewId}:receipt`, reviewId, toolId: 'hermes_agent', reviewedBy: input.reviewedBy, reviewedAt: input.reviewedAt, decision, reviewStatus, scope: 'hermes_wrapper_no_tool_mode_verification_review_only', approvedNextGate: passed ? 'Factory Hermes Research Runtime Adapter Approval Retry Gate v1' : null, limitations: REVIEW_REQUIRED_LIMITATIONS, notAuthorizedActions: REVIEW_NOT_AUTHORIZED_ACTIONS }, hermesWrapperNoToolModeVerificationReviewDecision: { decisionId: `${reviewId}:decision`, toolId: 'hermes_agent', decision, reviewStatus, reason: passed ? 'verification_evidence_accepted_with_limitations_for_adapter_approval_retry_only' : 'verification_evidence_or_prior_gate_chain_invalid', wrapperVerificationPassed: input.verificationResult?.wrapperVerificationPassed === true, adapterApprovalRetryAllowed: passed, runtimeAdapterApproved: false, researchExecutionApproved: false, hermesExecutionApproved: false }, reviewBlockerPlan, checks: [], blockers: passed ? [] : [{ blockerId: 'wrapper_no_tool_mode_verification_review_blocked', message: 'Verification review prerequisites were not satisfied.' }], warnings: REVIEW_REQUIRED_LIMITATIONS.map((message) => ({ warningId: message, message })), status, decision, reviewStatus, canProceedToResearchRuntimeAdapterApprovalRetry: passed, canProceedToResearchRuntimeAdapter: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canMutateFilesystemNow: false, canUseFindings: false, recommendedNextStep: passed ? 'Proceed to Factory Hermes Research Runtime Adapter Approval Retry Gate v1; runtime adapter execution and research remain blocked.' : 'Repair review blockers before any adapter approval retry.' }
}
export function validateFactoryHermesWrapperNoToolModeVerificationReviewInput(input: FactoryHermesWrapperNoToolModeVerificationReviewInput): FactoryHermesWrapperNoToolModeVerificationReviewValidationResult { const errors: string[] = []; const warnings: string[] = []; if (!input?.reviewedAt) errors.push('reviewedAt required.'); if (!input?.reviewedBy) errors.push('reviewedBy required.'); if (!input?.verificationResult) errors.push('verification result required.'); if (!input?.verificationApprovalResult) errors.push('verification approval result required.'); if (!input?.verificationPlanningResult) errors.push('verification planning result required.'); if (!input?.implementationResult) errors.push('implementation result required.'); if (!input?.adapterApprovalResult) errors.push('adapter approval result required.'); return { ok: errors.length === 0, errors, warnings } }
export function validateFactoryHermesWrapperNoToolModeVerificationReviewResult(result: any): FactoryHermesWrapperNoToolModeVerificationReviewValidationResult { const errors: string[] = []; const warnings: string[] = []; if (!['wrapper_no_tool_mode_verification_review_completed','wrapper_no_tool_mode_verification_review_blocked'].includes(result.status)) errors.push('invalid status.'); if (!['hermes_wrapper_no_tool_mode_verification_review_accepted_for_adapter_approval_retry','hermes_wrapper_no_tool_mode_verification_review_blocked'].includes(result.decision)) errors.push('invalid decision.'); for (const key of ['wrapperVerificationEvidenceReview','wrapperVerificationLimitationsReview','wrapperVerificationRiskDispositionRegister','wrapperNoToolModeVerificationReviewReceipt','hermesWrapperNoToolModeVerificationReviewDecision']) if (!result[key]) errors.push(`${key} required.`); if (result.status === 'wrapper_no_tool_mode_verification_review_completed' && !result.researchRuntimeAdapterApprovalRetryEnvelope) errors.push('retry envelope required when accepted.'); if (result.canProceedToResearchRuntimeAdapterApprovalRetry !== (result.status === 'wrapper_no_tool_mode_verification_review_completed')) errors.push('adapter approval retry flag must match status.'); for (const key of ['canProceedToResearchRuntimeAdapter','canRunResearchNow','canExecuteHermesNow','canPassPromptNow','canUseNetworkNow','canUseCredentialsNow','canReadEnvSecretsNow','canCallModelsNow','canEnableToolsetsNow','canMutateFilesystemNow','canUseFindings']) if (result[key] !== false) errors.push(`${key} must be false.`); for (const limitation of REVIEW_REQUIRED_LIMITATIONS) if (!result.wrapperVerificationLimitationsReview.acceptedLimitations.includes(limitation)) errors.push(`missing limitation: ${limitation}`); for (const risk of REVIEW_REQUIRED_RISKS) if (!result.wrapperVerificationRiskDispositionRegister.risks.some((item: any) => item.riskId === risk)) errors.push(`missing risk: ${risk}`); return { ok: errors.length === 0, errors, warnings } }
export const serializeFactoryHermesWrapperNoToolModeVerificationReviewResult = (result: any): string => `${JSON.stringify(result, null, 2)}\n`
export const parseFactoryHermesWrapperNoToolModeVerificationReviewResult = (json: string): any => JSON.parse(json)
export const summarizeFactoryHermesWrapperNoToolModeVerificationReviewResult = (result: any) => ({ reviewId: result.reviewId, status: result.status, decision: result.decision, reviewStatus: result.reviewStatus, canProceedToResearchRuntimeAdapterApprovalRetry: result.canProceedToResearchRuntimeAdapterApprovalRetry, canRunResearchNow: result.canRunResearchNow, nextStep: result.recommendedNextStep })
