export type FactoryHermesWrapperNoToolModeRuntimeVersion = '1.0'
export type FactoryHermesWrapperNoToolModeRuntimeKind = 'factory-hermes-wrapper-no-tool-mode-runtime'
export interface FactoryHermesWrapperNoToolModeRuntimeInput { builtAt: string; builtBy: string; runId: string; exactConfigSchemaKnown?: boolean | 'unknown'; emptyToolsetsSupported?: boolean | 'unknown' }
export interface FactoryHermesWrapperNoToolModePolicy { requireSerializedOnly: true; forbidSecrets: true; forbidCredentialValues: true; forbidEnvDump: true; forbidToolsets: true; forbidExecution: true }
export interface FactoryHermesWrapperNoToolModeTempConfigCandidate { kind: FactoryHermesWrapperNoToolModeRuntimeKind; version: FactoryHermesWrapperNoToolModeRuntimeVersion; runId: string; serializedOnly: true; containsSecrets: false; containsCredentialValues: false; containsEnvDump: false; cliToolsets: []; mcpEnabled: false; defaultToolsetsAllowed: false; runnable: false; exactConfigSchemaKnown: boolean | 'unknown'; emptyToolsetsSupported: boolean | 'unknown' }
export interface FactoryHermesWrapperNoToolModeSerializedConfig { text: string; serializedOnly: true; writesFiles: false; containsSecrets: false; containsCredentialValues: false; containsEnvDump: false }
export interface FactoryHermesWrapperNoToolModeConfigValidationResult { ok: boolean; runnable: false; errors: string[]; warnings: string[] }
export interface FactoryHermesWrapperNoToolModeCommandEnvelope { envelopeId: string; executionAllowed: false; hermesExecutionAllowed: false; wrapperExecutionAllowed: false; promptAllowed: false; networkAllowed: false; modelCallsAllowed: false; credentialAccessAllowed: false; toolsetsEnabled: false; runtimeAdapterAllowed: false; researchExecutionAllowed: false; commandPreviewOnly: true }
export interface FactoryHermesWrapperNoToolModeManifest { manifestId: string; requiresVerificationPlanning: true; restrictions: string[] }
export interface FactoryHermesWrapperNoToolModeSafetyManifest { noCommandExecution: true; noNetwork: true; noCredentialReads: true; noPromptPassing: true; noTempConfigWrites: true; noRunRootCreation: true; noHermesExecution: true; noWrapperExecution: true }
export interface FactoryHermesWrapperNoToolModeRuntimeCheck { checkId: string; ok: boolean }
export interface FactoryHermesWrapperNoToolModeRuntimeBlocker { blockerId: string; message: string }
export interface FactoryHermesWrapperNoToolModeRuntimeWarning { warningId: string; message: string }
export interface FactoryHermesWrapperNoToolModeBuildResult { status: 'built_virtual_not_executable'; tempConfigCandidate: FactoryHermesWrapperNoToolModeTempConfigCandidate; serializedConfig: FactoryHermesWrapperNoToolModeSerializedConfig; configValidation: FactoryHermesWrapperNoToolModeConfigValidationResult; commandEnvelope: FactoryHermesWrapperNoToolModeCommandEnvelope; manifest: FactoryHermesWrapperNoToolModeManifest; safetyManifest: FactoryHermesWrapperNoToolModeSafetyManifest; checks: FactoryHermesWrapperNoToolModeRuntimeCheck[]; blockers: FactoryHermesWrapperNoToolModeRuntimeBlocker[]; warnings: FactoryHermesWrapperNoToolModeRuntimeWarning[] }
export interface FactoryHermesWrapperNoToolModeSummary { status: string; serializedOnly: true; runnable: false; executionAllowed: false; requiresVerificationPlanning: true }
export function createFactoryHermesWrapperNoToolModeTempConfigCandidate(input: FactoryHermesWrapperNoToolModeRuntimeInput): FactoryHermesWrapperNoToolModeTempConfigCandidate { return { kind: 'factory-hermes-wrapper-no-tool-mode-runtime', version: '1.0', runId: input.runId, serializedOnly: true, containsSecrets: false, containsCredentialValues: false, containsEnvDump: false, cliToolsets: [], mcpEnabled: false, defaultToolsetsAllowed: false, runnable: false, exactConfigSchemaKnown: input.exactConfigSchemaKnown ?? 'unknown', emptyToolsetsSupported: input.emptyToolsetsSupported ?? 'unknown' } }
export function serializeFactoryHermesWrapperNoToolModeTempConfig(candidate: FactoryHermesWrapperNoToolModeTempConfigCandidate): FactoryHermesWrapperNoToolModeSerializedConfig { return { text: JSON.stringify({ cli: { toolsets: candidate.cliToolsets }, mcp: { enabled: candidate.mcpEnabled }, defaults: { toolsetsAllowed: candidate.defaultToolsetsAllowed }, runnable: false }, null, 2), serializedOnly: true, writesFiles: false, containsSecrets: false, containsCredentialValues: false, containsEnvDump: false } }
export function validateFactoryHermesWrapperNoToolModeTempConfig(candidate: FactoryHermesWrapperNoToolModeTempConfigCandidate | FactoryHermesWrapperNoToolModeSerializedConfig): FactoryHermesWrapperNoToolModeConfigValidationResult { const text = 'text' in candidate ? candidate.text : JSON.stringify(candidate); const errors: string[] = []; const warnings: string[] = []; if (/secret|credentialValue|apiKey|token|password/i.test(text)) errors.push('secret_like_content_detected'); if ('exactConfigSchemaKnown' in candidate && candidate.exactConfigSchemaKnown === 'unknown') warnings.push('exact_config_schema_unknown'); if ('emptyToolsetsSupported' in candidate && candidate.emptyToolsetsSupported === 'unknown') warnings.push('empty_toolsets_support_unknown'); return { ok: errors.length === 0, runnable: false, errors, warnings } }
export function buildFactoryHermesWrapperNoToolModeCommandEnvelope(input: FactoryHermesWrapperNoToolModeRuntimeInput): FactoryHermesWrapperNoToolModeCommandEnvelope { return { envelopeId: `wrapper-no-tool-mode-command:${input.runId}`, executionAllowed: false, hermesExecutionAllowed: false, wrapperExecutionAllowed: false, promptAllowed: false, networkAllowed: false, modelCallsAllowed: false, credentialAccessAllowed: false, toolsetsEnabled: false, runtimeAdapterAllowed: false, researchExecutionAllowed: false, commandPreviewOnly: true } }
export function buildFactoryHermesWrapperNoToolModeManifest(input: FactoryHermesWrapperNoToolModeRuntimeInput): FactoryHermesWrapperNoToolModeManifest { return { manifestId: `wrapper-no-tool-mode-manifest:${input.runId}`, requiresVerificationPlanning: true, restrictions: ['code only','serialized config only','command envelope is non executable','verification planning required before use'] } }
export function evaluateFactoryHermesWrapperNoToolModeRuntimeBuild(input: FactoryHermesWrapperNoToolModeRuntimeInput): FactoryHermesWrapperNoToolModeBuildResult { const tempConfigCandidate = createFactoryHermesWrapperNoToolModeTempConfigCandidate(input); const serializedConfig = serializeFactoryHermesWrapperNoToolModeTempConfig(tempConfigCandidate); const configValidation = validateFactoryHermesWrapperNoToolModeTempConfig(tempConfigCandidate); const commandEnvelope = buildFactoryHermesWrapperNoToolModeCommandEnvelope(input); const manifest = buildFactoryHermesWrapperNoToolModeManifest(input); return { status: 'built_virtual_not_executable', tempConfigCandidate, serializedConfig, configValidation, commandEnvelope, manifest, safetyManifest: { noCommandExecution: true, noNetwork: true, noCredentialReads: true, noPromptPassing: true, noTempConfigWrites: true, noRunRootCreation: true, noHermesExecution: true, noWrapperExecution: true }, checks: [{ checkId: 'virtual_config_serialized_only', ok: true }], blockers: [], warnings: configValidation.warnings.map((message) => ({ warningId: message, message })) } }
