import type { FactoryMemoryRegistryIntegrityReport } from '../memory-registry-integrity/index.ts'

export type FactoryMemoryReadAdmissionVersion = '1.0'
export type FactoryMemoryReadAdmissionKind = 'factory-memory-read-admission'
export type FactoryMemoryReadPurpose = 'jefe_review_context' | 'factory_planning_context' | 'memory_audit_context' | 'codex_task_preparation_candidate' | 'human_review_context'
export type FactoryMemoryReadScope = 'project'
export type FactoryMemoryReadCandidateStatus = 'read_candidate' | 'warning_candidate' | 'blocked'
export type FactoryMemoryReadAdmissionDecision = 'blocked' | 'reject_memory_read' | 'request_memory_repair' | 'human_review_required' | 'approve_memory_read_candidates'
export interface FactoryMemoryReadAdmissionPolicy { requireIntegrityReport: true; requireCleanEntries: true; requireCanUseForMemoryRead: true; rejectCriticalFindings: true; rejectUnsafeFlags: true; rejectMissingFingerprint: true; rejectMissingIdempotencyKey: true; requireProjectScopedMemory: true; rejectGlobalMemoryByDefault: true; requireNamespaceMatchForProjectScope: true; requireNoFullMemoryRecord: true; requireNoCanonicalPayload: true; requireNoRawEvidence: true; requireNoSecrets: true; allowMinimalFactsOnly: true; requireSafeReferencesOnly: true; requireHumanReviewForCodexTaskPreparation: true; allowCodexTaskCreation: false; allowContextAssembly: false; allowRuntimeRead: false; forbidEmbeddingsCreation: true; forbidCodexTaskCreation: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true }
export interface FactoryMemoryReadAdmissionInput { memoryRegistryIntegrityReport: FactoryMemoryRegistryIntegrityReport; requestedAt: string; requestedBy: string; readPurpose: FactoryMemoryReadPurpose; projectNamespace?: string; allowedMemoryRecordKinds?: string[]; maxCandidates?: number; policy?: Partial<FactoryMemoryReadAdmissionPolicy>; humanReviewRef?: string }
export interface FactoryMemoryReadAdmissionFinding { findingId: string; registryEntryId?: string; severity: 'info' | 'warning' | 'error' | 'critical'; message: string }
export interface FactoryMemoryReadAdmissionBlocker { blockerId: string; registryEntryId?: string; message: string }
export interface FactoryMemoryReadAdmissionWarning { warningId: string; registryEntryId?: string; message: string }
export interface FactoryMemoryReadAdmissionCheck { checkId: string; passed: boolean; message: string }
export interface FactoryMemoryReadCandidateDraft { readCandidateId: string; memoryRecordId: string; memoryRecordKind: string; memoryRecordVersion: string; namespace: string; projectNamespace: string; logicalTarget: string; metadataLogicalTarget: string; fingerprint: string; idempotencyKey: string; sourceIntegrityReportRef: string; sourceRegistryEntryId: string; readPurpose: FactoryMemoryReadPurpose; readScope: FactoryMemoryReadScope; status: FactoryMemoryReadCandidateStatus; allowedUse: string[]; deniedUse: string[]; safeReferences: { logicalTarget: string; metadataLogicalTarget: string }[]; minimalFacts: Record<string, string | boolean>; lineage: { sourceIntegrityReportRef: string; sourceRegistryEntryId: string; sourcePersistenceId?: string; sourceApprovalId?: string; sourceAdmissionId?: string }; freshness: { sourceWrittenAt?: string; integrityCheckedAt: string; freshnessStatus: 'current' | 'unknown' | 'stale_candidate' }; retention: { inheritedRetentionPolicy?: string; readOnly: true; noMutation: true }; warnings: string[]; blockers: string[]; containsFullMemoryRecord: false; containsCanonicalPayload: false; containsRawEvidence: false; containsSecrets: false; canReadMemoryRuntime: false; canAssembleContext: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateEmbeddings: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryReadAdmissionSummary { admissionId: string; readPurpose: FactoryMemoryReadPurpose; decision: FactoryMemoryReadAdmissionDecision; status: string; candidatesCount: number; rejectedCount: number; blockedCount: number; namespaces: string[]; canReadMemoryRuntime: false; canAssembleContext: false; canCreateCodexTask: false; recommendedNextStep: string }
export interface FactoryMemoryReadAdmissionResult { admissionId: string; admissionKind: FactoryMemoryReadAdmissionKind; admissionVersion: FactoryMemoryReadAdmissionVersion; requestedAt: string; requestedBy: string; readPurpose: FactoryMemoryReadPurpose; sourceIntegrityReportRef: string; decision: FactoryMemoryReadAdmissionDecision; status: 'blocked' | 'rejected' | 'repair_required' | 'human_review_required' | 'read_candidates_ready'; candidates: FactoryMemoryReadCandidateDraft[]; rejectedEntries: string[]; blockedEntries: string[]; checks: FactoryMemoryReadAdmissionCheck[]; findings: FactoryMemoryReadAdmissionFinding[]; blockers: FactoryMemoryReadAdmissionBlocker[]; warnings: FactoryMemoryReadAdmissionWarning[]; summary: FactoryMemoryReadAdmissionSummary; canReadMemoryRuntime: false; canAssembleContext: false; canCreateCodexTask: false; canExecuteCodex: false; canCreateEmbeddings: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryMemoryReadAdmissionValidationResult { ok: boolean; errors: string[]; warnings: string[] }
