import { FACTORY_MEMORY_READ_ADMISSION_KIND, FACTORY_MEMORY_READ_ADMISSION_VERSION, createFactoryMemoryReadAdmissionPolicy } from './memory-read-admission.defaults.ts'
import type { FactoryMemoryReadAdmissionInput, FactoryMemoryReadAdmissionResult, FactoryMemoryReadCandidateDraft } from './memory-read-admission.types.ts'

const token = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'unknown'
const validNamespace = (value: string) => Boolean(value) && !value.startsWith('/') && !value.includes('..') && value.split('/').every(Boolean)
export function createFactoryMemoryReadAdmissionPlan(input: FactoryMemoryReadAdmissionInput): FactoryMemoryReadAdmissionResult {
  if (!input?.memoryRegistryIntegrityReport || !input.requestedAt?.trim() || !input.requestedBy?.trim() || !input.readPurpose) throw new Error('memoryRegistryIntegrityReport, requestedAt, requestedBy and readPurpose are required.')
  createFactoryMemoryReadAdmissionPolicy(input.policy); const report = structuredClone(input.memoryRegistryIntegrityReport); const admissionId = `memory-read-admission:${token(input.requestedBy)}:${token(input.requestedAt)}`; const sourceRef = `${report.integrityKind}:${report.generatedAt}`
  const candidates: FactoryMemoryReadCandidateDraft[] = []; const rejectedEntries: string[] = []; const blockedEntries: string[] = []; const blockers: FactoryMemoryReadAdmissionResult['blockers'] = []; const warnings: FactoryMemoryReadAdmissionResult['warnings'] = []; const findings: FactoryMemoryReadAdmissionResult['findings'] = []
  for (const entry of report.entries) {
    const critical = entry.findings.some((finding) => finding.severity === 'critical'); const error = entry.findings.some((finding) => finding.severity === 'error'); const warning = entry.findings.some((finding) => finding.severity === 'warning'); const unsafeCapability = entry.canUseForCodexTask || entry.canCreateEmbeddings || entry.canExecuteCodex || entry.canCreateProject || entry.canCreateRepository || entry.canDeploy
    const namespaceMismatch = !validNamespace(entry.namespace) || !validNamespace(entry.projectNamespace) || !entry.namespace.startsWith(`${entry.projectNamespace}/`) || Boolean(input.projectNamespace && entry.projectNamespace !== input.projectNamespace); const kindRejected = Boolean(input.allowedMemoryRecordKinds?.length && !input.allowedMemoryRecordKinds.includes(entry.memoryRecordKind))
    if (critical) { rejectedEntries.push(entry.registryEntryId); findings.push({ findingId: `read-finding:${entry.registryEntryId}:critical`, registryEntryId: entry.registryEntryId, severity: 'critical', message: 'Critical integrity finding rejects memory read admission.' }); continue }
    if (error || !entry.canUseForMemoryRead || entry.status === 'blocked' || !entry.flagsSafe || !entry.pathContained || !entry.expectedFingerprint || !entry.expectedIdempotencyKey || unsafeCapability || namespaceMismatch || kindRejected) { blockedEntries.push(entry.registryEntryId); blockers.push({ blockerId: `read-blocker:${entry.registryEntryId}`, registryEntryId: entry.registryEntryId, message: namespaceMismatch ? 'Project-scoped namespace does not match the read request.' : 'Entry does not satisfy safe memory-read requirements.' }); continue }
    if (warning || entry.status === 'warning') warnings.push({ warningId: `read-warning:${entry.registryEntryId}`, registryEntryId: entry.registryEntryId, message: 'Non-critical integrity warning retained for governed review.' })
    const candidate: FactoryMemoryReadCandidateDraft = { readCandidateId: `memory-read-candidate:${token(entry.memoryRecordId)}:${entry.expectedFingerprint}`, memoryRecordId: entry.memoryRecordId, memoryRecordKind: entry.memoryRecordKind, memoryRecordVersion: entry.memoryRecordVersion, namespace: entry.namespace, projectNamespace: entry.projectNamespace, logicalTarget: entry.logicalTarget, metadataLogicalTarget: entry.metadataLogicalTarget, fingerprint: entry.expectedFingerprint, idempotencyKey: entry.expectedIdempotencyKey, sourceIntegrityReportRef: sourceRef, sourceRegistryEntryId: entry.registryEntryId, readPurpose: input.readPurpose, readScope: 'project', status: warning || entry.status === 'warning' ? 'warning_candidate' : 'read_candidate', allowedUse: ['governed_memory_read_candidate'], deniedUse: ['runtime_read', 'context_assembly', 'create_codex_task', 'execute_codex', 'create_embeddings', 'create_project', 'create_repository', 'deploy'], safeReferences: [{ logicalTarget: entry.logicalTarget, metadataLogicalTarget: entry.metadataLogicalTarget }], minimalFacts: { memoryRecordId: entry.memoryRecordId, memoryRecordKind: entry.memoryRecordKind, namespace: entry.namespace, projectNamespace: entry.projectNamespace, fingerprint: entry.expectedFingerprint, idempotencyKey: entry.expectedIdempotencyKey, logicalTarget: entry.logicalTarget, metadataLogicalTarget: entry.metadataLogicalTarget, integrityStatus: entry.status, flagsSafe: entry.flagsSafe, pathContained: entry.pathContained }, lineage: { sourceIntegrityReportRef: sourceRef, sourceRegistryEntryId: entry.registryEntryId }, freshness: { integrityCheckedAt: report.generatedAt, freshnessStatus: entry.status === 'warning' ? 'stale_candidate' : 'current' }, retention: { readOnly: true, noMutation: true }, warnings: warning ? ['Non-critical integrity warning requires downstream review.'] : [], blockers: [], containsFullMemoryRecord: false, containsCanonicalPayload: false, containsRawEvidence: false, containsSecrets: false, canReadMemoryRuntime: false, canAssembleContext: false, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: 'Submit this candidate to a future Memory Read Runtime Adapter or Memory Context Assembly Gate.' }
    candidates.push(candidate)
  }
  const limited = input.maxCandidates === undefined ? candidates : candidates.slice(0, Math.max(0, input.maxCandidates)); if (limited.length < candidates.length) warnings.push({ warningId: 'read-warning:max-candidates', message: 'Eligible candidates were limited by maxCandidates.' })
  let decision: FactoryMemoryReadAdmissionResult['decision']; let status: FactoryMemoryReadAdmissionResult['status']; let recommendedNextStep: string
  if (report.status === 'blocked') { decision = 'request_memory_repair'; status = 'repair_required'; recommendedNextStep = 'Repair and revalidate the Memory Registry before requesting read candidates.' }
  else if (input.readPurpose === 'codex_task_preparation_candidate' && !input.humanReviewRef?.trim()) { decision = 'human_review_required'; status = 'human_review_required'; recommendedNextStep = 'Obtain human review before preparing governed memory candidates; do not create a Codex Task.' }
  else if (!limited.length) { decision = blockers.length || rejectedEntries.length ? 'reject_memory_read' : 'blocked'; status = blockers.length || rejectedEntries.length ? 'rejected' : 'blocked'; recommendedNextStep = 'Review integrity findings or request eligible project-scoped memory entries.' }
  else { decision = 'approve_memory_read_candidates'; status = 'read_candidates_ready'; recommendedNextStep = 'Submit candidates to a future Memory Read Runtime Adapter or Memory Context Assembly Gate; do not execute Codex.' }
  const checks = [{ checkId: 'integrity-report', passed: report.status !== 'blocked', message: 'Integrity report must not be blocked.' }, { checkId: 'safe-candidates', passed: limited.length > 0, message: 'At least one safe project-scoped candidate is required.' }, { checkId: 'capabilities-disabled', passed: true, message: 'Runtime read, context assembly, Codex, embeddings, project, repository and deploy remain disabled.' }]
  if ((status === 'blocked' || status === 'rejected' || status === 'repair_required') && !blockers.length) blockers.push({ blockerId: 'read-blocker:result', message: recommendedNextStep })
  const summary = { admissionId, readPurpose: input.readPurpose, decision, status, candidatesCount: limited.length, rejectedCount: rejectedEntries.length, blockedCount: blockedEntries.length, namespaces: [...new Set(limited.map((item) => item.namespace))], canReadMemoryRuntime: false as const, canAssembleContext: false as const, canCreateCodexTask: false as const, recommendedNextStep }
  return { admissionId, admissionKind: FACTORY_MEMORY_READ_ADMISSION_KIND, admissionVersion: FACTORY_MEMORY_READ_ADMISSION_VERSION, requestedAt: input.requestedAt, requestedBy: input.requestedBy, readPurpose: input.readPurpose, sourceIntegrityReportRef: sourceRef, decision, status, candidates: limited, rejectedEntries, blockedEntries, checks, findings, blockers, warnings, summary, canReadMemoryRuntime: false, canAssembleContext: false, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep }
}
