import { DEFAULT_FACTORY_PROJECT_CONTRACT_CANDIDATE_STACK, FACTORY_PROJECT_CONTRACT_CANDIDATE_KIND, FACTORY_PROJECT_CONTRACT_CANDIDATE_VERSION, createFactoryProjectContractCandidatePolicy } from './project-contract-candidate.defaults.ts'
import type { FactoryProjectContractCandidate, FactoryProjectContractCandidateBlocker, FactoryProjectContractCandidateEnvironmentVariable, FactoryProjectContractCandidateInput } from './project-contract-candidate.types.ts'

export function createFactoryProjectContractCandidateSlug(value: string): string { return value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 63).replace(/-$/g, '') || 'factory-project-candidate' }

export function createFactoryProjectContractCandidateV1(input: FactoryProjectContractCandidateInput): FactoryProjectContractCandidate {
  const value = structuredClone(input); const draft = value.draft; const policy = createFactoryProjectContractCandidatePolicy(value.policy); const slug = createFactoryProjectContractCandidateSlug(draft.title)
  const stack = { ...structuredClone(DEFAULT_FACTORY_PROJECT_CONTRACT_CANDIDATE_STACK), ...value.stackSuggestion, packageManager: value.packageManagerSuggestion ?? value.stackSuggestion?.packageManager ?? DEFAULT_FACTORY_PROJECT_CONTRACT_CANDIDATE_STACK.packageManager }
  const environmentVariables: FactoryProjectContractCandidateEnvironmentVariable[] = value.environmentVariables ?? [{ name: 'NODE_ENV', required: true, secret: false, scope: 'runtime', description: 'Runtime environment name; value is supplied outside this candidate.', defaultAllowed: true, productionRequired: true }]
  const blockers: FactoryProjectContractCandidateBlocker[] = draft.blockers.map((description, index) => ({ blockerId: `brief-blocker-${index + 1}`, category: 'brief', description, blocking: true }))
  if (draft.preliminaryAcceptanceCriteria.length === 0) blockers.push({ blockerId: 'missing-acceptance-criteria', category: 'evidence', description: 'Preliminary acceptance criteria are required.', blocking: true })
  const approvalStatus = value.humanReviewRef ? 'approved' as const : 'pending' as const
  const approvalRequirements = [{ approvalId: 'human-contract-creation', stage: 'contract_creation' as const, required: true as const, status: approvalStatus, approvalRef: value.humanReviewRef }, { approvalId: 'human-before-codex', stage: 'before_codex' as const, required: true as const, status: 'pending' as const }]
  const approvalsPending = approvalRequirements.filter((item) => item.status === 'pending').length
  const readinessStatus = blockers.length > 0 ? 'not_ready' as const : value.humanReviewRef ? 'ready_for_contract_draft' as const : 'needs_human_review' as const
  const evidenceRequirements = [...draft.preliminaryAcceptanceCriteria.map((criterion, index) => ({ requirementId: `acceptance-${index + 1}`, description: criterion.statement, source: 'brief_acceptance_criterion' as const, required: true as const, status: 'pending' as const })), { requirementId: 'independence-proof', description: 'Demonstrate own root, own repository and no JEFE runtime dependency.', source: 'independence' as const, required: true as const, status: 'pending' as const }]
  return { candidateId: `factory-project-contract-candidate-${createFactoryProjectContractCandidateSlug(draft.opportunityId)}-${value.createdAt.replace(/[^0-9]/g, '')}`, candidateKind: FACTORY_PROJECT_CONTRACT_CANDIDATE_KIND, candidateVersion: FACTORY_PROJECT_CONTRACT_CANDIDATE_VERSION, createdAt: value.createdAt, createdBy: value.createdBy, status: readinessStatus === 'not_ready' ? 'blocked' : readinessStatus,
    source: { briefDraftId: draft.briefDraftId, generatedBy: 'JEFE', derivedFrom: 'FactoryBriefDraft' }, identity: { projectIdSuggestion: `project-${slug}`, slugSuggestion: slug, name: draft.title, displayName: draft.title, description: draft.executiveSummary, projectType: 'independent_application', owner: value.repositoryOwner },
    lineage: { briefDraftId: draft.briefDraftId, opportunityId: draft.opportunityId, decisionId: draft.source.decisionId, radarScore: draft.source.radarScore, hermesConfidence: draft.source.hermesConfidence, evidenceRefs: [...draft.source.evidenceRefs], humanReviewRef: value.humanReviewRef, generatedBy: 'JEFE', derivedFrom: 'FactoryBriefDraft' }, projectType: 'independent_application', description: draft.executiveSummary, problem: draft.problem.statement, audience: draft.audience.primary, proposedSolution: draft.proposedSolution.summary, monetization: draft.monetization.hypothesis,
    stack, repository: { repositoryRequired: true, provider: 'GitHub', owner: value.repositoryOwner, repoNameSuggestion: slug, ownRootRequired: true, creationAllowed: false }, environmentVariables,
    qualityProfile: { profile: 'factory_baseline_v1', preliminaryAcceptanceCriteria: draft.preliminaryAcceptanceCriteria.map((item) => item.statement), requiredChecks: ['typecheck', 'lint', 'unit_tests_planned', 'integration_tests_planned', 'e2e_tests_planned'], unitTestsPlanned: true, integrationTestsPlanned: true, e2eTestsPlanned: true, accessibilityPlanned: true, performancePlanned: true },
    securityProfile: { profile: 'factory_secure_default_v1', secretValuesForbidden: true, leastPrivilegeRequired: true, externalCallsRequireApproval: true, deployRequiresApproval: true, promptInjectionReviewRequired: true, dependencyReviewRequired: true }, evidenceRequirements, approvalRequirements, independencePolicy: structuredClone(draft.independencePolicy), executionPolicy: { codexExecutionAllowed: false, projectCreationAllowed: false, repositoryCreationAllowed: false, deployAllowed: false }, policy,
    readiness: { status: readinessStatus, blockersCount: blockers.length, approvalsPending, evidenceRequirementsCount: evidenceRequirements.length }, blockers, warnings: draft.warnings.map((item) => `Brief warning: ${item}`), recommendedNextStep: readinessStatus === 'ready_for_contract_draft' ? 'Draft a FactoryProjectContract for separate JEFE and human review; do not execute Codex.' : readinessStatus === 'needs_human_review' ? 'Obtain human review before drafting any FactoryProjectContract.' : 'Resolve candidate blockers before contract drafting.' }
}
