import { DEFAULT_FACTORY_HERMES_TOOLSETS_POLICY_PLANNING_POLICY, FACTORY_HERMES_TOOLSETS_POLICY_PLANNING_KIND, FACTORY_HERMES_TOOLSETS_POLICY_PLANNING_NEXT_STEP, FACTORY_HERMES_TOOLSETS_POLICY_PLANNING_VERSION, TOOLSETS_NOT_AUTHORIZED_ACTIONS, TOOLSETS_REQUIRED_NEXT_POLICIES } from './hermes-toolsets-policy-planning.defaults.ts'
import type { FactoryHermesToolsetCandidate, FactoryHermesToolsetsPolicyPlanningInput, FactoryHermesToolsetsPolicyPlanningResult, FactoryHermesToolsetsPolicyRule } from './hermes-toolsets-policy-planning.types.ts'

function candidates(): FactoryHermesToolsetCandidate[] {
  return [
    { toolsetId: 'no_toolsets_text_only', status: 'preferred_if_supported_by_cli', canUseNow: false, reason: 'Safest future mode if Hermes supports disabling all tools.', evidenceRequired: 'explicit empty toolsets/no tools/no_mcp behavior', requiresFutureApproval: true },
    { toolsetId: 'default_cli_toolsets', status: 'forbidden_without_explicit_approval', canUseNow: false, reason: 'Hidden defaults are not allowed.', requiresFutureApproval: true },
    { toolsetId: 'web_toolset', status: 'forbidden_until_network_and_toolsets_approval', canUseNow: false, reason: 'Web/search tools require network and toolsets approval.', risks: ['network', 'external content', 'browsing/search'], requiresFutureApproval: true },
    { toolsetId: 'browser_toolset', status: 'forbidden_until_network_and_toolsets_approval', canUseNow: false, reason: 'Browser automation requires explicit approval.', risks: ['network', 'browser automation', 'external content'], requiresFutureApproval: true },
    { toolsetId: 'terminal_toolset', status: 'forbidden', canUseNow: false, reason: 'Terminal tools are forbidden for initial research execution.', risks: ['command execution', 'filesystem mutation', 'process spawning'], requiresFutureApproval: true },
    { toolsetId: 'filesystem_toolset', status: 'forbidden_until_filesystem_policy', canUseNow: false, reason: 'Filesystem tools require Filesystem Mutation Policy.', risks: ['file reads/writes', 'source mutation', 'data leakage'], requiresFutureApproval: true },
    { toolsetId: 'mcp_toolset', status: 'forbidden_until_mcp_policy', canUseNow: false, reason: 'MCP requires explicit MCP Policy.', risks: ['external servers', 'local channels', 'capabilities outside Hermes boundary'], requiresFutureApproval: true },
    { toolsetId: 'arbitrary_toolsets', status: 'forbidden', canUseNow: false, reason: 'No arbitrary toolset names or config defaults.', requiresFutureApproval: true },
    { toolsetId: 'no_mcp_sentinel', status: 'candidate_only_if_supported', canUseNow: false, reason: 'Source may indicate sentinel behavior, but it requires future validation.', evidenceRequired: 'source-proven no_mcp behavior', requiresFutureApproval: true },
  ]
}

function rules(): FactoryHermesToolsetsPolicyRule[] {
  return [
    { ruleId: 'no_toolsets_now', ruleName: 'No toolsets now', requirements: ['canEnableToolsetsNow false.', 'No web/browser/terminal/MCP/filesystem now.'] },
    { ruleId: 'explicit_future_toolsets', ruleName: 'Explicit future toolsets', requirements: ['Future runtime must pass explicit toolsets.', 'No hidden CLI defaults.', 'No config-driven defaults without approval.'] },
    { ruleId: 'preferred_safe_mode', ruleName: 'Preferred safe mode', requirements: ['Prefer no_toolsets_text_only.', 'If disabling tools is not proven, require manual review.'] },
    { ruleId: 'web_browser_search', ruleName: 'Web/browser/search', requirements: ['Forbidden unless Network Policy and Toolsets Policy approve exact scope.'] },
    { ruleId: 'terminal_shell', ruleName: 'Terminal/shell', requirements: ['Forbidden for initial research execution.', 'No command execution.'] },
    { ruleId: 'filesystem', ruleName: 'Filesystem', requirements: ['Forbidden until Filesystem Mutation Policy.', 'No reads/writes outside approved output paths.'] },
    { ruleId: 'mcp', ruleName: 'MCP', requirements: ['Forbidden until explicit MCP Policy.', 'No arbitrary MCP servers.'] },
    { ruleId: 'tool_output', ruleName: 'Tool output', requirements: ['Tool outputs cannot become findings until ingestion and JEFE Review.', 'Tools disabled by default.'] },
    { ruleId: 'runtime_reporting', ruleName: 'Runtime reporting', requirements: ['Report toolsetsRequested, toolsetsApproved, toolsetsUsed, toolExecutionStatus and unexpectedToolUse.'] },
    { ruleId: 'failure_policy', ruleName: 'Failure policy', requirements: ['If Hermes attempts unapproved tool use, runtime/result ingestion must block.'] },
  ]
}

function base(input: FactoryHermesToolsetsPolicyPlanningInput): FactoryHermesToolsetsPolicyPlanningResult {
  return { planningId: `hermes-toolsets-policy-planning:75b300f:${input.plannedAt}`, planningKind: FACTORY_HERMES_TOOLSETS_POLICY_PLANNING_KIND, planningVersion: FACTORY_HERMES_TOOLSETS_POLICY_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', commandShapeUnderConsideration: 'oneshot_real_with_provider_model', futureCommandShape: 'hermes.exe --oneshot "<PROMPT>" --provider <PROVIDER> --model <MODEL> --toolsets <TOOLSETS>', toolsetCandidates: [], selectedToolsetPolicy: null, checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_network_policy_planning', canProceedToOutputContractPolicyPlanning: false, canProceedToResearchExecutionApproval: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canUseFindings: false, recommendedNextStep: FACTORY_HERMES_TOOLSETS_POLICY_PLANNING_NEXT_STEP }
}

export function evaluateFactoryHermesToolsetsPolicyPlanning(input: FactoryHermesToolsetsPolicyPlanningInput): FactoryHermesToolsetsPolicyPlanningResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_TOOLSETS_POLICY_PLANNING_POLICY, ...(input.policy || {}) }
  const out = base(input)
  const network = input.networkPolicyPlanningResult
  const credentials = input.credentialsPolicyPlanningResult
  const inspection = input.toolsetsSourceInspection
  if (!network) return { ...out, blockers: [{ blockerId: 'blocked_missing_network_policy_planning', message: 'Network policy planning result is required.' }] }
  const networkPlan = network.hermesNetworkPolicyPlanCandidate
  if (network.status !== 'network_policy_plan_created' || network.decision !== 'hermes_network_policy_plan_created' || network.canProceedToToolsetsPolicyPlanning !== true || network.canProceedToResearchExecutionApproval !== false || network.canRunResearchNow !== false || network.canExecuteHermesNow !== false || network.canPassPromptNow !== false || network.canUseNetworkNow !== false || network.canUseCredentialsNow !== false || network.canReadEnvSecretsNow !== false || network.canCallModelsNow !== false || networkPlan?.allowedHostsNow?.length !== 0 || networkPlan?.wildcardHostsAllowed !== false || networkPlan?.arbitraryInternetAllowed !== false || networkPlan?.toolsetsDependency?.toolsetNetworkDisabledUntilToolsetsPolicy !== true || networkPlan?.toolsetsDependency?.webBrowserSearchDisabledUntilToolsetsPolicy !== true) return { ...out, decision: 'blocked_network_policy_not_ready_for_toolsets_policy', blockers: [{ blockerId: 'blocked_network_policy_not_ready_for_toolsets_policy', message: 'Network policy planning is not ready for toolsets policy.' }] }
  const injection = credentials?.hermesCredentialsPolicyPlanCandidate?.credentialInjectionPlan
  if (policy.requireCredentialsPolicyPlanning && (!credentials || credentials.status !== 'credentials_policy_plan_created' || credentials.canUseCredentialsNow !== false || injection?.credentialValuesReadHere !== false || injection?.credentialValuesDefinedHere !== false)) return { ...out, decision: 'blocked_credentials_policy_not_ready_for_toolsets_policy', blockers: [{ blockerId: 'blocked_credentials_policy_not_ready_for_toolsets_policy', message: 'Credentials policy planning is not ready for toolsets policy.' }] }
  if (policy.requireToolsetsSourceInspection && !inspection) return { ...out, decision: 'blocked_missing_toolsets_source_inspection', blockers: [{ blockerId: 'blocked_missing_toolsets_source_inspection', message: 'Toolsets source inspection is required.' }] }
  if (inspection?.toolsetsEnabled === true || inspection?.networkUsed === true || inspection?.dnsResolved === true || inspection?.endpointsTested === true || inspection?.envValuesRead === true || inspection?.dotEnvRead === true) return { ...out, decision: 'blocked_toolsets_or_network_used_during_planning', blockers: [{ blockerId: 'blocked_toolsets_or_network_used_during_planning', message: 'Toolsets inspection must be text-only and must not enable tools, use network, DNS, endpoints, env values or dotenv.' }] }
  const toolsetCandidates = candidates()
  const selectedToolsetPolicy = inspection?.noToolsetsTextOnlySupported === true ? 'no_toolsets_text_only' : null
  const preferredFutureToolsetMode = selectedToolsetPolicy === 'no_toolsets_text_only' ? 'no_toolsets_text_only' as const : 'toolset_selection_requires_manual_review' as const
  const plan = { planCandidateId: `${out.planningId}:toolsets-policy-plan-candidate`, toolId: 'hermes_agent' as const, commandShapeUnderConsideration: 'oneshot_real_with_provider_model' as const, futureCommandShape: { executable: 'hermes.exe' as const, argsTemplate: ['--oneshot', '<PROMPT>', '--provider', '<PROVIDER>', '--model', '<MODEL>', '--toolsets', '<TOOLSETS>'] as ['--oneshot', '<PROMPT>', '--provider', '<PROVIDER>', '--model', '<MODEL>', '--toolsets', '<TOOLSETS>'], shell: false as const }, toolsetCandidates, toolsetsRules: rules(), selectedToolsetPolicy, toolsetsAllowedNow: false as const, toolsetsApprovedNow: [] as [], explicitToolsetsRequiredForFutureRuntime: true as const, hiddenDefaultToolsetsForbidden: true as const, configDrivenToolsetsForbiddenWithoutApproval: true as const, preferredFutureToolsetMode, webBrowserPolicy: { webToolsAllowedNow: false as const, browserToolsAllowedNow: false as const, searchToolsAllowedNow: false as const, requiresNetworkPolicyApproval: true as const }, terminalPolicy: { terminalToolsAllowedNow: false as const, terminalToolsAllowedInInitialResearch: false as const }, filesystemPolicy: { filesystemToolsAllowedNow: false as const, requiresFilesystemMutationPolicy: true as const }, mcpPolicy: { mcpAllowedNow: false as const, requiresSeparateMcpPolicy: true as const }, runtimeReportingRequirements: ['toolsetsRequested', 'toolsetsApproved', 'toolsetsUsed', 'toolExecutionStatus', 'unexpectedToolUse'] as ['toolsetsRequested', 'toolsetsApproved', 'toolsetsUsed', 'toolExecutionStatus', 'unexpectedToolUse'], requiredNextPolicies: TOOLSETS_REQUIRED_NEXT_POLICIES, canProceedToOutputContractPolicyPlanning: true as const, canProceedToResearchExecutionApproval: false as const, canEnableToolsetsNow: false as const }
  const receipt = { receiptId: `${out.planningId}:receipt`, planningId: out.planningId, toolId: 'hermes_agent' as const, plannedBy: input.plannedBy, plannedAt: input.plannedAt, decision: 'hermes_toolsets_policy_plan_created' as const, scope: 'hermes_toolsets_policy_planning_only' as const, approvedNextGate: 'Factory Hermes Output Contract Policy Planning Gate v1' as const, limitations: ['No toolsets are enabled by this gate.', 'Default CLI toolsets remain forbidden without explicit approval.', 'Web/browser/search/MCP/terminal/filesystem tools remain blocked.'], notAuthorizedActions: TOOLSETS_NOT_AUTHORIZED_ACTIONS }
  return { ...out, status: 'toolsets_policy_plan_created', decision: 'hermes_toolsets_policy_plan_created', toolsetCandidates, selectedToolsetPolicy, toolsetsPolicyPlanningReceipt: receipt, hermesToolsetsPolicyPlanCandidate: plan, canProceedToOutputContractPolicyPlanning: true }
}
