import { FACTORY_HERMES_RESEARCH_RUNTIME_PLANNING_KIND, FACTORY_HERMES_RESEARCH_RUNTIME_PLANNING_NEXT_STEP, FACTORY_HERMES_RESEARCH_RUNTIME_PLANNING_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_RESEARCH_RUNTIME_PLANNING_VERSION } from './hermes-research-runtime-planning.defaults.ts'
import type { FactoryHermesResearchRuntimePlanningDecision, FactoryHermesResearchRuntimePlanningInput, FactoryHermesResearchRuntimePlanningResult, FactoryHermesResearchRuntimePlanningStatus, FactoryHermesResearchRuntimePlanCandidate } from './hermes-research-runtime-planning.types.ts'

const nextGates = ['Factory Hermes Research Runtime Boundary Contract v1', 'Factory Hermes Research Runtime Approval Gate v1', 'Factory Hermes Research Runtime Adapter v1', 'Factory Hermes Research Result Ingestion Gate v1', 'Factory Hermes Research JEFE Review Gate v1']
function plan(input: FactoryHermesResearchRuntimePlanningInput, canProceed: boolean): FactoryHermesResearchRuntimePlanCandidate {
  const r = input.pythonInstallJefeReviewResult
  const s = input.sourceInspection
  return { planCandidateId: `hermes-research-runtime-plan:75b300f:${input.plannedAt}`, toolId: 'hermes_agent', auditedHead: r.auditedHead, sourceRootRef: r.sourceRootRef, installRootRef: r.installRootRef, pythonEnvRootRef: r.pythonEnvRootRef, uvExecutableRef: r.uvExecutableRef, interfaceStatus: s.interfaceStatus, selectedInterfaceCandidate: canProceed && s.interfaceCandidates.length === 1 ? s.interfaceCandidates[0] : undefined, interfaceCandidates: s.interfaceCandidates, runtimeModeCandidate: 'hermes_research_runtime_controlled', proposedRuntimeBoundary: { allowedFilesystemRoots: [r.installRootRef], forbiddenFilesystemRoots: ['.env', 'node_modules', 'web-prueba'], workingDirectory: r.sourceRootRef, outputDirectory: `${r.installRootRef}/research-output/`, tempDirectory: `${r.installRootRef}/research-temp/`, cacheDirectory: `${r.installRootRef}/research-cache/` }, proposedCommandPolicy: { commandsAllowedNow: [], commandsAllowedInFutureRuntimeCandidate: s.interfaceCandidates.map((c: any) => c.commandTextCandidate).filter(Boolean), commandsForbidden: ['pip', 'setup.py', 'uv pip', 'uv run unrestricted', 'shell', 'cmd', 'powershell'] }, proposedNetworkPolicy: { networkAllowedNow: false, futureNetworkRequiresApproval: true, allowedDomainsFuture: [], blockedByDefault: true }, proposedCredentialPolicy: { credentialsAllowedNow: false, futureCredentialsRequireApproval: true, noEnvReadInPlanning: true }, proposedModelPolicy: { modelCallsAllowedNow: false, futureModelCallsRequireApproval: true }, proposedInputContract: { researchQuestion: 'required', constraints: 'required', allowedSources: [], forbiddenSources: [], maxRuntimeMs: 300000, outputSchema: 'structured_findings_v1' }, proposedOutputContract: { structuredFindings: true, citationsOrEvidence: true, confidence: true, warnings: true, rawLogsSanitized: true }, proposedSafety: { timeouts: true, killSwitches: true, logSanitization: true, resultIngestionRequired: true, jefeReviewRequired: true }, requiredNextGates: nextGates }
}
export function evaluateFactoryHermesResearchRuntimePlanning(input: FactoryHermesResearchRuntimePlanningInput): FactoryHermesResearchRuntimePlanningResult {
  const r = input.pythonInstallJefeReviewResult
  const s = input.sourceInspection
  const base = { planningId: `hermes-research-runtime-planning:75b300f:${input.plannedAt}`, planningKind: FACTORY_HERMES_RESEARCH_RUNTIME_PLANNING_KIND, planningVersion: FACTORY_HERMES_RESEARCH_RUNTIME_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent' as const, auditedHead: r?.auditedHead || '', sourceRootRef: r?.sourceRootRef || '', installRootRef: r?.installRootRef || '', pythonEnvRootRef: r?.pythonEnvRootRef || '', uvExecutableRef: r?.uvExecutableRef || '', pythonInstallJefeReviewRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-install-jefe-review-result.json', pythonInstallVerificationRef: r?.pythonInstallVerificationRef || '', sourceInspectionSummary: s?.summary || {}, interfaceStatus: s?.interfaceStatus || 'missing', interfaceCandidates: s?.interfaceCandidates || [], checks: [], blockers: [], warnings: [], canExecuteHermes: false as const, canRunHermesScripts: false as const, canUseCredentials: false as const, canCallModels: false as const, canUseNetwork: false as const, canMutateProjectFiles: false as const, canDeploy: false as const, recommendedNextStep: FACTORY_HERMES_RESEARCH_RUNTIME_PLANNING_NEXT_STEP }
  if (!r) return { ...base, status: 'blocked', decision: 'blocked_missing_jefe_review', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_missing_jefe_review', message: 'JEFE Review result is required.' }] }
  if (r.status !== 'approved' || r.decision !== 'hermes_python_install_jefe_review_approved_for_research_runtime_planning' || r.canProceedToResearchRuntimePlanning !== true || r.canExecuteHermes !== false) return { ...base, status: 'blocked', decision: 'blocked_jefe_review_not_approved_for_planning', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_jefe_review_not_approved_for_planning', message: 'JEFE Review is not approved for planning.' }] }
  if (!s || s.interfaceStatus === 'blocked_source_missing') return { ...base, status: 'blocked', decision: 'blocked_source_missing', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_source_missing', message: 'Source inspection is required.' }] }
  if (s.pythonInstallVerified !== true || s.uvVerified !== true) return { ...base, status: 'blocked', decision: 'blocked_python_install_not_ready', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_python_install_not_ready', message: 'Python/UV readiness is not verified.' }] }
  const canProceed = s.interfaceStatus === 'interface_candidate_identified'
  const decision: FactoryHermesResearchRuntimePlanningDecision = canProceed ? 'hermes_research_runtime_plan_candidate_created' : s.interfaceStatus === 'interface_requires_manual_selection' ? 'hermes_research_runtime_plan_requires_manual_interface_selection' : 'request_source_interface_review'
  const status: FactoryHermesResearchRuntimePlanningStatus = canProceed ? 'plan_candidate_created' : 'manual_selection_required'
  const planningReceipt = { receiptId: `${base.planningId}:receipt`, planningId: base.planningId, toolId: 'hermes_agent' as const, auditedHead: r.auditedHead, plannedBy: input.plannedBy, plannedAt: input.plannedAt, decision, scope: 'hermes_research_runtime_planning_only' as const, approvedNextGate: 'Factory Hermes Research Runtime Boundary Contract v1' as const, limitations: ['Planning only.', 'No runtime execution.', 'No network, credentials or model calls.'], notAuthorizedActions: FACTORY_HERMES_RESEARCH_RUNTIME_PLANNING_NOT_AUTHORIZED_ACTIONS }
  return { ...base, status, decision, researchRuntimePlanningReceipt: planningReceipt, hermesResearchRuntimePlanCandidate: plan(input, canProceed), canProceedToResearchRuntimeBoundary: canProceed }
}
