export type FactoryHermesResearchRuntimePlanningVersion = '1.0'
export type FactoryHermesResearchRuntimePlanningKind = 'factory-hermes-research-runtime-planning'
export type FactoryHermesResearchRuntimePlanningStatus = 'plan_candidate_created' | 'manual_selection_required' | 'blocked'
export type FactoryHermesResearchRuntimePlanningDecision = 'hermes_research_runtime_plan_candidate_created' | 'hermes_research_runtime_plan_requires_manual_interface_selection' | 'blocked_missing_jefe_review' | 'blocked_jefe_review_not_approved_for_planning' | 'blocked_source_missing' | 'blocked_python_install_not_ready' | 'request_source_interface_review'
export interface FactoryHermesResearchRuntimeInterfaceCandidate { candidateId: string; label: string; source: string; confidence: 'low' | 'medium' | 'high'; commandTextCandidate?: string; reason: string }
export interface FactoryHermesResearchRuntimePlanningInput { plannedAt: string; plannedBy: string; pythonInstallJefeReviewResult?: any; sourceInspection?: any; targetUseCase?: string; policy?: Partial<FactoryHermesResearchRuntimePlanningPolicy>; planningNotes?: string }
export interface FactoryHermesResearchRuntimePlanningPolicy { requireJefeReviewApprovedForPlanning: boolean; requirePythonInstallVerified: boolean; requireUvVerified: boolean; requireSourceInspection: boolean; requireSourceRootUnderCodexTemp: boolean; requirePythonEnvRootUnderCodexTemp: boolean; requireResearchRuntimeBoundaryNext: boolean; requireApprovalBeforeRuntime: boolean; forbidHermesExecutionInThisGate: boolean; forbidHermesScriptsInThisGate: boolean; forbidUvExecutionInThisGate: boolean; forbidPipExecutionInThisGate: boolean; forbidPythonExecutionInThisGate: boolean; forbidSetupPyExecutionInThisGate: boolean; forbidCredentialsInThisGate: boolean; forbidModelCallsInThisGate: boolean; forbidNetworkInThisGate: boolean; forbidProjectMutationInThisGate: boolean; forbidDeployInThisGate: boolean; forbidDirectRuntimeAfterPlanning: boolean }
export interface FactoryHermesResearchRuntimePlanCandidate { planCandidateId: string; toolId: 'hermes_agent'; auditedHead: string; sourceRootRef: string; installRootRef: string; pythonEnvRootRef: string; uvExecutableRef: string; interfaceStatus: string; selectedInterfaceCandidate?: FactoryHermesResearchRuntimeInterfaceCandidate; interfaceCandidates: FactoryHermesResearchRuntimeInterfaceCandidate[]; runtimeModeCandidate: 'hermes_research_runtime_controlled'; proposedRuntimeBoundary: Record<string, unknown>; proposedCommandPolicy: Record<string, unknown>; proposedNetworkPolicy: Record<string, unknown>; proposedCredentialPolicy: Record<string, unknown>; proposedModelPolicy: Record<string, unknown>; proposedInputContract: Record<string, unknown>; proposedOutputContract: Record<string, unknown>; proposedSafety: Record<string, unknown>; requiredNextGates: string[] }
export interface FactoryHermesResearchRuntimePlanningReceipt { receiptId: string; planningId: string; toolId: 'hermes_agent'; auditedHead: string; plannedBy: string; plannedAt: string; decision: FactoryHermesResearchRuntimePlanningDecision; scope: 'hermes_research_runtime_planning_only'; approvedNextGate: 'Factory Hermes Research Runtime Boundary Contract v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesResearchRuntimePlanningCheck { checkId: string; ok: boolean; message: string }
export interface FactoryHermesResearchRuntimePlanningBlocker { blockerId: string; message: string }
export interface FactoryHermesResearchRuntimePlanningWarning { warningId: string; message: string }
export interface FactoryHermesResearchRuntimePlanningResult { planningId: string; planningKind: FactoryHermesResearchRuntimePlanningKind; planningVersion: FactoryHermesResearchRuntimePlanningVersion; plannedAt: string; plannedBy: string; toolId: 'hermes_agent'; auditedHead: string; sourceRootRef: string; installRootRef: string; pythonEnvRootRef: string; uvExecutableRef: string; pythonInstallJefeReviewRef: string; pythonInstallVerificationRef: string; sourceInspectionSummary: Record<string, unknown>; interfaceStatus: string; interfaceCandidates: FactoryHermesResearchRuntimeInterfaceCandidate[]; researchRuntimePlanningReceipt?: FactoryHermesResearchRuntimePlanningReceipt; hermesResearchRuntimePlanCandidate?: FactoryHermesResearchRuntimePlanCandidate; checks: FactoryHermesResearchRuntimePlanningCheck[]; blockers: FactoryHermesResearchRuntimePlanningBlocker[]; warnings: FactoryHermesResearchRuntimePlanningWarning[]; status: FactoryHermesResearchRuntimePlanningStatus; decision: FactoryHermesResearchRuntimePlanningDecision; canProceedToResearchRuntimeBoundary: boolean; canExecuteHermes: false; canRunHermesScripts: false; canUseCredentials: false; canCallModels: false; canUseNetwork: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesResearchRuntimePlanningValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesResearchRuntimePlanningSummary { planningId: string; toolId: 'hermes_agent'; auditedHead: string; interfaceStatus: string; interfaceCandidatesCount: number; decision: FactoryHermesResearchRuntimePlanningDecision; status: FactoryHermesResearchRuntimePlanningStatus; canProceedToResearchRuntimeBoundary: boolean; canExecuteHermes: false; approvedNextGate?: string; nextStep: string }
