import type { FactoryContractRegistryIndex } from '../contract-registry/index.ts'
export type FactoryContractRegistryIntegrityVersion = '1.0'
export type FactoryContractRegistryIntegrityKind = 'factory-contract-registry-integrity'
export type FactoryContractRegistryIntegrityStatus = 'clean' | 'warning' | 'blocked'
export type FactoryContractRegistryIntegrityFindingSeverity = 'info' | 'warning' | 'error' | 'critical'
export type FactoryContractRegistryIntegrityFindingKind = 'missing_contract_file' | 'missing_metadata_file' | 'fingerprint_mismatch' | 'idempotency_mismatch' | 'metadata_contract_mismatch' | 'unsafe_path' | 'unsafe_flags' | 'duplicate_fingerprint' | 'duplicate_idempotency_key' | 'conflicting_project_identity' | 'invalid_entry' | 'stale_index' | 'unknown_warning'
export interface FactoryContractRegistryIntegrityInput { storageRoot: string; registryIndex?: FactoryContractRegistryIndex; checkedAt: string; checkedBy: string; policy?: Partial<FactoryContractRegistryIntegrityPolicy> }
export interface FactoryContractRegistryIntegrityPolicy { requireStorageRootInsideCodexTemp: true; requireContractFile: true; requireMetadataFile: true; requireFingerprintMatch: true; requireIdempotencyKeyMatch: true; requireFlagsSafe: true; requirePathContainment: true; requireNoDuplicateCriticalConflicts: true; requireNoMissingContract: true; requireNoMissingMetadata: true; requireNoTamperingSignals: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; allowMemoryUseOnlyIfClean: true; allowCodexTaskUse: false }
export interface FactoryContractRegistryIntegrityCheck { checkId: string; passed: boolean; message: string }
export interface FactoryContractRegistryIntegrityFinding { findingId: string; registryEntryId?: string; kind: FactoryContractRegistryIntegrityFindingKind; severity: FactoryContractRegistryIntegrityFindingSeverity; message: string }
export interface FactoryContractRegistryIntegrityEntryResult { registryEntryId: string; contractProjectId: string; projectSlug: string; targetPath: string; metadataPath: string; expectedFingerprint: string; recalculatedFingerprint?: string; expectedIdempotencyKey: string; recalculatedIdempotencyKey?: string; contractExists: boolean; metadataExists: boolean; metadataMatchesContract: boolean; fingerprintMatches: boolean; idempotencyMatches: boolean; flagsSafe: boolean; pathContained: boolean; status: FactoryContractRegistryIntegrityStatus; checks: FactoryContractRegistryIntegrityCheck[]; findings: FactoryContractRegistryIntegrityFinding[]; canUseForMemory: boolean; canUseForCodexTask: false; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false }
export interface FactoryContractRegistryIntegritySummary { totalEntries: number; statusCounts: Record<string, number>; severityCounts: Record<string, number>; criticalFindings: number; cleanEntries: number; blockedEntries: number; canUseForMemory: number; canUseForCodexTask: 0; recommendedNextStep: string }
export interface FactoryContractRegistryIntegrityReport { integrityKind: FactoryContractRegistryIntegrityKind; integrityVersion: FactoryContractRegistryIntegrityVersion; generatedAt: string; checkedBy: string; storageRoot: string; registryIndexRef?: string; status: FactoryContractRegistryIntegrityStatus; entries: FactoryContractRegistryIntegrityEntryResult[]; summary: FactoryContractRegistryIntegritySummary; findings: FactoryContractRegistryIntegrityFinding[]; blockers: string[]; warnings: string[]; recommendedNextStep: string }
export interface FactoryContractRegistryIntegrityValidationResult { ok: boolean; errors: string[]; warnings: string[] }
