import { FACTORY_CONTRACT_REGISTRY_INTEGRITY_KIND, FACTORY_CONTRACT_REGISTRY_INTEGRITY_STATUSES, FACTORY_CONTRACT_REGISTRY_INTEGRITY_VERSION } from './contract-registry-integrity.defaults.ts'
import type { FactoryContractRegistryIntegrityEntryResult, FactoryContractRegistryIntegrityReport, FactoryContractRegistryIntegrityValidationResult } from './contract-registry-integrity.types.ts'
const unsafe = (entry: FactoryContractRegistryIntegrityEntryResult) => entry.canUseForCodexTask !== false || entry.canExecuteCodex !== false || entry.canCreateProject !== false || entry.canCreateRepository !== false || entry.canDeploy !== false
export function validateFactoryContractRegistryIntegrityEntryResult(entry: FactoryContractRegistryIntegrityEntryResult): FactoryContractRegistryIntegrityValidationResult {
  const errors: string[] = []; const warnings = entry?.findings?.filter((item) => item.severity === 'warning').map((item) => item.message) ?? []
  if (!entry?.registryEntryId?.trim() || !entry?.contractProjectId?.trim()) errors.push('Entry and project IDs are required.'); if (!entry?.targetPath?.trim() || !entry?.metadataPath?.trim()) errors.push('Entry paths are required.'); if (!FACTORY_CONTRACT_REGISTRY_INTEGRITY_STATUSES.includes(entry?.status)) errors.push('Integrity entry status is invalid.'); if (!Array.isArray(entry?.findings)) errors.push('findings must be an array.'); if (unsafe(entry)) errors.push('Execution and creation capabilities must remain disabled.')
  const critical = entry?.findings?.some((item) => item.severity === 'critical'); if (entry?.status === 'clean' && critical) errors.push('Clean entry cannot contain critical findings.'); if (entry?.status === 'clean' && (!entry.flagsSafe || !entry.pathContained || !entry.fingerprintMatches || !entry.idempotencyMatches)) errors.push('Clean entry must pass flags, containment, fingerprint and idempotency checks.'); if (entry?.status === 'clean' && entry.expectedFingerprint && entry.recalculatedFingerprint && entry.expectedFingerprint !== entry.recalculatedFingerprint) errors.push('Clean entry fingerprints must match.')
  return { ok: errors.length === 0, errors, warnings }
}
export function validateFactoryContractRegistryIntegrityReport(report: FactoryContractRegistryIntegrityReport): FactoryContractRegistryIntegrityValidationResult {
  const errors: string[] = []; const warnings = [...(report?.warnings ?? [])]
  if (report?.integrityKind !== FACTORY_CONTRACT_REGISTRY_INTEGRITY_KIND) errors.push('integrityKind is invalid.'); if (report?.integrityVersion !== FACTORY_CONTRACT_REGISTRY_INTEGRITY_VERSION) errors.push('integrityVersion is invalid.'); if (!Array.isArray(report?.entries) || !report?.summary) errors.push('entries and summary are required.'); if (!Array.isArray(report?.blockers) || !Array.isArray(report?.warnings)) errors.push('blockers and warnings must be arrays.'); if (report?.entries?.some(unsafe)) errors.push('Report contains an unsafe entry.'); if (report?.findings?.some((item) => item.severity === 'critical') && report.status === 'clean') errors.push('Report with critical findings cannot be clean.'); if (!report?.recommendedNextStep?.trim()) errors.push('recommendedNextStep is required.')
  return { ok: errors.length === 0, errors, warnings }
}
