import type { FactoryHermesResearchExecutionBoundaryPlanningKind, FactoryHermesResearchExecutionBoundaryPlanningPolicy, FactoryHermesResearchExecutionBoundaryPlanningVersion } from './hermes-research-execution-boundary-planning.types.ts'

export const FACTORY_HERMES_RESEARCH_EXECUTION_BOUNDARY_PLANNING_KIND: FactoryHermesResearchExecutionBoundaryPlanningKind = 'factory-hermes-research-execution-boundary-planning'
export const FACTORY_HERMES_RESEARCH_EXECUTION_BOUNDARY_PLANNING_VERSION: FactoryHermesResearchExecutionBoundaryPlanningVersion = '1.0'
export const FACTORY_HERMES_RESEARCH_EXECUTION_BOUNDARY_PLANNING_NEXT_STEP = 'Proceed to Factory Hermes Research Execution Approval Gate v1 for evaluation only; do not execute Hermes or pass prompts.'

export const DEFAULT_FACTORY_HERMES_RESEARCH_EXECUTION_BOUNDARY_PLANNING_POLICY: FactoryHermesResearchExecutionBoundaryPlanningPolicy = {
  requirePolicyChainPlanning: true, requirePromptPolicyPlanning: true, requireModelProviderPolicyPlanning: true, requireCredentialsPolicyPlanning: true, requireNetworkPolicyPlanning: true, requireToolsetsPolicyPlanning: true, requireOutputContractPolicyPlanning: true, requireResultIngestionContractPlanning: true, requireTimeoutKillSwitchPolicyPlanning: true, requireFilesystemMutationPolicyPlanning: true, requireAllPoliciesConsolidated: true, requireMissingRuntimeSelections: true, requireResearchExecutionApprovalNext: true, forbidExecutionInThisGate: true, forbidPromptExecutionInThisGate: true, forbidHermesExecutionInThisGate: true, forbidResearchExecutionInThisGate: true, forbidNetworkInThisGate: true, forbidCredentialUseInThisGate: true, forbidEnvSecretReadsInThisGate: true, forbidModelCallsInThisGate: true, forbidToolsetEnablementInThisGate: true, forbidFilesystemMutationInThisGate: true, forbidOutputIngestionInThisGate: true, forbidFindingsUseInThisGate: true, forbidDeployInThisGate: true,
}

export const RESEARCH_EXECUTION_BOUNDARY_NOT_AUTHORIZED_ACTIONS = ['approve_execution_now', 'execute_oneshot_now', 'pass_prompt_now', 'run_research_now', 'execute_hermes_now', 'call_models_now', 'use_network_now', 'access_credentials_now', 'enable_toolsets_now', 'mutate_filesystem_now', 'write_project_files_now', 'ingest_real_output_now', 'promote_findings_now', 'write_findings_to_memory_now', 'execute_uv_now', 'execute_python_now', 'execute_pip_now', 'execute_setup_py_now', 'deploy_now']
