import { createJefeOpportunityDecisionPolicy, JEFE_OPPORTUNITY_DECISION_GATE_KIND, JEFE_OPPORTUNITY_DECISION_GATE_VERSION, JEFE_SENSITIVE_OPPORTUNITY_CATEGORIES } from './jefe-decision.defaults.ts'
import type { JefeFactoryBriefDraftSignal, JefeFactoryProjectCandidateSignal, JefeOpportunityDecisionEvidenceSummary, JefeOpportunityDecisionInput, JefeOpportunityDecisionReason, JefeOpportunityDecisionResult, JefeOpportunityDecisionRisk, JefeOpportunityDecisionType } from './jefe-decision.types.ts'

const reason = (code: string, message: string, source: JefeOpportunityDecisionReason['source']): JefeOpportunityDecisionReason => ({ code, message, source })
const slugify = (value: string) => value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 63) || 'factory-candidate'

export function evaluateJefeOpportunityDecision(input: JefeOpportunityDecisionInput): JefeOpportunityDecisionResult {
  const value = structuredClone(input); const policy = createJefeOpportunityDecisionPolicy(value.policy)
  const { opportunity, radarEvaluation, hermesReport } = value; const radarScore = radarEvaluation.score.total
  const requiredCoverage = hermesReport?.requiredCoverage ?? []; const satisfiedCoverage = hermesReport?.satisfiedCoverage ?? []
  const missingCoverage = requiredCoverage.filter((item) => !satisfiedCoverage.includes(item))
  const evidenceSummary: JefeOpportunityDecisionEvidenceSummary = { radarEvidenceSufficient: radarEvaluation.evidenceSufficient, hermesReportPresent: Boolean(hermesReport), hermesReportStatus: hermesReport?.status, evidenceItems: hermesReport?.evidence.length ?? 0, distinctSources: hermesReport?.confidence.distinctSourceCount ?? 0, confidence: hermesReport ? hermesReport.confidence.score / 100 : undefined, requiredCoverage, satisfiedCoverage, missingCoverage, contradictions: hermesReport?.contradictions.length ?? 0 }
  const risks: JefeOpportunityDecisionRisk[] = [
    ...opportunity.risks.map((risk) => ({ riskId: risk.riskId, severity: risk.severity, category: risk.type, description: risk.description, source: 'opportunity' as const })),
    ...radarEvaluation.risks.map((risk) => ({ riskId: risk.riskId, severity: risk.severity, category: risk.type, description: risk.description, source: 'radar' as const })),
    ...(hermesReport?.riskFindings.map((risk) => ({ riskId: risk.riskId, severity: risk.severity, category: risk.category, description: risk.description, source: 'hermes' as const })) ?? []),
  ]
  const criticalRisk = risks.some((risk) => risk.severity === 'critical'); const sensitive = JEFE_SENSITIVE_OPPORTUNITY_CATEGORIES.includes(opportunity.category as typeof JEFE_SENSITIVE_OPPORTUNITY_CATEGORIES[number]) || opportunity.legalSensitivity >= 4
  const strongContradictions = evidenceSummary.contradictions >= 2 || (hermesReport?.confidence.contradictionPenalty ?? 0) >= 0.25
  const evidenceReady = Boolean(hermesReport && hermesReport.status === 'completed' && evidenceSummary.evidenceItems >= policy.minimumEvidenceItemsForBrief && (!policy.requireDiverseSources || evidenceSummary.distinctSources >= 2) && evidenceSummary.missingCoverage.length === 0 && (evidenceSummary.confidence ?? 0) >= policy.minimumHermesConfidenceForBrief)
  let decision: JefeOpportunityDecisionType = 'blocked'; const reasons: JefeOpportunityDecisionReason[] = []; const blockers: string[] = []; const warnings: string[] = []

  if (radarEvaluation.decision.type === 'reject') { decision = 'reject_opportunity'; reasons.push(reason('radar_rejected', 'Radar rejected the opportunity.', 'radar')) }
  else if (radarEvaluation.decision.type === 'hold') { decision = 'hold_opportunity'; reasons.push(reason('radar_hold', 'Radar placed the opportunity on hold.', 'radar')) }
  else if (criticalRisk || sensitive || radarEvaluation.decision.type === 'needs_human_review' || hermesReport?.recommendedDecisionForJefe === 'human_review_required') { decision = 'human_review_required'; blockers.push(criticalRisk ? 'critical_risk' : 'sensitive_or_human_review_policy'); reasons.push(reason('human_review_gate', 'Risk or sensitivity requires human review before any brief or candidate signal.', 'jefe_policy')) }
  else if (!hermesReport && (radarEvaluation.decision.type === 'research_with_hermes' || policy.requireHermesForBrief)) { decision = 'request_more_research'; blockers.push('hermes_report_missing'); reasons.push(reason('hermes_required', 'A completed Hermes report is required before brief approval.', 'jefe_policy')) }
  else if (strongContradictions) { decision = 'request_more_research'; blockers.push('strong_contradictions'); reasons.push(reason('contradictions', 'Strong contradictions prevent brief approval.', 'hermes')) }
  else if (!evidenceReady) { decision = 'request_more_research'; blockers.push('evidence_or_coverage_insufficient'); reasons.push(reason('research_incomplete', 'Hermes evidence, confidence, diversity or coverage is insufficient.', 'hermes')) }
  else if (radarScore < policy.minimumRadarScoreForBrief) { decision = 'hold_opportunity'; blockers.push('radar_score_below_threshold'); reasons.push(reason('radar_threshold', 'Radar score is below the brief threshold.', 'radar')) }
  else if (value.humanApproval?.approved && value.humanApproval.scope === 'project_candidate') { decision = 'prepare_factory_project_candidate'; reasons.push(reason('human_candidate_approval', 'Human approval authorizes preparation of a contract candidate signal only.', 'human')) }
  else { decision = 'approve_brief_draft'; reasons.push(reason('brief_evidence_ready', 'Radar and Hermes evidence meet the governed brief-draft thresholds.', 'jefe_policy')) }

  if (!opportunity.monetizationHypothesis.trim()) warnings.push('Monetization hypothesis is missing.')
  if (opportunity.buildComplexity >= 4) warnings.push('Build complexity is high and must be reflected in the future brief.')
  if (opportunity.operationalCost >= 4) warnings.push('Operational cost is high and needs explicit acceptance criteria.')
  const requiredHumanReview = { required: decision === 'human_review_required' || decision === 'prepare_factory_project_candidate', satisfied: decision === 'prepare_factory_project_candidate', reason: decision === 'prepare_factory_project_candidate' ? 'Human approval supplied for candidate preparation.' : decision === 'human_review_required' ? 'Risk or sensitivity requires review.' : 'No human approval required at this gate.', approvedBy: value.humanApproval?.approvedBy, approvedAt: value.humanApproval?.approvedAt }
  let briefDraftSignal: JefeFactoryBriefDraftSignal | undefined; let projectCandidateSignal: JefeFactoryProjectCandidateSignal | undefined
  if (decision === 'approve_brief_draft') briefDraftSignal = { opportunityId: opportunity.id, title: opportunity.title, problem: opportunity.problem, audience: opportunity.audience, proposedSolution: opportunity.proposedSolution, monetizationHypothesis: opportunity.monetizationHypothesis, evidenceSummary, risks, assumptions: [...opportunity.assumptions], openQuestions: [...opportunity.openQuestions], requiredAcceptanceCriteriaDraft: ['Satisfy the validated market problem and target audience.', 'Preserve product runtime independence from JEFE.', 'Define measurable quality, security and monetization acceptance criteria.'], nextStep: 'draft_factory_brief' }
  if (decision === 'prepare_factory_project_candidate' && value.humanApproval) projectCandidateSignal = { opportunityId: opportunity.id, candidateSlugSuggestion: slugify(opportunity.title), candidateName: opportunity.title, contractReadiness: 'candidate_only', repositoryRequired: true, runtimeIndependenceRequired: true, requiresFactoryProjectContract: true, requiresHumanApprovalBeforeCodex: true, humanApprovalReference: `${value.humanApproval.approvedBy}:${value.humanApproval.approvedAt}`, nextStep: 'create_factory_project_contract_candidate' }
  const nextSteps: Record<JefeOpportunityDecisionType, string> = { reject_opportunity: 'Archive the decision evidence; no construction is authorized.', hold_opportunity: 'Hold and revisit when market or policy evidence changes.', request_more_research: 'Request bounded research through JefeHermesAdapter.', human_review_required: 'Escalate evidence and risks to a human reviewer.', approve_brief_draft: 'Draft a Factory brief for JEFE review.', prepare_factory_project_candidate: 'Prepare a FactoryProjectContract candidate for human review; do not invoke Codex.', blocked: 'Resolve validation blockers before reevaluation.' }
  return { decisionId: `jefe-decision-${slugify(opportunity.id)}-${value.createdAt.replace(/[^0-9]/g, '')}`, decisionKind: JEFE_OPPORTUNITY_DECISION_GATE_KIND, decisionVersion: JEFE_OPPORTUNITY_DECISION_GATE_VERSION, createdAt: value.createdAt, opportunityId: opportunity.id, radarScore, hermesConfidence: evidenceSummary.confidence, decision, reasons, risks, blockers, warnings, evidenceSummary, requiredHumanReview, briefDraftSignal, projectCandidateSignal, appliedPolicy: policy, recommendedNextStep: nextSteps[decision], codexAllowed: false, projectCreationAllowed: false, deployAllowed: false }
}
