export type FactoryHermesWrapperNoToolModePlanningVersion = '1.0'
export type FactoryHermesWrapperNoToolModePlanningKind = 'factory-hermes-wrapper-no-tool-mode-planning'
export type FactoryHermesWrapperNoToolModePlanningStatus = 'wrapper_no_tool_mode_plan_created' | 'wrapper_no_tool_mode_plan_blocked'
export type FactoryHermesWrapperNoToolModePlanningDecision = 'hermes_wrapper_no_tool_mode_plan_created_for_approval' | 'hermes_wrapper_no_tool_mode_plan_blocked_no_safe_wrapper_strategy'
export type FactoryHermesWrapperNoToolModePlanningState = 'plan_candidate_created' | 'blocked'
export interface FactoryHermesWrapperNoToolModePlanningInput { plannedAt: string; plannedBy: string; runtimeSelectionRevisionPlanningResult?: any; toolsetDisableVerificationApprovalResult?: any; researchRuntimeAdapterApprovalResult?: any; runtimeSelectionDecisionResult?: any; sourceInspection?: any; policy?: Partial<FactoryHermesWrapperNoToolModePlanningPolicy>; planningNotes?: string }
export interface FactoryHermesWrapperNoToolModePlanningPolicy { requireRuntimeSelectionRevisionPlanning: boolean; requireToolsetDisableApprovalBlocked: boolean; requireSourceInspection: boolean; requireWrapperStrategyCandidates: boolean; requireNoSourceMutationInPlanning: boolean; requireNoWrapperImplementationInPlanning: boolean; requireNoExecutionInThisGate: boolean; requireNoPromptPassingInThisGate: boolean; requireNoNetworkInThisGate: boolean; requireNoCredentialUseInThisGate: boolean; requireNoModelCallsInThisGate: boolean; requireNoToolsetEnablementInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidResearchExecutionInThisGate: boolean; forbidUsingFindingsInThisGate: boolean; forbidDeployInThisGate: boolean }
export interface FactoryHermesWrapperSourceInspectionMap { entryPoints: Record<string, any>; toolLoading: Record<string, any>; wrapperOpportunities: Record<string, any>; wrapperBlockers: string[]; sourceFilesInspected: string[] }
export interface FactoryHermesWrapperStrategyCandidate { strategyId: string; description: string; status: string; risk: string; requiresSourceProof?: boolean; requiresApprovedTempConfigPath?: boolean; modifiesHermesSource: boolean; executesNow: false; reason?: string }
export interface FactoryHermesWrapperNoToolModeDecisionPack { packId: string; pendingDecisions: Array<{ decisionId: string; label: string; status: 'pending_human_decision'; risk: string; impact: string; recommended: boolean; blockedUntilChosen: boolean }> }
export interface FactoryHermesWrapperNoToolModeRecommendation { chosenStrategyId: string; pathId: string; reason: string; requiredNextGate: string; executionAllowedNow: false }
export interface FactoryHermesWrapperNoToolModePlanCandidate { planCandidateId: string; toolId: 'hermes_agent'; purpose: string; wrapperSourceInspectionMap: FactoryHermesWrapperSourceInspectionMap; wrapperStrategyCandidates: FactoryHermesWrapperStrategyCandidate[]; recommendedWrapperPath: FactoryHermesWrapperNoToolModeRecommendation; directHermesRuntimeAdapterBlocked: true; sourceMutationAllowedNow: false; wrapperImplementationAllowedNow: false; wrapperExecutionAllowedNow: false; runtimeAdapterAllowedNow: false; researchExecutionAllowedNow: false; canProceedToHermesWrapperNoToolModeApproval: boolean; canProceedToResearchRuntimeAdapterApprovalRetry: false; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false }
export interface FactoryHermesWrapperNoToolModePlanningReceipt { receiptId: string; planningId: string; toolId: 'hermes_agent'; plannedBy: string; plannedAt: string; decision: FactoryHermesWrapperNoToolModePlanningDecision; scope: 'hermes_wrapper_no_tool_mode_planning_only'; approvedNextGate: string; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesWrapperNoToolModePlanningCheck { checkId: string; message: string }
export interface FactoryHermesWrapperNoToolModePlanningBlocker { blockerId: string; message: string }
export interface FactoryHermesWrapperNoToolModePlanningWarning { warningId: string; message: string }
export interface FactoryHermesWrapperNoToolModePlanningResult { planningId: string; planningKind: FactoryHermesWrapperNoToolModePlanningKind; planningVersion: FactoryHermesWrapperNoToolModePlanningVersion; plannedAt: string; plannedBy: string; toolId: 'hermes_agent'; revisionPlanningRef?: string; blockedAdapterApprovalRef?: string; wrapperSourceInspectionMap: FactoryHermesWrapperSourceInspectionMap; wrapperStrategyCandidates: FactoryHermesWrapperStrategyCandidate[]; wrapperNoToolModeDecisionPack: FactoryHermesWrapperNoToolModeDecisionPack; recommendedWrapperPath: FactoryHermesWrapperNoToolModeRecommendation; wrapperNoToolModePlanningReceipt: FactoryHermesWrapperNoToolModePlanningReceipt; hermesWrapperNoToolModePlanCandidate: FactoryHermesWrapperNoToolModePlanCandidate; checks: FactoryHermesWrapperNoToolModePlanningCheck[]; blockers: FactoryHermesWrapperNoToolModePlanningBlocker[]; warnings: FactoryHermesWrapperNoToolModePlanningWarning[]; status: FactoryHermesWrapperNoToolModePlanningStatus; decision: FactoryHermesWrapperNoToolModePlanningDecision; wrapperPlanningStatus: FactoryHermesWrapperNoToolModePlanningState; canProceedToHermesWrapperNoToolModeApproval: boolean; canProceedToKeepHermesResearchBlockedDecision: boolean; canProceedToResearchRuntimeAdapterApprovalRetry: false; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false; canExecuteHermesNow: false; canPassPromptNow: false; canUseNetworkNow: false; canUseCredentialsNow: false; canReadEnvSecretsNow: false; canCallModelsNow: false; canEnableToolsetsNow: false; canMutateFilesystemNow: false; canUseFindings: false; recommendedNextStep: string }
export interface FactoryHermesWrapperNoToolModePlanningValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesWrapperNoToolModePlanningSummary { planningId: string; status: FactoryHermesWrapperNoToolModePlanningStatus; decision: FactoryHermesWrapperNoToolModePlanningDecision; wrapperPlanningStatus: FactoryHermesWrapperNoToolModePlanningState; recommendedWrapperPath: string; canProceedToHermesWrapperNoToolModeApproval: boolean; canRunResearchNow: false; nextStep: string }
