import { FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_PLANNING_KIND, FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_PLANNING_VERSION, WRAPPER_NO_TOOL_MODE_NOT_AUTHORIZED_ACTIONS, WRAPPER_NO_TOOL_MODE_PLANNING_NEXT_STEP } from './hermes-wrapper-no-tool-mode-planning.defaults.ts'
import type { FactoryHermesWrapperNoToolModePlanningInput, FactoryHermesWrapperNoToolModePlanningResult } from './hermes-wrapper-no-tool-mode-planning.types.ts'
function validRevision(r: any) { return r?.status === 'runtime_selection_revision_plan_created' && r?.decision === 'hermes_runtime_selection_revision_plan_created_toolset_mode_blocked' && r?.revisionStatus === 'manual_revision_required' && r?.hermesRuntimeSelectionRevisionPlanCandidate?.directHermesRuntimeAdapterBlocked === true && r?.hermesRuntimeSelectionRevisionPlanCandidate?.wrapperPlanningRecommended === true && r?.canProceedToHermesWrapperNoToolModePlanning === true && r?.canRunResearchNow === false }
function validToolsetApproval(r: any) { return r?.status === 'toolset_disable_verification_approval_blocked' && r?.decision === 'hermes_toolset_disable_verification_approval_blocked_no_safe_probe_shape' && r?.approvalStatus === 'blocked' }
function sourceMap(source: any) { return { sourceFilesInspected: source?.sourceFilesInspected || ['hermes_cli/main.py', 'hermes_cli/oneshot.py', 'hermes_cli/tools_config.py', 'hermes_cli/config.py', 'hermes_cli/runtime_provider.py', 'hermes_cli/auth.py', 'toolsets.py', 'run_agent.py', 'README.md', 'pyproject.toml'], entryPoints: { cliMain: 'hermes_cli.main:main', oneshot: 'hermes_cli.oneshot.run_oneshot', runAgent: '_run_agent', aiAgent: 'run_agent.AIAgent', providerModelResolution: 'hermes_cli.oneshot._run_agent resolves model/provider before AIAgent' }, toolLoading: { runOneshotAcceptsToolsetsArgument: source?.runOneshotAcceptsToolsetsArgument !== false, explicitToolsetValidationExists: source?.explicitToolsetValidationExists !== false, emptyInternalToolsetsSupport: 'not_proven', configDefaultsRisk: true, aiAgentEmptyToolsSupport: 'unknown' }, wrapperOpportunities: { internalOneshotEmptyToolsets: 'candidate_needs_approval_and_source_proof', tempConfigNoToolsets: 'candidate_needs_approval_and_temp_config_boundary', emptyToolRegistry: 'candidate_needs_design_review', processWrapperOnly: 'insufficient_by_itself' }, wrapperBlockers: ['direct CLI no_toolsets_text_only is invalid', 'no_mcp is not full no-tools', 'omitted --toolsets may use config/defaults', 'monkeypatch/source mutation forbidden initially'] } }
function strategies() { return [
  { strategyId: 'wrapper_internal_oneshot_empty_toolsets', description: 'wrapper propio llama internamente a run_oneshot o equivalente con toolsets vacios.', status: 'candidate_if_source_supports_empty_internal_toolsets', risk: 'medium', requiresSourceProof: true, modifiesHermesSource: false, executesNow: false as const },
  { strategyId: 'wrapper_temp_config_no_toolsets', description: 'wrapper crea config temporal controlada con toolsets vacios/no MCP/defaults desactivados, si Hermes lo soporta.', status: 'candidate_if_config_supports_empty_toolsets', risk: 'medium', requiresApprovedTempConfigPath: true, modifiesHermesSource: false, executesNow: false as const },
  { strategyId: 'wrapper_empty_tool_registry', description: 'wrapper controla registry/tools antes de AIAgent.', status: 'candidate_if_AIAgent_accepts_empty_tools', risk: 'medium_high', requiresSourceProof: true, modifiesHermesSource: false, executesNow: false as const },
  { strategyId: 'wrapper_monkeypatch_tool_loading', description: 'monkeypatch de carga de tools.', status: 'forbidden_initially', risk: 'high', modifiesHermesSource: false, executesNow: false as const, reason: 'fragile, unsafe, hard to govern.' },
  { strategyId: 'wrapper_modify_hermes_source', description: 'modificar source Hermes para no-tools.', status: 'forbidden_initially', risk: 'high', modifiesHermesSource: true, executesNow: false as const, reason: 'mutates third-party source, breaks audited source boundary.' },
  { strategyId: 'wrapper_known_minimal_safe_toolset', description: 'usar toolset real minimo conocido.', status: 'not_recommended', risk: 'high', modifiesHermesSource: false, executesNow: false as const, reason: 'still enables real tools; not equivalent to no-tool mode.' },
  { strategyId: 'keep_hermes_research_blocked', description: 'mantener Hermes research bloqueado.', status: 'safe_available_fallback', risk: 'low', modifiesHermesSource: false, executesNow: false as const, reason: 'lowest risk if no wrapper strategy is safe.' },
] }
function pack(id: string) { return { packId: `${id}:decision-pack`, pendingDecisions: [
  { decisionId: 'approve_wrapper_planning', label: 'Aprobar planificacion de wrapper no-tools si hay estrategia segura.', status: 'pending_human_decision' as const, risk: 'medium', impact: 'Allows wrapper approval review only.', recommended: true, blockedUntilChosen: true },
  { decisionId: 'keep_hermes_research_blocked', label: 'Mantener Hermes research bloqueado si no hay estrategia segura.', status: 'pending_human_decision' as const, risk: 'low', impact: 'No adapter path proceeds.', recommended: false, blockedUntilChosen: true },
  { decisionId: 'deeper_source_review', label: 'Autorizar source review mas profundo.', status: 'pending_human_decision' as const, risk: 'low', impact: 'More evidence before design.', recommended: false, blockedUntilChosen: true },
  { decisionId: 'future_controlled_source_modification_design', label: 'Autorizar diseno futuro con modificacion controlada de Hermes source.', status: 'pending_human_decision' as const, risk: 'high', impact: 'Would break current audited source boundary.', recommended: false, blockedUntilChosen: true },
  { decisionId: 'change_research_tool', label: 'Cambiar herramienta de research.', status: 'pending_human_decision' as const, risk: 'medium', impact: 'Changes strategy away from Hermes.', recommended: false, blockedUntilChosen: true },
] } }
export function evaluateFactoryHermesWrapperNoToolModePlanning(input: FactoryHermesWrapperNoToolModePlanningInput): FactoryHermesWrapperNoToolModePlanningResult {
  const id = `hermes-wrapper-no-tool-mode-planning:75b300f:${input.plannedAt}`; const ok = validRevision(input.runtimeSelectionRevisionPlanningResult) && validToolsetApproval(input.toolsetDisableVerificationApprovalResult)
  const map = sourceMap(input.sourceInspection); const wrapperStrategyCandidates = strategies(); const wrapperNoToolModeDecisionPack = pack(id)
  const recommendedWrapperPath = ok ? { chosenStrategyId: 'wrapper_temp_config_no_toolsets', pathId: 'plan_wrapper_enforced_no_tool_mode', reason: 'A governed wrapper design can be planned around temp config/internal boundaries without implementing or executing it now.', requiredNextGate: 'Factory Hermes Wrapper No-Tool Mode Approval Gate v1', executionAllowedNow: false as const } : { chosenStrategyId: 'keep_hermes_research_blocked', pathId: 'keep_hermes_research_blocked', reason: 'Required blocked revision inputs were not valid.', requiredNextGate: 'Factory Hermes Keep Hermes Research Blocked Decision Gate v1', executionAllowedNow: false as const }
  const status = ok ? 'wrapper_no_tool_mode_plan_created' : 'wrapper_no_tool_mode_plan_blocked'; const decision = ok ? 'hermes_wrapper_no_tool_mode_plan_created_for_approval' : 'hermes_wrapper_no_tool_mode_plan_blocked_no_safe_wrapper_strategy'; const wrapperPlanningStatus = ok ? 'plan_candidate_created' : 'blocked'
  const candidate = { planCandidateId: `${id}:candidate`, toolId: 'hermes_agent' as const, purpose: 'enforce no-tool/text-only Hermes research mode without relying on invalid CLI toolset label', wrapperSourceInspectionMap: map, wrapperStrategyCandidates, recommendedWrapperPath, directHermesRuntimeAdapterBlocked: true as const, sourceMutationAllowedNow: false as const, wrapperImplementationAllowedNow: false as const, wrapperExecutionAllowedNow: false as const, runtimeAdapterAllowedNow: false as const, researchExecutionAllowedNow: false as const, canProceedToHermesWrapperNoToolModeApproval: ok, canProceedToResearchRuntimeAdapterApprovalRetry: false as const, canProceedToResearchRuntimeAdapter: false as const, canRunResearchNow: false as const }
  return { planningId: id, planningKind: FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_PLANNING_KIND, planningVersion: FACTORY_HERMES_WRAPPER_NO_TOOL_MODE_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', revisionPlanningRef: input.runtimeSelectionRevisionPlanningResult?.planningId, blockedAdapterApprovalRef: input.researchRuntimeAdapterApprovalResult?.adapterApprovalId, wrapperSourceInspectionMap: map, wrapperStrategyCandidates, wrapperNoToolModeDecisionPack, recommendedWrapperPath, wrapperNoToolModePlanningReceipt: { receiptId: `${id}:receipt`, planningId: id, toolId: 'hermes_agent', plannedBy: input.plannedBy, plannedAt: input.plannedAt, decision, scope: 'hermes_wrapper_no_tool_mode_planning_only', approvedNextGate: ok ? 'Factory Hermes Wrapper No-Tool Mode Approval Gate v1' : 'Factory Hermes Keep Hermes Research Blocked Decision Gate v1', limitations: ['Planning only; wrapper implementation, source mutation, adapter approval, and execution are not authorized.'], notAuthorizedActions: WRAPPER_NO_TOOL_MODE_NOT_AUTHORIZED_ACTIONS }, hermesWrapperNoToolModePlanCandidate: candidate, checks: [], blockers: ok ? [] : [{ blockerId: 'invalid_wrapper_planning_inputs', message: 'Runtime selection revision or toolset approval input is invalid.' }], warnings: [{ warningId: 'wrapper_strategy_requires_future_approval', message: 'Wrapper planning does not prove runtime safety or implement wrapper code.' }], status, decision, wrapperPlanningStatus, canProceedToHermesWrapperNoToolModeApproval: ok, canProceedToKeepHermesResearchBlockedDecision: !ok, canProceedToResearchRuntimeAdapterApprovalRetry: false, canProceedToResearchRuntimeAdapter: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canMutateFilesystemNow: false, canUseFindings: false, recommendedNextStep: ok ? WRAPPER_NO_TOOL_MODE_PLANNING_NEXT_STEP : 'Proceed to Factory Hermes Keep Hermes Research Blocked Decision Gate v1.' }
}
