export type FactoryHermesResearchRuntimeAdapterVersion = '1.0'
export type FactoryHermesResearchRuntimeAdapterKind = 'factory-hermes-research-runtime-adapter'
export type FactoryHermesResearchRuntimeAdapterMode = 'help_probe_only'
export type FactoryHermesResearchRuntimeAdapterStatus = 'completed' | 'blocked' | 'failed' | 'timed_out'
export type FactoryHermesResearchRuntimeAdapterDecision = 'hermes_research_runtime_help_probe_completed' | 'blocked_missing_approval_envelope' | 'blocked_boundary_not_satisfied' | 'blocked_executable_missing' | 'blocked_mode_not_allowed' | 'failed_hermes_help_probe' | 'timed_out_hermes_help_probe' | 'killed_hermes_help_probe' | 'request_adapter_repair'
export interface FactoryHermesResearchRuntimeAdapterInput { executedAt: string; executedBy: string; approvalResult?: unknown; boundaryResult?: unknown; mode?: FactoryHermesResearchRuntimeAdapterMode; policy?: Partial<FactoryHermesResearchRuntimeAdapterPolicy>; executionNotes?: string }
export interface FactoryHermesResearchRuntimeAdapterPolicy { requireApprovalEnvelope: boolean; requireBoundaryContract: boolean; requireSelectedInterface: boolean; requireModeHelpProbeOnly: boolean; requireExecutableUnderPythonEnv: boolean; requireCwdSourceRoot: boolean; requireShellFalse: boolean; requireTimeout: boolean; requireKillSwitch: boolean; requireProcessTreeKillBestEffort: boolean; requireSanitizedLogs: boolean; requireBoundedOutputRoots: boolean; requireResultIngestionNext: boolean; forbidInteractiveNoArgs: boolean; forbidResearchPromptInV1: boolean; forbidNetwork: boolean; forbidCredentials: boolean; forbidModelCalls: boolean; forbidUvExecution: boolean; forbidPipExecution: boolean; forbidPythonDirectExecution: boolean; forbidSetupPyExecution: boolean; forbidHermesScripts: boolean; forbidProjectMutation: boolean; forbidDeploy: boolean }
export interface FactoryHermesResearchRuntimeCommandResult { commandKind: 'hermes_help_probe'; executableRef: string; args: ['--help']; cwdRef: string; shell: false; timeoutMs: number; stdinStatus: 'closed'; stdoutPreview: string; stderrPreview: string; exitCode: number | null; timedOut: boolean; killed: boolean; started: boolean; completed: boolean }
export interface FactoryHermesResearchRuntimeAdapterResult { adapterRunId: string; adapterKind: FactoryHermesResearchRuntimeAdapterKind; adapterVersion: FactoryHermesResearchRuntimeAdapterVersion; executedAt: string; executedBy: string; toolId: 'hermes_agent'; selectedCandidateId: string; commandName: 'hermes' | string; pythonEntrypoint: 'hermes_cli.main:main' | string; executableRef: string; cwdRef: string; outputRootRef: string; tempRootRef: string; mode: FactoryHermesResearchRuntimeAdapterMode; commandResults: FactoryHermesResearchRuntimeCommandResult[]; stdoutPreview: string; stderrPreview: string; exitCode: number | null; timedOut: boolean; killed: boolean; status: FactoryHermesResearchRuntimeAdapterStatus; decision: FactoryHermesResearchRuntimeAdapterDecision; blockers: string[]; warnings: string[]; networkStatus: 'not_allowed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; filesystemMutationStatus: 'bounded_artifacts_only'; hermesExecutionStatus: 'help_probe_only_completed' | 'help_probe_only_failed' | 'help_probe_only_timed_out' | 'not_executed'; scriptsStatus: 'not_executed'; pipStatus: 'not_executed'; pythonDirectStatus: 'not_executed'; setupPyStatus: 'not_executed'; uvStatus: 'not_executed'; canProceedToResultIngestion: boolean; canTreatAsResearchResult: false; canUseFindings: false; canCallModels: false; canUseCredentials: false; canUseNetwork: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesResearchRuntimeAdapterValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesResearchRuntimeAdapterSummary { adapterRunId: string; mode: FactoryHermesResearchRuntimeAdapterMode; commandName: string; exitCode: number | null; timedOut: boolean; status: FactoryHermesResearchRuntimeAdapterStatus; decision: FactoryHermesResearchRuntimeAdapterDecision; hermesExecutionStatus: FactoryHermesResearchRuntimeAdapterResult['hermesExecutionStatus']; canProceedToResultIngestion: boolean; canTreatAsResearchResult: false; networkStatus: 'not_allowed'; credentialsStatus: 'not_allowed'; modelCallStatus: 'not_allowed'; nextStep: string }
