const { readFile } = require('node:fs/promises')
const { assertFactoryMemoryReadRuntimeRootAllowed, resolveFactoryMemoryReadRuntimeCandidatePaths } = require('./memory-read-runtime.path.cjs')
const KIND = 'factory-memory-read-runtime'; const VERSION = '1.0'; const missing = (error) => Boolean(error && error.code === 'ENOENT'); const sanitize = (error) => String(error && error.message || 'Unknown memory read failure.').replace(/[A-Za-z]:[\\/][^\s]+/gu, '[controlled-path]').replace(/(?:api[_-]?key|secret|password|token)\s*[:=]\s*[^\s]+/giu, '[redacted]').slice(0, 300)
const sensitiveKeys = new Set(['apikey', 'password', 'accesstoken', 'privatekey', 'secret', 'secrets', 'credentials', 'runtimecredentials'])
function hasSensitive(value) { if (Array.isArray(value)) return value.some(hasSensitive); if (!value || typeof value !== 'object') return false; return Object.entries(value).some(([key, item]) => { const normalized = key.replace(/[_-]/gu, '').toLowerCase(); if (sensitiveKeys.has(normalized)) return item !== undefined && item !== null && item !== false && item !== ''; if (normalized === 'rawevidence') return item !== undefined && item !== null && item !== false && item !== '' && (!Array.isArray(item) || item.length > 0); return hasSensitive(item) }) }
const unsafeFlags = (value) => value.notExecutable !== true || value.embeddingsCreated !== false || value.codexTaskCreated !== false || value.globalPromotionAllowed !== false || value.projectCreated !== false || value.repositoryCreated !== false || value.deployed !== false
function safeRecord(record) { const allowed = ['memoryRecordId', 'memoryRecordKind', 'memoryRecordVersion', 'namespace', 'projectNamespace', 'title', 'summary', 'canonicalFacts', 'references', 'lineage', 'tags', 'retentionPolicy', 'promotionPolicy', 'stalePolicy']; return Object.fromEntries(allowed.filter((key) => record[key] !== undefined).map((key) => [key, structuredClone(record[key])])) }
function safeMetadata(meta) { const allowed = ['metadataKind', 'metadataVersion', 'memoryRecordId', 'memoryRecordKind', 'namespace', 'projectNamespace', 'fingerprint', 'idempotencyKey', 'logicalTarget', 'writtenAt', 'writtenBy', 'notExecutable', 'embeddingsCreated', 'codexTaskCreated', 'globalPromotionAllowed', 'projectCreated', 'repositoryCreated', 'deployed']; return Object.fromEntries(allowed.map((key) => [key, meta[key]])) }
async function executeFactoryMemoryReadRuntime(input) { const value = structuredClone(input); const admission = value && value.memoryReadAdmissionResult; const runtimeReadId = `memory-read-runtime:${admission && admission.admissionId || 'invalid'}:${String(value && value.executedAt || '').replace(/[^0-9]/gu, '') || 'unknown'}`; const readItems = []; const blockers = []; const warnings = []; const checks = []
  const finish = (forced) => { const recordsRead = readItems.filter((item) => item.readStatus === 'read').length; const recordsMissing = readItems.filter((item) => item.readStatus === 'missing').length; const recordsBlocked = readItems.length - recordsRead - recordsMissing; const status = forced || (recordsRead && (recordsBlocked || recordsMissing) ? 'partial' : recordsRead ? 'success' : 'blocked'); return { runtimeReadId, runtimeReadKind: KIND, runtimeReadVersion: VERSION, executedAt: value && value.executedAt || '', executedBy: value && value.executedBy || '', sourceReadAdmissionId: admission && admission.admissionId || '', readPurpose: admission && admission.readPurpose || '', status, readItems, recordsRead, recordsBlocked, recordsMissing, checks, blockers, warnings, canAssembleContext: false, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false, recommendedNextStep: recordsRead ? 'Proceed to Memory Context Assembly Gate after review; Codex remains disabled until a dedicated Codex Task Contract Gate approves a separate handoff.' : 'Repair memory read blockers and repeat governed admission before context assembly.' } }
  try { assertFactoryMemoryReadRuntimeRootAllowed(value.storageRoot) } catch (error) { blockers.push({ blockerId: 'unsafe-storage-root', message: sanitize(error) }); return finish('blocked') }
  if (!admission || admission.decision !== 'approve_memory_read_candidates' || admission.status !== 'read_candidates_ready' || !admission.candidates?.length || !value.executedAt || !value.executedBy) { blockers.push({ blockerId: 'invalid-read-admission', message: 'Read admission must be approved and contain candidates.' }); return finish('blocked') }
  const candidates = value.maxRecords === undefined ? admission.candidates : admission.candidates.slice(0, Math.max(0, value.maxRecords)); for (const candidate of candidates) { const readItemId = `memory-read-item:${candidate.readCandidateId}`; const itemBlockers = []; const itemWarnings = []; const readbackChecks = []; const base = { readItemId, sourceReadCandidateId: candidate.readCandidateId, memoryRecordId: candidate.memoryRecordId, memoryRecordKind: candidate.memoryRecordKind, memoryRecordVersion: candidate.memoryRecordVersion, namespace: candidate.namespace, projectNamespace: candidate.projectNamespace, logicalTarget: candidate.logicalTarget, metadataLogicalTarget: candidate.metadataLogicalTarget, fingerprint: candidate.fingerprint, idempotencyKey: candidate.idempotencyKey, readbackChecks, warnings: itemWarnings, blockers: itemBlockers, containsFullMemoryRecord: false, containsCanonicalPayload: false, containsRawEvidence: false, containsSecrets: false, canAssembleContext: false, canCreateCodexTask: false, canExecuteCodex: false, canCreateEmbeddings: false, canCreateProject: false, canCreateRepository: false, canDeploy: false }
    let paths; try { if (candidate.blockers?.length || candidate.readScope !== 'project' || candidate.containsSecrets || candidate.containsRawEvidence || candidate.canCreateCodexTask || candidate.canExecuteCodex || candidate.canCreateEmbeddings || candidate.canCreateProject || candidate.canCreateRepository || candidate.canDeploy) throw new Error('Candidate enables unsafe read capabilities.'); paths = resolveFactoryMemoryReadRuntimeCandidatePaths({ storageRoot: value.storageRoot, candidate }); let recordText; let metadataText; try { recordText = await readFile(paths.targetAbsolutePath, 'utf8') } catch (error) { if (missing(error)) { itemBlockers.push({ blockerId: 'missing-record', readItemId, message: 'Memory record is missing.' }); readItems.push({ ...base, readStatus: 'missing', readResult: { exists: false, parsed: false, verified: false } }); continue } throw error } try { metadataText = await readFile(paths.metadataAbsolutePath, 'utf8') } catch (error) { if (missing(error)) { itemBlockers.push({ blockerId: 'missing-metadata', readItemId, message: 'Memory metadata is missing.' }); readItems.push({ ...base, readStatus: 'missing', readResult: { exists: true, parsed: false, verified: false } }); continue } throw error }
      const record = JSON.parse(recordText); const metadata = JSON.parse(metadataText); const badIdentity = record.memoryRecordId !== candidate.memoryRecordId || record.memoryRecordKind !== candidate.memoryRecordKind || record.namespace !== candidate.namespace || record.projectNamespace !== candidate.projectNamespace || metadata.memoryRecordId !== candidate.memoryRecordId || metadata.namespace !== candidate.namespace || metadata.projectNamespace !== candidate.projectNamespace; const badFingerprint = metadata.fingerprint !== candidate.fingerprint; const badIdempotency = metadata.idempotencyKey !== candidate.idempotencyKey; const badFlags = unsafeFlags(metadata); const sensitive = hasSensitive(record) || record.containsSecrets === true || record.containsRawEvidence === true
      readbackChecks.push({ checkId: `${readItemId}:identity`, passed: !badIdentity, message: 'Record and metadata identity must match the candidate.' }, { checkId: `${readItemId}:fingerprint`, passed: !badFingerprint, message: 'Metadata fingerprint must match.' }, { checkId: `${readItemId}:idempotency`, passed: !badIdempotency, message: 'Metadata idempotency key must match.' }, { checkId: `${readItemId}:flags`, passed: !badFlags && !sensitive, message: 'Metadata and record flags must remain safe.' })
      if (badIdentity || badFingerprint || badIdempotency || badFlags || sensitive) { itemBlockers.push({ blockerId: 'readback-mismatch', readItemId, message: badFingerprint ? 'Fingerprint mismatch.' : badIdempotency ? 'Idempotency mismatch.' : badFlags ? 'Unsafe metadata flags.' : sensitive ? 'Sensitive or raw evidence content detected.' : 'Record identity mismatch.' }); readItems.push({ ...base, readStatus: 'blocked', readResult: { exists: true, parsed: true, verified: false } }); continue }
      readItems.push({ ...base, readStatus: 'read', safeMemoryRecord: safeRecord(record), metadataReadback: safeMetadata(metadata), readResult: { exists: true, parsed: true, verified: true } })
    } catch (error) { itemBlockers.push({ blockerId: 'memory-read-failed', readItemId, message: sanitize(error) }); readItems.push({ ...base, readStatus: 'blocked', readResult: { exists: false, parsed: false, verified: false, sanitizedError: sanitize(error) } }) }
  }
  for (const item of readItems) { blockers.push(...item.blockers); warnings.push(...item.warnings) } checks.push({ checkId: 'candidates-processed', passed: readItems.length === candidates.length, message: 'All selected candidates were processed.' }); return finish()
}
module.exports = { executeFactoryMemoryReadRuntime }
