const fs = require('node:fs/promises');
const path = require('node:path');
const { resolveFactoryHermesResearchRuntimeInterfaceSelectionPaths, assertInterfaceSelectionPathContained } = require('./hermes-research-runtime-interface-selection.path.cjs');

const KIND = 'factory-hermes-research-runtime-interface-selection';
const VERSION = '1.0';
const NEXT = 'Proceed to Factory Hermes Research Runtime Boundary Contract v1; selected interface remains non-executable.';
const notAuthorizedActions = ['execute_hermes_now', 'run_hermes_scripts_now', 'execute_selected_interface_now', 'execute_python_now', 'execute_uv_now', 'execute_pip_now', 'execute_setup_py_now', 'call_models_now', 'access_credentials_now', 'use_network_now', 'scrape_now', 'create_runtime_now', 'deploy_now', 'mutate_project_files_now'];
async function readJson(file) { return JSON.parse(await fs.readFile(file, 'utf8')); }
function selectedInterface() { return { candidateId: 'pyproject-console-script-1', interfaceType: 'package_entrypoint', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', sourceDeclarationRef: 'pyproject.toml [project.scripts]', futureExecutableCandidateWindows: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/Scripts/hermes.exe', futureWorkingDirectory: '.codex-temp/external-tools/hermes-agent/install/75b300f/source', confidence: 'high', selectionReason: 'Unique real package entrypoint declared in pyproject and documented as the primary CLI.', limitations: ['CLI may be interactive.', 'Boundary must define stdin/stdout/timeouts.', 'No network, credentials or model calls by default.'] }; }
function evaluate(input) {
  const p = input.planningResult;
  const id = `hermes-research-runtime-interface-selection:75b300f:${input.selectedAt}`;
  const base = { interfaceSelectionId: id, interfaceSelectionKind: KIND, interfaceSelectionVersion: VERSION, selectedAt: input.selectedAt, selectedBy: input.selectedBy, toolId: 'hermes_agent', auditedHead: p?.auditedHead || '', selectedCandidateId: input.selectedCandidateId || '', checks: [], blockers: [], warnings: [], canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: NEXT };
  if (!p) return { ...base, status: 'blocked', decision: 'blocked_missing_planning_result', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_missing_planning_result', message: 'Planning result is required.' }] };
  if (!['manual_selection_required', 'plan_candidate_created'].includes(p.status) || (p.status === 'manual_selection_required' && p.decision !== 'hermes_research_runtime_plan_requires_manual_interface_selection') || p.canExecuteHermes !== false || p.canUseNetwork !== false || p.canUseCredentials !== false || p.canCallModels !== false) return { ...base, auditedHead: p.auditedHead, status: 'blocked', decision: 'blocked_planning_not_manual_selection_required', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_planning_not_manual_selection_required', message: 'Planning result is not eligible.' }] };
  const candidate = (p.interfaceCandidates || []).find((c) => c.candidateId === input.selectedCandidateId);
  if (!input.selectedCandidateId || !candidate) return { ...base, auditedHead: p.auditedHead, status: 'blocked', decision: 'blocked_selected_candidate_not_found', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_selected_candidate_not_found', message: 'Selected candidate is missing.' }] };
  if (input.selectedCandidateId !== 'pyproject-console-script-1') return { ...base, auditedHead: p.auditedHead, status: 'blocked', decision: 'blocked_selected_candidate_not_recommended', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_selected_candidate_not_recommended', message: 'Selected candidate is not recommended.' }] };
  if (!input.humanApprovalRef) return { ...base, auditedHead: p.auditedHead, status: 'human_review_required', decision: 'blocked_missing_human_approval', canProceedToResearchRuntimeBoundary: false, blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] };
  const si = selectedInterface();
  const receipt = { receiptId: `${id}:receipt`, interfaceSelectionId: id, toolId: 'hermes_agent', auditedHead: p.auditedHead, selectedBy: input.selectedBy, selectedAt: input.selectedAt, humanApprovalRef: input.humanApprovalRef, selectedCandidateId: input.selectedCandidateId, selectedInterfaceType: si.interfaceType, decision: 'hermes_research_runtime_interface_selected_for_boundary_planning', scope: 'hermes_research_runtime_interface_selection_only', approvedNextGate: 'Factory Hermes Research Runtime Boundary Contract v1', limitations: si.limitations, notAuthorizedActions };
  const envelope = { envelopeId: `${id}:envelope`, interfaceSelectionId: id, toolId: 'hermes_agent', auditedHead: p.auditedHead, selectedCandidateId: input.selectedCandidateId, selectedInterface: si, sourceRootRef: p.sourceRootRef, installRootRef: p.installRootRef, pythonEnvRootRef: p.pythonEnvRootRef, planningResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/research-runtime-planning-result.json', dossierRef: '.codex-temp/hermes-research-runtime-interface-selection-dossier-v1/INTERFACE_SELECTION_DOSSIER.md', approvedNextGate: 'Factory Hermes Research Runtime Boundary Contract v1', interfaceReadinessStatus: 'selected_for_boundary_only', hermesExecutionStatus: 'not_allowed', scriptsStatus: 'not_allowed', networkStatus: 'not_allowed', credentialsStatus: 'not_allowed', modelCallStatus: 'not_allowed', projectMutationStatus: 'not_allowed', deployStatus: 'not_allowed', canProceedToResearchRuntimeBoundary: true, canExecuteHermes: false, canRunHermesScripts: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, recommendedNextStep: NEXT };
  return { ...base, auditedHead: p.auditedHead, status: 'selected', decision: 'hermes_research_runtime_interface_selected_for_boundary_planning', selectedInterface: si, interfaceSelectionReceipt: receipt, selectedHermesResearchRuntimeInterfaceEnvelope: envelope, canProceedToResearchRuntimeBoundary: true };
}
async function executeFactoryHermesResearchRuntimeInterfaceSelection(input = {}) {
  const paths = resolveFactoryHermesResearchRuntimeInterfaceSelectionPaths();
  assertInterfaceSelectionPathContained(paths.installRoot, path.join(paths.root, '.codex-temp'));
  assertInterfaceSelectionPathContained(paths.selectionResult, paths.installRoot);
  const planningResult = await readJson(paths.planningResult);
  await readJson(paths.jefeReviewResult);
  const dossier = await fs.readFile(paths.dossier, 'utf8');
  const result = evaluate({ selectedAt: input.selectedAt || '2026-07-21T17:00:00.000Z', selectedBy: input.selectedBy || 'factory-hermes-research-runtime-interface-selection-smoke', selectedCandidateId: input.selectedCandidateId || 'pyproject-console-script-1', humanApprovalRef: input.humanApprovalRef || 'human-review/hermes-research-runtime-interface-selection-v1', planningResult, dossierSummary: dossier.includes('hermes = "hermes_cli.main:main"') ? 'recommended pyproject-console-script-1 with hermes_cli.main:main evidence' : 'dossier evidence missing' });
  await fs.writeFile(paths.selectionResult, JSON.stringify(result, null, 2));
  return result;
}
module.exports = { executeFactoryHermesResearchRuntimeInterfaceSelection, evaluateFactoryHermesResearchRuntimeInterfaceSelection: evaluate };
