const fs = require('node:fs/promises');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { assertWrapperNoToolModeImplementationPlanningPathContained, resolveFactoryHermesWrapperNoToolModeImplementationPlanningPaths } = require('./hermes-wrapper-no-tool-mode-implementation-planning.path.cjs');
async function readJson(file) { const text = await fs.readFile(file, 'utf8'); if (!text.trim()) throw new Error(`json_file_empty: ${file}`); return JSON.parse(text); }
async function readText(file) { try { return await fs.readFile(file, 'utf8'); } catch { return ''; } }
function inspect(texts) { const joined = Object.values(texts).join('\n'); return { sourceFilesInspected: Object.keys(texts), configSchemaKnown: joined.includes('validate_config_structure') || joined.includes('config.yaml'), configPathSelectionMethodKnown: joined.includes('get_config_path') || joined.includes('HERMES_CONFIG'), emptyToolsetsInConfigSupported: joined.includes('toolsets') && joined.includes('[]') ? true : 'unknown', noMcpIsOnlyMcpSentinel: joined.includes('no_mcp'), hiddenDefaultsRisk: joined.includes('platform_toolsets') || joined.includes('_get_platform_tools') }; }
async function executeFactoryHermesWrapperNoToolModeImplementationPlanning(input = {}) { const paths = resolveFactoryHermesWrapperNoToolModeImplementationPlanningPaths(); for (const [key, value] of Object.entries(paths)) { if (!['repoRoot','installRoot','sourceRoot'].includes(key) && String(value).includes(`${path.sep}.codex-temp${path.sep}`)) assertWrapperNoToolModeImplementationPlanningPathContained(value, paths.installRoot); } const texts = { 'hermes_cli/main.py': await readText(paths.main), 'hermes_cli/oneshot.py': await readText(paths.oneshot), 'hermes_cli/tools_config.py': await readText(paths.toolsConfig), 'hermes_cli/config.py': await readText(paths.config), 'hermes_cli/runtime_provider.py': await readText(paths.runtimeProvider), 'hermes_cli/auth.py': await readText(paths.auth), 'toolsets.py': await readText(paths.toolsets), 'run_agent.py': await readText(paths.runAgent), 'README.md': await readText(paths.readme), 'pyproject.toml': await readText(paths.pyproject) }; const moduleUrl = pathToFileURL(path.join(paths.repoRoot, 'src', 'factory', 'hermes-wrapper-no-tool-mode-implementation-planning', 'index.ts')).href; const { evaluateFactoryHermesWrapperNoToolModeImplementationPlanning, serializeFactoryHermesWrapperNoToolModeImplementationPlanningResult } = await import(moduleUrl); const result = evaluateFactoryHermesWrapperNoToolModeImplementationPlanning({ plannedAt: input.plannedAt || '2026-07-23T03:00:00.000Z', plannedBy: input.plannedBy || 'factory-hermes-wrapper-no-tool-mode-implementation-planning-smoke', wrapperNoToolModeApprovalResult: input.wrapperNoToolModeApprovalResult || await readJson(paths.approvalResult), wrapperNoToolModePlanningResult: input.wrapperNoToolModePlanningResult || await readJson(paths.wrapperPlanningResult), sourceInspection: input.sourceInspection || inspect(texts), planningNotes: input.planningNotes }); await fs.mkdir(path.dirname(paths.implementationPlanningResult), { recursive: true }); await fs.writeFile(paths.implementationPlanningResult, serializeFactoryHermesWrapperNoToolModeImplementationPlanningResult(result)); return result; }
module.exports = { executeFactoryHermesWrapperNoToolModeImplementationPlanning };
