const fs = require('node:fs');
const path = require('node:path');
const { inspectFactoryHermesEntrypointMaterializationVerificationState } = require('./hermes-entrypoint-materialization-verification.inspect.cjs');

const KIND = 'factory-hermes-entrypoint-materialization-verification';
const VERSION = '1.0';
const NEXT = 'Proceed to Factory Hermes Research Runtime Adapter Retry Gate v1 under its future approval envelope.';
const NOT_AUTH = ['execute_hermes_now', 'execute_entrypoint_now', 'retry_research_adapter_now', 'execute_uv_now', 'execute_uv_sync_now', 'execute_python_now', 'execute_pip_now', 'execute_setup_py_now', 'use_network_now', 'call_models_now', 'access_credentials_now', 'mutate_project_files_now', 'deploy_now'];

function evaluate(input) {
  const r = input.runtimeRetryResult;
  const exe = input.executableInspection || {};
  const src = input.sourceInspection || {};
  const base = { verificationId: `hermes-entrypoint-materialization-verification:75b300f:${input.verifiedAt}`, verificationKind: KIND, verificationVersion: VERSION, verifiedAt: input.verifiedAt, verifiedBy: input.verifiedBy, toolId: 'hermes_agent', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', expectedExecutableRef: r?.expectedExecutableRef || '', executableStatus: 'unknown', executableSizeBytes: null, executableSha256: '', materializationStatus: r?.materializationStatus || '', sourceMutationStatus: 'unknown', knownWarnings: [], runtimeRetryDecision: r?.decision || '', checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_runtime_retry_result', canProceedToResearchRuntimeAdapterRetry: false, canRetryResearchAdapterNow: false, canExecuteHermesNow: false, canTreatAsResearchResult: false, canUseFindings: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: NEXT };
  if (!r) return { ...base, blockers: [{ blockerId: 'blocked_missing_runtime_retry_result', message: 'Runtime retry result is required.' }] };
  if (r.status !== 'success' || r.decision !== 'hermes_entrypoint_materialized_after_cache_verified_retry' || r.materializationStatus !== 'materialized' || r.executableStatusAfter !== 'present') return { ...base, decision: 'blocked_runtime_retry_not_success', blockers: [{ blockerId: 'blocked_runtime_retry_not_success', message: 'Runtime retry is not success.' }] };
  if (r.hermesExecutionStatus !== 'not_executed' || r.researchAdapterRetryStatus !== 'not_attempted' || r.pipStatus !== 'not_executed' || r.pythonDirectStatus !== 'not_executed' || r.setupPyDirectStatus !== 'not_executed' || r.networkStatus !== 'not_allowed') return { ...base, decision: 'blocked_boundary_violation_detected', blockers: [{ blockerId: 'blocked_boundary_violation_detected', message: 'Unsafe runtime retry boundary.' }] };
  if (!exe.exists) return { ...base, decision: 'blocked_entrypoint_executable_missing', blockers: [{ blockerId: 'blocked_entrypoint_executable_missing', message: 'hermes.exe missing.' }] };
  if (!exe.contained) return { ...base, decision: 'blocked_entrypoint_path_not_contained', blockers: [{ blockerId: 'blocked_entrypoint_path_not_contained', message: 'hermes.exe path not contained.' }] };
  if (!exe.sizeBytes || exe.sizeBytes <= 0 || !exe.sha256) return { ...base, decision: 'blocked_entrypoint_executable_empty', blockers: [{ blockerId: 'blocked_entrypoint_executable_empty', message: 'hermes.exe empty or hash missing.' }] };
  if (src.keyFileHashesUnchanged !== true || src.unexpectedSourceMutation) return { ...base, decision: 'blocked_unexpected_source_mutation', blockers: [{ blockerId: 'blocked_unexpected_source_mutation', message: 'Source mutation detected.' }] };
  const decision = 'hermes_entrypoint_materialization_verified_for_research_runtime_adapter_retry';
  const warnings = (src.knownWarnings || []).map((warningId) => ({ warningId, message: warningId }));
  const receipt = { receiptId: `${base.verificationId}:receipt`, verificationId: base.verificationId, toolId: 'hermes_agent', verifiedBy: input.verifiedBy, verifiedAt: input.verifiedAt, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', expectedExecutableRef: r.expectedExecutableRef, executableStatus: 'present', executableSha256: exe.sha256, materializationStatus: 'materialized', sourceMutationStatus: src.sourceMutationStatus, decision, scope: 'hermes_entrypoint_materialization_verification_only', approvedNextGate: 'Factory Hermes Research Runtime Adapter Retry Gate v1', limitations: ['Verification only.', 'No immediate execution is authorized.'], notAuthorizedActions: NOT_AUTH };
  const record = { recordId: `${base.verificationId}:record`, verificationId: base.verificationId, toolId: 'hermes_agent', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', runtimeRetryResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/entrypoint-materialization-runtime-retry-result.json', runtimeRetryManifestRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/entrypoint-materialization-runtime-retry-manifest.json', expectedExecutableRef: r.expectedExecutableRef, executableVerification: { exists: true, contained: true, sizeBytes: exe.sizeBytes, sha256: exe.sha256, extension: 'exe' }, materializationVerification: { materializationStatus: 'materialized', runtimeRetryDecision: r.decision, uvOffline: true, cacheVerified: true }, safetyVerification: { noHermesExecution: true, noSelectedInterfaceExecution: true, noResearchAdapterRetry: true, noPip: true, noPythonDirect: true, noSetupPyDirect: true, noUvRun: true, noUvPip: true, noUvVenv: true, noNetwork: true, noCredentials: true, noModelCalls: true }, sourceVerification: { keyFileHashesUnchanged: true, knownWarnings: src.knownWarnings || [], unexpectedSourceMutation: false }, canProceedToResearchRuntimeAdapterRetry: true, canRetryResearchAdapterNow: false, canExecuteHermesNow: false };
  const envelope = { envelopeId: `${base.verificationId}:envelope`, verificationId: base.verificationId, toolId: 'hermes_agent', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', selectedInterface: { interfaceType: 'package_entrypoint', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main' }, executableRef: r.expectedExecutableRef, executableSha256: exe.sha256, sourceRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/source', pythonEnvRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env', retryMethodCandidate: 'research_runtime_adapter_help_probe_retry', approvedNextGate: 'Factory Hermes Research Runtime Adapter Retry Gate v1', retryAllowedNow: false, futureRetryMayExecuteHermesHelpOnly: true, futureRetryCommand: { executableRef: r.expectedExecutableRef, args: ['--help'], shell: false, cwd: '.codex-temp/external-tools/hermes-agent/install/75b300f/source', timeoutMs: 120000 }, futureRetryMustNotUseNetwork: true, futureRetryMustNotUseCredentials: true, futureRetryMustNotCallModels: true, futureRetryMustSanitizeOutput: true, futureRetryMustNotTreatHelpAsResearchFindings: true, requiredFutureGates: ['Factory Hermes Research Runtime Adapter Retry Gate v1', 'Factory Hermes Research Result Ingestion Gate v2', 'Factory Hermes Research JEFE Review Gate v2'] };
  return { ...base, status: warnings.length ? 'warning_verified' : 'verified', decision, expectedExecutableRef: r.expectedExecutableRef, executableStatus: 'present', executableSizeBytes: exe.sizeBytes, executableSha256: exe.sha256, materializationStatus: 'materialized', sourceMutationStatus: src.sourceMutationStatus, knownWarnings: src.knownWarnings || [], warnings, entrypointMaterializationVerificationReceipt: receipt, hermesEntrypointMaterializationVerificationRecord: record, approvedResearchRuntimeAdapterRetryEnvelope: envelope, canProceedToResearchRuntimeAdapterRetry: true };
}

function executeFactoryHermesEntrypointMaterializationVerification(input = {}) {
  const inspected = inspectFactoryHermesEntrypointMaterializationVerificationState(input.root);
  const runInput = { verifiedAt: input.verifiedAt || '2026-07-22T04:10:00.000Z', verifiedBy: input.verifiedBy || 'factory-hermes-entrypoint-materialization-verification-smoke', runtimeRetryResult: inspected.runtimeRetryResult, runtimeRetryManifest: inspected.runtimeRetryManifest, executableInspection: inspected.executableInspection, sourceInspection: inspected.sourceInspection, cacheVerificationResult: inspected.cacheVerificationResult };
  const result = evaluate(runInput);
  fs.writeFileSync(inspected.paths.result, `${JSON.stringify(result, null, 2)}\n`);
  return result;
}

module.exports = { executeFactoryHermesEntrypointMaterializationVerification, evaluateFactoryHermesEntrypointMaterializationVerificationRuntime: evaluate };
