export type Direction = 'editorial' | 'comercial' | 'expresiva'
export type Project = { projectId: string; projectType: string; platform: string; generationProfile: string; visualDirection: Direction | null; visibility?: 'user' | 'internal_fixture'; timestamps: { updatedAt: string | null }; delivery: { status: string }; inputAssets: { totalFiles: number } }
export type Version = { versionId: string; runId?: string; createdAt: string | null; summary: string | null; changeOrigin: { kind: string; reference: string | null } }
export type Event = { eventId: string; sequence: number; type: string; occurredAt: string; versionId?: string; approved?: boolean; changeRequest?: string; sourceVersionId?: string }
export type Snapshot = { projectId: string; projectName: string; state: string; versionCount: number; activeVersionId: string; previewAvailable: boolean; previewMode: string; deliveryAvailable: boolean; delivery: { status: string; deliveredAt: string | null }; approval: { approved: boolean; approvedAt: string | null; observation: string | null }; nextStep: string; blockers: string[]; lastActivity: string | null; generationProfile: string; projectType: string; platform: string; creativeDirection: Direction | null; planning: { objective: string; audience: string; strategy: string; sections: string[]; primaryMessage: string; contentTitle: string; expectedArtifacts: string[] }; materials: { totalFiles: number; references: number; files: Array<{ safeName: string; kind: string; sizeBytes: number }>; colors: string[]; notes: string | null; urls: string[] }; milestones: Record<string, boolean>; capabilities: { createVersion: boolean; approval: boolean; comparison: boolean; restore: boolean; delivery: boolean }; events: Event[] }
export type Draft = { schemaVersion: 1; savedAt: string; step: number; name: string; need: string; projectType: string; platform: string; businessType: string; audience: string; proposition: string; cta: string; colors: string; notes: string; urls: string; direction: Direction | ''; assets: Array<{ safeName: string; kind: string; sizeBytes: number }> }
export type WorkspaceArea = 'summary' | 'build' | 'materials' | 'versions'
export type HumanGateSummary = { state: string; decision?: string; reason?: string | null; reviewer?: string; timestamp?: string; snapshotSha256?: string }
export const HUMAN_STATE_LABELS: Record<string, string> = { pending_review: 'Pendiente de revisión', preview_ready: 'Preview listo', approval_required: 'Requiere aprobación', review_and_approve: 'Revisar y aprobar', rejected: 'Rechazado', approved: 'Aprobado', superseded: 'Reemplazado por una versión nueva', blocked: 'Bloqueado', expired: 'Vencido', reviewed: 'Revisión registrada', viewed: 'Preview visto', not_ready: 'En preparación', delivered_local: 'Entrega local disponible' }
export function humanStateLabel(value: string | null | undefined, fallback = 'Estado no disponible') { return value ? HUMAN_STATE_LABELS[value] || value.replaceAll('_', ' ') : fallback }
export const COLORS_MAX_LENGTH = 500
export const emptyDraft = (): Draft => ({ schemaVersion: 1, savedAt: new Date().toISOString(), step: 1, name: '', need: '', projectType: '', platform: '', businessType: '', audience: '', proposition: '', cta: '', colors: '', notes: '', urls: '', direction: '', assets: [] })
export function validateStep(d: Draft, step: number) { if (step === 1) return d.name.trim() && d.need.trim() ? null : 'Completá el nombre y lo que necesitás.'; if (step === 2) return d.businessType.trim() && d.audience.trim() && d.proposition.trim() ? null : 'Completá negocio, audiencia y propuesta.'; if (step === 3 && d.colors.length > COLORS_MAX_LENGTH) return 'Los colores superan el máximo permitido'; if (step === 4) return d.direction ? null : 'Elegí una dirección visual.'; return null }
export function loadDraft(raw: string | null): Draft | null { try { const draft = JSON.parse(raw || 'null'); return draft?.schemaVersion === 1 && typeof draft.name === 'string' ? { ...emptyDraft(), ...draft, assets: Array.isArray(draft.assets) ? draft.assets : [] } : null } catch { return null } }
const INTERNAL_FIXTURE_ID = /(?:^|[-_])(qa|test|fixture|smoke|factory|pipeline)(?:[-_]|$)/iu
export function isInternalFixtureProject(project: Project) { return project.visibility === 'internal_fixture' || project.generationProfile !== 'commercial_site' || INTERNAL_FIXTURE_ID.test(project.projectId) }
export function chooseActive(projects: Project[], active: string | null) { return visibleProjects(projects, '', 'recent').some((p) => p.projectId === active) ? active : visibleProjects(projects, '', 'recent')[0]?.projectId || null }
export function visibleProjects(projects: Project[], query: string, order: 'recent' | 'name', status = '') { const q = query.trim().toLowerCase(); return projects.filter((p) => !isInternalFixtureProject(p) && (!q || p.projectId.toLowerCase().includes(q) || p.projectType.toLowerCase().includes(q)) && (!status || p.delivery.status === status)).sort((a, b) => order === 'name' ? a.projectId.localeCompare(b.projectId) : String(b.timestamps.updatedAt || '').localeCompare(String(a.timestamps.updatedAt || ''))) }
export function commercialState(snapshot: Snapshot, humanGate?: HumanGateSummary | null) { const gateState = humanGate?.state; if (gateState === 'rejected') return { label: 'Rechazado', nextStep: 'Corregir versión', blocker: 'Requiere correcciones' }; if (gateState === 'approved') return { label: 'Aprobado', nextStep: 'Listo para siguiente etapa', blocker: null }; if (gateState === 'reviewed') return { label: 'Revisión registrada', nextStep: 'Revisar y aprobar', blocker: 'Pendiente de decisión' }; if (gateState === 'pending_review') return { label: 'Pendiente de revisión', nextStep: 'Revisar y aprobar', blocker: 'Requiere aprobación' }; if (gateState === 'superseded') return { label: 'Reemplazado por una versión nueva', nextStep: 'Revisar la versión vigente', blocker: null }; if (gateState === 'blocked') return { label: 'Bloqueado', nextStep: 'Resolver bloqueo', blocker: null }; if (gateState === 'expired') return { label: 'Vencido', nextStep: 'Solicitar una nueva revisión', blocker: null }; return { label: snapshot.deliveryAvailable ? 'Entrega local disponible' : snapshot.approval?.approved ? 'Aprobada para entrega local' : snapshot.previewAvailable ? 'Pendiente de revisión' : 'En preparación', nextStep: humanStateLabel(snapshot.nextStep), blocker: humanStateLabel(snapshot.blockers[0], '') || null } }
export function eventLabel(event: Event) { return ({ project_created: 'Proyecto creado', change_requested: 'Cambio solicitado', version_created: 'Nueva versión creada', change_applied: 'Cambio aplicado', version_approval_changed: event.approved ? 'Versión aprobada por el usuario' : 'Aprobación retirada', version_restored: 'Versión restaurada como nueva versión', local_delivery_prepared: 'Entrega local preparada' } as Record<string, string>)[event.type] || 'Actividad registrada' }
export function workspaceView(snapshot: Snapshot, versions: Version[], humanGate?: HumanGateSummary | null) { const state = commercialState(snapshot, humanGate); const rejected = humanGate?.state === 'rejected'; const approved = humanGate?.state === 'approved' || (!humanGate && snapshot.milestones.approved); const progress = [{ label: 'Brief guardado', done: snapshot.milestones.brief }, { label: 'Materiales conservados', done: snapshot.milestones.materials }, { label: 'Dirección elegida', done: snapshot.milestones.direction }, { label: 'Versión local creada', done: snapshot.milestones.version }, { label: 'Revisión humana completada', done: ['reviewed', 'approved', 'rejected'].includes(humanGate?.state || '') }, { label: 'Versión aprobada', done: approved && !rejected }, { label: 'Correcciones requeridas', done: rejected }, { label: 'Entrega local preparada', done: snapshot.milestones.delivery && !rejected }]; return { title: snapshot.projectName, state, progress, actions: { createVersion: snapshot.capabilities.createVersion, approve: snapshot.capabilities.approval && !snapshot.approval.approved && !['approved', 'rejected'].includes(humanGate?.state || ''), delivery: snapshot.capabilities.delivery && !rejected, compare: snapshot.capabilities.comparison, restore: snapshot.capabilities.restore, preview: snapshot.previewAvailable }, currentVersion: versions.find((version) => version.versionId === snapshot.activeVersionId) || null, hasComparison: versions.length > 1 } }
export function payloadFromDraft(d: Draft) { const id = d.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'proyecto'; const nonce = Date.now().toString(36); const detectedHexColors = [...d.colors.matchAll(/#[0-9a-f]{6}/giu)].map(([value]) => value.toUpperCase()); return { projectId: `${id}-${nonce}`, runId: `run-${nonce}`, versionId: `version-${nonce}`, projectName: d.name, brief: d.need, objective: d.need, projectType: d.projectType, platform: d.platform, generationProfile: 'commercial_site', creativeDirection: d.direction, businessType: d.businessType, audience: d.audience, proposition: d.proposition, primaryCta: d.cta, brandSpec: { name: d.name, visualNotes: d.notes, primaryColor: detectedHexColors[0] || null }, inputAssets: { manifestId: `assets-${nonce}`, files: d.assets, detectedHexColors, manualBrandColors: d.colors, visualNotes: d.notes, urlReferences: d.urls.split(/\s+/).filter((v) => /^https?:\/\//.test(v)) } } }
