export type Direction = 'editorial' | 'comercial' | 'expresiva'
export type Project = { projectId: string; projectType: string; platform: string; generationProfile: string; visualDirection: Direction | null; timestamps: { updatedAt: string | null }; delivery: { status: string }; inputAssets: { totalFiles: number } }
export type Version = { versionId: string; runId?: string; createdAt: string | null; summary: string | null; changeOrigin: { kind: string; reference: string | null } }
export type Event = { eventId: string; sequence: number; type: string; occurredAt: string; versionId?: string; approved?: boolean; changeRequest?: string; sourceVersionId?: string }
export type Snapshot = { projectId: string; projectName: string; state: string; versionCount: number; activeVersionId: string; previewAvailable: boolean; previewMode: string; deliveryAvailable: boolean; delivery: { status: string; deliveredAt: string | null }; approval: { approved: boolean; approvedAt: string | null; observation: string | null }; nextStep: string; blockers: string[]; lastActivity: string | null; generationProfile: string; projectType: string; platform: string; creativeDirection: Direction | null; materials: { totalFiles: number; references: number; files: Array<{ safeName: string; kind: string; sizeBytes: number }>; colors: string[]; notes: string | null; urls: string[] }; milestones: Record<string, boolean>; capabilities: { createVersion: boolean; approval: boolean; comparison: boolean; restore: boolean; delivery: boolean }; events: Event[] }
export type Draft = { schemaVersion: 1; savedAt: string; step: number; name: string; need: string; projectType: string; platform: string; businessType: string; audience: string; proposition: string; colors: string; notes: string; urls: string; direction: Direction | ''; assets: Array<{ safeName: string; kind: string; sizeBytes: number }> }
export type WorkspaceArea = 'summary' | 'build' | 'materials' | 'versions'
export const emptyDraft = (): Draft => ({ schemaVersion: 1, savedAt: new Date().toISOString(), step: 1, name: '', need: '', projectType: 'agency_site', platform: 'web', businessType: '', audience: '', proposition: '', colors: '', notes: '', urls: '', direction: '', assets: [] })
export function validateStep(d: Draft, step: number) { if (step === 1) return d.name.trim() && d.need.trim() ? null : 'Completá el nombre y lo que necesitás.'; if (step === 2) return d.businessType.trim() && d.audience.trim() && d.proposition.trim() ? null : 'Completá negocio, audiencia y propuesta.'; if (step === 4) return d.direction ? null : 'Elegí una dirección visual.'; return null }
export function loadDraft(raw: string | null): Draft | null { try { const draft = JSON.parse(raw || 'null'); return draft?.schemaVersion === 1 && typeof draft.name === 'string' ? { ...emptyDraft(), ...draft, assets: Array.isArray(draft.assets) ? draft.assets : [] } : null } catch { return null } }
export function chooseActive(projects: Project[], active: string | null) { return projects.some((p) => p.projectId === active) ? active : visibleProjects(projects, '', 'recent')[0]?.projectId || null }
export function visibleProjects(projects: Project[], query: string, order: 'recent' | 'name', status = '') { const q = query.trim().toLowerCase(); return projects.filter((p) => (!q || p.projectId.toLowerCase().includes(q) || p.projectType.toLowerCase().includes(q)) && (!status || p.delivery.status === status)).sort((a, b) => order === 'name' ? a.projectId.localeCompare(b.projectId) : String(b.timestamps.updatedAt || '').localeCompare(String(a.timestamps.updatedAt || ''))) }
export function commercialState(snapshot: Snapshot) { return { label: snapshot.deliveryAvailable ? 'Entrega local disponible' : snapshot.approval?.approved ? 'Aprobada para entrega local' : snapshot.previewAvailable ? 'Pendiente de revisión' : 'En preparación', nextStep: snapshot.nextStep, blocker: snapshot.blockers[0] || null } }
export function eventLabel(event: Event) { return ({ project_created: 'Proyecto creado', change_requested: 'Cambio solicitado', version_created: 'Nueva versión creada', change_applied: 'Cambio aplicado', version_approval_changed: event.approved ? 'Versión aprobada por el usuario' : 'Aprobación retirada', version_restored: 'Versión restaurada como nueva versión', local_delivery_prepared: 'Entrega local preparada' } as Record<string, string>)[event.type] || 'Actividad registrada' }
export function workspaceView(snapshot: Snapshot, versions: Version[]) { const state = commercialState(snapshot); const progress = [{ label: 'Brief guardado', done: snapshot.milestones.brief }, { label: 'Materiales conservados', done: snapshot.milestones.materials }, { label: 'Dirección elegida', done: snapshot.milestones.direction }, { label: 'Versión local creada', done: snapshot.milestones.version }, { label: 'Versión aprobada', done: snapshot.milestones.approved }, { label: 'Entrega local preparada', done: snapshot.milestones.delivery }]; return { title: snapshot.projectName, state, progress, actions: { createVersion: snapshot.capabilities.createVersion, approve: snapshot.capabilities.approval && !snapshot.approval.approved, delivery: snapshot.capabilities.delivery, compare: snapshot.capabilities.comparison, restore: snapshot.capabilities.restore, preview: snapshot.previewAvailable }, currentVersion: versions.find((version) => version.versionId === snapshot.activeVersionId) || null, hasComparison: versions.length > 1 } }
export function payloadFromDraft(d: Draft) { const id = d.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'proyecto'; const nonce = Date.now().toString(36); return { projectId: `${id}-${nonce}`, runId: `run-${nonce}`, versionId: `version-${nonce}`, projectName: d.name, brief: d.need, projectType: d.projectType, platform: d.platform, generationProfile: 'commercial_site', creativeDirection: d.direction, businessType: d.businessType, audience: d.audience, proposition: d.proposition, brandSpec: { name: d.name, visualNotes: d.notes, primaryColor: d.colors.split(',')[0]?.trim() || null }, inputAssets: { manifestId: `assets-${nonce}`, files: d.assets, detectedHexColors: d.colors.split(',').map((v) => v.trim()).filter(Boolean), visualNotes: d.notes, urlReferences: d.urls.split(/\s+/).filter((v) => /^https?:\/\//.test(v)) } } }
