export type Direction = 'editorial' | 'comercial' | 'expresiva'
export type Project = { projectId: string; projectType: string; platform: string; generationProfile: string; visualDirection: Direction | null; timestamps: { updatedAt: string | null }; delivery: { status: string }; inputAssets: { totalFiles: number } }
export type Snapshot = { projectId: string; state: string; versionCount: number; previewAvailable: boolean; deliveryAvailable: boolean; nextStep: string; blockers: string[]; lastActivity: string | null; generationProfile: string; projectType: string; platform: string; creativeDirection: Direction | null; materials: { totalFiles: number } }
export type Draft = { schemaVersion: 1; savedAt: string; step: number; name: string; need: string; projectType: string; platform: string; businessType: string; audience: string; proposition: string; colors: string; notes: string; urls: string; direction: Direction | ''; assets: Array<{ safeName: string; kind: string; sizeBytes: number }> }
export const emptyDraft = (): Draft => ({ schemaVersion: 1, savedAt: new Date().toISOString(), step: 1, name: '', need: '', projectType: 'agency_site', platform: 'web', businessType: '', audience: '', proposition: '', colors: '', notes: '', urls: '', direction: '', assets: [] })
export function validateStep(d: Draft, step: number) { if (step === 1) return d.name.trim() && d.need.trim() ? null : 'Completá el nombre y lo que necesitás.'; if (step === 2) return d.businessType.trim() && d.audience.trim() && d.proposition.trim() ? null : 'Completá negocio, audiencia y propuesta.'; if (step === 4) return d.direction ? null : 'Elegí una dirección visual.'; return null }
export function loadDraft(raw: string | null): Draft | null { try { const draft = JSON.parse(raw || 'null'); return draft?.schemaVersion === 1 && typeof draft.name === 'string' ? { ...emptyDraft(), ...draft, assets: Array.isArray(draft.assets) ? draft.assets : [] } : null } catch { return null } }
export function chooseActive(projects: Project[], active: string | null) { return projects.some((p) => p.projectId === active) ? active : visibleProjects(projects, '', 'recent')[0]?.projectId || null }
export function visibleProjects(projects: Project[], query: string, order: 'recent' | 'name', status = '') { const q = query.trim().toLowerCase(); return projects.filter((p) => (!q || p.projectId.toLowerCase().includes(q) || p.projectType.toLowerCase().includes(q)) && (!status || p.delivery.status === status)).sort((a, b) => order === 'name' ? a.projectId.localeCompare(b.projectId) : String(b.timestamps.updatedAt || '').localeCompare(String(a.timestamps.updatedAt || ''))) }
export function commercialState(snapshot: Snapshot) { return { label: snapshot.deliveryAvailable ? 'Entrega local disponible' : snapshot.previewAvailable ? 'Versión local disponible' : 'En preparación', nextStep: snapshot.nextStep, blocker: snapshot.blockers[0] || null } }
export function payloadFromDraft(d: Draft) { const id = d.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'proyecto'; const nonce = Date.now().toString(36); return { projectId: `${id}-${nonce}`, runId: `run-${nonce}`, versionId: `version-${nonce}`, projectName: d.name, brief: d.need, projectType: d.projectType, platform: d.platform, generationProfile: 'commercial_site', creativeDirection: d.direction, businessType: d.businessType, audience: d.audience, proposition: d.proposition, brandSpec: { name: d.name, visualNotes: d.notes, primaryColor: d.colors.split(',')[0]?.trim() || null }, inputAssets: { manifestId: `assets-${nonce}`, files: d.assets, detectedHexColors: d.colors.split(',').map((v) => v.trim()).filter(Boolean), visualNotes: d.notes, urlReferences: d.urls.split(/\s+/).filter((v) => /^https?:\/\//.test(v)) } } }
