const fs = require('node:fs/promises');
const fsSync = require('node:fs');
const path = require('node:path');
const { resolvePaths, contained, runUv, sanitizeOutput } = require('./hermes-python-install-runtime-retry.path.cjs');
const KIND = 'factory-hermes-python-install-runtime-retry';
const VERSION = '1.0';
const HEAD = '75b300f13af40878ad6482b2ecb39c55c86679fe';
const NEXT = 'Proceed to Factory Hermes Python Install Verification Gate v1; Hermes execution remains forbidden.';
function base(input, overrides = {}) { const p = resolvePaths(); return { retryId: `hermes-python-install-runtime-retry:75b300f:${input.executedAt}`, retryKind: KIND, retryVersion: VERSION, executedAt: input.executedAt, executedBy: input.executedBy, toolId: 'hermes_agent', auditedHead: HEAD, sourceRootRef: p.refs.sourceRootRef, installRootRef: p.refs.installRootRef, pythonEnvRootRef: p.refs.pythonEnvRootRef, uvExecutableRef: p.refs.uvExecutableRef, uvVerificationRef: p.refs.uvVerificationRef, commandResults: [], pythonInstallStatus: 'not_installed', venvStatus: 'not_created', uvStatus: 'not_executed', pipStatus: 'not_executed', pythonDirectStatus: 'not_executed', setupPyStatus: 'not_executed', hermesExecutionStatus: 'not_allowed', scriptsStatus: 'not_executed', credentialsStatus: 'not_allowed', modelCallStatus: 'not_allowed', projectMutationStatus: 'not_allowed', deployStatus: 'not_allowed', status: 'blocked', decision: 'request_hermes_python_install_runtime_repair', blockers: [], warnings: [], checks: [], canProceedToPythonInstallVerification: false, canExecuteHermes: false, canRunHermesScripts: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: NEXT, ...overrides }; }
async function readJson(file) { return JSON.parse(await fs.readFile(file, 'utf8')); }
async function readJsonIfExists(file) { try { return await readJson(file); } catch { return null; } }
function isReusableSuccess(result, paths) { const reusableDecisions = ['hermes_python_install_completed_with_verified_uv', 'hermes_python_install_confirmed_existing_env_with_verified_uv_sync', 'hermes_python_install_reused_existing_success_with_verified_uv']; const reusableVenvStatuses = ['created_with_verified_uv', 'existing_uv_env_reused', 'existing_verified_uv_env_reused']; const reusableUvStatuses = ['executed_verified_allowlisted', 'verified_uv_existing_install_reused']; return Boolean(result && fsSync.existsSync(paths.pythonEnvRoot) && result.status === 'success' && reusableDecisions.includes(result.decision) && result.pythonInstallStatus === 'installed_with_verified_uv_lock_isolated' && reusableVenvStatuses.includes(result.venvStatus) && reusableUvStatuses.includes(result.uvStatus) && result.pipStatus === 'not_executed' && result.setupPyStatus === 'not_executed' && result.hermesExecutionStatus === 'not_allowed' && result.uvExecutableRef === paths.refs.uvExecutableRef && result.auditedHead === HEAD); }
async function writeArtifacts(paths, result) { const manifest = { manifestKind: 'factory_hermes_python_install_manifest', manifestVersion: '1.0', toolId: 'hermes_agent', auditedHead: HEAD, sourceRootRef: paths.refs.sourceRootRef, installRootRef: paths.refs.installRootRef, pythonEnvRootRef: paths.refs.pythonEnvRootRef, uvExecutableRef: paths.refs.uvExecutableRef, uvVerificationRef: paths.refs.uvVerificationRef, uvVersionOutput: result.uvVersionOutput, managerDecision: 'prefer_uv_lock', pythonInstallMethodScope: 'uv_lock_isolated_only', pyprojectPresent: fsSync.existsSync(path.join(paths.sourceRoot, 'pyproject.toml')), uvLockPresent: fsSync.existsSync(path.join(paths.sourceRoot, 'uv.lock')), setupPyPresent: fsSync.existsSync(path.join(paths.sourceRoot, 'setup.py')), commandSummary: result.commandResults.map(c => ({ kind: c.kind, exitCode: c.exitCode, shell: false })), pythonInstallStatus: result.pythonInstallStatus, venvStatus: result.venvStatus, uvStatus: result.uvStatus, idempotentExistingInstallUsed: result.idempotentExistingInstallUsed === true, reusedExistingPythonEnv: result.reusedExistingPythonEnv === true, syncConfirmedExistingEnv: result.syncConfirmedExistingEnv === true, previousDecision: result.previousDecision, decision: result.decision, pipStatus: 'not_executed', pythonDirectStatus: 'not_executed', setupPyStatus: 'not_executed', hermesExecutionStatus: 'not_allowed', scriptsStatus: 'not_executed', credentialsStatus: 'not_allowed', modelCallStatus: 'not_allowed', projectMutationStatus: 'not_allowed', installedAt: result.executedAt, installedBy: result.executedBy, nextRequiredGate: ['Factory Hermes Python Install Verification Gate v1'] }; await fs.writeFile(paths.pythonInstallManifest, JSON.stringify(manifest, null, 2)); await fs.writeFile(paths.pythonInstallResult, JSON.stringify(result, null, 2)); }
async function executeFactoryHermesPythonInstallRuntimeRetry(input) { const p = resolvePaths(); const blockers = []; try { contained(p.installRoot, path.join(p.root, '.codex-temp')); contained(p.sourceRoot, p.installRoot); contained(p.pythonEnvRoot, p.installRoot); contained(p.uvExe, p.uvRoot); } catch (e) { blockers.push({ blockerId: 'path_containment_failed', message: sanitizeOutput(e.message) }); }
  let uvv, manifest, installResult; try { uvv = await readJson(p.uvVerification); manifest = await readJson(p.installManifest); installResult = await readJson(p.installResult); } catch (e) { blockers.push({ blockerId: 'missing_required_artifact', message: sanitizeOutput(e.message) }); }
  if (uvv && (uvv.toolId !== 'uv' || uvv.status !== 'verified' || uvv.decision !== 'uv_provisioning_verified' || uvv.canUseUvForHermesPythonRuntime !== true || uvv.executableRef !== p.refs.uvExecutableRef)) blockers.push({ blockerId: 'blocked_uv_not_verified_for_hermes_python_runtime', message: 'UV verification result is not approved for Hermes Python runtime.' });
  if (manifest && (manifest.auditedHead !== HEAD || manifest.nodeInstallStatus !== 'installed_with_npm_ci_ignore_scripts' || manifest.hermesExecutionStatus !== 'not_allowed')) blockers.push({ blockerId: 'blocked_invalid_hermes_python_install_inputs', message: 'Hermes install manifest is not compatible.' });
  if (installResult && (installResult.auditedHead !== HEAD || installResult.nodeInstallStatus !== 'installed_with_npm_ci_ignore_scripts' || installResult.hermesExecutionStatus !== 'not_allowed')) blockers.push({ blockerId: 'blocked_invalid_hermes_python_install_inputs', message: 'Hermes install result is not compatible.' });
  for (const file of [p.uvExe, p.installRoot, p.sourceRoot, path.join(p.sourceRoot, 'pyproject.toml'), path.join(p.sourceRoot, 'uv.lock')]) if (!fsSync.existsSync(file)) blockers.push({ blockerId: 'blocked_invalid_hermes_python_install_inputs', message: `${file} is missing.` });
  if (blockers.length) { const result = base(input, { decision: blockers.some(b => b.blockerId.includes('uv')) ? 'blocked_uv_not_verified_for_hermes_python_runtime' : 'blocked_invalid_hermes_python_install_inputs', blockers }); await writeArtifacts(p, result); return result; }
  const previousPythonInstallResult = await readJsonIfExists(p.pythonInstallResult);
  const pythonEnvExists = fsSync.existsSync(p.pythonEnvRoot);
  const existingState = isReusableSuccess(previousPythonInstallResult, p) ? 'existing_success_reusable' : pythonEnvExists ? 'existing_env_requires_sync_confirmation' : 'fresh_install_required';
  await fs.mkdir(path.join(p.uvRoot, 'cache'), { recursive: true });
  const commands = [];
  const version = await runUv(p, 'uv_version_recheck_for_hermes', ['--version'], p.sourceRoot); commands.push(version.command); if (!version.ok) { const result = base(input, { status: 'failed', decision: 'failed_uv_version_check', commandResults: commands, blockers: [{ blockerId: 'failed_uv_version_check', message: version.command.stderr }] }); await writeArtifacts(p, result); return result; }
  if (existingState === 'existing_success_reusable') { const result = base(input, { status: 'success', decision: 'hermes_python_install_reused_existing_success_with_verified_uv', uvVersionOutput: version.command.stdout.trim(), commandResults: commands, pythonInstallStatus: 'installed_with_verified_uv_lock_isolated', venvStatus: 'existing_verified_uv_env_reused', uvStatus: 'verified_uv_existing_install_reused', idempotentExistingInstallUsed: true, reusedExistingPythonEnv: true, previousDecision: previousPythonInstallResult.decision, canProceedToPythonInstallVerification: true }); await writeArtifacts(p, result); return result; }
  if (existingState === 'existing_env_requires_sync_confirmation') { const syncArgs = ['sync', '--locked', '--no-install-project', '--no-dev', '--project', p.sourceRoot]; const sync = await runUv(p, 'uv_sync_hermes_locked_no_install_project', syncArgs, p.sourceRoot); commands.push(sync.command); if (!sync.ok) { const result = base(input, { status: 'failed', decision: 'failed_uv_sync', uvVersionOutput: version.command.stdout.trim(), commandResults: commands, venvStatus: 'existing_uv_env_reused', uvStatus: 'executed_verified_allowlisted', reusedExistingPythonEnv: true, previousDecision: previousPythonInstallResult?.decision, blockers: [{ blockerId: 'failed_uv_sync', message: sync.command.stderr }] }); await writeArtifacts(p, result); return result; } const result = base(input, { status: 'success', decision: 'hermes_python_install_confirmed_existing_env_with_verified_uv_sync', uvVersionOutput: version.command.stdout.trim(), commandResults: commands, pythonInstallStatus: 'installed_with_verified_uv_lock_isolated', venvStatus: 'existing_uv_env_reused', uvStatus: 'executed_verified_allowlisted', reusedExistingPythonEnv: true, syncConfirmedExistingEnv: true, previousDecision: previousPythonInstallResult?.decision, canProceedToPythonInstallVerification: true }); await writeArtifacts(p, result); return result; }
  await fs.mkdir(p.pythonEnvRoot, { recursive: true });
  const venv = await runUv(p, 'uv_venv_hermes_python_env', ['venv', p.pythonEnvRoot], p.sourceRoot); commands.push(venv.command); if (!venv.ok) { const result = base(input, { status: 'failed', decision: 'failed_uv_venv', uvVersionOutput: version.command.stdout.trim(), commandResults: commands, venvStatus: 'failed', uvStatus: 'executed_verified_allowlisted', blockers: [{ blockerId: 'failed_uv_venv', message: venv.command.stderr }] }); await writeArtifacts(p, result); return result; }
  const syncArgs = ['sync', '--locked', '--no-install-project', '--no-dev', '--project', p.sourceRoot]; const sync = await runUv(p, 'uv_sync_hermes_locked_no_install_project', syncArgs, p.sourceRoot); commands.push(sync.command); if (!sync.ok) { const result = base(input, { status: 'failed', decision: 'failed_uv_sync', uvVersionOutput: version.command.stdout.trim(), commandResults: commands, venvStatus: 'created_with_verified_uv', uvStatus: 'executed_verified_allowlisted', blockers: [{ blockerId: 'failed_uv_sync', message: sync.command.stderr }] }); await writeArtifacts(p, result); return result; }
  const result = base(input, { status: 'success', decision: 'hermes_python_install_completed_with_verified_uv', uvVersionOutput: version.command.stdout.trim(), commandResults: commands, pythonInstallStatus: 'installed_with_verified_uv_lock_isolated', venvStatus: 'created_with_verified_uv', uvStatus: 'executed_verified_allowlisted', canProceedToPythonInstallVerification: true });
  await writeArtifacts(p, result); return result; }
module.exports = { executeFactoryHermesPythonInstallRuntimeRetry };
