const path = require('node:path');
const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const runFile = promisify(execFile);
function repoRoot() { return path.resolve(__dirname, '../../..'); }
function resolvePaths() { const root = repoRoot(); const installRoot = path.join(root, '.codex-temp/external-tools/hermes-agent/install/75b300f'); const sourceRoot = path.join(installRoot, 'source'); const pythonEnvRoot = path.join(installRoot, 'python-env'); const uvRoot = path.join(root, '.codex-temp/external-tools/uv'); const uvExe = path.join(uvRoot, 'bin/uv.exe'); return { root, installRoot, sourceRoot, pythonEnvRoot, uvRoot, uvExe, uvVerification: path.join(uvRoot, 'provisioning-verification-result.json'), installManifest: path.join(installRoot, 'install-manifest.json'), installResult: path.join(installRoot, 'install-result.json'), pythonInstallManifest: path.join(installRoot, 'python-install-manifest.json'), pythonInstallResult: path.join(installRoot, 'python-install-result.json'), refs: { installRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f', sourceRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/source', pythonEnvRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/', uvExecutableRef: '.codex-temp/external-tools/uv/bin/uv.exe', uvVerificationRef: '.codex-temp/external-tools/uv/provisioning-verification-result.json' } }; }
function contained(target, root) { const rel = path.relative(path.resolve(root), path.resolve(target)); if (rel.startsWith('..') || path.isAbsolute(rel)) throw new Error(`Path escapes root: ${target}`); return path.resolve(target); }
function sanitizeOutput(value) { return String(value ?? '').replace(/\r/g, '').slice(0, 4000); }
function sanitizeEnvironment(paths) { const deny = /SECRET|TOKEN|API_KEY|PASSWORD|PRIVATE|OPENAI|GITHUB_TOKEN|NPM_TOKEN|NODE_AUTH_TOKEN|UV_INDEX|PIP_INDEX|PIP_EXTRA_INDEX|TWINE/iu; const keep = ['PATH', 'Path', 'SystemRoot', 'TEMP', 'TMP', 'HOME', 'USERPROFILE', 'LOCALAPPDATA', 'APPDATA']; const env = {}; for (const key of keep) if (process.env[key] && !deny.test(key)) env[key] = process.env[key]; env.UV_PROJECT_ENVIRONMENT = paths.pythonEnvRoot; env.UV_CACHE_DIR = path.join(paths.uvRoot, 'cache'); env.UV_NO_PROGRESS = '1'; env.PYTHONNOUSERSITE = '1'; env.PIP_CONFIG_FILE = 'NUL'; return env; }
function displayArgs(paths, args) { return args.map((arg) => arg === paths.pythonEnvRoot ? paths.refs.pythonEnvRootRef : arg === paths.sourceRoot ? paths.refs.sourceRootRef : arg); }
async function runUv(paths, kind, args, cwd) { const shownArgs = displayArgs(paths, args); try { const { stdout, stderr } = await runFile(paths.uvExe, args, { cwd, env: sanitizeEnvironment(paths), shell: false, timeout: 300000, windowsHide: true }); return { ok: true, command: { kind, commandRef: paths.refs.uvExecutableRef, args: shownArgs, cwd: path.relative(paths.root, cwd).replace(/\\/g, '/'), shell: false, exitCode: 0, stdout: sanitizeOutput(stdout), stderr: sanitizeOutput(stderr), timedOut: false, envRefs: { UV_PROJECT_ENVIRONMENT: paths.refs.pythonEnvRootRef, UV_CACHE_DIR: '.codex-temp/external-tools/uv/cache/' } } }; } catch (error) { return { ok: false, command: { kind, commandRef: paths.refs.uvExecutableRef, args: shownArgs, cwd: path.relative(paths.root, cwd).replace(/\\/g, '/'), shell: false, exitCode: typeof error.code === 'number' ? error.code : null, stdout: sanitizeOutput(error.stdout), stderr: sanitizeOutput(error.stderr || error.message), timedOut: Boolean(error.killed), envRefs: { UV_PROJECT_ENVIRONMENT: paths.refs.pythonEnvRootRef, UV_CACHE_DIR: '.codex-temp/external-tools/uv/cache/' } } }; } }
module.exports = { resolvePaths, contained, sanitizeOutput, sanitizeEnvironment, runUv };
