export const FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_PREPARATION_REVIEW_KIND = 'factory-hermes-controlled-research-runtime-preparation-review'
export const FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_PREPARATION_REVIEW_VERSION = '1.0'

export type FactoryHermesControlledResearchRuntimePreparationReviewVersion = '1.0'
export type FactoryHermesControlledResearchRuntimePreparationReviewKind = typeof FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_PREPARATION_REVIEW_KIND
export type FactoryHermesControlledResearchRuntimePreparationReviewStatus = 'controlled_research_runtime_preparation_review_completed' | 'controlled_research_runtime_preparation_review_blocked'
export type FactoryHermesControlledResearchRuntimePreparationReviewDecision = 'hermes_controlled_research_runtime_preparation_review_accepted_for_live_artifact_planning' | 'hermes_controlled_research_runtime_preparation_review_blocked_artifacts_incomplete_or_unsafe'
export interface FactoryHermesControlledResearchRuntimePreparationReviewInput { reviewedAt: string, reviewedBy: string, controlledRuntimePreparationResult?: any, controlledRuntimeApprovalResult?: any, controlledRuntimePlanningResult?: any, runtimeSelectionDecisionResult?: any }
export interface FactoryHermesControlledResearchRuntimePreparationReviewPolicy { policyId: string, accepted: boolean, blocksExecution: boolean }
export interface FactoryHermesControlledRuntimePreparationArtifactsReview { [key: string]: boolean | string }
export interface FactoryHermesControlledRuntimeVirtualTempConfigCandidateReview { [key: string]: boolean | string }
export interface FactoryHermesControlledRuntimeRunRootPathValidationReview { [key: string]: boolean | string }
export interface FactoryHermesControlledRuntimeCredentialReferenceBoundaryReview { [key: string]: boolean | string }
export interface FactoryHermesControlledRuntimePromptReferencePolicyReview { [key: string]: boolean | string }
export interface FactoryHermesControlledRuntimeModelNetworkAllowlistReview { [key: string]: boolean | string }
export interface FactoryHermesControlledRuntimeToolsetDisableProofRequirementsReview { [key: string]: boolean | string }
export interface FactoryHermesControlledRuntimeTimeoutKillSwitchEnvelopeReview { [key: string]: boolean | string | number }
export interface FactoryHermesControlledRuntimeOutputIngestionContractReview { [key: string]: boolean | string }
export interface FactoryHermesControlledRuntimePreparationLimitationsCarryForward { limitations: string[], limitationsAcceptableForLiveArtifactPlanning: boolean, limitationsBlockImmediateRuntimeExecution: boolean, limitationsBlockImmediateResearchExecution: boolean, limitationsBlockImmediateFindingsUse: boolean }
export interface FactoryHermesControlledRuntimePreparationReviewRiskDispositionRegister { registerId: string, risks: any[] }
export interface FactoryHermesControlledRuntimeLiveArtifactPlanningEnvelope { envelopeId: string, toolId: 'hermes_agent', approvedFor: string, selectedWrapperStrategy: string, sourcePreparationReviewRef: string, sourcePreparationRef: string, targetNextGate: string, purpose: string, allowedInNextGate: string[], forbiddenEvenInNextGate: string[], flags: Record<string, boolean>, recommendedNextGate: string }
export interface FactoryHermesControlledResearchRuntimePreparationReviewReceipt { receiptId: string, reviewId: string, toolId: 'hermes_agent', reviewedBy: string, reviewedAt: string, decision: string, preparationReviewStatus: string, scope: string, approvedNextGate: string, notAuthorizedActions: string[] }
export interface FactoryHermesControlledResearchRuntimePreparationReviewDecisionRecord { decisionId: string, preparationReviewStatus: string, decision: string, controlledRuntimeLiveArtifactPlanningAllowed: boolean, controlledRuntimeExecutionAllowedNow: boolean }
export interface FactoryHermesControlledResearchRuntimePreparationReviewBlockerPlan { blockerPlanId: string, blockers: string[], recommendedConservativeNextGate: string }
export interface FactoryHermesControlledResearchRuntimePreparationReviewCheck { checkId: string, passed: boolean, message: string }
export interface FactoryHermesControlledResearchRuntimePreparationReviewBlocker { blockerId: string, message: string }
export interface FactoryHermesControlledResearchRuntimePreparationReviewWarning { warningId: string, message: string }
export interface FactoryHermesControlledResearchRuntimePreparationReviewValidationResult { ok: boolean, errors: string[] }
export interface FactoryHermesControlledResearchRuntimePreparationReviewSummary { reviewId: string, status: string, decision: string, canProceedToControlledResearchRuntimeLiveArtifactPlanning: boolean, canRunResearchNow: boolean }
export interface FactoryHermesControlledResearchRuntimePreparationReviewResult { [key: string]: any }

const limitations = [
  'virtual_temp_config_is_not_live_config',
  'run_root_path_is_not_created_directory',
  'credential_ref_is_not_credential_value',
  'prompt_reference_policy_is_not_prompt_approval',
  'model_network_allowlist_is_not_network_approval',
  'toolset_requirements_are_not_disable_proof',
  'timeout_envelope_is_not_active_process_control',
  'output_contract_is_not_output_ingestion',
  'config_schema_unknown',
  'empty_toolsets_support_unknown',
  'hidden_defaults_risk_carried_forward',
  'findings_use_requires_real_ingestion_review',
]

const forbiddenEvenInNextGate = [
  'execute Hermes', 'execute hermes.exe', 'execute --oneshot', 'execute wrapper against Hermes',
  'create live temp config', 'create live run root', 'pass prompt', 'call model', 'use network',
  'resolve DNS', 'test endpoints', 'read credential values', 'read .env', 'enable actual toolsets',
  'execute research', 'ingest real output', 'promote findings', 'mutate Hermes source', 'run uv/pip/python/setup.py',
]

const notAuthorizedActions = [
  'prepare_live_runtime_now', 'create_live_temp_config_now', 'create_config_yaml_now', 'create_run_root_now',
  'execute_research_now', 'execute_research_runtime_adapter_now', 'execute_wrapper_against_hermes_now',
  'execute_hermes_now', 'execute_hermes_help_now', 'execute_oneshot_now', 'pass_prompt_now',
  'call_models_now', 'use_network_now', 'resolve_dns_now', 'test_endpoints_now', 'access_credentials_now',
  'read_env_secrets_now', 'read_dotenv_now', 'read_credential_values_now', 'enable_toolsets_now',
  'ingest_real_output_now', 'promote_findings_now', 'modify_hermes_source_now', 'modify_python_env_now',
  'modify_cache_now', 'execute_uv_now', 'execute_python_now', 'execute_pip_now', 'execute_setup_py_now',
]

function review(id: string, name: string, checks: Record<string, boolean | string | number>, extra: Record<string, boolean | string | number> = {}) {
  const accepted = Object.values(checks).every((value) => value === true || value === 'unknown' || typeof value === 'number')
  return { reviewId: `${id}:${name}`, ...checks, ...extra, acceptedForLiveArtifactPlanning: accepted, blocksImmediateRuntimeExecution: true }
}

function riskRegister(id: string) {
  const riskIds = ['preparation_review_confused_with_execution_approval', 'live_artifact_planning_confused_with_live_artifact_creation', 'virtual_temp_config_confused_with_live_config', 'run_root_path_confused_with_created_directory', 'credential_ref_confused_with_credential_value', 'prompt_policy_confused_with_prompt_approval', 'model_network_policy_confused_with_network_approval', 'toolset_requirements_confused_with_toolset_disable_proof', 'output_contract_confused_with_output_ingestion', 'hidden_defaults_loaded_in_future_runtime', 'schema_unknown_overlooked', 'findings_used_without_real_ingestion_review']
  return { registerId: `${id}:risk-disposition-register`, risks: riskIds.map((riskId) => ({ riskId, severity: ['preparation_review_confused_with_execution_approval', 'hidden_defaults_loaded_in_future_runtime'].includes(riskId) ? 'critical' : 'high', disposition: ['accepted_for_live_artifact_planning_only', 'blocks_live_artifact_creation', 'blocks_runtime_execution', 'blocks_research_execution', 'requires_future_gate_control'], mitigation: 'Require future gates before live artifact creation, runtime execution, credentials, prompt, network, toolsets, output ingestion, or findings use.', blocksPreparationReview: false, blocksLiveArtifactPlanning: false, blocksLiveArtifactCreation: true, blocksRuntimeExecution: true, blocksResearchExecution: true })) }
}

export function evaluateFactoryHermesControlledResearchRuntimePreparationReview(input: FactoryHermesControlledResearchRuntimePreparationReviewInput): FactoryHermesControlledResearchRuntimePreparationReviewResult {
  const id = `hermes-controlled-research-runtime-preparation-review:75b300f:${input.reviewedAt}`
  const p = input.controlledRuntimePreparationResult || {}
  const a = input.controlledRuntimeApprovalResult || {}
  const plan = input.controlledRuntimePlanningResult || {}
  const prepOk = p.status === 'controlled_research_runtime_prepared' && p.decision === 'hermes_controlled_research_runtime_prepared_for_preparation_review' && p.preparationStatus === 'prepared_non_executing_runtime_artifacts' && p.selectedWrapperStrategy === 'wrapper_temp_config_no_toolsets' && p.canProceedToControlledResearchRuntimePreparationReview === true && p.canProceedToControlledResearchRuntimeExecution === false && p.canRunResearchNow === false
  const approvalOk = a.status === 'controlled_research_runtime_approval_granted' && a.decision === 'hermes_controlled_research_runtime_approved_for_preparation_gate' && a.controlledRuntimeApprovalStatus === 'approved_for_preparation_only' && a.controlledRuntimePreparationAllowed === true && a.controlledRuntimeExecutionAllowedNow === false && a.researchExecutionApprovedNow === false
  const planOk = plan.status === 'controlled_research_runtime_plan_created' && plan.decision === 'hermes_controlled_research_runtime_plan_created_for_approval'
  const artifacts = review(id, 'preparation-artifacts-review', { preparationManifestPresent: Boolean(p.controlledRuntimePreparationManifest), virtualTempConfigCandidatePresent: Boolean(p.controlledRuntimeVirtualTempConfigCandidate), runRootPathValidationManifestPresent: Boolean(p.controlledRuntimeRunRootPathValidationManifest), credentialReferenceBoundaryPresent: Boolean(p.controlledRuntimeCredentialReferenceBoundary), promptReferencePolicyPresent: Boolean(p.controlledRuntimePromptReferencePolicy), modelNetworkAllowlistPolicyPresent: Boolean(p.controlledRuntimeModelNetworkAllowlistPolicy), toolsetDisableProofRequirementsPresent: Boolean(p.controlledRuntimeToolsetDisableProofRequirements), timeoutKillSwitchEnvelopePresent: Boolean(p.controlledRuntimeTimeoutKillSwitchEnvelope), outputIngestionContractPresent: Boolean(p.controlledRuntimeOutputIngestionContract), riskRegisterPresent: Boolean(p.controlledRuntimePreparationRiskRegister), reviewEnvelopePresent: Boolean(p.controlledRuntimePreparationReviewEnvelope), artifactsAreNonExecutable: p.controlledRuntimePreparationManifest?.artifactsAreNonExecutable === true }, { artifactsDoNotCreateLiveRuntime: true, artifactsSupportLiveArtifactPlanning: true, artifactsDoNotApproveExecution: true })
  const temp = p.controlledRuntimeVirtualTempConfigCandidate || {}
  const tempReview = { ...review(id, 'virtual-temp-config-candidate-review', { virtualOnly: temp.virtualOnly === true, fileWritten: temp.fileWritten === false, liveTempConfigCreated: temp.liveTempConfigCreated === false, plannedPathStringOnly: temp.plannedPathStringOnly === true, containsSecrets: temp.containsSecrets === false, containsCredentialValues: temp.containsCredentialValues === false, containsEnvDump: temp.containsEnvDump === false, usesProjectRoot: temp.usesProjectRoot === false, modifiesHermesSource: temp.modifiesHermesSource === false, exactConfigSchemaKnown: temp.exactConfigSchemaKnown || 'unknown', emptyToolsetsInConfigSupported: temp.emptyToolsetsInConfigSupported || 'unknown', runnableModeAllowed: temp.runnableModeAllowed === false, runtimeUseRequiresFutureApproval: temp.runtimeUseRequiresFutureApproval === true, runtimeUseRequiresVerificationArtifact: temp.runtimeUseRequiresVerificationArtifact === true }, { blocksImmediateResearchExecution: true }), fileWritten: false, liveTempConfigCreated: false, containsSecrets: false, containsCredentialValues: false, containsEnvDump: false, usesProjectRoot: false, modifiesHermesSource: false, runnableModeAllowed: false }
  const rr = p.controlledRuntimeRunRootPathValidationManifest || {}
  const runRootReview = { ...review(id, 'run-root-path-validation-review', { runRootCreated: rr.runRootCreated === false, runRootCreationAllowedNow: rr.runRootCreationAllowedNow === false, pathStringOnly: rr.pathStringOnly === true, underCodexTemp: rr.underCodexTemp === true, pathEscapesCodexTemp: rr.pathEscapesCodexTemp === false, overwriteExistingDataAllowed: rr.overwriteExistingDataAllowed === false, manifestRequiredBeforeUse: rr.manifestRequiredBeforeUse === true, cleanupOrRetentionPolicyRequired: rr.cleanupOrRetentionPolicyRequired === true, filesystemMutationPolicyRequiredBeforeRuntime: rr.filesystemMutationPolicyRequiredBeforeRuntime === true, futureRunRootCreationRequiresApproval: rr.futureRunRootCreationRequiresApproval === true }, { blocksImmediateFilesystemMutation: true }), runRootCreated: false, runRootCreationAllowedNow: false, pathEscapesCodexTemp: false, overwriteExistingDataAllowed: false }
  const cr = p.controlledRuntimeCredentialReferenceBoundary || {}
  const credentialReview = { ...review(id, 'credential-reference-boundary-review', { credentialRef: cr.credentialRef === 'OPENAI_API_KEY', credentialValueRead: cr.credentialValueRead === false, credentialAccessAllowedNow: cr.credentialAccessAllowedNow === false, envSecretReadAllowedNow: cr.envSecretReadAllowedNow === false, dotEnvReadAllowedNow: cr.dotEnvReadAllowedNow === false, processEnvReadAllowedNow: cr.processEnvReadAllowedNow === false, credentialValueInArtifact: cr.credentialValueInArtifact === false, credentialValueInStdout: cr.credentialValueInStdout === false, futureCredentialAccessRequiresApproval: cr.futureCredentialAccessRequiresApproval === true, redactionPolicyRequired: cr.redactionPolicyRequired === true, postRunSecretAuditRequired: cr.postRunSecretAuditRequired === true }, { blocksImmediateCredentialAccess: true }), credentialRef: 'OPENAI_API_KEY', credentialValueRead: false, credentialAccessAllowedNow: false, envSecretReadAllowedNow: false, dotEnvReadAllowedNow: false, processEnvReadAllowedNow: false, credentialValueInArtifact: false, credentialValueInStdout: false }
  const pr = p.controlledRuntimePromptReferencePolicy || {}
  const promptReview = { ...review(id, 'prompt-reference-policy-review', { promptPassingAllowedNow: pr.promptPassingAllowedNow === false, promptCreatedNow: pr.promptCreatedNow === false, promptSentNow: pr.promptSentNow === false, plannedPromptKind: pr.plannedPromptKind === 'first_controlled_research_prompt', promptReferenceRequiredBeforeRuntime: pr.promptReferenceRequiredBeforeRuntime === true, promptMustHaveOutputContract: pr.promptMustHaveOutputContract === true, promptMustHaveNoSecrets: pr.promptMustHaveNoSecrets === true, promptMustHaveNoToolInstructionsOutsidePolicy: pr.promptMustHaveNoToolInstructionsOutsidePolicy === true, promptMustBeLoggedOnlyAsHashOrSafeSummaryBeforeRuntime: pr.promptMustBeLoggedOnlyAsHashOrSafeSummaryBeforeRuntime === true, futurePromptApprovalGateRequired: pr.futurePromptApprovalGateRequired === true }, { blocksImmediatePromptPassing: true }), promptPassingAllowedNow: false, promptCreatedNow: false, promptSentNow: false, plannedPromptKind: 'first_controlled_research_prompt' }
  const mn = p.controlledRuntimeModelNetworkAllowlistPolicy || {}
  const modelNetworkReview = review(id, 'model-network-allowlist-review', { provider: mn.provider === 'openai', model: mn.model === 'gpt-4o-mini', host: mn.host === 'api.openai.com', modelCallsAllowedNow: mn.modelCallsAllowedNow === false, networkAllowedNow: mn.networkAllowedNow === false, dnsAllowedNow: mn.dnsAllowedNow === false, endpointTestsAllowedNow: mn.endpointTestsAllowedNow === false, endpointAllowlistRequiredBeforeRuntime: mn.endpointAllowlistRequiredBeforeRuntime === true, timeoutRequiredBeforeRuntime: mn.timeoutRequiredBeforeRuntime === true, retryPolicyRequiredBeforeRuntime: mn.retryPolicyRequiredBeforeRuntime === true, rateLimitRequiredBeforeRuntime: mn.rateLimitRequiredBeforeRuntime === true, killSwitchRequiredBeforeRuntime: mn.killSwitchRequiredBeforeRuntime === true, hostReferencedButNotTested: mn.hostReferencedButNotTested === true }, { blocksImmediateNetwork: true, blocksImmediateModelCalls: true })
  const tr = p.controlledRuntimeToolsetDisableProofRequirements || {}
  const toolsetReview = review(id, 'toolset-disable-proof-requirements-review', { selectedWrapperStrategy: tr.selectedWrapperStrategy === 'wrapper_temp_config_no_toolsets', toolsetEnablementAllowedNow: tr.toolsetEnablementAllowedNow === false, directNoToolsetsTextOnlyRejected: tr.directNoToolsetsTextOnlyRejected === true, directHermesCliDefaultsForbidden: tr.directHermesCliDefaultsForbidden === true, noMcpInsufficientAlone: tr.noMcpInsufficientAlone === true, hiddenDefaultsRiskCarriedForward: tr.hiddenDefaultsRiskCarriedForward === true, futureRuntimeMustUseWrapperBoundary: tr.futureRuntimeMustUseWrapperBoundary === true, futureRuntimeMustFailIfToolsetsCannotBeProvenDisabled: tr.futureRuntimeMustFailIfToolsetsCannotBeProvenDisabled === true, futureRuntimeMustFailIfDefaultToolsetsLoad: tr.futureRuntimeMustFailIfDefaultToolsetsLoad === true, futureRuntimeMustFailIfMcpEnabled: tr.futureRuntimeMustFailIfMcpEnabled === true, futureRuntimeMustFailIfAnyToolUsageAppearsInOutput: tr.futureRuntimeMustFailIfAnyToolUsageAppearsInOutput === true, proofArtifactRequiredBeforeRuntime: tr.proofArtifactRequiredBeforeRuntime === true, runtimeNoToolModeNotYetProven: tr.runtimeNoToolModeNotYetProven === true }, { blocksImmediateToolsetEnablement: true })
  const to = p.controlledRuntimeTimeoutKillSwitchEnvelope || {}
  const timeoutReview = review(id, 'timeout-kill-switch-envelope-review', { processCreatedNow: to.processCreatedNow === false, timeoutAppliedNow: to.timeoutAppliedNow === false, futureRuntimeTimeoutRequired: to.futureRuntimeTimeoutRequired === true, maxRuntimeSeconds: to.maxRuntimeSeconds === 60, noOutputTimeoutSeconds: to.noOutputTimeoutSeconds === 20, killSwitchRequired: to.killSwitchRequired === true, cancellationSignalRequired: to.cancellationSignalRequired === true, processTreeKillRequiredIfProcessExistsInFuture: to.processTreeKillRequiredIfProcessExistsInFuture === true, runawayOutputLimitRequired: to.runawayOutputLimitRequired === true, maxStdoutBytes: to.maxStdoutBytes === 200000, maxStderrBytes: to.maxStderrBytes === 100000, timeoutMustBlockFindings: to.timeoutMustBlockFindings === true, failureMustBlockFindings: to.failureMustBlockFindings === true }, { blocksImmediateProcessCreation: true })
  const oc = p.controlledRuntimeOutputIngestionContract || {}
  const outputReview = review(id, 'output-ingestion-contract-review', { outputIngestionAllowedNow: oc.outputIngestionAllowedNow === false, findingsUseAllowedNow: oc.findingsUseAllowedNow === false, futureOutputIngestionRequiresApproval: oc.futureOutputIngestionRequiresApproval === true, outputMustHaveContract: oc.outputMustHaveContract === true, outputMustBeStoredUnderCodexTemp: oc.outputMustBeStoredUnderCodexTemp === true, outputMustBeRedacted: oc.outputMustBeRedacted === true, outputMustBeBounded: oc.outputMustBeBounded === true, outputMustBeClassifiedBeforeUse: oc.outputMustBeClassifiedBeforeUse === true, findingsRequireReviewGate: oc.findingsRequireReviewGate === true, rawOutputMustNotBePromotedToFindingsAutomatically: oc.rawOutputMustNotBePromotedToFindingsAutomatically === true, failedRunOutputMustNotBeUsedAsFindings: oc.failedRunOutputMustNotBeUsedAsFindings === true, timeoutOutputMustNotBeUsedAsFindings: oc.timeoutOutputMustNotBeUsedAsFindings === true }, { blocksImmediateOutputIngestion: true, blocksImmediateFindingsUse: true })
  const accepted = [prepOk, approvalOk, planOk, artifacts.acceptedForLiveArtifactPlanning, tempReview.acceptedForLiveArtifactPlanning, runRootReview.acceptedForLiveArtifactPlanning, credentialReview.acceptedForLiveArtifactPlanning, promptReview.acceptedForLiveArtifactPlanning, modelNetworkReview.acceptedForLiveArtifactPlanning, toolsetReview.acceptedForLiveArtifactPlanning, timeoutReview.acceptedForLiveArtifactPlanning, outputReview.acceptedForLiveArtifactPlanning].every(Boolean)
  const blockers = accepted ? [] : [{ blockerId: 'preparation_artifacts_incomplete_or_unsafe', message: 'Preparation review inputs are incomplete or unsafe.' }]
  const status = accepted ? 'controlled_research_runtime_preparation_review_completed' : 'controlled_research_runtime_preparation_review_blocked'
  const decision = accepted ? 'hermes_controlled_research_runtime_preparation_review_accepted_for_live_artifact_planning' : 'hermes_controlled_research_runtime_preparation_review_blocked_artifacts_incomplete_or_unsafe'
  const envelope = { envelopeId: `${id}:live-artifact-planning-envelope`, toolId: 'hermes_agent', approvedFor: 'controlled_research_runtime_live_artifact_planning_only', selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets', sourcePreparationReviewRef: 'controlled-research-runtime-preparation-review-result.json', sourcePreparationRef: 'controlled-research-runtime-preparation-result.json', targetNextGate: 'Factory Hermes Controlled Research Runtime Live Artifact Planning Gate v1', purpose: 'plan whether and how live temp config and live run root artifacts may be created in future gates while keeping Hermes execution, prompt, model, network, credentials, toolsets, research and findings blocked', allowedInNextGate: ['read controlled-research-runtime-preparation-review-result.json', 'read controlled-research-runtime-preparation-result.json', 'plan live temp config creation boundary', 'plan run root creation boundary', 'plan filesystem mutation allowlist', 'plan secret redaction and artifact safety checks', 'plan pre-runtime verification of temp config/run root', 'plan approval gates before actual creation', 'write ignored planning artifact'], forbiddenEvenInNextGate, flags: { liveArtifactPlanningAllowedNow: true, liveTempConfigCreationAllowedNow: false, liveRunRootCreationAllowedNow: false, controlledRuntimeExecutionAllowedNow: false, researchExecutionApprovedNow: false, promptPassingAllowedNow: false, modelCallsAllowedNow: false, networkAllowedNow: false, credentialAccessAllowedNow: false, toolsetEnablementAllowedNow: false, findingsUseAllowedNow: false, canProceedToControlledResearchRuntimeLiveArtifactPlanning: true, canProceedToControlledResearchRuntimeLiveArtifactCreation: false, canProceedToControlledResearchRuntimeExecution: false, canRunResearchNow: false }, recommendedNextGate: 'Factory Hermes Controlled Research Runtime Live Artifact Planning Gate v1' }
  return {
    reviewId: id, reviewKind: FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_PREPARATION_REVIEW_KIND, reviewVersion: FACTORY_HERMES_CONTROLLED_RESEARCH_RUNTIME_PREPARATION_REVIEW_VERSION, reviewedAt: input.reviewedAt, reviewedBy: input.reviewedBy, toolId: 'hermes_agent',
    controlledRuntimePreparationRef: p.preparationId, controlledRuntimeApprovalRef: a.approvalId, controlledRuntimePlanningRef: plan.planningId, selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets',
    controlledRuntimePreparationArtifactsReview: artifacts, controlledRuntimeVirtualTempConfigCandidateReview: tempReview, controlledRuntimeRunRootPathValidationReview: runRootReview, controlledRuntimeCredentialReferenceBoundaryReview: credentialReview, controlledRuntimePromptReferencePolicyReview: promptReview, controlledRuntimeModelNetworkAllowlistReview: modelNetworkReview, controlledRuntimeToolsetDisableProofRequirementsReview: toolsetReview, controlledRuntimeTimeoutKillSwitchEnvelopeReview: timeoutReview, controlledRuntimeOutputIngestionContractReview: outputReview,
    controlledRuntimePreparationLimitationsCarryForward: { limitations, limitationsAcceptableForLiveArtifactPlanning: true, limitationsBlockImmediateRuntimeExecution: true, limitationsBlockImmediateResearchExecution: true, limitationsBlockImmediateFindingsUse: true },
    controlledRuntimePreparationReviewRiskDispositionRegister: riskRegister(id),
    ...(accepted ? { controlledRuntimeLiveArtifactPlanningEnvelope: envelope } : { reviewBlockerPlan: { blockerPlanId: `${id}:blocker-plan`, blockers: blockers.map((b) => b.blockerId), recommendedConservativeNextGate: 'Factory Hermes Keep Hermes Research Blocked Decision Gate v1' } }),
    controlledResearchRuntimePreparationReviewReceipt: { receiptId: `${id}:receipt`, reviewId: id, toolId: 'hermes_agent', reviewedBy: input.reviewedBy, reviewedAt: input.reviewedAt, decision, preparationReviewStatus: accepted ? 'accepted_with_limitations' : 'blocked', scope: 'hermes_controlled_research_runtime_preparation_review_only', approvedNextGate: accepted ? 'Factory Hermes Controlled Research Runtime Live Artifact Planning Gate v1' : 'Factory Hermes Keep Hermes Research Blocked Decision Gate v1', notAuthorizedActions },
    hermesControlledResearchRuntimePreparationReviewDecision: { decisionId: `${id}:decision`, preparationReviewStatus: accepted ? 'accepted_with_limitations' : 'blocked', decision, controlledRuntimeLiveArtifactPlanningAllowed: accepted, controlledRuntimeExecutionAllowedNow: false },
    checks: [{ checkId: 'controlled_runtime_preparation_valid', passed: prepOk, message: 'Preparation result is ready for review.' }, { checkId: 'controlled_runtime_approval_valid', passed: approvalOk, message: 'Approval remains preparation-only.' }, { checkId: 'controlled_runtime_planning_valid', passed: planOk, message: 'Planning result is present.' }],
    blockers, warnings: limitations.map((message) => ({ warningId: message, message })),
    status, decision, preparationReviewStatus: accepted ? 'accepted_with_limitations' : 'blocked',
    preparationArtifactsAccepted: accepted, virtualTempConfigCandidateAccepted: accepted, runRootPathValidationAccepted: accepted, credentialReferenceBoundaryAccepted: accepted, promptReferencePolicyAccepted: accepted, modelNetworkAllowlistAccepted: accepted, toolsetDisableProofRequirementsAccepted: accepted, timeoutKillSwitchEnvelopeAccepted: accepted, outputIngestionContractAccepted: accepted, controlledRuntimeLiveArtifactPlanningAllowed: accepted,
    controlledRuntimeExecutionAllowedNow: false, researchExecutionApprovedNow: false, tempConfigCreationApprovedNow: false, runRootCreationApprovedNow: false, promptPassingApprovedNow: false, modelCallsApprovedNow: false, networkApprovedNow: false, credentialAccessApprovedNow: false, toolsetEnablementApprovedNow: false, findingsUseApprovedNow: false,
    canProceedToControlledResearchRuntimeLiveArtifactPlanning: accepted, canProceedToControlledResearchRuntimeLiveArtifactCreation: false, canProceedToControlledResearchRuntimeExecution: false, canProceedToResearchRuntimeAdapterExecution: false, canProceedToKeepHermesResearchBlockedDecision: !accepted, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canEnableToolsetsNow: false, canMutateFilesystemNow: false, canUseFindings: false,
    recommendedNextStep: accepted ? 'Proceed to Factory Hermes Controlled Research Runtime Live Artifact Planning Gate v1; live artifact creation and runtime execution remain blocked.' : 'Keep Hermes research blocked or repair preparation artifacts.',
  }
}

export function validateFactoryHermesControlledResearchRuntimePreparationReviewInput(input: FactoryHermesControlledResearchRuntimePreparationReviewInput): FactoryHermesControlledResearchRuntimePreparationReviewValidationResult {
  const errors: string[] = []
  if (!input?.reviewedAt) errors.push('reviewedAt_required')
  if (!input?.reviewedBy) errors.push('reviewedBy_required')
  return { ok: errors.length === 0, errors }
}

export function validateFactoryHermesControlledResearchRuntimePreparationReviewResult(result: any): FactoryHermesControlledResearchRuntimePreparationReviewValidationResult {
  const errors: string[] = []
  if (!['controlled_research_runtime_preparation_review_completed', 'controlled_research_runtime_preparation_review_blocked'].includes(result?.status)) errors.push('invalid_status')
  for (const key of ['canProceedToControlledResearchRuntimeLiveArtifactCreation', 'canProceedToControlledResearchRuntimeExecution', 'canProceedToResearchRuntimeAdapterExecution', 'canRunResearchNow', 'canExecuteHermesNow', 'canPassPromptNow', 'canUseNetworkNow', 'canUseCredentialsNow', 'canReadEnvSecretsNow', 'canCallModelsNow', 'canEnableToolsetsNow', 'canMutateFilesystemNow', 'canUseFindings', 'controlledRuntimeExecutionAllowedNow', 'researchExecutionApprovedNow', 'tempConfigCreationApprovedNow', 'runRootCreationApprovedNow', 'promptPassingApprovedNow', 'modelCallsApprovedNow', 'networkApprovedNow', 'credentialAccessApprovedNow', 'toolsetEnablementApprovedNow', 'findingsUseApprovedNow']) if (result?.[key] !== false) errors.push(`${key}_must_be_false`)
  if (result?.status === 'controlled_research_runtime_preparation_review_completed' && result?.canProceedToControlledResearchRuntimeLiveArtifactPlanning !== true) errors.push('live_artifact_planning_must_be_true')
  return { ok: errors.length === 0, errors }
}

export function serializeFactoryHermesControlledResearchRuntimePreparationReviewResult(result: any): string { return JSON.stringify(result, null, 2) }
export function parseFactoryHermesControlledResearchRuntimePreparationReviewResult(text: string): any { return JSON.parse(text) }
export function summarizeFactoryHermesControlledResearchRuntimePreparationReviewResult(result: any): FactoryHermesControlledResearchRuntimePreparationReviewSummary {
  return { reviewId: result.reviewId, status: result.status, decision: result.decision, canProceedToControlledResearchRuntimeLiveArtifactPlanning: result.canProceedToControlledResearchRuntimeLiveArtifactPlanning, canRunResearchNow: result.canRunResearchNow }
}
