export type FactoryHermesWrapperNoToolModeImplementationApprovalVersion = '1.0'
export type FactoryHermesWrapperNoToolModeImplementationApprovalKind = 'factory-hermes-wrapper-no-tool-mode-implementation-approval'
export type FactoryHermesWrapperNoToolModeImplementationApprovalStatus = 'wrapper_no_tool_mode_implementation_approval_granted' | 'wrapper_no_tool_mode_implementation_approval_blocked'
export type FactoryHermesWrapperNoToolModeImplementationApprovalDecision = 'hermes_wrapper_no_tool_mode_implementation_approved_for_next_gate' | 'hermes_wrapper_no_tool_mode_implementation_approval_blocked_plan_incomplete_or_unsafe'
export type FactoryHermesWrapperNoToolModeImplementationApprovalStatusValue = 'approved_for_implementation_only' | 'blocked'
export interface FactoryHermesWrapperNoToolModeImplementationApprovalInput { evaluatedAt: string; evaluatedBy: string; implementationPlanningResult?: any; wrapperNoToolModeApprovalResult?: any; wrapperNoToolModePlanningResult?: any; runtimeSelectionRevisionPlanningResult?: any; toolsetDisableVerificationApprovalResult?: any; researchRuntimeAdapterApprovalResult?: any; policy?: Partial<FactoryHermesWrapperNoToolModeImplementationApprovalPolicy>; approvalNotes?: string }
export interface FactoryHermesWrapperNoToolModeImplementationApprovalPolicy { requireImplementationPlanningGate: boolean; requireWrapperApprovalGate: boolean; requireImplementationOnlyApproval: boolean; requireNoWrapperExecutionInThisGate: boolean; requireNoTempConfigCreationInThisGate: boolean; requireNoSourceMutationInThisGate: boolean; requireNoResearchAdapterApprovalInThisGate: boolean; requireNoResearchExecutionInThisGate: boolean; requireNoHermesExecutionInThisGate: boolean; requireNoPromptPassingInThisGate: boolean; requireNoNetworkInThisGate: boolean; requireNoCredentialUseInThisGate: boolean; requireNoModelCallsInThisGate: boolean; requireNoToolsetEnablementInThisGate: boolean; forbidResearchRuntimeAdapterApprovalInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidResearchExecutionInThisGate: boolean; forbidUsingFindingsInThisGate: boolean; forbidDeployInThisGate: boolean }
export interface FactoryHermesApprovedWrapperNoToolModeImplementationEnvelope { envelopeId: string; toolId: 'hermes_agent'; approvedFor: 'wrapper_no_tool_mode_implementation_only'; selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets'; implementationTarget: 'Factory Hermes Wrapper No-Tool Mode Implementation Gate v1'; purpose: string; allowedInNextImplementationGate: string[]; forbiddenEvenInNextImplementationGate: string[]; implementationMustPreserve: string[]; futureVerificationStillRequired: string[]; recommendedNextGate: 'Factory Hermes Wrapper No-Tool Mode Implementation Gate v1' }
export interface FactoryHermesWrapperNoToolModeImplementationApprovalDecisionRecord { decisionId: string; toolId: 'hermes_agent'; implementationApprovalStatus: FactoryHermesWrapperNoToolModeImplementationApprovalStatusValue; decision: FactoryHermesWrapperNoToolModeImplementationApprovalDecision; reason: string; implementationPlanningValidated: boolean; wrapperImplementationApproved: boolean; wrapperExecutionApproved: false; tempConfigCreationApproved: false; researchRuntimeAdapterApproved: false; researchExecutionApproved: false; hermesExecutionApproved: false; modelCallsApproved: false; networkApproved: false; credentialAccessApproved: false; canProceedToHermesWrapperNoToolModeImplementation: boolean; requiredNextGate: string }
export interface FactoryHermesWrapperNoToolModeImplementationApprovalReceipt { receiptId: string; approvalId: string; toolId: 'hermes_agent'; evaluatedBy: string; evaluatedAt: string; decision: FactoryHermesWrapperNoToolModeImplementationApprovalDecision; implementationApprovalStatus: FactoryHermesWrapperNoToolModeImplementationApprovalStatusValue; scope: 'hermes_wrapper_no_tool_mode_implementation_approval_only'; approvedNextGate: string; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesWrapperNoToolModeImplementationApprovalBlockerPlan { blockerPlanId: string; toolId: 'hermes_agent'; blockerType: 'wrapper_implementation_plan_incomplete_or_unsafe'; blockers: string[]; resolutionOptions: string[]; recommendedConservativeNextGate: 'Factory Hermes Keep Hermes Research Blocked Decision Gate v1' }
export interface FactoryHermesWrapperNoToolModeImplementationApprovalResult { approvalId: string; approvalKind: FactoryHermesWrapperNoToolModeImplementationApprovalKind; approvalVersion: FactoryHermesWrapperNoToolModeImplementationApprovalVersion; evaluatedAt: string; evaluatedBy: string; toolId: 'hermes_agent'; implementationPlanningRef?: string; wrapperApprovalRef?: string; wrapperPlanningRef?: string; selectedWrapperStrategy: 'wrapper_temp_config_no_toolsets'; approvedWrapperNoToolModeImplementationEnvelope?: FactoryHermesApprovedWrapperNoToolModeImplementationEnvelope; hermesWrapperNoToolModeImplementationApprovalDecision: FactoryHermesWrapperNoToolModeImplementationApprovalDecisionRecord; wrapperNoToolModeImplementationApprovalReceipt: FactoryHermesWrapperNoToolModeImplementationApprovalReceipt; approvalBlockerPlan?: FactoryHermesWrapperNoToolModeImplementationApprovalBlockerPlan; checks: any[]; blockers: any[]; warnings: any[]; status: FactoryHermesWrapperNoToolModeImplementationApprovalStatus; decision: FactoryHermesWrapperNoToolModeImplementationApprovalDecision; implementationApprovalStatus: FactoryHermesWrapperNoToolModeImplementationApprovalStatusValue; canProceedToHermesWrapperNoToolModeImplementation: boolean; canProceedToHermesWrapperNoToolModeVerificationPlanning: false; canProceedToKeepHermesResearchBlockedDecision: boolean; canProceedToResearchRuntimeAdapterApprovalRetry: false; canProceedToResearchRuntimeAdapter: false; canRunResearchNow: false; canExecuteHermesNow: false; canPassPromptNow: false; canUseNetworkNow: false; canUseCredentialsNow: false; canReadEnvSecretsNow: false; canCallModelsNow: false; canEnableToolsetsNow: false; canMutateFilesystemNow: false; canUseFindings: false; recommendedNextStep: string }
export interface FactoryHermesWrapperNoToolModeImplementationApprovalValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesWrapperNoToolModeImplementationApprovalSummary { approvalId: string; status: FactoryHermesWrapperNoToolModeImplementationApprovalStatus; decision: FactoryHermesWrapperNoToolModeImplementationApprovalDecision; implementationApprovalStatus: FactoryHermesWrapperNoToolModeImplementationApprovalStatusValue; selectedWrapperStrategy: string; canProceedToHermesWrapperNoToolModeImplementation: boolean; canRunResearchNow: false; canExecuteHermesNow: false; nextStep: string }
