import { FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_VERIFICATION_KIND, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_VERIFICATION_NEXT_STEP, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_VERIFICATION_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_VERIFICATION_VERSION } from './hermes-entrypoint-materialization-verification.defaults.ts'
import type { FactoryHermesEntrypointMaterializationVerificationInput, FactoryHermesEntrypointMaterializationVerificationResult } from './hermes-entrypoint-materialization-verification.types.ts'

function base(input: FactoryHermesEntrypointMaterializationVerificationInput): FactoryHermesEntrypointMaterializationVerificationResult {
  const r = input.runtimeRetryResult || {}
  return { verificationId: `hermes-entrypoint-materialization-verification:75b300f:${input.verifiedAt}`, verificationKind: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_VERIFICATION_KIND, verificationVersion: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_VERIFICATION_VERSION, verifiedAt: input.verifiedAt, verifiedBy: input.verifiedBy, toolId: 'hermes_agent', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', expectedExecutableRef: r.expectedExecutableRef || '', executableStatus: 'unknown', executableSizeBytes: null, executableSha256: '', materializationStatus: r.materializationStatus || '', sourceMutationStatus: 'unknown', knownWarnings: [], runtimeRetryDecision: r.decision || '', checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_runtime_retry_result', canProceedToResearchRuntimeAdapterRetry: false, canRetryResearchAdapterNow: false, canExecuteHermesNow: false, canTreatAsResearchResult: false, canUseFindings: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canMutateProjectFiles: false, canDeploy: false, recommendedNextStep: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_VERIFICATION_NEXT_STEP }
}

export function evaluateFactoryHermesEntrypointMaterializationVerification(input: FactoryHermesEntrypointMaterializationVerificationInput): FactoryHermesEntrypointMaterializationVerificationResult {
  const r = input.runtimeRetryResult
  const exe = input.executableInspection || {}
  const src = input.sourceInspection || {}
  const out = base(input)
  if (!r) return { ...out, blockers: [{ blockerId: 'blocked_missing_runtime_retry_result', message: 'Runtime retry result is required.' }] }
  if (r.status !== 'success' || r.decision !== 'hermes_entrypoint_materialized_after_cache_verified_retry' || r.materializationStatus !== 'materialized' || r.executableStatusAfter !== 'present' || r.canProceedToEntrypointMaterializationVerification !== true) return { ...out, decision: 'blocked_runtime_retry_not_success', blockers: [{ blockerId: 'blocked_runtime_retry_not_success', message: 'Runtime retry did not successfully materialize the entrypoint.' }] }
  const unsafe = r.canRetryResearchAdapterNow !== false || r.canExecuteHermesNow !== false || r.canTreatAsResearchResult !== false || r.networkStatus !== 'not_allowed' || r.credentialsStatus !== 'not_allowed' || r.modelCallStatus !== 'not_allowed' || r.pipStatus !== 'not_executed' || r.pythonDirectStatus !== 'not_executed' || r.setupPyDirectStatus !== 'not_executed' || r.hermesExecutionStatus !== 'not_executed' || r.scriptsStatus !== 'not_executed' || r.researchAdapterRetryStatus !== 'not_attempted'
  if (unsafe) return { ...out, decision: 'blocked_boundary_violation_detected', blockers: [{ blockerId: 'blocked_boundary_violation_detected', message: 'Runtime retry boundary flags are unsafe.' }] }
  if (!exe.exists) return { ...out, decision: 'blocked_entrypoint_executable_missing', blockers: [{ blockerId: 'blocked_entrypoint_executable_missing', message: 'hermes.exe is missing.' }] }
  if (!exe.contained) return { ...out, decision: 'blocked_entrypoint_path_not_contained', blockers: [{ blockerId: 'blocked_entrypoint_path_not_contained', message: 'hermes.exe path is not contained.' }] }
  if (!exe.sizeBytes || exe.sizeBytes <= 0) return { ...out, decision: 'blocked_entrypoint_executable_empty', blockers: [{ blockerId: 'blocked_entrypoint_executable_empty', message: 'hermes.exe is empty.' }] }
  if (!exe.sha256) return { ...out, decision: 'blocked_entrypoint_executable_empty', blockers: [{ blockerId: 'blocked_entrypoint_executable_empty', message: 'hermes.exe sha256 is missing.' }] }
  if (src.keyFileHashesUnchanged !== true || src.unexpectedSourceMutation === true) return { ...out, decision: 'blocked_unexpected_source_mutation', blockers: [{ blockerId: 'blocked_unexpected_source_mutation', message: 'Source mutation detected.' }] }
  const warnings = (src.knownWarnings || []).map((warningId: string) => ({ warningId, message: warningId }))
  const decision = 'hermes_entrypoint_materialization_verified_for_research_runtime_adapter_retry' as const
  const receipt = { receiptId: `${out.verificationId}:receipt`, verificationId: out.verificationId, toolId: 'hermes_agent', verifiedBy: input.verifiedBy, verifiedAt: input.verifiedAt, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', expectedExecutableRef: r.expectedExecutableRef, executableStatus: 'present', executableSha256: exe.sha256, materializationStatus: 'materialized', sourceMutationStatus: src.sourceMutationStatus || 'unchanged', decision, scope: 'hermes_entrypoint_materialization_verification_only', approvedNextGate: 'Factory Hermes Research Runtime Adapter Retry Gate v1', limitations: ['Verification only.', 'No Hermes, entrypoint, adapter, uv, pip, Python, setup.py, network, credentials or model execution is authorized now.'], notAuthorizedActions: FACTORY_HERMES_ENTRYPOINT_MATERIALIZATION_VERIFICATION_NOT_AUTHORIZED_ACTIONS }
  const record = { recordId: `${out.verificationId}:record`, verificationId: out.verificationId, toolId: 'hermes_agent', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', runtimeRetryResultRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/entrypoint-materialization-runtime-retry-result.json', runtimeRetryManifestRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/entrypoint-materialization-runtime-retry-manifest.json', expectedExecutableRef: r.expectedExecutableRef, executableVerification: { exists: true, contained: true, sizeBytes: exe.sizeBytes, sha256: exe.sha256, extension: 'exe' }, materializationVerification: { materializationStatus: 'materialized', runtimeRetryDecision: r.decision, uvOffline: true, cacheVerified: true }, safetyVerification: { noHermesExecution: true, noSelectedInterfaceExecution: true, noResearchAdapterRetry: true, noPip: true, noPythonDirect: true, noSetupPyDirect: true, noUvRun: true, noUvPip: true, noUvVenv: true, noNetwork: true, noCredentials: true, noModelCalls: true }, sourceVerification: { keyFileHashesUnchanged: true, knownWarnings: src.knownWarnings || [], unexpectedSourceMutation: false }, canProceedToResearchRuntimeAdapterRetry: true, canRetryResearchAdapterNow: false, canExecuteHermesNow: false }
  const envelope = { envelopeId: `${out.verificationId}:envelope`, verificationId: out.verificationId, toolId: 'hermes_agent', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', selectedInterface: { interfaceType: 'package_entrypoint', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main' }, executableRef: r.expectedExecutableRef, executableSha256: exe.sha256, sourceRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/source', pythonEnvRootRef: '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env', retryMethodCandidate: 'research_runtime_adapter_help_probe_retry', approvedNextGate: 'Factory Hermes Research Runtime Adapter Retry Gate v1', retryAllowedNow: false, futureRetryMayExecuteHermesHelpOnly: true, futureRetryCommand: { executableRef: r.expectedExecutableRef, args: ['--help'], shell: false, cwd: '.codex-temp/external-tools/hermes-agent/install/75b300f/source', timeoutMs: 120000 }, futureRetryMustNotUseNetwork: true, futureRetryMustNotUseCredentials: true, futureRetryMustNotCallModels: true, futureRetryMustSanitizeOutput: true, futureRetryMustNotTreatHelpAsResearchFindings: true, requiredFutureGates: ['Factory Hermes Research Runtime Adapter Retry Gate v1', 'Factory Hermes Research Result Ingestion Gate v2', 'Factory Hermes Research JEFE Review Gate v2'] }
  return { ...out, status: warnings.length ? 'warning_verified' : 'verified', decision, expectedExecutableRef: r.expectedExecutableRef, executableStatus: 'present', executableSizeBytes: exe.sizeBytes, executableSha256: exe.sha256, materializationStatus: 'materialized', sourceMutationStatus: src.sourceMutationStatus || 'unchanged', knownWarnings: src.knownWarnings || [], warnings, entrypointMaterializationVerificationReceipt: receipt, hermesEntrypointMaterializationVerificationRecord: record, approvedResearchRuntimeAdapterRetryEnvelope: envelope, canProceedToResearchRuntimeAdapterRetry: true }
}
