import type { FactoryHermesResearchRuntimeInterfaceSelectionResult, FactoryHermesResearchRuntimeSelectedInterface } from '../hermes-research-runtime-interface-selection/index.ts'

export type FactoryHermesResearchRuntimeBoundaryVersion = '1.0'
export type FactoryHermesResearchRuntimeBoundaryKind = 'factory-hermes-research-runtime-boundary'
export type FactoryHermesResearchRuntimeBoundaryStatus = 'boundary_contract_created' | 'blocked' | 'human_review_required'
export type FactoryHermesResearchRuntimeBoundaryDecision = 'hermes_research_runtime_boundary_contract_created' | 'blocked_missing_interface_selection' | 'blocked_interface_not_selected' | 'blocked_boundary_would_allow_execution_now' | 'blocked_boundary_would_allow_network_now' | 'blocked_boundary_would_allow_credentials_now' | 'blocked_boundary_would_allow_model_calls_now' | 'blocked_missing_human_approval' | 'request_boundary_review'
export interface FactoryHermesResearchRuntimeBoundaryPolicy { requireInterfaceSelection: boolean; requireSelectedInterface: boolean; requireHumanApprovalRef: boolean; requireBoundaryApprovalNext: boolean; requireResultIngestionFuture: boolean; requireJefeReviewFuture: boolean; forbidExecutionInThisGate: boolean; forbidHermesExecutionInThisGate: boolean; forbidHermesScriptsInThisGate: boolean; forbidPythonExecutionInThisGate: boolean; forbidUvExecutionInThisGate: boolean; forbidPipExecutionInThisGate: boolean; forbidSetupPyExecutionInThisGate: boolean; forbidNetworkInThisGate: boolean; forbidCredentialsInThisGate: boolean; forbidModelCallsInThisGate: boolean; forbidProjectMutationInThisGate: boolean; forbidDeployInThisGate: boolean; requireShellFalseFutureRuntime: boolean; requireNoShellFutureRuntime: boolean; requireTimeoutFutureRuntime: boolean; requireKillSwitchFutureRuntime: boolean; requireSanitizedLogsFutureRuntime: boolean; requireStructuredResultFutureRuntime: boolean }
export interface FactoryHermesResearchRuntimeBoundaryInput { boundedAt: string; boundedBy: string; humanApprovalRef?: string; interfaceSelectionResult?: FactoryHermesResearchRuntimeInterfaceSelectionResult; policy?: Partial<FactoryHermesResearchRuntimeBoundaryPolicy>; boundaryNotes?: string }
export interface FactoryHermesResearchRuntimeFilesystemBoundary { allowedReadRootsFuture: string[]; allowedWriteRootsFuture: string[]; forbiddenRoots: string[]; projectMutationAllowedNow: false; projectMutationAllowedFuture: false; writeRequiresRuntimeApproval: true }
export interface FactoryHermesResearchRuntimeCommandBoundary { commandsAllowedNow: string[]; futureCommandCandidate: { executableRef: string; argsPolicy: 'boundary_defined_only'; shell: false; cwd: string; timeoutMsDefault: 60000; timeoutMsMax: 300000; stdinPolicy: 'controlled_or_disabled'; stdoutPolicy: 'captured_sanitized_truncated'; stderrPolicy: 'captured_sanitized_truncated' }; forbiddenCommands: string[]; noCommandExecutionInThisGate: true }
export interface FactoryHermesResearchRuntimeNetworkBoundary { networkAllowedNow: false; networkAllowedFutureDefault: false; futureNetworkRequiresSeparateApproval: true; allowedDomainsFuture: string[]; blockAllByDefault: true; scrapingAllowedNow: false; scrapingAllowedFutureRequiresApproval: true }
export interface FactoryHermesResearchRuntimeCredentialBoundary { credentialsAllowedNow: false; credentialsAllowedFutureDefault: false; futureCredentialsRequireSeparateApproval: true; envReadAllowedNow: false; envReadAllowedFutureDefault: false; secretNamesAllowedFuture: string[] }
export interface FactoryHermesResearchRuntimeModelBoundary { modelCallsAllowedNow: false; modelCallsAllowedFutureDefault: false; futureModelCallsRequireSeparateApproval: true; allowedProvidersFuture: string[]; allowedModelsFuture: string[] }
export interface FactoryHermesResearchRuntimeIoBoundary { inputContractFuture: Record<string, unknown>; outputContractFuture: Record<string, unknown>; rawLogLimitBytes: number; stdoutLimitBytes: number; stderrLimitBytes: number }
export interface FactoryHermesResearchRuntimeSafetyBoundary { killSwitchRequired: true; timeoutRequired: true; maxRuntimeMsHardLimit: 300000; processTreeKillRequired: true; retryPolicy: 'disabled_by_default'; logSanitizationRequired: true; resultIngestionRequired: true; jefeReviewRequired: true }
export interface FactoryHermesResearchRuntimeBoundaryReceipt { receiptId: string; boundaryId: string; toolId: 'hermes_agent'; auditedHead: string; boundedBy: string; boundedAt: string; humanApprovalRef: string; selectedCandidateId: string; decision: FactoryHermesResearchRuntimeBoundaryDecision; scope: 'hermes_research_runtime_boundary_contract_only'; approvedNextGate: 'Factory Hermes Research Runtime Approval Gate v1'; limitations: string[]; notAuthorizedActions: string[] }
export interface FactoryHermesResearchRuntimeBoundaryContract { contractId: string; toolId: 'hermes_agent'; auditedHead: string; selectedCandidateId: string; commandName: 'hermes'; pythonEntrypoint: 'hermes_cli.main:main'; futureExecutableCandidateWindows: string; filesystemBoundary: FactoryHermesResearchRuntimeFilesystemBoundary; commandBoundary: FactoryHermesResearchRuntimeCommandBoundary; networkBoundary: FactoryHermesResearchRuntimeNetworkBoundary; credentialBoundary: FactoryHermesResearchRuntimeCredentialBoundary; modelBoundary: FactoryHermesResearchRuntimeModelBoundary; ioBoundary: FactoryHermesResearchRuntimeIoBoundary; safetyBoundary: FactoryHermesResearchRuntimeSafetyBoundary; nextRequiredGates: string[] }
export interface FactoryHermesResearchRuntimeBoundaryCheck { checkId: string; ok: boolean; message: string }
export interface FactoryHermesResearchRuntimeBoundaryBlocker { blockerId: string; message: string }
export interface FactoryHermesResearchRuntimeBoundaryWarning { warningId: string; message: string }
export interface FactoryHermesResearchRuntimeBoundaryResult { boundaryId: string; boundaryKind: FactoryHermesResearchRuntimeBoundaryKind; boundaryVersion: FactoryHermesResearchRuntimeBoundaryVersion; boundedAt: string; boundedBy: string; toolId: 'hermes_agent'; auditedHead: string; selectedCandidateId: string; selectedInterface?: FactoryHermesResearchRuntimeSelectedInterface; researchRuntimeBoundaryReceipt?: FactoryHermesResearchRuntimeBoundaryReceipt; hermesResearchRuntimeBoundaryContract?: FactoryHermesResearchRuntimeBoundaryContract; checks: FactoryHermesResearchRuntimeBoundaryCheck[]; blockers: FactoryHermesResearchRuntimeBoundaryBlocker[]; warnings: FactoryHermesResearchRuntimeBoundaryWarning[]; status: FactoryHermesResearchRuntimeBoundaryStatus; decision: FactoryHermesResearchRuntimeBoundaryDecision; canProceedToResearchRuntimeApproval: boolean; canCreateRuntimeNow: false; canExecuteHermes: false; canRunHermesScripts: false; canUseNetwork: false; canUseCredentials: false; canCallModels: false; canMutateProjectFiles: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryHermesResearchRuntimeBoundaryValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryHermesResearchRuntimeBoundarySummary { boundaryId: string; selectedCandidateId: string; commandName?: string; status: FactoryHermesResearchRuntimeBoundaryStatus; decision: FactoryHermesResearchRuntimeBoundaryDecision; canProceedToResearchRuntimeApproval: boolean; canCreateRuntimeNow: false; canExecuteHermes: false; networkAllowedNow: false; credentialsAllowedNow: false; modelCallsAllowedNow: false; approvedNextGate?: string; nextStep: string }
