import { DEFAULT_FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_POLICY, FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_KIND, FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_NEXT_STEP, FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_NOT_AUTHORIZED_ACTIONS, FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_VERSION } from './hermes-research-runtime-boundary.defaults.ts'
import type { FactoryHermesResearchRuntimeBoundaryContract, FactoryHermesResearchRuntimeBoundaryInput, FactoryHermesResearchRuntimeBoundaryResult } from './hermes-research-runtime-boundary.types.ts'

const nextGates = ['Factory Hermes Research Runtime Approval Gate v1', 'Factory Hermes Research Runtime Adapter v1', 'Factory Hermes Research Result Ingestion Gate v1', 'Factory Hermes Research JEFE Review Gate v1']
function contract(id: string, s: NonNullable<FactoryHermesResearchRuntimeBoundaryInput['interfaceSelectionResult']>): FactoryHermesResearchRuntimeBoundaryContract {
  const selected = s.selectedInterface!
  const installRoot = s.selectedHermesResearchRuntimeInterfaceEnvelope?.installRootRef || '.codex-temp/external-tools/hermes-agent/install/75b300f'
  const sourceRoot = s.selectedHermesResearchRuntimeInterfaceEnvelope?.sourceRootRef || selected.futureWorkingDirectory
  const pyEnv = s.selectedHermesResearchRuntimeInterfaceEnvelope?.pythonEnvRootRef || '.codex-temp/external-tools/hermes-agent/install/75b300f/python-env/'
  return { contractId: `${id}:contract`, toolId: 'hermes_agent', auditedHead: s.auditedHead, selectedCandidateId: s.selectedCandidateId, commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', futureExecutableCandidateWindows: selected.futureExecutableCandidateWindows, filesystemBoundary: { allowedReadRootsFuture: [sourceRoot, pyEnv.replace(/\/$/u, '')], allowedWriteRootsFuture: [`${installRoot}/research-runtime-output/`, `${installRoot}/research-runtime-temp/`], forbiddenRoots: ['repo root except explicit artifacts', '.env', 'user home', 'desktop/documents/downloads', 'Program Files', 'AppData except explicit .codex-temp roots', 'system directories'], projectMutationAllowedNow: false, projectMutationAllowedFuture: false, writeRequiresRuntimeApproval: true }, commandBoundary: { commandsAllowedNow: [], futureCommandCandidate: { executableRef: 'python-env/Scripts/hermes.exe', argsPolicy: 'boundary_defined_only', shell: false, cwd: sourceRoot, timeoutMsDefault: 60000, timeoutMsMax: 300000, stdinPolicy: 'controlled_or_disabled', stdoutPolicy: 'captured_sanitized_truncated', stderrPolicy: 'captured_sanitized_truncated' }, forbiddenCommands: ['shell', 'cmd.exe', 'powershell', 'pip', 'python -m pip', 'setup.py', 'uv pip', 'uv run unrestricted', 'curl', 'wget', 'arbitrary scripts'], noCommandExecutionInThisGate: true }, networkBoundary: { networkAllowedNow: false, networkAllowedFutureDefault: false, futureNetworkRequiresSeparateApproval: true, allowedDomainsFuture: [], blockAllByDefault: true, scrapingAllowedNow: false, scrapingAllowedFutureRequiresApproval: true }, credentialBoundary: { credentialsAllowedNow: false, credentialsAllowedFutureDefault: false, futureCredentialsRequireSeparateApproval: true, envReadAllowedNow: false, envReadAllowedFutureDefault: false, secretNamesAllowedFuture: [] }, modelBoundary: { modelCallsAllowedNow: false, modelCallsAllowedFutureDefault: false, futureModelCallsRequireSeparateApproval: true, allowedProvidersFuture: [], allowedModelsFuture: [] }, ioBoundary: { inputContractFuture: { researchQuestion: 'required', allowedSources: 'required', forbiddenSources: 'required', constraints: 'required', maxRuntimeMs: 'required', outputSchema: 'required' }, outputContractFuture: { structuredFindings: true, evidence: true, warnings: true, confidence: true, rawLogsSanitized: true, exitStatus: true }, rawLogLimitBytes: 262144, stdoutLimitBytes: 131072, stderrLimitBytes: 131072 }, safetyBoundary: { killSwitchRequired: true, timeoutRequired: true, maxRuntimeMsHardLimit: 300000, processTreeKillRequired: true, retryPolicy: 'disabled_by_default', logSanitizationRequired: true, resultIngestionRequired: true, jefeReviewRequired: true }, nextRequiredGates: nextGates }
}
export function evaluateFactoryHermesResearchRuntimeBoundary(input: FactoryHermesResearchRuntimeBoundaryInput): FactoryHermesResearchRuntimeBoundaryResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_POLICY, ...(input.policy || {}) }
  const s = input.interfaceSelectionResult
  const id = `hermes-research-runtime-boundary:75b300f:${input.boundedAt}`
  const base = { boundaryId: id, boundaryKind: FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_KIND, boundaryVersion: FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_VERSION, boundedAt: input.boundedAt, boundedBy: input.boundedBy, toolId: 'hermes_agent' as const, auditedHead: s?.auditedHead || '', selectedCandidateId: s?.selectedCandidateId || '', selectedInterface: s?.selectedInterface, checks: [], blockers: [], warnings: [], canCreateRuntimeNow: false as const, canExecuteHermes: false as const, canRunHermesScripts: false as const, canUseNetwork: false as const, canUseCredentials: false as const, canCallModels: false as const, canMutateProjectFiles: false as const, canDeploy: false as const, recommendedNextStep: FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_NEXT_STEP }
  if (!s) return { ...base, status: 'blocked', decision: 'blocked_missing_interface_selection', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_missing_interface_selection', message: 'Interface selection result is required.' }] }
  if (s.status !== 'selected' || s.decision !== 'hermes_research_runtime_interface_selected_for_boundary_planning' || s.canProceedToResearchRuntimeBoundary !== true || s.canExecuteHermes !== false || !s.selectedInterface) return { ...base, status: 'blocked', decision: 'blocked_interface_not_selected', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_interface_not_selected', message: 'Interface selection is not selected for boundary planning.' }] }
  if (s.canUseNetwork !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_would_allow_network_now', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_boundary_would_allow_network_now', message: 'Selection allows network.' }] }
  if (s.canUseCredentials !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_would_allow_credentials_now', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_boundary_would_allow_credentials_now', message: 'Selection allows credentials.' }] }
  if (s.canCallModels !== false) return { ...base, status: 'blocked', decision: 'blocked_boundary_would_allow_model_calls_now', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_boundary_would_allow_model_calls_now', message: 'Selection allows model calls.' }] }
  if (policy.requireHumanApprovalRef && !input.humanApprovalRef) return { ...base, status: 'human_review_required', decision: 'blocked_missing_human_approval', canProceedToResearchRuntimeApproval: false, blockers: [{ blockerId: 'blocked_missing_human_approval', message: 'humanApprovalRef is required.' }] }
  const c = contract(id, s)
  const receipt = { receiptId: `${id}:receipt`, boundaryId: id, toolId: 'hermes_agent' as const, auditedHead: s.auditedHead, boundedBy: input.boundedBy, boundedAt: input.boundedAt, humanApprovalRef: input.humanApprovalRef || '', selectedCandidateId: s.selectedCandidateId, decision: 'hermes_research_runtime_boundary_contract_created' as const, scope: 'hermes_research_runtime_boundary_contract_only' as const, approvedNextGate: 'Factory Hermes Research Runtime Approval Gate v1' as const, limitations: ['Boundary contract only.', 'No runtime is created.', 'No Hermes, Python, uv, network, credentials or model execution.'], notAuthorizedActions: [...FACTORY_HERMES_RESEARCH_RUNTIME_BOUNDARY_NOT_AUTHORIZED_ACTIONS] }
  return { ...base, status: 'boundary_contract_created', decision: 'hermes_research_runtime_boundary_contract_created', researchRuntimeBoundaryReceipt: receipt, hermesResearchRuntimeBoundaryContract: c, canProceedToResearchRuntimeApproval: true }
}
