import { CREDENTIAL_REQUIRED_NEXT_POLICIES, CREDENTIALS_NOT_AUTHORIZED_ACTIONS, DEFAULT_FACTORY_HERMES_CREDENTIALS_POLICY_PLANNING_POLICY, FACTORY_HERMES_CREDENTIALS_POLICY_PLANNING_KIND, FACTORY_HERMES_CREDENTIALS_POLICY_PLANNING_NEXT_STEP, FACTORY_HERMES_CREDENTIALS_POLICY_PLANNING_VERSION } from './hermes-credentials-policy-planning.defaults.ts'
import type { FactoryHermesCredentialReference, FactoryHermesCredentialsPolicyPlanningInput, FactoryHermesCredentialsPolicyPlanningResult } from './hermes-credentials-policy-planning.types.ts'

const PROVIDER_BY_REF: Record<string, string> = { OPENAI_API_KEY: 'openai', ANTHROPIC_API_KEY: 'anthropic', GEMINI_API_KEY: 'gemini_google', GOOGLE_API_KEY: 'gemini_google' }

export function buildCredentialReferences(inspection?: any, deep?: any): FactoryHermesCredentialReference[] {
  const refs = new Set<string>([...(inspection?.credentialRefsObserved || []), ...(deep?.providerModelFindings?.credentialEnvNamesObserved || [])])
  return [...refs].filter((ref) => PROVIDER_BY_REF[ref]).map((ref) => ({ refName: ref, providerCandidate: PROVIDER_BY_REF[ref], status: 'referenced_not_read' as const, valueKnown: false as const, valueRead: false as const, approvedForUseNow: false as const, requiresFutureCredentialApproval: true as const }))
}

function rules() {
  return [
    { ruleId: 'no_implicit_env_read', ruleName: 'No implicit env read', requirements: ['Future runtime cannot depend on implicit env/config without approval.', '.env cannot be read.', 'Full env cannot be printed.'] },
    { ruleId: 'explicit_credential_selection', ruleName: 'Explicit credential selection', requirements: ['Future provider must map to one approved credential ref.', 'No wildcard credentials.', 'No all available keys.'] },
    { ruleId: 'credential_injection_policy', ruleName: 'Credential injection policy', requirements: ['This gate defines no values.', 'Future source must be secure runtime injection, explicit secret ref, or managed store if available.', 'Values never stored in artifacts.'] },
    { ruleId: 'masking_logging', ruleName: 'Masking / logging', requirements: ['Never log values.', 'Logs may contain ref name and redacted marker only.', 'Sanitizer must block secret patterns.'] },
    { ruleId: 'credential_scope', ruleName: 'Credential scope', requirements: ['Credential only for selected provider.', 'No cross-provider reuse.', 'No automatic fallback to another key.'] },
    { ruleId: 'credential_validation', ruleName: 'Credential validation', requirements: ['Do not validate existence or value in planning.', 'Future runtime validation only after approval.', 'Prefer fail-fast if ref missing.'] },
    { ruleId: 'revocation_kill_switch', ruleName: 'Revocation / kill switch', requirements: ['Credential kill switch required.', 'credentialUsageStatus required in future results.'] },
    { ruleId: 'config_env_fallback', ruleName: 'Config/env fallback', requirements: ['Env/config defaults prohibited unless approved.', 'HERMES_INFERENCE_PROVIDER and HERMES_INFERENCE_MODEL are not credentials.'] },
  ]
}

function base(input: FactoryHermesCredentialsPolicyPlanningInput): FactoryHermesCredentialsPolicyPlanningResult {
  return { planningId: `hermes-credentials-policy-planning:75b300f:${input.plannedAt}`, planningKind: FACTORY_HERMES_CREDENTIALS_POLICY_PLANNING_KIND, planningVersion: FACTORY_HERMES_CREDENTIALS_POLICY_PLANNING_VERSION, plannedAt: input.plannedAt, plannedBy: input.plannedBy, toolId: 'hermes_agent', commandShapeUnderConsideration: 'oneshot_real_with_provider_model', futureCommandShape: 'hermes.exe --oneshot "<PROMPT>" --provider <PROVIDER> --model <MODEL>', credentialReferences: [], providerCredentialRequirements: [], checks: [], blockers: [], warnings: [], status: 'blocked', decision: 'blocked_missing_model_provider_policy_planning', canProceedToNetworkPolicyPlanning: false, canProceedToResearchExecutionApproval: false, canRunResearchNow: false, canExecuteHermesNow: false, canPassPromptNow: false, canUseNetworkNow: false, canUseCredentialsNow: false, canReadEnvSecretsNow: false, canCallModelsNow: false, canUseFindings: false, recommendedNextStep: FACTORY_HERMES_CREDENTIALS_POLICY_PLANNING_NEXT_STEP }
}

export function evaluateFactoryHermesCredentialsPolicyPlanning(input: FactoryHermesCredentialsPolicyPlanningInput): FactoryHermesCredentialsPolicyPlanningResult {
  const policy = { ...DEFAULT_FACTORY_HERMES_CREDENTIALS_POLICY_PLANNING_POLICY, ...(input.policy || {}) }
  const out = base(input)
  const model = input.modelProviderPolicyPlanningResult
  const prompt = input.promptPolicyPlanningResult
  const inspection = input.credentialSourceInspection
  if (!model) return { ...out, blockers: [{ blockerId: 'blocked_missing_model_provider_policy_planning', message: 'Model provider policy planning result is required.' }] }
  const selection = model.hermesModelProviderPolicyPlanCandidate?.providerSelection
  if (model.status !== 'model_provider_policy_plan_created' || model.decision !== 'hermes_model_provider_policy_plan_created' || model.canProceedToCredentialsPolicyPlanning !== true || model.canProceedToResearchExecutionApproval !== false || model.canRunResearchNow !== false || model.canExecuteHermesNow !== false || model.canPassPromptNow !== false || model.canUseNetworkNow !== false || model.canUseCredentialsNow !== false || model.canCallModelsNow !== false || selection?.providerSelectionRequired !== true || selection?.selectedProvider !== null || selection?.selectedModel !== null || selection?.noImplicitProviderFromEnv !== true || selection?.noImplicitModelFromEnv !== true || selection?.noDefaultFallbackProvider !== true) return { ...out, decision: 'blocked_model_provider_policy_not_ready_for_credentials_policy', blockers: [{ blockerId: 'blocked_model_provider_policy_not_ready_for_credentials_policy', message: 'Model provider policy planning is not ready.' }] }
  if (policy.requirePromptPolicyPlanning && (!prompt || prompt.status !== 'prompt_policy_plan_created')) return { ...out, decision: 'blocked_model_provider_policy_not_ready_for_credentials_policy', blockers: [{ blockerId: 'blocked_prompt_policy_missing', message: 'Prompt policy planning result is required.' }] }
  if (policy.requireCredentialSourceInspection && !inspection) return { ...out, decision: 'blocked_missing_credential_source_inspection', blockers: [{ blockerId: 'blocked_missing_credential_source_inspection', message: 'Credential source inspection is required.' }] }
  if (inspection?.credentialValuesRead === true || inspection?.dotEnvRead === true || inspection?.envValuesRead === true) return { ...out, decision: 'blocked_credential_values_present', blockers: [{ blockerId: 'blocked_credential_values_present', message: 'Credential inspection must not read values, env or .env.' }] }
  const credentialReferences = buildCredentialReferences(inspection, input.deepSourceReview)
  if (policy.requireCredentialReferences && credentialReferences.length < 4) return { ...out, decision: 'blocked_missing_credential_source_inspection', blockers: [{ blockerId: 'blocked_missing_credential_source_inspection', message: 'Expected credential references are missing.' }] }
  const providerCredentialRequirements = ['openai', 'anthropic', 'gemini_google'].map((providerCandidate) => ({ providerCandidate, allowedCredentialRefs: credentialReferences.filter((r) => r.providerCandidate === providerCandidate).map((r) => r.refName), selectedCredentialRef: null, noCrossProviderFallback: true as const }))
  const plan = { planCandidateId: `${out.planningId}:credentials-policy-plan-candidate`, toolId: 'hermes_agent' as const, commandShapeUnderConsideration: 'oneshot_real_with_provider_model' as const, futureCommandShape: { executable: 'hermes.exe' as const, argsTemplate: ['--oneshot', '<PROMPT>', '--provider', '<PROVIDER>', '--model', '<MODEL>'] as ['--oneshot', '<PROMPT>', '--provider', '<PROVIDER>', '--model', '<MODEL>'], shell: false as const }, credentialReferences, providerCredentialRequirements, credentialRules: rules(), credentialInjectionPlan: { credentialValuesDefinedHere: false as const, credentialValuesReadHere: false as const, futureCredentialSourceRequiresApproval: true as const, allowedFutureSourcesCandidate: ['explicit_secret_reference', 'managed_secret_store_if_available', 'runtime_injection_under_boundary'], forbiddenSources: ['implicit_dotenv', 'implicit_process_env_without_approval', 'config_yaml_secret_values', 'logs'] }, maskingPolicy: { logCredentialNamesOnly: true as const, redactValues: true as const, noEnvDump: true as const }, killSwitchPolicy: { credentialKillSwitchRequired: true as const, providerKillSwitchRequired: true as const }, requiredNextPolicies: CREDENTIAL_REQUIRED_NEXT_POLICIES, canProceedToNetworkPolicyPlanning: true as const, canProceedToResearchExecutionApproval: false as const, canUseCredentialsNow: false as const, canReadEnvSecretsNow: false as const, canCallModelsNow: false as const }
  const receipt = { receiptId: `${out.planningId}:receipt`, planningId: out.planningId, toolId: 'hermes_agent' as const, plannedBy: input.plannedBy, plannedAt: input.plannedAt, decision: 'hermes_credentials_policy_plan_created' as const, scope: 'hermes_credentials_policy_planning_only' as const, approvedNextGate: 'Factory Hermes Network Policy Planning Gate v1' as const, limitations: ['Credential refs are names only; values are not read.', '.env and env secret values remain forbidden.', 'Credential use requires future approval and runtime boundary.'], notAuthorizedActions: CREDENTIALS_NOT_AUTHORIZED_ACTIONS }
  return { ...out, status: 'credentials_policy_plan_created', decision: 'hermes_credentials_policy_plan_created', credentialReferences, providerCredentialRequirements, credentialsPolicyPlanningReceipt: receipt, hermesCredentialsPolicyPlanCandidate: plan, canProceedToNetworkPolicyPlanning: true }
}
