const childProcess = require('node:child_process');
const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const fss = require('node:fs');
const path = require('node:path');
const { resolveFactoryHermesResearchRuntimeAdapterRetryPaths, assertResearchRuntimeAdapterRetryPathContained } = require('./hermes-research-runtime-adapter-retry.path.cjs');

const KIND = 'factory-hermes-research-runtime-adapter-retry';
const VERSION = '1.0';
const TIMEOUT = 120000;
const MAX_TIMEOUT = 180000;
const MAX_BYTES = 12000;
const NEXT = 'Proceed to Factory Hermes Research Result Ingestion Gate v2; help output is not research findings.';
const secretKey = /SECRET|TOKEN|API_KEY|PASSWORD|PRIVATE|OPENAI|GITHUB_TOKEN|NPM_TOKEN|NODE_AUTH_TOKEN|UV_INDEX|PIP_INDEX|PIP_EXTRA_INDEX|TWINE/iu;
const secretValue = /password|secret|token|api[_-]?key|bearer|BEGIN [A-Z ]*PRIVATE KEY/giu;
async function readJson(file) { return JSON.parse(await fs.readFile(file, 'utf8')); }
function hash(file) { return crypto.createHash('sha256').update(fss.readFileSync(file)).digest('hex'); }
function sanitizeCommandOutput(value) { const out = String(value || '').replace(secretValue, '[REDACTED]').replace(/\r/g, ''); return { text: Buffer.from(out).subarray(0, MAX_BYTES).toString('utf8'), truncated: Buffer.byteLength(out) > MAX_BYTES }; }
function sanitizeEnvironment(env = process.env) { const keep = ['PATH', 'Path', 'SystemRoot', 'TEMP', 'TMP', 'HOME', 'USERPROFILE', 'LOCALAPPDATA', 'APPDATA']; const clean = {}; for (const k of keep) if (env[k] && !secretKey.test(k)) clean[k] = env[k]; clean.HERMES_NO_NETWORK = '1'; clean.HERMES_NO_MODEL_CALLS = '1'; clean.HERMES_NO_CREDENTIALS = '1'; clean.PYTHONNOUSERSITE = '1'; clean.NO_COLOR = '1'; return clean; }
function commandResult(paths, patch = {}) { return { commandKind: 'hermes_help_probe', executableRef: paths.refs.executableRef, args: ['--help'], cwdRef: paths.refs.sourceRootRef, shell: false, timeoutMs: TIMEOUT, envRefs: { HERMES_NO_NETWORK: '1', HERMES_NO_MODEL_CALLS: '1', HERMES_NO_CREDENTIALS: '1', PYTHONNOUSERSITE: '1', NO_COLOR: '1' }, stdoutPreview: '', stderrPreview: '', exitCode: null, timedOut: false, killed: false, signal: null, started: false, completed: false, ...patch }; }
function base(input, paths, verification = {}, patch = {}) { return { retryRunId: `hermes-research-runtime-adapter-retry:75b300f:${input.executedAt}`, retryKind: KIND, retryVersion: VERSION, executedAt: input.executedAt, executedBy: input.executedBy, toolId: 'hermes_agent', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main', executableRef: paths.refs.executableRef, executableSha256: verification.executableSha256 || '', selectedInterface: { interfaceType: 'package_entrypoint', commandName: 'hermes', pythonEntrypoint: 'hermes_cli.main:main' }, commandResults: [], helpProbeStatus: 'not_started', stdoutPreview: '', stderrPreview: '', stdoutTruncated: false, stderrTruncated: false, exitCode: null, timedOut: false, killed: false, signal: null, hermesExecutionStatus: 'not_executed', selectedInterfaceExecutionStatus: 'not_executed', networkStatus: 'not_allowed', credentialsStatus: 'not_allowed', modelCallStatus: 'not_allowed', pipStatus: 'not_executed', pythonDirectStatus: 'not_executed', setupPyDirectStatus: 'not_executed', uvStatus: 'not_executed', materializationStatus: 'not_attempted', cacheRuntimeStatus: 'not_attempted', researchRuntimeStatus: 'help_probe_only', status: 'blocked', decision: 'request_research_runtime_adapter_retry_repair', blockers: [], warnings: [], canProceedToResearchResultIngestionV2: false, canTreatAsResearchResult: false, canUseFindings: false, canProceedToResearchJefeReview: false, canExecuteHermesNow: false, canUseNetwork: false, canUseCredentials: false, canCallModels: false, canDeploy: false, recommendedNextStep: NEXT, ...patch }; }
async function runHermesHelpProbeRetry(paths, timeoutMs = TIMEOUT) { return await new Promise((resolve) => { childProcess.execFile(paths.executable, ['--help'], { cwd: paths.sourceRoot, env: sanitizeEnvironment(), shell: false, timeout: Math.min(Math.max(timeoutMs, TIMEOUT), MAX_TIMEOUT), windowsHide: true, maxBuffer: MAX_BYTES * 2 }, (error, stdout, stderr) => { const so = sanitizeCommandOutput(stdout); const se = sanitizeCommandOutput(stderr || error?.message || ''); resolve(commandResult(paths, { stdoutPreview: so.text, stderrPreview: se.text, stdoutTruncated: so.truncated, stderrTruncated: se.truncated, exitCode: typeof error?.code === 'number' ? error.code : 0, timedOut: Boolean(error?.killed), killed: Boolean(error?.killed), signal: error?.signal || null, started: true, completed: !error })); }); }); }
async function executeFactoryHermesResearchRuntimeAdapterRetry(input = {}) {
  const paths = resolveFactoryHermesResearchRuntimeAdapterRetryPaths();
  for (const t of [paths.executable, paths.manifest, paths.result, paths.logsRoot]) assertResearchRuntimeAdapterRetryPathContained(t, paths.installRoot);
  const runInput = { executedAt: input.executedAt || '2026-07-22T05:10:00.000Z', executedBy: input.executedBy || 'factory-hermes-research-runtime-adapter-retry-smoke' };
  let verification = null;
  try {
    verification = input.entrypointMaterializationVerificationResult || await readJson(paths.verificationResult);
    await readJson(paths.boundaryResult); await readJson(paths.approvalResult); await readJson(paths.interfaceSelectionResult);
  } catch (error) { const result = base(runInput, paths, {}, { decision: 'blocked_missing_entrypoint_materialization_verification', blockers: [{ blockerId: 'blocked_missing_entrypoint_materialization_verification', message: sanitizeCommandOutput(error.message).text }] }); await write(paths, result); return result; }
  const env = verification.approvedResearchRuntimeAdapterRetryEnvelope || {};
  if (!['verified', 'warning_verified'].includes(verification.status) || verification.decision !== 'hermes_entrypoint_materialization_verified_for_research_runtime_adapter_retry' || verification.canProceedToResearchRuntimeAdapterRetry !== true) { const result = base(runInput, paths, verification, { decision: 'blocked_entrypoint_not_verified', blockers: [{ blockerId: 'blocked_entrypoint_not_verified', message: 'Entrypoint materialization verification is not ready.' }] }); await write(paths, result); return result; }
  if (!fss.existsSync(paths.executable)) { const result = base(runInput, paths, verification, { decision: 'blocked_executable_missing', blockers: [{ blockerId: 'blocked_executable_missing', message: 'hermes.exe missing.' }] }); await write(paths, result); return result; }
  if (hash(paths.executable) !== verification.executableSha256) { const result = base(runInput, paths, verification, { decision: 'blocked_executable_hash_mismatch', blockers: [{ blockerId: 'blocked_executable_hash_mismatch', message: 'hermes.exe hash mismatch.' }] }); await write(paths, result); return result; }
  if (env.futureRetryMayExecuteHermesHelpOnly !== true || JSON.stringify(env.futureRetryCommand?.args) !== JSON.stringify(['--help']) || env.futureRetryCommand?.shell !== false || env.futureRetryMustNotUseNetwork !== true || env.futureRetryMustNotUseCredentials !== true || env.futureRetryMustNotCallModels !== true) { const result = base(runInput, paths, verification, { decision: 'blocked_retry_command_not_safe', blockers: [{ blockerId: 'blocked_retry_command_not_safe', message: 'Retry envelope command is unsafe.' }] }); await write(paths, result); return result; }
  await fs.mkdir(paths.logsRoot, { recursive: true });
  const cmd = await runHermesHelpProbeRetry(paths, input.timeoutMs || TIMEOUT);
  const output = `${cmd.stdoutPreview}\n${cmd.stderrPreview}`;
  const networkHint = /https?:\/\/|connection refused|network unreachable|timed out connecting|failed to connect|fetch failed|request failed|enter .*api[_ -]?key|paste .*token|credential prompt/iu.test(output);
  const success = cmd.exitCode === 0 && !cmd.timedOut && !networkHint;
  const status = success ? 'success' : 'controlled_failure';
  const decision = success ? 'hermes_research_runtime_adapter_retry_help_probe_succeeded' : cmd.timedOut ? 'failed_hermes_help_probe_timeout' : networkHint ? 'blocked_network_attempt_detected' : 'failed_hermes_help_probe';
  const result = base(runInput, paths, verification, { status, decision, commandResults: [cmd], helpProbeStatus: success ? 'succeeded' : cmd.timedOut ? 'timed_out' : 'failed', stdoutPreview: cmd.stdoutPreview, stderrPreview: cmd.stderrPreview, stdoutTruncated: cmd.stdoutTruncated, stderrTruncated: cmd.stderrTruncated, exitCode: cmd.exitCode, timedOut: cmd.timedOut, killed: cmd.killed, signal: cmd.signal, hermesExecutionStatus: success ? 'executed_help_probe_only' : 'executed_help_probe_only_failed', selectedInterfaceExecutionStatus: success ? 'executed_help_probe_only' : 'executed_help_probe_only_failed', canProceedToResearchResultIngestionV2: true, blockers: success ? [] : [{ blockerId: decision, message: cmd.stderrPreview || cmd.stdoutPreview || 'help probe failed' }] });
  await write(paths, result); return result;
}
async function write(paths, result) { const manifest = { manifestKind: 'factory-hermes-research-runtime-adapter-retry-manifest', manifestVersion: VERSION, toolId: 'hermes_agent', commandName: result.commandName, pythonEntrypoint: result.pythonEntrypoint, selectedInterface: result.selectedInterface, executableRef: result.executableRef, executableSha256: result.executableSha256, commandSummary: { executableRef: paths.refs.executableRef, args: ['--help'], shell: false }, commandResultSummary: result.commandResults.map((c) => ({ exitCode: c.exitCode, timedOut: c.timedOut, shell: c.shell })), helpProbeStatus: result.helpProbeStatus, hermesExecutionStatus: result.hermesExecutionStatus, selectedInterfaceExecutionStatus: result.selectedInterfaceExecutionStatus, networkStatus: result.networkStatus, credentialsStatus: result.credentialsStatus, modelCallStatus: result.modelCallStatus, pipStatus: result.pipStatus, pythonDirectStatus: result.pythonDirectStatus, setupPyDirectStatus: result.setupPyDirectStatus, uvStatus: result.uvStatus, materializationStatus: result.materializationStatus, cacheRuntimeStatus: result.cacheRuntimeStatus, stdoutPreviewSanitized: result.stdoutPreview, stderrPreviewSanitized: result.stderrPreview, executedAt: result.executedAt, executedBy: result.executedBy, nextRequiredGate: 'Factory Hermes Research Result Ingestion Gate v2' }; await fs.writeFile(paths.manifest, `${JSON.stringify(manifest, null, 2)}\n`); await fs.writeFile(paths.result, `${JSON.stringify(result, null, 2)}\n`); }
module.exports = { executeFactoryHermesResearchRuntimeAdapterRetry, resolveFactoryHermesResearchRuntimeAdapterRetryPaths, assertResearchRuntimeAdapterRetryPathContained, sanitizeEnvironment, sanitizeCommandOutput, runHermesHelpProbeRetry };
