import type { FactoryProjectContractPersistenceResult } from '../project-contract-persistence/index.ts'

export type FactoryProjectContractPersistenceRuntimeVersion = '1.0'
export type FactoryProjectContractPersistenceRuntimeKind = 'factory-project-contract-persistence-runtime-adapter'
export type FactoryProjectContractPersistenceRuntimeStatus = 'persisted' | 'idempotent_noop' | 'blocked' | 'failed'
export interface FactoryProjectContractPersistenceRuntimePolicy { requireStorageRootInsideCodexTemp: true; requireRelativeTargetPath: true; forbidPathTraversal: true; forbidAbsoluteTargetPath: true; requireIdempotencyKey: true; requireFingerprint: true; requireAtomicTempWrite: true; requireReadbackVerification: true; requireMetadataWrite: true; requireNoShell: true; requireNoExternalCommands: true; requireNoSecrets: true; forbidCodexExecution: true; forbidProjectCreation: true; forbidRepositoryCreation: true; forbidDeploy: true; allowOverwriteSameFingerprint: true; blockOverwriteDifferentFingerprint: true }
export interface FactoryProjectContractPersistenceRuntimeInput { persistenceResult: FactoryProjectContractPersistenceResult; storageRoot: string; executedAt: string; executedBy: string; policy?: Partial<FactoryProjectContractPersistenceRuntimePolicy>; allowOverwriteSameFingerprint?: boolean }
export interface FactoryProjectContractPersistenceRuntimeCheck { checkId: string; category: 'input' | 'plan' | 'path' | 'write' | 'readback' | 'idempotency'; passed: boolean; message: string }
export interface FactoryProjectContractPersistenceRuntimeBlocker { blockerId: string; category: FactoryProjectContractPersistenceRuntimeCheck['category']; message: string }
export interface FactoryProjectContractPersistenceRuntimeWarning { warningId: string; message: string }
export interface FactoryProjectContractPersistenceRuntimeWriteResult { written: boolean; idempotent: boolean; contractWritten: boolean; metadataWritten: boolean; readbackVerified: boolean; rollbackAttempted: boolean; rollbackSucceeded?: boolean; sanitizedError?: string }
export interface FactoryProjectContractPersistenceRuntimeMetadata { metadataKind: 'factory-project-contract-persistence-metadata'; metadataVersion: '1.0'; persistenceId: string; approvalId: string; candidateId: string; fingerprint: string; idempotencyKey: string; targetPath: string; writtenAt: string; writtenBy: string; sourceStatus: string; runtimePersistenceId: string; notExecutable: true; codexAllowed: false; projectCreated: false; repositoryCreated: false; deployed: false }
export interface FactoryProjectContractPersistenceRuntimeResult { runtimePersistenceId: string; runtimePersistenceKind: FactoryProjectContractPersistenceRuntimeKind; runtimePersistenceVersion: FactoryProjectContractPersistenceRuntimeVersion; executedAt: string; executedBy: string; persistenceId: string; approvalId: string; candidateId: string; storageRoot: string; status: FactoryProjectContractPersistenceRuntimeStatus; targetAbsolutePath: string; metadataAbsolutePath: string; tempAbsolutePath?: string; backupAbsolutePath?: string; fingerprint: string; idempotencyKey: string; writeResult: FactoryProjectContractPersistenceRuntimeWriteResult; metadata?: FactoryProjectContractPersistenceRuntimeMetadata; checks: FactoryProjectContractPersistenceRuntimeCheck[]; blockers: FactoryProjectContractPersistenceRuntimeBlocker[]; warnings: FactoryProjectContractPersistenceRuntimeWarning[]; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryProjectContractPersistenceRuntimeValidationResult { ok: boolean; errors: string[]; warnings: string[] }
export interface FactoryProjectContractPersistenceRuntimeSummary { runtimePersistenceId: string; persistenceId: string; status: FactoryProjectContractPersistenceRuntimeStatus; targetPath: string; fingerprint: string; idempotencyKey: string; writeResult: FactoryProjectContractPersistenceRuntimeWriteResult; canExecuteCodex: false; canCreateProject: false; canCreateRepository: false; canDeploy: false; recommendedNextStep: string }
export interface FactoryProjectContractPersistenceResolvedPaths { storageRootAbsolute: string; targetAbsolutePath: string; metadataAbsolutePath: string; tempAbsolutePath: string; backupAbsolutePath: string; lockAbsolutePath: string }
